In [1]:
import time
import requests
def requests_view(response):
    import webbrowser
    request_url = response.url
    base_url = '<head><base href="%s">'%(request_url)
    base_url = base_url.encode()
    content = response.content.replace(b"<head>",base_url)
    tem_html = open('tmp.html','wb')
    tem_html.write(content)
    tem_html.close()
    webbrowser.open_new_tab("tmp.html") #mac fail to open

In [3]:
respond = requests.get("http://sz.ganji.com/zufang/pn1/")

In [4]:
requests_view(respond)

In [5]:
from lxml import etree
#html = etree.HTML(respond.content)
html = etree.HTML(respond.content.decode())

In [6]:
path = './/*[@class="f-main-list"]//div[contains(@class,"f-list-item ershoufang-list")]'
items = html.xpath(path)

In [7]:
for i in items:
    title = i.xpath('.//dd/a/@title')
    price = i.xpath('.//dd[@class="dd-item info"]/div/span/text()')
    size = i.xpath('.//dd[@class="dd-item size"]/span/text()')
    agent = i.xpath('.//dd[4]/span/span/text()')[0].split()

In [8]:
## Create SQLsite to store data
from sqlalchemy import create_engine
engine = create_engine('sqlite:///ganji_rential.sqlite', echo = True)

from sqlalchemy import Table,Column,Integer,String,ForeignKey  
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
DBSession = sessionmaker(bind=engine)
session = DBSession()
class rental(Base):
    __tablename__ = "rental"
    id = Column(Integer, primary_key=True)
    title = Column(String(400))
    price = Column(String(400))
    info = Column(String(400))
    agent = Column(String(400))
    
    @classmethod
    def save(cls, data):
        session.add(data)
        session.commit()
        return data.id
        
Base.metadata.create_all(engine)

2019-07-23 11:40:19,706 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-07-23 11:40:19,707 INFO sqlalchemy.engine.base.Engine ()
2019-07-23 11:40:19,709 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-07-23 11:40:19,710 INFO sqlalchemy.engine.base.Engine ()
2019-07-23 11:40:19,711 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("rental")
2019-07-23 11:40:19,712 INFO sqlalchemy.engine.base.Engine ()

In [9]:
rent = rental()
rent.title = 'title'
rent.price = 'price'
rent.info = 'info'
rent.agent = 'agent'
rent.save(rent)

2019-07-23 11:40:19,720 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:19,723 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:19,723 INFO sqlalchemy.engine.base.Engine ('title', 'price', 'info', 'agent')
2019-07-23 11:40:19,726 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:19,730 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:19,731 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:19,732 INFO sqlalchemy.engine.base.Engine (1520,)

1520

In [11]:
base_url = "http://sz.ganji.com/zufang/pn{}"
headers = {
    #'Referer':,
    'User-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36'
}

def pass_data(respond):
    html = etree.HTML(respond.content.decode())
    path = './/*[@class="f-main-list"]//div[contains(@class,"f-list-item ershoufang-list")]'
    items = html.xpath(path)
    for i in items:
        title = i.xpath('.//dd/a/@title')
        price = i.xpath('.//dd[@class="dd-item info"]/div/span/text()')
        info = i.xpath('.//dd[@class="dd-item size"]/span/text()')
        agent = i.xpath('.//dd[4]/span/span/text()')[0].split()
        rent = rental()
        rent.title = " ".join(title)
        rent.price = " ".join(price)
        rent.info = " ".join(info)
        rent.agent = " ".join(agent)
        rent.save(rent)

for num in range(71):
    re_url = base_url.format(num)
    response = requests.get(re_url, headers = headers)
    if response.status_code == 403:
        for i in range(3):
            response = requests.get(re_url, headers = headers)
            if response.status_code == 200:
                break
    if response.status_code == 200:
        pass_data(respond)
    print(re_url, "status:",response.status_code)
    time.sleep(0.5)

2019-07-23 11:40:33,022 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,046 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,047 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:40:33,048 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,052 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,053 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,053 INFO sqlalchemy.engine.base.Engine (1766,)
2019-07-23 11:40:33,056 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,056 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:40:33,058 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,060 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,061 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,062 INFO sqlalchemy.engine.base.Engine (1767,)
2019-07-23 11:40:33,064 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,064 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:40:33,065 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,069 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,070 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,071 INFO sqlalchemy.engine.base.Engine (1768,)
2019-07-23 11:40:33,074 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,074 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:40:33,076 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,079 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,080 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,080 INFO sqlalchemy.engine.base.Engine (1769,)
2019-07-23 11:40:33,083 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,083 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:40:33,086 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,088 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,089 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,090 INFO sqlalchemy.engine.base.Engine (1770,)
2019-07-23 11:40:33,092 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,093 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:40:33,094 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,097 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,098 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,098 INFO sqlalchemy.engine.base.Engine (1771,)
2019-07-23 11:40:33,101 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,101 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:40:33,103 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,105 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,106 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,107 INFO sqlalchemy.engine.base.Engine (1772,)
2019-07-23 11:40:33,110 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,110 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:33,112 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,115 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,116 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,116 INFO sqlalchemy.engine.base.Engine (1773,)
2019-07-23 11:40:33,119 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,119 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:40:33,121 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,123 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,124 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,124 INFO sqlalchemy.engine.base.Engine (1774,)
2019-07-23 11:40:33,127 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,128 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:33,130 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,133 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,134 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,134 INFO sqlalchemy.engine.base.Engine (1775,)
2019-07-23 11:40:33,137 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,138 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:40:33,139 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,142 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,143 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,143 INFO sqlalchemy.engine.base.Engine (1776,)
2019-07-23 11:40:33,145 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:33,146 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:40:33,149 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,152 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,153 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,154 INFO sqlalchemy.engine.base.Engine (1777,)
2019-07-23 11:40:33,156 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,156 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:40:33,158 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,160 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,161 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,161 INFO sqlalchemy.engine.base.Engine (1778,)
2019-07-23 11:40:33,164 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,164 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:40:33,165 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,168 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,169 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,170 INFO sqlalchemy.engine.base.Engine (1779,)
2019-07-23 11:40:33,172 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,173 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:40:33,175 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,178 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,180 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,180 INFO sqlalchemy.engine.base.Engine (1780,)
2019-07-23 11:40:33,183 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,184 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:40:33,185 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,188 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,189 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,189 INFO sqlalchemy.engine.base.Engine (1781,)
2019-07-23 11:40:33,192 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,193 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:40:33,194 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,197 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,198 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,199 INFO sqlalchemy.engine.base.Engine (1782,)
2019-07-23 11:40:33,201 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,202 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:40:33,204 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,207 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,208 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,208 INFO sqlalchemy.engine.base.Engine (1783,)
2019-07-23 11:40:33,210 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,211 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:40:33,212 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,215 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,216 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,216 INFO sqlalchemy.engine.base.Engine (1784,)
2019-07-23 11:40:33,218 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,219 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:40:33,220 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,225 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,227 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,229 INFO sqlalchemy.engine.base.Engine (1785,)
2019-07-23 11:40:33,232 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,234 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:40:33,235 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,239 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,240 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,241 INFO sqlalchemy.engine.base.Engine (1786,)
2019-07-23 11:40:33,244 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,246 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:40:33,247 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,251 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,251 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,252 INFO sqlalchemy.engine.base.Engine (1787,)
2019-07-23 11:40:33,254 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,255 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:40:33,256 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:40:33,259 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,260 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,261 INFO sqlalchemy.engine.base.Engine (1788,)
2019-07-23 11:40:33,264 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,265 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:40:33,267 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,270 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,271 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,271 INFO sqlalchemy.engine.base.Engine (1789,)
2019-07-23 11:40:33,273 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,274 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:40:33,275 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,278 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,279 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,280 INFO sqlalchemy.engine.base.Engine (1790,)
2019-07-23 11:40:33,282 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,283 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:40:33,284 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,288 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,290 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,290 INFO sqlalchemy.engine.base.Engine (1791,)
2019-07-23 11:40:33,294 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,295 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:40:33,297 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,300 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,301 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,302 INFO sqlalchemy.engine.base.Engine (1792,)
2019-07-23 11:40:33,304 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,305 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:40:33,306 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,309 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,310 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,310 INFO sqlalchemy.engine.base.Engine (1793,)
2019-07-23 11:40:33,312 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,313 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:40:33,315 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,318 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,319 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,320 INFO sqlalchemy.engine.base.Engine (1794,)
2019-07-23 11:40:33,322 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,323 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:40:33,324 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,327 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,328 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,329 INFO sqlalchemy.engine.base.Engine (1795,)
2019-07-23 11:40:33,331 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,332 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:40:33,334 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,338 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,338 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,339 INFO sqlalchemy.engine.base.Engine (1796,)
2019-07-23 11:40:33,342 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,342 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:40:33,344 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,347 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,348 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,349 INFO sqlalchemy.engine.base.Engine (1797,)
2019-07-23 11:40:33,352 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,352 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:40:33,354 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,357 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,358 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,359 INFO sqlalchemy.engine.base.Engine (1798,)
2019-07-23 11:40:33,362 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,362 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:40:33,364 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,367 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,368 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:33,369 INFO sqlalchemy.engine.base.Engine (1799,)
2019-07-23 11:40:33,371 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,371 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:40:33,372 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,376 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,376 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,377 INFO sqlalchemy.engine.base.Engine (1800,)
2019-07-23 11:40:33,380 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,380 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:40:33,382 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,386 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,387 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,388 INFO sqlalchemy.engine.base.Engine (1801,)
2019-07-23 11:40:33,390 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,392 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:40:33,394 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,397 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,398 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,398 INFO sqlalchemy.engine.base.Engine (1802,)
2019-07-23 11:40:33,400 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,401 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:40:33,403 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,406 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,406 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,407 INFO sqlalchemy.engine.base.Engine (1803,)
2019-07-23 11:40:33,410 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,410 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:40:33,411 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,415 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,415 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,416 INFO sqlalchemy.engine.base.Engine (1804,)
2019-07-23 11:40:33,419 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,419 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:40:33,421 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,424 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,425 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,426 INFO sqlalchemy.engine.base.Engine (1805,)
2019-07-23 11:40:33,427 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,428 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:40:33,430 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,433 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,434 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,435 INFO sqlalchemy.engine.base.Engine (1806,)
2019-07-23 11:40:33,438 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,439 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:40:33,440 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,444 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,445 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,446 INFO sqlalchemy.engine.base.Engine (1807,)
2019-07-23 11:40:33,449 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,449 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:40:33,451 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,454 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,455 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,455 INFO sqlalchemy.engine.base.Engine (1808,)
2019-07-23 11:40:33,458 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,459 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:40:33,461 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,463 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,464 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,465 INFO sqlalchemy.engine.base.Engine (1809,)
2019-07-23 11:40:33,468 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,469 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:40:33,470 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,473 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,473 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,474 INFO sqlalchemy.engine.base.Engine (1810,)
2019-07-23 11:40:33,476 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:33,477 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:33,478 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,482 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,483 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,484 INFO sqlalchemy.engine.base.Engine (1811,)
2019-07-23 11:40:33,487 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,488 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:40:33,490 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,493 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,494 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,494 INFO sqlalchemy.engine.base.Engine (1812,)
2019-07-23 11:40:33,497 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,497 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:40:33,499 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,501 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,502 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,503 INFO sqlalchemy.engine.base.Engine (1813,)
2019-07-23 11:40:33,505 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,506 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:33,507 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,510 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,511 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,511 INFO sqlalchemy.engine.base.Engine (1814,)
2019-07-23 11:40:33,513 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,514 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:40:33,515 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,518 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,520 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,521 INFO sqlalchemy.engine.base.Engine (1815,)
2019-07-23 11:40:33,524 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,525 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:40:33,527 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,530 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,531 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,532 INFO sqlalchemy.engine.base.Engine (1816,)
2019-07-23 11:40:33,536 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,537 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:40:33,538 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,541 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,542 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,543 INFO sqlalchemy.engine.base.Engine (1817,)
2019-07-23 11:40:33,545 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,545 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:40:33,547 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,550 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,551 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,552 INFO sqlalchemy.engine.base.Engine (1818,)
2019-07-23 11:40:33,555 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,556 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:40:33,557 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,560 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,561 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,562 INFO sqlalchemy.engine.base.Engine (1819,)
2019-07-23 11:40:33,564 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,565 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:40:33,566 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,569 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,570 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,571 INFO sqlalchemy.engine.base.Engine (1820,)
2019-07-23 11:40:33,573 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,574 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:33,575 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,578 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,579 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,579 INFO sqlalchemy.engine.base.Engine (1821,)
2019-07-23 11:40:33,583 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,583 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:33,585 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,588 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:40:33,590 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,591 INFO sqlalchemy.engine.base.Engine (1822,)
2019-07-23 11:40:33,594 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,595 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:40:33,596 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,599 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,600 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,601 INFO sqlalchemy.engine.base.Engine (1823,)
2019-07-23 11:40:33,606 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,607 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:40:33,608 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,611 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,611 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,613 INFO sqlalchemy.engine.base.Engine (1824,)
2019-07-23 11:40:33,615 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,616 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:40:33,617 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,620 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,620 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,621 INFO sqlalchemy.engine.base.Engine (1825,)
2019-07-23 11:40:33,623 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,624 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:40:33,626 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,628 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,629 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,630 INFO sqlalchemy.engine.base.Engine (1826,)
2019-07-23 11:40:33,632 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,633 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:40:33,635 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,638 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,639 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,640 INFO sqlalchemy.engine.base.Engine (1827,)
2019-07-23 11:40:33,641 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,642 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:40:33,643 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,646 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,647 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,648 INFO sqlalchemy.engine.base.Engine (1828,)
2019-07-23 11:40:33,650 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,651 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:40:33,653 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,655 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,656 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,657 INFO sqlalchemy.engine.base.Engine (1829,)
2019-07-23 11:40:33,659 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,660 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:33,661 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,665 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,666 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,667 INFO sqlalchemy.engine.base.Engine (1830,)
2019-07-23 11:40:33,669 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,670 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:33,671 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,674 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,675 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,675 INFO sqlalchemy.engine.base.Engine (1831,)
2019-07-23 11:40:33,678 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,678 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:40:33,680 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,683 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,683 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,684 INFO sqlalchemy.engine.base.Engine (1832,)
2019-07-23 11:40:33,687 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,687 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:40:33,689 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,692 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,693 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,694 INFO sqlalchemy.engine.base.Engine (1833,)

2019-07-23 11:40:33,695 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,696 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:40:33,698 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,701 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,702 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,703 INFO sqlalchemy.engine.base.Engine (1834,)
2019-07-23 11:40:33,706 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,707 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:40:33,708 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,712 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,713 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,714 INFO sqlalchemy.engine.base.Engine (1835,)
2019-07-23 11:40:33,716 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,717 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:40:33,719 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,722 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,723 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,724 INFO sqlalchemy.engine.base.Engine (1836,)
2019-07-23 11:40:33,727 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,727 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:40:33,728 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,732 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,733 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,734 INFO sqlalchemy.engine.base.Engine (1837,)
2019-07-23 11:40:33,736 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,737 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:40:33,739 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,741 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,742 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,743 INFO sqlalchemy.engine.base.Engine (1838,)
2019-07-23 11:40:33,745 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,746 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:40:33,748 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,751 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,752 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,753 INFO sqlalchemy.engine.base.Engine (1839,)
2019-07-23 11:40:33,755 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,755 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:40:33,758 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,761 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,762 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,762 INFO sqlalchemy.engine.base.Engine (1840,)
2019-07-23 11:40:33,765 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,765 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:40:33,767 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,770 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,770 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,771 INFO sqlalchemy.engine.base.Engine (1841,)
2019-07-23 11:40:33,773 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,774 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:40:33,776 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,779 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,780 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,780 INFO sqlalchemy.engine.base.Engine (1842,)
2019-07-23 11:40:33,783 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,784 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:40:33,785 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,788 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,789 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,789 INFO sqlalchemy.engine.base.Engine (1843,)
2019-07-23 11:40:33,792 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,793 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:40:33,794 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,797 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,797 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,798 INFO sqlalchemy.engine.base.Engine (1844,)
2019-07-23 11:40:33,800 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,801 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:40:33,803 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,805 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:40:33,806 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,806 INFO sqlalchemy.engine.base.Engine (1845,)
2019-07-23 11:40:33,809 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,810 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:40:33,812 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,815 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,816 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,817 INFO sqlalchemy.engine.base.Engine (1846,)
2019-07-23 11:40:33,819 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,820 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:33,821 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,825 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,826 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,826 INFO sqlalchemy.engine.base.Engine (1847,)
2019-07-23 11:40:33,829 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,830 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:33,832 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,834 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,835 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,836 INFO sqlalchemy.engine.base.Engine (1848,)
2019-07-23 11:40:33,838 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,839 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:40:33,841 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,844 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,845 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,846 INFO sqlalchemy.engine.base.Engine (1849,)
2019-07-23 11:40:33,849 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,850 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:40:33,852 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,855 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,856 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,856 INFO sqlalchemy.engine.base.Engine (1850,)
2019-07-23 11:40:33,858 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,860 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:40:33,861 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,864 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,865 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,866 INFO sqlalchemy.engine.base.Engine (1851,)
2019-07-23 11:40:33,869 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,870 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:40:33,871 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,875 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,876 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,877 INFO sqlalchemy.engine.base.Engine (1852,)
2019-07-23 11:40:33,880 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,880 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:40:33,882 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,885 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,886 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,887 INFO sqlalchemy.engine.base.Engine (1853,)
2019-07-23 11:40:33,890 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,890 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:40:33,892 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,895 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,896 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,896 INFO sqlalchemy.engine.base.Engine (1854,)
2019-07-23 11:40:33,899 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,900 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:40:33,901 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,904 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,905 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,906 INFO sqlalchemy.engine.base.Engine (1855,)
2019-07-23 11:40:33,909 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,910 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:40:33,911 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,915 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,916 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,917 INFO sqlalchemy.engine.base.Engine (1856,)

2019-07-23 11:40:33,919 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,920 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:40:33,921 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,924 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,925 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,926 INFO sqlalchemy.engine.base.Engine (1857,)
2019-07-23 11:40:33,928 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,929 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:40:33,930 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,933 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,934 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,935 INFO sqlalchemy.engine.base.Engine (1858,)
2019-07-23 11:40:33,938 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,938 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:40:33,940 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,943 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,944 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,945 INFO sqlalchemy.engine.base.Engine (1859,)
2019-07-23 11:40:33,948 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,949 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:33,951 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,954 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,955 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,955 INFO sqlalchemy.engine.base.Engine (1860,)
2019-07-23 11:40:33,958 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,959 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:40:33,960 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,963 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,964 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,965 INFO sqlalchemy.engine.base.Engine (1861,)
2019-07-23 11:40:33,967 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,969 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:40:33,971 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,974 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,975 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,976 INFO sqlalchemy.engine.base.Engine (1862,)
2019-07-23 11:40:33,978 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,979 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:40:33,980 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,983 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,984 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,985 INFO sqlalchemy.engine.base.Engine (1863,)
2019-07-23 11:40:33,987 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,988 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:40:33,989 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:33,991 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:33,992 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:33,993 INFO sqlalchemy.engine.base.Engine (1864,)
2019-07-23 11:40:33,995 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:33,995 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:40:33,997 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,000 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,001 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,002 INFO sqlalchemy.engine.base.Engine (1865,)
2019-07-23 11:40:34,004 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,005 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:40:34,006 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,009 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,010 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,010 INFO sqlalchemy.engine.base.Engine (1866,)
2019-07-23 11:40:34,013 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,014 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:34,016 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,019 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,020 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,021 INFO sqlalchemy.engine.base.Engine (1867,)
2019-07-23 11:40:34,023 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,024 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')

2019-07-23 11:40:34,026 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,028 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,029 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,030 INFO sqlalchemy.engine.base.Engine (1868,)
2019-07-23 11:40:34,032 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,033 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:40:34,034 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,037 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,038 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,038 INFO sqlalchemy.engine.base.Engine (1869,)
2019-07-23 11:40:34,041 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,041 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:40:34,043 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,046 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,047 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,047 INFO sqlalchemy.engine.base.Engine (1870,)
2019-07-23 11:40:34,049 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,050 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:40:34,051 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,054 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,055 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,055 INFO sqlalchemy.engine.base.Engine (1871,)
2019-07-23 11:40:34,058 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,058 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:40:34,060 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,062 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,063 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,064 INFO sqlalchemy.engine.base.Engine (1872,)
2019-07-23 11:40:34,066 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,067 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:40:34,069 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,072 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,073 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,073 INFO sqlalchemy.engine.base.Engine (1873,)
2019-07-23 11:40:34,076 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,076 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:40:34,078 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,081 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,081 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,082 INFO sqlalchemy.engine.base.Engine (1874,)
2019-07-23 11:40:34,085 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,085 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:40:34,087 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,090 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,091 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,091 INFO sqlalchemy.engine.base.Engine (1875,)
2019-07-23 11:40:34,094 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,095 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:40:34,096 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,100 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,101 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,101 INFO sqlalchemy.engine.base.Engine (1876,)
2019-07-23 11:40:34,103 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,104 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:40:34,106 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,109 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,110 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,110 INFO sqlalchemy.engine.base.Engine (1877,)
2019-07-23 11:40:34,112 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,113 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:40:34,114 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,118 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,119 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,120 INFO sqlalchemy.engine.base.Engine (1878,)
2019-07-23 11:40:34,123 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,124 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:40:34,125 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,128 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,128 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:34,129 INFO sqlalchemy.engine.base.Engine (1879,)
2019-07-23 11:40:34,132 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,133 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:40:34,135 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,138 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,138 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,139 INFO sqlalchemy.engine.base.Engine (1880,)
2019-07-23 11:40:34,142 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,143 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:40:34,144 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,148 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,149 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,150 INFO sqlalchemy.engine.base.Engine (1881,)
2019-07-23 11:40:34,152 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,153 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:40:34,154 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,157 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,158 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,158 INFO sqlalchemy.engine.base.Engine (1882,)
2019-07-23 11:40:34,161 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,162 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:40:34,163 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,166 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,168 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,168 INFO sqlalchemy.engine.base.Engine (1883,)
2019-07-23 11:40:34,171 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,172 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:40:34,174 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,177 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,178 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,179 INFO sqlalchemy.engine.base.Engine (1884,)
2019-07-23 11:40:34,181 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,181 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:40:34,183 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,187 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,188 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,188 INFO sqlalchemy.engine.base.Engine (1885,)
2019-07-23 11:40:34,191 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,192 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:40:34,193 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,196 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,197 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,198 INFO sqlalchemy.engine.base.Engine (1886,)
2019-07-23 11:40:34,201 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,202 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:40:34,204 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,206 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,207 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,208 INFO sqlalchemy.engine.base.Engine (1887,)
2019-07-23 11:40:34,211 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,212 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:40:34,214 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,218 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,219 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,219 INFO sqlalchemy.engine.base.Engine (1888,)
2019-07-23 11:40:34,222 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,223 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:40:34,224 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,227 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,228 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,228 INFO sqlalchemy.engine.base.Engine (1889,)
2019-07-23 11:40:34,231 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,231 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:40:34,233 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,237 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,238 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,238 INFO sqlalchemy.engine.base.Engine (1890,)
2019-07-23 11:40:34,241 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,242 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')

2019-07-23 11:40:34,243 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,246 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,247 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,248 INFO sqlalchemy.engine.base.Engine (1891,)
2019-07-23 11:40:34,252 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,252 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:40:34,254 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,258 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,259 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,260 INFO sqlalchemy.engine.base.Engine (1892,)
2019-07-23 11:40:34,262 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,263 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:40:34,264 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,267 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,268 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,268 INFO sqlalchemy.engine.base.Engine (1893,)
2019-07-23 11:40:34,271 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,271 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:40:34,272 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,276 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,277 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,277 INFO sqlalchemy.engine.base.Engine (1894,)
2019-07-23 11:40:34,280 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,281 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:40:34,283 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,286 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,287 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,287 INFO sqlalchemy.engine.base.Engine (1895,)
2019-07-23 11:40:34,290 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,290 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:40:34,292 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,295 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,295 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,296 INFO sqlalchemy.engine.base.Engine (1896,)
2019-07-23 11:40:34,298 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,298 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:40:34,300 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,304 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,305 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,306 INFO sqlalchemy.engine.base.Engine (1897,)
2019-07-23 11:40:34,309 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,310 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:40:34,311 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,314 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,315 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,316 INFO sqlalchemy.engine.base.Engine (1898,)
2019-07-23 11:40:34,319 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,320 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:40:34,323 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,326 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,327 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,327 INFO sqlalchemy.engine.base.Engine (1899,)
2019-07-23 11:40:34,330 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,331 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:40:34,333 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,336 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,337 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,338 INFO sqlalchemy.engine.base.Engine (1900,)
2019-07-23 11:40:34,341 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,342 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:40:34,343 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,347 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,348 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,348 INFO sqlalchemy.engine.base.Engine (1901,)
2019-07-23 11:40:34,351 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,352 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:40:34,354 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,357 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,359 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:34,359 INFO sqlalchemy.engine.base.Engine (1902,)
2019-07-23 11:40:34,363 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,363 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:40:34,365 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,368 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,369 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,370 INFO sqlalchemy.engine.base.Engine (1903,)
2019-07-23 11:40:34,372 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:34,373 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:40:34,375 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:34,378 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:34,379 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:34,380 INFO sqlalchemy.engine.base.Engine (1904,)
http://sz.ganji.com/zufang/pn0 status: 200
2019-07-23 11:40:35,581 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,581 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:40:35,583 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,587 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,587 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,588 INFO sqlalchemy.engine.base.Engine (1905,)
2019-07-23 11:40:35,590 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,591 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:40:35,592 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,595 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,596 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,597 INFO sqlalchemy.engine.base.Engine (1906,)
2019-07-23 11:40:35,599 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,600 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:40:35,602 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,605 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,607 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,607 INFO sqlalchemy.engine.base.Engine (1907,)
2019-07-23 11:40:35,610 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,610 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:40:35,612 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,615 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,616 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,617 INFO sqlalchemy.engine.base.Engine (1908,)
2019-07-23 11:40:35,620 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,621 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:40:35,623 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,627 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,628 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,628 INFO sqlalchemy.engine.base.Engine (1909,)
2019-07-23 11:40:35,631 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,632 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:40:35,634 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,637 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,638 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,639 INFO sqlalchemy.engine.base.Engine (1910,)
2019-07-23 11:40:35,642 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,643 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:40:35,645 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,648 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,649 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,650 INFO sqlalchemy.engine.base.Engine (1911,)
2019-07-23 11:40:35,652 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,652 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:35,654 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,657 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,658 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,658 INFO sqlalchemy.engine.base.Engine (1912,)
2019-07-23 11:40:35,661 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,662 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:40:35,664 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,667 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,668 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,669 INFO sqlalchemy.engine.base.Engine (1913,)
2019-07-23 11:40:35,671 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:35,671 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:35,673 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,676 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,677 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,678 INFO sqlalchemy.engine.base.Engine (1914,)
2019-07-23 11:40:35,681 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,682 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:40:35,684 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,687 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,688 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,689 INFO sqlalchemy.engine.base.Engine (1915,)
2019-07-23 11:40:35,692 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,692 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:40:35,695 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,698 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,699 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,699 INFO sqlalchemy.engine.base.Engine (1916,)
2019-07-23 11:40:35,702 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,703 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:40:35,704 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,708 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,709 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,710 INFO sqlalchemy.engine.base.Engine (1917,)
2019-07-23 11:40:35,712 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,714 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:40:35,715 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,720 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,721 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,722 INFO sqlalchemy.engine.base.Engine (1918,)
2019-07-23 11:40:35,724 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,725 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:40:35,727 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,731 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,732 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,733 INFO sqlalchemy.engine.base.Engine (1919,)
2019-07-23 11:40:35,736 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,736 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:40:35,738 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,741 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,742 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,742 INFO sqlalchemy.engine.base.Engine (1920,)
2019-07-23 11:40:35,745 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,745 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:40:35,747 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,751 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,752 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,753 INFO sqlalchemy.engine.base.Engine (1921,)
2019-07-23 11:40:35,756 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,757 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:40:35,758 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,762 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,762 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,763 INFO sqlalchemy.engine.base.Engine (1922,)
2019-07-23 11:40:35,766 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,768 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:40:35,770 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,773 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,774 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,775 INFO sqlalchemy.engine.base.Engine (1923,)
2019-07-23 11:40:35,778 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,779 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:40:35,780 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,784 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,785 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,786 INFO sqlalchemy.engine.base.Engine (1924,)
2019-07-23 11:40:35,789 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,790 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:40:35,791 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:40:35,795 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,796 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,797 INFO sqlalchemy.engine.base.Engine (1925,)
2019-07-23 11:40:35,800 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,801 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:40:35,802 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,807 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,808 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,809 INFO sqlalchemy.engine.base.Engine (1926,)
2019-07-23 11:40:35,811 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,812 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:40:35,814 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,818 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,819 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,820 INFO sqlalchemy.engine.base.Engine (1927,)
2019-07-23 11:40:35,823 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,824 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:40:35,826 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,831 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,832 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,833 INFO sqlalchemy.engine.base.Engine (1928,)
2019-07-23 11:40:35,835 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,836 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:40:35,838 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,841 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,843 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,844 INFO sqlalchemy.engine.base.Engine (1929,)
2019-07-23 11:40:35,846 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,847 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:40:35,849 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,852 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,853 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,854 INFO sqlalchemy.engine.base.Engine (1930,)
2019-07-23 11:40:35,857 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,858 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:40:35,859 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,863 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,864 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,865 INFO sqlalchemy.engine.base.Engine (1931,)
2019-07-23 11:40:35,868 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,869 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:40:35,870 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,873 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,874 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,874 INFO sqlalchemy.engine.base.Engine (1932,)
2019-07-23 11:40:35,877 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,878 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:40:35,880 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,884 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,886 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,886 INFO sqlalchemy.engine.base.Engine (1933,)
2019-07-23 11:40:35,889 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,890 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:40:35,891 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,894 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,896 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,896 INFO sqlalchemy.engine.base.Engine (1934,)
2019-07-23 11:40:35,899 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,900 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:40:35,902 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,906 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,907 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,907 INFO sqlalchemy.engine.base.Engine (1935,)
2019-07-23 11:40:35,910 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,911 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:40:35,912 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,916 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,917 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:35,918 INFO sqlalchemy.engine.base.Engine (1936,)
2019-07-23 11:40:35,920 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,921 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:40:35,923 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,927 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,928 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,929 INFO sqlalchemy.engine.base.Engine (1937,)
2019-07-23 11:40:35,932 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,933 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:40:35,934 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,937 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,938 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,939 INFO sqlalchemy.engine.base.Engine (1938,)
2019-07-23 11:40:35,942 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,943 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:40:35,944 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,948 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,949 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,949 INFO sqlalchemy.engine.base.Engine (1939,)
2019-07-23 11:40:35,952 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,953 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:40:35,955 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,958 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,959 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,960 INFO sqlalchemy.engine.base.Engine (1940,)
2019-07-23 11:40:35,962 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,962 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:40:35,964 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,967 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,968 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,969 INFO sqlalchemy.engine.base.Engine (1941,)
2019-07-23 11:40:35,971 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,972 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:40:35,974 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,978 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,979 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,980 INFO sqlalchemy.engine.base.Engine (1942,)
2019-07-23 11:40:35,983 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,983 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:40:35,985 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,988 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:35,989 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:35,989 INFO sqlalchemy.engine.base.Engine (1943,)
2019-07-23 11:40:35,992 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:35,993 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:40:35,996 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:35,999 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,000 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,001 INFO sqlalchemy.engine.base.Engine (1944,)
2019-07-23 11:40:36,004 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,005 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:40:36,007 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,010 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,011 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,012 INFO sqlalchemy.engine.base.Engine (1945,)
2019-07-23 11:40:36,015 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,016 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:40:36,018 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,021 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,022 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,023 INFO sqlalchemy.engine.base.Engine (1946,)
2019-07-23 11:40:36,027 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,027 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:40:36,029 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,032 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,033 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,034 INFO sqlalchemy.engine.base.Engine (1947,)
2019-07-23 11:40:36,037 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:36,038 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:40:36,040 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,044 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,045 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,046 INFO sqlalchemy.engine.base.Engine (1948,)
2019-07-23 11:40:36,048 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,049 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:40:36,050 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,054 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,055 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,056 INFO sqlalchemy.engine.base.Engine (1949,)
2019-07-23 11:40:36,058 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,059 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:36,061 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,064 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,065 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,066 INFO sqlalchemy.engine.base.Engine (1950,)
2019-07-23 11:40:36,069 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,070 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:40:36,072 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,076 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,077 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,078 INFO sqlalchemy.engine.base.Engine (1951,)
2019-07-23 11:40:36,082 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,082 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:40:36,084 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,088 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,088 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,089 INFO sqlalchemy.engine.base.Engine (1952,)
2019-07-23 11:40:36,092 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,093 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:36,095 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,098 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,099 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,100 INFO sqlalchemy.engine.base.Engine (1953,)
2019-07-23 11:40:36,103 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,104 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:40:36,106 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,109 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,110 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,111 INFO sqlalchemy.engine.base.Engine (1954,)
2019-07-23 11:40:36,114 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,114 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:40:36,116 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,120 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,121 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,121 INFO sqlalchemy.engine.base.Engine (1955,)
2019-07-23 11:40:36,125 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,126 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:40:36,127 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,131 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,132 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,133 INFO sqlalchemy.engine.base.Engine (1956,)
2019-07-23 11:40:36,136 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,137 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:40:36,138 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,142 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,143 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,143 INFO sqlalchemy.engine.base.Engine (1957,)
2019-07-23 11:40:36,147 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,148 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:40:36,151 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,154 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,155 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,155 INFO sqlalchemy.engine.base.Engine (1958,)
2019-07-23 11:40:36,158 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,159 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:40:36,160 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,164 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:40:36,165 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,165 INFO sqlalchemy.engine.base.Engine (1959,)
2019-07-23 11:40:36,168 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,170 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:36,172 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,176 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,177 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,178 INFO sqlalchemy.engine.base.Engine (1960,)
2019-07-23 11:40:36,180 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,181 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:36,183 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,187 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,188 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,189 INFO sqlalchemy.engine.base.Engine (1961,)
2019-07-23 11:40:36,191 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,192 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:40:36,194 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,197 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,198 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,199 INFO sqlalchemy.engine.base.Engine (1962,)
2019-07-23 11:40:36,201 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,202 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:40:36,204 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,208 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,209 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,210 INFO sqlalchemy.engine.base.Engine (1963,)
2019-07-23 11:40:36,212 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,213 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:40:36,214 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,218 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,219 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,220 INFO sqlalchemy.engine.base.Engine (1964,)
2019-07-23 11:40:36,223 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,224 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:40:36,226 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,229 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,230 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,231 INFO sqlalchemy.engine.base.Engine (1965,)
2019-07-23 11:40:36,234 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,235 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:40:36,238 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,243 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,244 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,245 INFO sqlalchemy.engine.base.Engine (1966,)
2019-07-23 11:40:36,248 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,249 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:40:36,251 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,254 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,256 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,256 INFO sqlalchemy.engine.base.Engine (1967,)
2019-07-23 11:40:36,259 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,260 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:40:36,263 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,266 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,266 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,267 INFO sqlalchemy.engine.base.Engine (1968,)
2019-07-23 11:40:36,271 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,271 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:36,274 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,277 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,279 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,279 INFO sqlalchemy.engine.base.Engine (1969,)
2019-07-23 11:40:36,283 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,284 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:36,286 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,289 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,290 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,291 INFO sqlalchemy.engine.base.Engine (1970,)

2019-07-23 11:40:36,294 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,295 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:40:36,297 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,301 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,302 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,302 INFO sqlalchemy.engine.base.Engine (1971,)
2019-07-23 11:40:36,305 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,306 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:40:36,308 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,312 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,313 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,313 INFO sqlalchemy.engine.base.Engine (1972,)
2019-07-23 11:40:36,316 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,316 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:40:36,319 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,323 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,324 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,324 INFO sqlalchemy.engine.base.Engine (1973,)
2019-07-23 11:40:36,327 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,328 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:40:36,330 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,334 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,336 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,337 INFO sqlalchemy.engine.base.Engine (1974,)
2019-07-23 11:40:36,341 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,342 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:40:36,344 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,348 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,349 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,350 INFO sqlalchemy.engine.base.Engine (1975,)
2019-07-23 11:40:36,353 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,354 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:40:36,357 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,360 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,361 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,361 INFO sqlalchemy.engine.base.Engine (1976,)
2019-07-23 11:40:36,364 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,365 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:40:36,367 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,371 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,372 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,373 INFO sqlalchemy.engine.base.Engine (1977,)
2019-07-23 11:40:36,376 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,376 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:40:36,378 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,382 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,383 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,384 INFO sqlalchemy.engine.base.Engine (1978,)
2019-07-23 11:40:36,388 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,389 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:40:36,390 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,395 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,396 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,397 INFO sqlalchemy.engine.base.Engine (1979,)
2019-07-23 11:40:36,400 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,401 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:40:36,402 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,406 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,407 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,408 INFO sqlalchemy.engine.base.Engine (1980,)
2019-07-23 11:40:36,411 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,412 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:40:36,414 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,418 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,419 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,419 INFO sqlalchemy.engine.base.Engine (1981,)
2019-07-23 11:40:36,422 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,423 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:40:36,425 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,428 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:40:36,429 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,430 INFO sqlalchemy.engine.base.Engine (1982,)
2019-07-23 11:40:36,433 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,434 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:40:36,438 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,441 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,442 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,443 INFO sqlalchemy.engine.base.Engine (1983,)
2019-07-23 11:40:36,447 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,448 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:40:36,449 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,453 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,455 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,455 INFO sqlalchemy.engine.base.Engine (1984,)
2019-07-23 11:40:36,459 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,459 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:40:36,461 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,465 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,466 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,466 INFO sqlalchemy.engine.base.Engine (1985,)
2019-07-23 11:40:36,470 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,471 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:36,473 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,476 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,477 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,478 INFO sqlalchemy.engine.base.Engine (1986,)
2019-07-23 11:40:36,483 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,483 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:36,485 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,490 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,491 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,492 INFO sqlalchemy.engine.base.Engine (1987,)
2019-07-23 11:40:36,495 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,496 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:40:36,498 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,503 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,504 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,505 INFO sqlalchemy.engine.base.Engine (1988,)
2019-07-23 11:40:36,509 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,510 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:40:36,512 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,517 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,518 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,519 INFO sqlalchemy.engine.base.Engine (1989,)
2019-07-23 11:40:36,523 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,524 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:40:36,525 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,530 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,532 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,533 INFO sqlalchemy.engine.base.Engine (1990,)
2019-07-23 11:40:36,537 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,538 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:40:36,540 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,544 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,546 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,547 INFO sqlalchemy.engine.base.Engine (1991,)
2019-07-23 11:40:36,550 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,551 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:40:36,553 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,557 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,558 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,558 INFO sqlalchemy.engine.base.Engine (1992,)
2019-07-23 11:40:36,561 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,562 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:40:36,564 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,568 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,569 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,570 INFO sqlalchemy.engine.base.Engine (1993,)

2019-07-23 11:40:36,573 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,574 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:40:36,577 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,581 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,584 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,585 INFO sqlalchemy.engine.base.Engine (1994,)
2019-07-23 11:40:36,589 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,590 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:40:36,591 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,595 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,596 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,597 INFO sqlalchemy.engine.base.Engine (1995,)
2019-07-23 11:40:36,600 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,600 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:40:36,603 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,606 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,607 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,608 INFO sqlalchemy.engine.base.Engine (1996,)
2019-07-23 11:40:36,612 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,613 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:40:36,615 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,618 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,619 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,620 INFO sqlalchemy.engine.base.Engine (1997,)
2019-07-23 11:40:36,623 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,624 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:40:36,626 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,629 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,630 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,631 INFO sqlalchemy.engine.base.Engine (1998,)
2019-07-23 11:40:36,634 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,636 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:36,638 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,642 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,643 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,643 INFO sqlalchemy.engine.base.Engine (1999,)
2019-07-23 11:40:36,646 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,647 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:40:36,650 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,654 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,655 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,656 INFO sqlalchemy.engine.base.Engine (2000,)
2019-07-23 11:40:36,659 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,660 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:40:36,662 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,666 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,667 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,667 INFO sqlalchemy.engine.base.Engine (2001,)
2019-07-23 11:40:36,672 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,673 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:40:36,674 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,678 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,679 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,680 INFO sqlalchemy.engine.base.Engine (2002,)
2019-07-23 11:40:36,683 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,683 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:40:36,685 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,689 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,690 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,691 INFO sqlalchemy.engine.base.Engine (2003,)
2019-07-23 11:40:36,693 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,694 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:40:36,696 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,701 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,702 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,703 INFO sqlalchemy.engine.base.Engine (2004,)
2019-07-23 11:40:36,705 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,706 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')

2019-07-23 11:40:36,708 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,711 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,712 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,712 INFO sqlalchemy.engine.base.Engine (2005,)
2019-07-23 11:40:36,716 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,717 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:36,719 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,724 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,725 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,726 INFO sqlalchemy.engine.base.Engine (2006,)
2019-07-23 11:40:36,729 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,730 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:40:36,733 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,736 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,738 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,738 INFO sqlalchemy.engine.base.Engine (2007,)
2019-07-23 11:40:36,742 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,743 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:40:36,745 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,749 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,750 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,751 INFO sqlalchemy.engine.base.Engine (2008,)
2019-07-23 11:40:36,754 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,755 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:40:36,757 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,761 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,762 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,764 INFO sqlalchemy.engine.base.Engine (2009,)
2019-07-23 11:40:36,767 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,768 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:40:36,770 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,773 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,774 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,775 INFO sqlalchemy.engine.base.Engine (2010,)
2019-07-23 11:40:36,777 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,778 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:40:36,781 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,786 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,787 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,788 INFO sqlalchemy.engine.base.Engine (2011,)
2019-07-23 11:40:36,792 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,793 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:40:36,794 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,798 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,799 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,799 INFO sqlalchemy.engine.base.Engine (2012,)
2019-07-23 11:40:36,804 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,805 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:40:36,807 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,811 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,812 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,813 INFO sqlalchemy.engine.base.Engine (2013,)
2019-07-23 11:40:36,816 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,817 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:40:36,819 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,823 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,824 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,825 INFO sqlalchemy.engine.base.Engine (2014,)
2019-07-23 11:40:36,830 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,832 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:40:36,835 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,838 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,839 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,840 INFO sqlalchemy.engine.base.Engine (2015,)
2019-07-23 11:40:36,843 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,844 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:40:36,847 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,850 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,852 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:36,852 INFO sqlalchemy.engine.base.Engine (2016,)
2019-07-23 11:40:36,857 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,857 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:40:36,860 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,864 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,865 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,865 INFO sqlalchemy.engine.base.Engine (2017,)
2019-07-23 11:40:36,869 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,870 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:40:36,872 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,875 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,876 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,877 INFO sqlalchemy.engine.base.Engine (2018,)
2019-07-23 11:40:36,880 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,881 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:40:36,884 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,888 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,890 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,891 INFO sqlalchemy.engine.base.Engine (2019,)
2019-07-23 11:40:36,895 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,896 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:40:36,899 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,903 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,904 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,905 INFO sqlalchemy.engine.base.Engine (2020,)
2019-07-23 11:40:36,909 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,910 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:40:36,912 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,916 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,917 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,918 INFO sqlalchemy.engine.base.Engine (2021,)
2019-07-23 11:40:36,921 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,922 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:40:36,924 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,928 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,929 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,930 INFO sqlalchemy.engine.base.Engine (2022,)
2019-07-23 11:40:36,934 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,936 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:40:36,938 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,942 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,943 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,945 INFO sqlalchemy.engine.base.Engine (2023,)
2019-07-23 11:40:36,949 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,950 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:40:36,952 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,957 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,959 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,959 INFO sqlalchemy.engine.base.Engine (2024,)
2019-07-23 11:40:36,963 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,964 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:40:36,967 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,971 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,972 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,974 INFO sqlalchemy.engine.base.Engine (2025,)
2019-07-23 11:40:36,977 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,978 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:40:36,980 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,984 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:36,985 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:36,986 INFO sqlalchemy.engine.base.Engine (2026,)
2019-07-23 11:40:36,990 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:36,992 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:40:36,995 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:36,999 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,001 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,002 INFO sqlalchemy.engine.base.Engine (2027,)
2019-07-23 11:40:37,005 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,007 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')

2019-07-23 11:40:37,009 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,013 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,014 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,015 INFO sqlalchemy.engine.base.Engine (2028,)
2019-07-23 11:40:37,018 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,019 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:40:37,021 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,025 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,026 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,028 INFO sqlalchemy.engine.base.Engine (2029,)
2019-07-23 11:40:37,030 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,031 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:40:37,034 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,038 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,039 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,040 INFO sqlalchemy.engine.base.Engine (2030,)
2019-07-23 11:40:37,044 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,045 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:40:37,047 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,051 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,052 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,054 INFO sqlalchemy.engine.base.Engine (2031,)
2019-07-23 11:40:37,058 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,059 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:40:37,061 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,065 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,066 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,067 INFO sqlalchemy.engine.base.Engine (2032,)
2019-07-23 11:40:37,070 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,071 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:40:37,073 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,077 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,078 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,079 INFO sqlalchemy.engine.base.Engine (2033,)
2019-07-23 11:40:37,083 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,084 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:40:37,087 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,090 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,091 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,091 INFO sqlalchemy.engine.base.Engine (2034,)
2019-07-23 11:40:37,094 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,095 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:40:37,097 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,103 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,104 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,105 INFO sqlalchemy.engine.base.Engine (2035,)
2019-07-23 11:40:37,108 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,109 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:40:37,111 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,114 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,115 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,116 INFO sqlalchemy.engine.base.Engine (2036,)
2019-07-23 11:40:37,120 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,120 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:40:37,123 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,127 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,128 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,129 INFO sqlalchemy.engine.base.Engine (2037,)
2019-07-23 11:40:37,132 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,133 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:40:37,135 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,139 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,141 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,142 INFO sqlalchemy.engine.base.Engine (2038,)
2019-07-23 11:40:37,145 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,146 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:40:37,149 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,152 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,153 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:37,154 INFO sqlalchemy.engine.base.Engine (2039,)
2019-07-23 11:40:37,157 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,158 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:40:37,161 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,164 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,165 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,166 INFO sqlalchemy.engine.base.Engine (2040,)
2019-07-23 11:40:37,169 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,170 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:40:37,173 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,177 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,178 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,179 INFO sqlalchemy.engine.base.Engine (2041,)
2019-07-23 11:40:37,183 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,183 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:40:37,185 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,189 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,191 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,191 INFO sqlalchemy.engine.base.Engine (2042,)
2019-07-23 11:40:37,195 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:37,196 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:40:37,199 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:37,203 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:37,204 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:37,204 INFO sqlalchemy.engine.base.Engine (2043,)
http://sz.ganji.com/zufang/pn1 status: 200
2019-07-23 11:40:38,139 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,140 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:40:38,142 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,146 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,147 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,148 INFO sqlalchemy.engine.base.Engine (2044,)
2019-07-23 11:40:38,150 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,151 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:40:38,153 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,157 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,158 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,159 INFO sqlalchemy.engine.base.Engine (2045,)
2019-07-23 11:40:38,163 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,163 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:40:38,164 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,168 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,169 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,170 INFO sqlalchemy.engine.base.Engine (2046,)
2019-07-23 11:40:38,173 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,174 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:40:38,176 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,181 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,182 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,183 INFO sqlalchemy.engine.base.Engine (2047,)
2019-07-23 11:40:38,186 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,187 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:40:38,189 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,192 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,193 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,194 INFO sqlalchemy.engine.base.Engine (2048,)
2019-07-23 11:40:38,198 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,199 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:40:38,201 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,205 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,206 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,207 INFO sqlalchemy.engine.base.Engine (2049,)
2019-07-23 11:40:38,209 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,210 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:40:38,212 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,216 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,218 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,219 INFO sqlalchemy.engine.base.Engine (2050,)
2019-07-23 11:40:38,222 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:38,223 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:38,225 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,230 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,231 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,232 INFO sqlalchemy.engine.base.Engine (2051,)
2019-07-23 11:40:38,235 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,236 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:40:38,238 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,242 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,243 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,243 INFO sqlalchemy.engine.base.Engine (2052,)
2019-07-23 11:40:38,247 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,248 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:38,251 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,254 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,255 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,256 INFO sqlalchemy.engine.base.Engine (2053,)
2019-07-23 11:40:38,259 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,260 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:40:38,262 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,266 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,267 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,268 INFO sqlalchemy.engine.base.Engine (2054,)
2019-07-23 11:40:38,270 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,271 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:40:38,272 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,277 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,278 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,278 INFO sqlalchemy.engine.base.Engine (2055,)
2019-07-23 11:40:38,282 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,283 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:40:38,284 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,288 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,289 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,290 INFO sqlalchemy.engine.base.Engine (2056,)
2019-07-23 11:40:38,293 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,294 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:40:38,298 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,302 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,303 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,303 INFO sqlalchemy.engine.base.Engine (2057,)
2019-07-23 11:40:38,307 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,308 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:40:38,310 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,315 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,316 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,317 INFO sqlalchemy.engine.base.Engine (2058,)
2019-07-23 11:40:38,320 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,321 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:40:38,322 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,327 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,328 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,329 INFO sqlalchemy.engine.base.Engine (2059,)
2019-07-23 11:40:38,333 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,334 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:40:38,337 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,341 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,342 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,343 INFO sqlalchemy.engine.base.Engine (2060,)
2019-07-23 11:40:38,346 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,347 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:40:38,349 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,353 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,355 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,355 INFO sqlalchemy.engine.base.Engine (2061,)
2019-07-23 11:40:38,359 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,360 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:40:38,362 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:40:38,366 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,367 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,368 INFO sqlalchemy.engine.base.Engine (2062,)
2019-07-23 11:40:38,371 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,372 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:40:38,374 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,379 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,380 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,380 INFO sqlalchemy.engine.base.Engine (2063,)
2019-07-23 11:40:38,384 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,385 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:40:38,387 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,392 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,393 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,394 INFO sqlalchemy.engine.base.Engine (2064,)
2019-07-23 11:40:38,398 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,398 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:40:38,400 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,405 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,406 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,407 INFO sqlalchemy.engine.base.Engine (2065,)
2019-07-23 11:40:38,409 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,410 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:40:38,413 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,417 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,418 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,419 INFO sqlalchemy.engine.base.Engine (2066,)
2019-07-23 11:40:38,423 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,424 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:40:38,427 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,430 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,431 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,432 INFO sqlalchemy.engine.base.Engine (2067,)
2019-07-23 11:40:38,435 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,436 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:40:38,438 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,442 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,443 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,445 INFO sqlalchemy.engine.base.Engine (2068,)
2019-07-23 11:40:38,448 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,449 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:40:38,450 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,454 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,455 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,456 INFO sqlalchemy.engine.base.Engine (2069,)
2019-07-23 11:40:38,459 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,460 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:40:38,462 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,467 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,468 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,468 INFO sqlalchemy.engine.base.Engine (2070,)
2019-07-23 11:40:38,472 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,473 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:40:38,475 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,479 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,480 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,481 INFO sqlalchemy.engine.base.Engine (2071,)
2019-07-23 11:40:38,485 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,486 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:40:38,487 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,491 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,492 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,493 INFO sqlalchemy.engine.base.Engine (2072,)
2019-07-23 11:40:38,496 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,497 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:40:38,499 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,504 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,506 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:38,506 INFO sqlalchemy.engine.base.Engine (2073,)
2019-07-23 11:40:38,510 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,511 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:40:38,513 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,518 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,519 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,520 INFO sqlalchemy.engine.base.Engine (2074,)
2019-07-23 11:40:38,522 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,523 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:40:38,525 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,529 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,530 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,531 INFO sqlalchemy.engine.base.Engine (2075,)
2019-07-23 11:40:38,535 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,536 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:40:38,538 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,542 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,543 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,544 INFO sqlalchemy.engine.base.Engine (2076,)
2019-07-23 11:40:38,548 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,548 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:40:38,551 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,555 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,557 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,558 INFO sqlalchemy.engine.base.Engine (2077,)
2019-07-23 11:40:38,561 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,562 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:40:38,564 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,568 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,570 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,570 INFO sqlalchemy.engine.base.Engine (2078,)
2019-07-23 11:40:38,574 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,575 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:40:38,577 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,582 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,583 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,583 INFO sqlalchemy.engine.base.Engine (2079,)
2019-07-23 11:40:38,587 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,587 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:40:38,590 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,595 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,596 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,596 INFO sqlalchemy.engine.base.Engine (2080,)
2019-07-23 11:40:38,599 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,600 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:40:38,602 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,607 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,608 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,609 INFO sqlalchemy.engine.base.Engine (2081,)
2019-07-23 11:40:38,612 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,613 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:40:38,615 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,620 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,622 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,622 INFO sqlalchemy.engine.base.Engine (2082,)
2019-07-23 11:40:38,626 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,627 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:40:38,629 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,634 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,636 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,636 INFO sqlalchemy.engine.base.Engine (2083,)
2019-07-23 11:40:38,640 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,642 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:40:38,644 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,648 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,650 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,651 INFO sqlalchemy.engine.base.Engine (2084,)
2019-07-23 11:40:38,654 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,655 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')

2019-07-23 11:40:38,656 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,661 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,662 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,663 INFO sqlalchemy.engine.base.Engine (2085,)
2019-07-23 11:40:38,666 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,668 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:40:38,670 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,674 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,676 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,677 INFO sqlalchemy.engine.base.Engine (2086,)
2019-07-23 11:40:38,681 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,682 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:40:38,684 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,689 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,691 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,691 INFO sqlalchemy.engine.base.Engine (2087,)
2019-07-23 11:40:38,695 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,696 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:40:38,697 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,702 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,703 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,704 INFO sqlalchemy.engine.base.Engine (2088,)
2019-07-23 11:40:38,707 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,708 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:38,711 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,715 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,716 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,717 INFO sqlalchemy.engine.base.Engine (2089,)
2019-07-23 11:40:38,721 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,722 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:40:38,724 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,728 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,729 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,729 INFO sqlalchemy.engine.base.Engine (2090,)
2019-07-23 11:40:38,733 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,734 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:40:38,736 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,741 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,742 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,743 INFO sqlalchemy.engine.base.Engine (2091,)
2019-07-23 11:40:38,746 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,747 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:38,749 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,753 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,754 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,755 INFO sqlalchemy.engine.base.Engine (2092,)
2019-07-23 11:40:38,759 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,760 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:40:38,761 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,765 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,767 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,767 INFO sqlalchemy.engine.base.Engine (2093,)
2019-07-23 11:40:38,771 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,772 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:40:38,774 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,780 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,781 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,782 INFO sqlalchemy.engine.base.Engine (2094,)
2019-07-23 11:40:38,786 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,787 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:40:38,789 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,793 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,795 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,796 INFO sqlalchemy.engine.base.Engine (2095,)
2019-07-23 11:40:38,799 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,800 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:40:38,802 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,807 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,808 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:38,809 INFO sqlalchemy.engine.base.Engine (2096,)
2019-07-23 11:40:38,812 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,813 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:40:38,815 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,820 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,821 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,821 INFO sqlalchemy.engine.base.Engine (2097,)
2019-07-23 11:40:38,826 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,827 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:40:38,829 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,833 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,835 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,835 INFO sqlalchemy.engine.base.Engine (2098,)
2019-07-23 11:40:38,838 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,839 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:38,842 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,847 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,848 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,849 INFO sqlalchemy.engine.base.Engine (2099,)
2019-07-23 11:40:38,852 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,853 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:38,855 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,860 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,861 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,862 INFO sqlalchemy.engine.base.Engine (2100,)
2019-07-23 11:40:38,866 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,867 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:40:38,870 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,873 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,875 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,875 INFO sqlalchemy.engine.base.Engine (2101,)
2019-07-23 11:40:38,879 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,880 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:40:38,882 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,886 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,887 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,888 INFO sqlalchemy.engine.base.Engine (2102,)
2019-07-23 11:40:38,891 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,893 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:40:38,896 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,901 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,902 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,903 INFO sqlalchemy.engine.base.Engine (2103,)
2019-07-23 11:40:38,906 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,907 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:40:38,909 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,913 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,915 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,915 INFO sqlalchemy.engine.base.Engine (2104,)
2019-07-23 11:40:38,919 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,920 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:40:38,922 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,927 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,928 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,929 INFO sqlalchemy.engine.base.Engine (2105,)
2019-07-23 11:40:38,934 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,935 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:40:38,936 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,941 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,942 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,943 INFO sqlalchemy.engine.base.Engine (2106,)
2019-07-23 11:40:38,946 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,948 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:40:38,950 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,954 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,956 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,958 INFO sqlalchemy.engine.base.Engine (2107,)
2019-07-23 11:40:38,961 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,962 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')

2019-07-23 11:40:38,964 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,968 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,969 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,970 INFO sqlalchemy.engine.base.Engine (2108,)
2019-07-23 11:40:38,973 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,975 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:38,977 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,982 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,984 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:38,985 INFO sqlalchemy.engine.base.Engine (2109,)
2019-07-23 11:40:38,988 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:38,990 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:40:38,992 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:38,998 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:38,999 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,000 INFO sqlalchemy.engine.base.Engine (2110,)
2019-07-23 11:40:39,003 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,004 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:40:39,007 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,011 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,012 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,013 INFO sqlalchemy.engine.base.Engine (2111,)
2019-07-23 11:40:39,017 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,018 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:40:39,021 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,025 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,026 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,028 INFO sqlalchemy.engine.base.Engine (2112,)
2019-07-23 11:40:39,031 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,032 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:40:39,034 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,039 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,040 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,041 INFO sqlalchemy.engine.base.Engine (2113,)
2019-07-23 11:40:39,045 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,046 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:40:39,049 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,054 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,055 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,056 INFO sqlalchemy.engine.base.Engine (2114,)
2019-07-23 11:40:39,060 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,061 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:40:39,064 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,068 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,070 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,071 INFO sqlalchemy.engine.base.Engine (2115,)
2019-07-23 11:40:39,075 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,076 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:40:39,079 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,084 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,086 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,087 INFO sqlalchemy.engine.base.Engine (2116,)
2019-07-23 11:40:39,090 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,091 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:40:39,093 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,098 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,100 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,101 INFO sqlalchemy.engine.base.Engine (2117,)
2019-07-23 11:40:39,105 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,106 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:40:39,108 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,113 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,114 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,116 INFO sqlalchemy.engine.base.Engine (2118,)
2019-07-23 11:40:39,121 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,122 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:40:39,125 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,129 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,130 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:39,131 INFO sqlalchemy.engine.base.Engine (2119,)
2019-07-23 11:40:39,135 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,136 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:40:39,138 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,142 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,143 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,144 INFO sqlalchemy.engine.base.Engine (2120,)
2019-07-23 11:40:39,148 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,149 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:40:39,151 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,156 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,157 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,158 INFO sqlalchemy.engine.base.Engine (2121,)
2019-07-23 11:40:39,160 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,161 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:40:39,164 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,169 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,170 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,171 INFO sqlalchemy.engine.base.Engine (2122,)
2019-07-23 11:40:39,174 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,175 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:40:39,177 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,182 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,183 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,185 INFO sqlalchemy.engine.base.Engine (2123,)
2019-07-23 11:40:39,189 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,189 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:40:39,192 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,197 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,198 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,199 INFO sqlalchemy.engine.base.Engine (2124,)
2019-07-23 11:40:39,203 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,204 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:39,206 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,210 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,211 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,211 INFO sqlalchemy.engine.base.Engine (2125,)
2019-07-23 11:40:39,215 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,215 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:39,218 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,223 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,224 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,225 INFO sqlalchemy.engine.base.Engine (2126,)
2019-07-23 11:40:39,228 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,229 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:40:39,232 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,237 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,238 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,239 INFO sqlalchemy.engine.base.Engine (2127,)
2019-07-23 11:40:39,241 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,241 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:40:39,243 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,247 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,249 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,250 INFO sqlalchemy.engine.base.Engine (2128,)
2019-07-23 11:40:39,253 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,254 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:40:39,256 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,261 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,263 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,264 INFO sqlalchemy.engine.base.Engine (2129,)
2019-07-23 11:40:39,269 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,270 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:40:39,273 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,277 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,278 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,279 INFO sqlalchemy.engine.base.Engine (2130,)
2019-07-23 11:40:39,283 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,284 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')

2019-07-23 11:40:39,287 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,291 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,293 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,294 INFO sqlalchemy.engine.base.Engine (2131,)
2019-07-23 11:40:39,298 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,299 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:40:39,302 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,305 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,307 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,307 INFO sqlalchemy.engine.base.Engine (2132,)
2019-07-23 11:40:39,311 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,312 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:40:39,314 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,318 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,319 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,320 INFO sqlalchemy.engine.base.Engine (2133,)
2019-07-23 11:40:39,323 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,324 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:40:39,327 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,332 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,334 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,335 INFO sqlalchemy.engine.base.Engine (2134,)
2019-07-23 11:40:39,339 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,340 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:40:39,343 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,348 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,349 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,350 INFO sqlalchemy.engine.base.Engine (2135,)
2019-07-23 11:40:39,353 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,355 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:40:39,358 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,361 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,363 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,364 INFO sqlalchemy.engine.base.Engine (2136,)
2019-07-23 11:40:39,366 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,367 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:40:39,369 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,374 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,375 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,376 INFO sqlalchemy.engine.base.Engine (2137,)
2019-07-23 11:40:39,380 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,381 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:39,383 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,388 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,390 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,391 INFO sqlalchemy.engine.base.Engine (2138,)
2019-07-23 11:40:39,394 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,396 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:40:39,398 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,402 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,403 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,404 INFO sqlalchemy.engine.base.Engine (2139,)
2019-07-23 11:40:39,407 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,408 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:40:39,411 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,416 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,417 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,419 INFO sqlalchemy.engine.base.Engine (2140,)
2019-07-23 11:40:39,422 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,423 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:40:39,425 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,428 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,430 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,430 INFO sqlalchemy.engine.base.Engine (2141,)
2019-07-23 11:40:39,434 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,435 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:40:39,437 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,441 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,443 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:39,444 INFO sqlalchemy.engine.base.Engine (2142,)
2019-07-23 11:40:39,448 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,449 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:40:39,452 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,456 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,458 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,458 INFO sqlalchemy.engine.base.Engine (2143,)
2019-07-23 11:40:39,462 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,462 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:40:39,465 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,469 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,470 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,471 INFO sqlalchemy.engine.base.Engine (2144,)
2019-07-23 11:40:39,473 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,474 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:39,477 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,482 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,484 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,485 INFO sqlalchemy.engine.base.Engine (2145,)
2019-07-23 11:40:39,489 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,490 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:40:39,492 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,496 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,497 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,498 INFO sqlalchemy.engine.base.Engine (2146,)
2019-07-23 11:40:39,502 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,503 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:40:39,506 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,512 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,513 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,515 INFO sqlalchemy.engine.base.Engine (2147,)
2019-07-23 11:40:39,518 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,519 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:40:39,522 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,527 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,528 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,529 INFO sqlalchemy.engine.base.Engine (2148,)
2019-07-23 11:40:39,531 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,532 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:40:39,535 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,540 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,541 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,542 INFO sqlalchemy.engine.base.Engine (2149,)
2019-07-23 11:40:39,547 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,548 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:40:39,550 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,555 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,556 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,557 INFO sqlalchemy.engine.base.Engine (2150,)
2019-07-23 11:40:39,560 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,560 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:40:39,562 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,568 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,569 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,570 INFO sqlalchemy.engine.base.Engine (2151,)
2019-07-23 11:40:39,576 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,577 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:40:39,579 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,583 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,585 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,586 INFO sqlalchemy.engine.base.Engine (2152,)
2019-07-23 11:40:39,591 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,592 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:40:39,595 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,599 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,600 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,601 INFO sqlalchemy.engine.base.Engine (2153,)
2019-07-23 11:40:39,604 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,605 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')

2019-07-23 11:40:39,608 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,612 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,613 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,614 INFO sqlalchemy.engine.base.Engine (2154,)
2019-07-23 11:40:39,617 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,618 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:40:39,621 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,625 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,626 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,627 INFO sqlalchemy.engine.base.Engine (2155,)
2019-07-23 11:40:39,631 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,632 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:40:39,634 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,639 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,641 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,642 INFO sqlalchemy.engine.base.Engine (2156,)
2019-07-23 11:40:39,647 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,648 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:40:39,651 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,655 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,656 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,657 INFO sqlalchemy.engine.base.Engine (2157,)
2019-07-23 11:40:39,660 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,661 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:40:39,663 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,667 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,668 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,669 INFO sqlalchemy.engine.base.Engine (2158,)
2019-07-23 11:40:39,672 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,673 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:40:39,675 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,680 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,682 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,683 INFO sqlalchemy.engine.base.Engine (2159,)
2019-07-23 11:40:39,686 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,687 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:40:39,690 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,694 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,696 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,696 INFO sqlalchemy.engine.base.Engine (2160,)
2019-07-23 11:40:39,701 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,702 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:40:39,705 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,710 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,711 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,712 INFO sqlalchemy.engine.base.Engine (2161,)
2019-07-23 11:40:39,716 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,716 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:40:39,719 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,723 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,724 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,725 INFO sqlalchemy.engine.base.Engine (2162,)
2019-07-23 11:40:39,728 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,730 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:40:39,732 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,737 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,739 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,740 INFO sqlalchemy.engine.base.Engine (2163,)
2019-07-23 11:40:39,742 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,743 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:40:39,746 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,751 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,752 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,753 INFO sqlalchemy.engine.base.Engine (2164,)
2019-07-23 11:40:39,756 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,757 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:40:39,759 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,764 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,765 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:39,766 INFO sqlalchemy.engine.base.Engine (2165,)
2019-07-23 11:40:39,769 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,770 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:40:39,773 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,777 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,778 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,779 INFO sqlalchemy.engine.base.Engine (2166,)
2019-07-23 11:40:39,783 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,784 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:40:39,786 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,792 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,793 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,794 INFO sqlalchemy.engine.base.Engine (2167,)
2019-07-23 11:40:39,798 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,800 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:40:39,803 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,808 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,809 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,810 INFO sqlalchemy.engine.base.Engine (2168,)
2019-07-23 11:40:39,813 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,814 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:40:39,817 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,822 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,823 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,824 INFO sqlalchemy.engine.base.Engine (2169,)
2019-07-23 11:40:39,827 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,828 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:40:39,830 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,836 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,837 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,838 INFO sqlalchemy.engine.base.Engine (2170,)
2019-07-23 11:40:39,842 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,845 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:40:39,848 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,853 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,854 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,855 INFO sqlalchemy.engine.base.Engine (2171,)
2019-07-23 11:40:39,859 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,860 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:40:39,863 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,868 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,870 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,872 INFO sqlalchemy.engine.base.Engine (2172,)
2019-07-23 11:40:39,876 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,877 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:40:39,880 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,885 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,887 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,888 INFO sqlalchemy.engine.base.Engine (2173,)
2019-07-23 11:40:39,892 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,894 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:40:39,896 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,900 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,901 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,902 INFO sqlalchemy.engine.base.Engine (2174,)
2019-07-23 11:40:39,906 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,907 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:40:39,909 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,913 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,915 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,916 INFO sqlalchemy.engine.base.Engine (2175,)
2019-07-23 11:40:39,920 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,920 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:40:39,923 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,927 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,928 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,930 INFO sqlalchemy.engine.base.Engine (2176,)
2019-07-23 11:40:39,934 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,935 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')

2019-07-23 11:40:39,938 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,944 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,946 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,947 INFO sqlalchemy.engine.base.Engine (2177,)
2019-07-23 11:40:39,953 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,954 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:40:39,957 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,961 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,963 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,964 INFO sqlalchemy.engine.base.Engine (2178,)
2019-07-23 11:40:39,966 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,967 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:40:39,969 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,975 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,976 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,977 INFO sqlalchemy.engine.base.Engine (2179,)
2019-07-23 11:40:39,981 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,982 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:40:39,985 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:39,990 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:39,992 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:39,993 INFO sqlalchemy.engine.base.Engine (2180,)
2019-07-23 11:40:39,997 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:39,998 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:40:40,000 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:40,005 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:40,006 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:40,007 INFO sqlalchemy.engine.base.Engine (2181,)
2019-07-23 11:40:40,011 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:40,012 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:40:40,015 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:40,019 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:40,020 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:40,021 INFO sqlalchemy.engine.base.Engine (2182,)
http://sz.ganji.com/zufang/pn2 status: 200
2019-07-23 11:40:41,076 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,077 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:40:41,079 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,085 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,086 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,087 INFO sqlalchemy.engine.base.Engine (2183,)
2019-07-23 11:40:41,091 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,092 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:40:41,094 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,098 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,099 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,100 INFO sqlalchemy.engine.base.Engine (2184,)
2019-07-23 11:40:41,103 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,104 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:40:41,106 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,110 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,112 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,112 INFO sqlalchemy.engine.base.Engine (2185,)
2019-07-23 11:40:41,116 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,117 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:40:41,119 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,123 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,124 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,125 INFO sqlalchemy.engine.base.Engine (2186,)
2019-07-23 11:40:41,129 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,130 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:40:41,132 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,136 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,137 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,138 INFO sqlalchemy.engine.base.Engine (2187,)
2019-07-23 11:40:41,141 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,141 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:40:41,144 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,148 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,149 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:41,150 INFO sqlalchemy.engine.base.Engine (2188,)
2019-07-23 11:40:41,154 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,156 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:40:41,158 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,162 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,163 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,163 INFO sqlalchemy.engine.base.Engine (2189,)
2019-07-23 11:40:41,167 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,168 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:41,170 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,174 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,175 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,175 INFO sqlalchemy.engine.base.Engine (2190,)
2019-07-23 11:40:41,178 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,179 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:40:41,182 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,186 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,187 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,188 INFO sqlalchemy.engine.base.Engine (2191,)
2019-07-23 11:40:41,191 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,192 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:41,194 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,199 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,200 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,200 INFO sqlalchemy.engine.base.Engine (2192,)
2019-07-23 11:40:41,203 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,204 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:40:41,206 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,211 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,212 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,213 INFO sqlalchemy.engine.base.Engine (2193,)
2019-07-23 11:40:41,216 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,217 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:40:41,219 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,223 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,224 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,225 INFO sqlalchemy.engine.base.Engine (2194,)
2019-07-23 11:40:41,229 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,231 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:40:41,233 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,237 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,238 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,238 INFO sqlalchemy.engine.base.Engine (2195,)
2019-07-23 11:40:41,241 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,242 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:40:41,244 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,250 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,251 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,252 INFO sqlalchemy.engine.base.Engine (2196,)
2019-07-23 11:40:41,255 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,256 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:40:41,258 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,262 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,263 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,264 INFO sqlalchemy.engine.base.Engine (2197,)
2019-07-23 11:40:41,266 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,267 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:40:41,268 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,272 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,273 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,274 INFO sqlalchemy.engine.base.Engine (2198,)
2019-07-23 11:40:41,278 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,279 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:40:41,281 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,285 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,287 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,288 INFO sqlalchemy.engine.base.Engine (2199,)
2019-07-23 11:40:41,292 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,292 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')

2019-07-23 11:40:41,294 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,298 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,299 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,300 INFO sqlalchemy.engine.base.Engine (2200,)
2019-07-23 11:40:41,303 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,304 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:40:41,307 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,311 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,312 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,314 INFO sqlalchemy.engine.base.Engine (2201,)
2019-07-23 11:40:41,318 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,319 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:40:41,321 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,324 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,325 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,326 INFO sqlalchemy.engine.base.Engine (2202,)
2019-07-23 11:40:41,329 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,330 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:40:41,333 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,337 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,338 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,340 INFO sqlalchemy.engine.base.Engine (2203,)
2019-07-23 11:40:41,343 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,344 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:40:41,346 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,351 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,352 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,353 INFO sqlalchemy.engine.base.Engine (2204,)
2019-07-23 11:40:41,356 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,357 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:40:41,360 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,363 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,364 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,365 INFO sqlalchemy.engine.base.Engine (2205,)
2019-07-23 11:40:41,368 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,369 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:40:41,371 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,375 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,376 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,377 INFO sqlalchemy.engine.base.Engine (2206,)
2019-07-23 11:40:41,380 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,381 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:40:41,384 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,388 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,389 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,390 INFO sqlalchemy.engine.base.Engine (2207,)
2019-07-23 11:40:41,393 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,394 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:40:41,396 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,401 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,403 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,404 INFO sqlalchemy.engine.base.Engine (2208,)
2019-07-23 11:40:41,408 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,408 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:40:41,411 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,414 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,415 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,416 INFO sqlalchemy.engine.base.Engine (2209,)
2019-07-23 11:40:41,420 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,420 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:40:41,423 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,428 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,429 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,430 INFO sqlalchemy.engine.base.Engine (2210,)
2019-07-23 11:40:41,434 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,435 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:40:41,437 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,442 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,444 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:41,445 INFO sqlalchemy.engine.base.Engine (2211,)
2019-07-23 11:40:41,448 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,449 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:40:41,451 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,455 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,456 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,457 INFO sqlalchemy.engine.base.Engine (2212,)
2019-07-23 11:40:41,460 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,461 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:40:41,464 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,469 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,470 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,471 INFO sqlalchemy.engine.base.Engine (2213,)
2019-07-23 11:40:41,473 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,474 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:40:41,476 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,481 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,482 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,483 INFO sqlalchemy.engine.base.Engine (2214,)
2019-07-23 11:40:41,486 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,488 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:40:41,491 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,495 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,496 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,497 INFO sqlalchemy.engine.base.Engine (2215,)
2019-07-23 11:40:41,501 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,502 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:40:41,504 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,508 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,510 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,511 INFO sqlalchemy.engine.base.Engine (2216,)
2019-07-23 11:40:41,514 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,515 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:40:41,517 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,522 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,523 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,524 INFO sqlalchemy.engine.base.Engine (2217,)
2019-07-23 11:40:41,528 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,529 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:40:41,532 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,536 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,537 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,537 INFO sqlalchemy.engine.base.Engine (2218,)
2019-07-23 11:40:41,541 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,541 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:40:41,544 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,548 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,549 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,550 INFO sqlalchemy.engine.base.Engine (2219,)
2019-07-23 11:40:41,553 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,554 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:40:41,556 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,560 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,561 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,562 INFO sqlalchemy.engine.base.Engine (2220,)
2019-07-23 11:40:41,564 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,565 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:40:41,568 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,573 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,574 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,574 INFO sqlalchemy.engine.base.Engine (2221,)
2019-07-23 11:40:41,578 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,579 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:40:41,581 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,585 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,586 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,587 INFO sqlalchemy.engine.base.Engine (2222,)
2019-07-23 11:40:41,590 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,592 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')

2019-07-23 11:40:41,595 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,598 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,600 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,600 INFO sqlalchemy.engine.base.Engine (2223,)
2019-07-23 11:40:41,604 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,605 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:40:41,607 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,610 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,612 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,613 INFO sqlalchemy.engine.base.Engine (2224,)
2019-07-23 11:40:41,616 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,617 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:40:41,620 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,624 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,625 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,626 INFO sqlalchemy.engine.base.Engine (2225,)
2019-07-23 11:40:41,629 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,630 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:40:41,632 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,636 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,637 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,637 INFO sqlalchemy.engine.base.Engine (2226,)
2019-07-23 11:40:41,640 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,641 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:40:41,644 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,649 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,651 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,652 INFO sqlalchemy.engine.base.Engine (2227,)
2019-07-23 11:40:41,655 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,656 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:41,658 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,662 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,663 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,664 INFO sqlalchemy.engine.base.Engine (2228,)
2019-07-23 11:40:41,668 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,669 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:40:41,671 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,675 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,676 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,676 INFO sqlalchemy.engine.base.Engine (2229,)
2019-07-23 11:40:41,680 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,681 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:40:41,683 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,687 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,688 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,689 INFO sqlalchemy.engine.base.Engine (2230,)
2019-07-23 11:40:41,692 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,693 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:41,694 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,698 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,700 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,701 INFO sqlalchemy.engine.base.Engine (2231,)
2019-07-23 11:40:41,704 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,705 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:40:41,709 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,712 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,714 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,714 INFO sqlalchemy.engine.base.Engine (2232,)
2019-07-23 11:40:41,718 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,719 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:40:41,721 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,725 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,726 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,726 INFO sqlalchemy.engine.base.Engine (2233,)
2019-07-23 11:40:41,731 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,732 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:40:41,735 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,738 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,739 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:41,740 INFO sqlalchemy.engine.base.Engine (2234,)
2019-07-23 11:40:41,743 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,743 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:40:41,746 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,751 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,752 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,753 INFO sqlalchemy.engine.base.Engine (2235,)
2019-07-23 11:40:41,756 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,757 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:40:41,759 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,763 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,764 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,765 INFO sqlalchemy.engine.base.Engine (2236,)
2019-07-23 11:40:41,770 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,771 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:40:41,773 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,776 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,777 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,778 INFO sqlalchemy.engine.base.Engine (2237,)
2019-07-23 11:40:41,782 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,783 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:41,785 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,789 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,790 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,792 INFO sqlalchemy.engine.base.Engine (2238,)
2019-07-23 11:40:41,796 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,797 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:41,798 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,802 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,803 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,804 INFO sqlalchemy.engine.base.Engine (2239,)
2019-07-23 11:40:41,807 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,808 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:40:41,810 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,814 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,815 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,816 INFO sqlalchemy.engine.base.Engine (2240,)
2019-07-23 11:40:41,819 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,820 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:40:41,823 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,827 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,829 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,829 INFO sqlalchemy.engine.base.Engine (2241,)
2019-07-23 11:40:41,834 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,835 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:40:41,839 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,843 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,845 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,846 INFO sqlalchemy.engine.base.Engine (2242,)
2019-07-23 11:40:41,850 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,852 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:40:41,854 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,857 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,858 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,859 INFO sqlalchemy.engine.base.Engine (2243,)
2019-07-23 11:40:41,863 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,864 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:40:41,867 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,871 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,872 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,874 INFO sqlalchemy.engine.base.Engine (2244,)
2019-07-23 11:40:41,877 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,878 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:40:41,880 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,885 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,886 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,887 INFO sqlalchemy.engine.base.Engine (2245,)
2019-07-23 11:40:41,892 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,893 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')

2019-07-23 11:40:41,895 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,900 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,902 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,903 INFO sqlalchemy.engine.base.Engine (2246,)
2019-07-23 11:40:41,906 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,907 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:41,910 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,915 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,917 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,918 INFO sqlalchemy.engine.base.Engine (2247,)
2019-07-23 11:40:41,920 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,921 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:41,924 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,928 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,929 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,930 INFO sqlalchemy.engine.base.Engine (2248,)
2019-07-23 11:40:41,934 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,935 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:40:41,937 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,942 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,943 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,944 INFO sqlalchemy.engine.base.Engine (2249,)
2019-07-23 11:40:41,948 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,949 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:40:41,952 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,956 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,958 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,959 INFO sqlalchemy.engine.base.Engine (2250,)
2019-07-23 11:40:41,962 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,963 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:40:41,966 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,970 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,971 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,972 INFO sqlalchemy.engine.base.Engine (2251,)
2019-07-23 11:40:41,975 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,976 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:40:41,978 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,983 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,984 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:41,986 INFO sqlalchemy.engine.base.Engine (2252,)
2019-07-23 11:40:41,990 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:41,991 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:40:41,993 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:41,998 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:41,999 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,000 INFO sqlalchemy.engine.base.Engine (2253,)
2019-07-23 11:40:42,003 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,005 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:40:42,007 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,013 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,014 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,015 INFO sqlalchemy.engine.base.Engine (2254,)
2019-07-23 11:40:42,019 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,020 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:40:42,022 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,026 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,028 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,029 INFO sqlalchemy.engine.base.Engine (2255,)
2019-07-23 11:40:42,033 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,034 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:40:42,037 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,041 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,043 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,044 INFO sqlalchemy.engine.base.Engine (2256,)
2019-07-23 11:40:42,049 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,051 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:40:42,052 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,057 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,059 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,060 INFO sqlalchemy.engine.base.Engine (2257,)

2019-07-23 11:40:42,064 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,064 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:40:42,066 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,071 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,072 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,073 INFO sqlalchemy.engine.base.Engine (2258,)
2019-07-23 11:40:42,077 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,077 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:40:42,079 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,083 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,085 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,086 INFO sqlalchemy.engine.base.Engine (2259,)
2019-07-23 11:40:42,089 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,090 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:40:42,091 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,095 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,096 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,097 INFO sqlalchemy.engine.base.Engine (2260,)
2019-07-23 11:40:42,100 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,101 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:40:42,104 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,108 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,109 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,109 INFO sqlalchemy.engine.base.Engine (2261,)
2019-07-23 11:40:42,113 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,114 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:40:42,116 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,120 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,121 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,122 INFO sqlalchemy.engine.base.Engine (2262,)
2019-07-23 11:40:42,126 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,127 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:40:42,129 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,133 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,135 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,135 INFO sqlalchemy.engine.base.Engine (2263,)
2019-07-23 11:40:42,138 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,139 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:42,142 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,147 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,148 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,149 INFO sqlalchemy.engine.base.Engine (2264,)
2019-07-23 11:40:42,153 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,154 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:42,156 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,159 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,160 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,161 INFO sqlalchemy.engine.base.Engine (2265,)
2019-07-23 11:40:42,165 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,166 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:40:42,168 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,172 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,174 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,174 INFO sqlalchemy.engine.base.Engine (2266,)
2019-07-23 11:40:42,177 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,178 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:40:42,180 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,185 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,186 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,188 INFO sqlalchemy.engine.base.Engine (2267,)
2019-07-23 11:40:42,191 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,192 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:40:42,194 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,198 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,199 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,199 INFO sqlalchemy.engine.base.Engine (2268,)
2019-07-23 11:40:42,204 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,205 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:40:42,207 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:40:42,212 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,213 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,214 INFO sqlalchemy.engine.base.Engine (2269,)
2019-07-23 11:40:42,217 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,218 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:40:42,220 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,224 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,225 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,226 INFO sqlalchemy.engine.base.Engine (2270,)
2019-07-23 11:40:42,229 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,230 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:40:42,233 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,237 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,239 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,240 INFO sqlalchemy.engine.base.Engine (2271,)
2019-07-23 11:40:42,243 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,244 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:40:42,247 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,250 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,252 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,253 INFO sqlalchemy.engine.base.Engine (2272,)
2019-07-23 11:40:42,256 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,257 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:40:42,259 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,263 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,264 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,265 INFO sqlalchemy.engine.base.Engine (2273,)
2019-07-23 11:40:42,268 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,269 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:40:42,272 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,276 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,277 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,278 INFO sqlalchemy.engine.base.Engine (2274,)
2019-07-23 11:40:42,281 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,282 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:40:42,284 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,289 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,290 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,290 INFO sqlalchemy.engine.base.Engine (2275,)
2019-07-23 11:40:42,294 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,295 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:40:42,298 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,302 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,303 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,304 INFO sqlalchemy.engine.base.Engine (2276,)
2019-07-23 11:40:42,308 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,308 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:42,310 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,315 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,316 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,317 INFO sqlalchemy.engine.base.Engine (2277,)
2019-07-23 11:40:42,320 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,321 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:40:42,324 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,327 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,328 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,329 INFO sqlalchemy.engine.base.Engine (2278,)
2019-07-23 11:40:42,333 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,334 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:40:42,337 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,342 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,343 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,344 INFO sqlalchemy.engine.base.Engine (2279,)
2019-07-23 11:40:42,348 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,349 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:40:42,351 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,355 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,356 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:42,357 INFO sqlalchemy.engine.base.Engine (2280,)
2019-07-23 11:40:42,360 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,361 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:40:42,363 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,368 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,369 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,370 INFO sqlalchemy.engine.base.Engine (2281,)
2019-07-23 11:40:42,373 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,374 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:40:42,376 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,380 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,381 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,382 INFO sqlalchemy.engine.base.Engine (2282,)
2019-07-23 11:40:42,386 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,387 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:40:42,390 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,394 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,395 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,396 INFO sqlalchemy.engine.base.Engine (2283,)
2019-07-23 11:40:42,401 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,402 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:42,404 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,407 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,408 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,409 INFO sqlalchemy.engine.base.Engine (2284,)
2019-07-23 11:40:42,413 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,414 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:40:42,417 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,420 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,422 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,422 INFO sqlalchemy.engine.base.Engine (2285,)
2019-07-23 11:40:42,425 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,427 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:40:42,429 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,434 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,435 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,436 INFO sqlalchemy.engine.base.Engine (2286,)
2019-07-23 11:40:42,439 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,440 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:40:42,443 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,447 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,448 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,450 INFO sqlalchemy.engine.base.Engine (2287,)
2019-07-23 11:40:42,455 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,456 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:40:42,459 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,462 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,464 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,464 INFO sqlalchemy.engine.base.Engine (2288,)
2019-07-23 11:40:42,468 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,469 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:40:42,472 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,476 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,478 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,479 INFO sqlalchemy.engine.base.Engine (2289,)
2019-07-23 11:40:42,483 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,484 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:40:42,486 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,490 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,491 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,492 INFO sqlalchemy.engine.base.Engine (2290,)
2019-07-23 11:40:42,495 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,497 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:40:42,499 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,504 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,505 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,506 INFO sqlalchemy.engine.base.Engine (2291,)
2019-07-23 11:40:42,509 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,510 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')

2019-07-23 11:40:42,512 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,516 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,517 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,518 INFO sqlalchemy.engine.base.Engine (2292,)
2019-07-23 11:40:42,522 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,524 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:40:42,526 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,531 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,532 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,533 INFO sqlalchemy.engine.base.Engine (2293,)
2019-07-23 11:40:42,537 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,538 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:40:42,540 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,544 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,545 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,546 INFO sqlalchemy.engine.base.Engine (2294,)
2019-07-23 11:40:42,550 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,551 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:40:42,553 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,557 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,559 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,560 INFO sqlalchemy.engine.base.Engine (2295,)
2019-07-23 11:40:42,564 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,565 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:40:42,568 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,571 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,572 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,573 INFO sqlalchemy.engine.base.Engine (2296,)
2019-07-23 11:40:42,578 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,579 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:40:42,582 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,585 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,587 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,587 INFO sqlalchemy.engine.base.Engine (2297,)
2019-07-23 11:40:42,592 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,593 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:40:42,596 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,600 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,602 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,603 INFO sqlalchemy.engine.base.Engine (2298,)
2019-07-23 11:40:42,606 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,607 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:40:42,609 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,614 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,616 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,617 INFO sqlalchemy.engine.base.Engine (2299,)
2019-07-23 11:40:42,621 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,622 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:40:42,624 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,627 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,629 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,629 INFO sqlalchemy.engine.base.Engine (2300,)
2019-07-23 11:40:42,633 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,635 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:40:42,637 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,641 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,643 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,644 INFO sqlalchemy.engine.base.Engine (2301,)
2019-07-23 11:40:42,647 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,649 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:40:42,651 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,656 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,657 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,658 INFO sqlalchemy.engine.base.Engine (2302,)
2019-07-23 11:40:42,662 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,663 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:40:42,665 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,670 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,672 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:42,672 INFO sqlalchemy.engine.base.Engine (2303,)
2019-07-23 11:40:42,676 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,677 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:40:42,679 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,683 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,684 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,685 INFO sqlalchemy.engine.base.Engine (2304,)
2019-07-23 11:40:42,689 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,690 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:40:42,693 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,697 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,698 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,699 INFO sqlalchemy.engine.base.Engine (2305,)
2019-07-23 11:40:42,703 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,703 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:40:42,706 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,710 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,711 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,712 INFO sqlalchemy.engine.base.Engine (2306,)
2019-07-23 11:40:42,716 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,717 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:40:42,719 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,723 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,725 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,726 INFO sqlalchemy.engine.base.Engine (2307,)
2019-07-23 11:40:42,730 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,731 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:40:42,734 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,738 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,739 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,740 INFO sqlalchemy.engine.base.Engine (2308,)
2019-07-23 11:40:42,743 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,743 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:40:42,746 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,751 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,752 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,753 INFO sqlalchemy.engine.base.Engine (2309,)
2019-07-23 11:40:42,757 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,758 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:40:42,760 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,766 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,768 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,769 INFO sqlalchemy.engine.base.Engine (2310,)
2019-07-23 11:40:42,772 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,773 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:40:42,775 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,779 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,780 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,781 INFO sqlalchemy.engine.base.Engine (2311,)
2019-07-23 11:40:42,784 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,786 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:40:42,788 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,794 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,795 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,796 INFO sqlalchemy.engine.base.Engine (2312,)
2019-07-23 11:40:42,799 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,800 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:40:42,802 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,807 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,808 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,809 INFO sqlalchemy.engine.base.Engine (2313,)
2019-07-23 11:40:42,813 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,814 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:40:42,816 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,821 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,822 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,823 INFO sqlalchemy.engine.base.Engine (2314,)
2019-07-23 11:40:42,827 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,827 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')

2019-07-23 11:40:42,830 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,834 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,836 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,837 INFO sqlalchemy.engine.base.Engine (2315,)
2019-07-23 11:40:42,841 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,842 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:40:42,844 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,849 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,851 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,852 INFO sqlalchemy.engine.base.Engine (2316,)
2019-07-23 11:40:42,855 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,856 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:40:42,857 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,861 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,863 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,864 INFO sqlalchemy.engine.base.Engine (2317,)
2019-07-23 11:40:42,867 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,868 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:40:42,870 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,874 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,876 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,877 INFO sqlalchemy.engine.base.Engine (2318,)
2019-07-23 11:40:42,880 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,882 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:40:42,885 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,889 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,891 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,891 INFO sqlalchemy.engine.base.Engine (2319,)
2019-07-23 11:40:42,896 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,896 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:40:42,899 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,903 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,904 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,905 INFO sqlalchemy.engine.base.Engine (2320,)
2019-07-23 11:40:42,909 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:42,910 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:40:42,913 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:42,919 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:42,920 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:42,921 INFO sqlalchemy.engine.base.Engine (2321,)
http://sz.ganji.com/zufang/pn3 status: 200
2019-07-23 11:40:51,888 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,889 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:40:51,890 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,894 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,895 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:51,895 INFO sqlalchemy.engine.base.Engine (2322,)
2019-07-23 11:40:51,897 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,898 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:40:51,899 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,903 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,904 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:51,905 INFO sqlalchemy.engine.base.Engine (2323,)
2019-07-23 11:40:51,907 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,908 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:40:51,910 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,913 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,914 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:51,915 INFO sqlalchemy.engine.base.Engine (2324,)
2019-07-23 11:40:51,919 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,919 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:40:51,921 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,924 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,925 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:51,925 INFO sqlalchemy.engine.base.Engine (2325,)
2019-07-23 11:40:51,928 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,929 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:40:51,930 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,933 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,934 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:51,934 INFO sqlalchemy.engine.base.Engine (2326,)
2019-07-23 11:40:51,937 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,938 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:40:51,940 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,942 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,943 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:51,944 INFO sqlalchemy.engine.base.Engine (2327,)
2019-07-23 11:40:51,947 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,947 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:40:51,949 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,952 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,953 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:51,954 INFO sqlalchemy.engine.base.Engine (2328,)
2019-07-23 11:40:51,956 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,957 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:51,959 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,961 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,962 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:51,962 INFO sqlalchemy.engine.base.Engine (2329,)
2019-07-23 11:40:51,965 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,965 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:40:51,966 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,969 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,970 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:51,970 INFO sqlalchemy.engine.base.Engine (2330,)
2019-07-23 11:40:51,972 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,973 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:51,974 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,977 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,978 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:51,978 INFO sqlalchemy.engine.base.Engine (2331,)
2019-07-23 11:40:51,980 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,981 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:40:51,982 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,986 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,987 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:51,987 INFO sqlalchemy.engine.base.Engine (2332,)
2019-07-23 11:40:51,990 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,991 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:40:51,992 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:51,995 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:51,996 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:51,996 INFO sqlalchemy.engine.base.Engine (2333,)
2019-07-23 11:40:51,998 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:51,998 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:40:52,000 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,002 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,003 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,004 INFO sqlalchemy.engine.base.Engine (2334,)
2019-07-23 11:40:52,006 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,007 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:40:52,009 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,012 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,013 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,013 INFO sqlalchemy.engine.base.Engine (2335,)
2019-07-23 11:40:52,015 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,015 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:40:52,016 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,019 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,020 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,021 INFO sqlalchemy.engine.base.Engine (2336,)
2019-07-23 11:40:52,023 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,023 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:40:52,024 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,027 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,028 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,028 INFO sqlalchemy.engine.base.Engine (2337,)
2019-07-23 11:40:52,031 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:52,031 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:40:52,032 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,036 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,037 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,037 INFO sqlalchemy.engine.base.Engine (2338,)
2019-07-23 11:40:52,039 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,040 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:40:52,041 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,044 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,045 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,046 INFO sqlalchemy.engine.base.Engine (2339,)
2019-07-23 11:40:52,048 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,049 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:40:52,050 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,053 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,054 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,055 INFO sqlalchemy.engine.base.Engine (2340,)
2019-07-23 11:40:52,056 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,057 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:40:52,058 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,061 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,062 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,062 INFO sqlalchemy.engine.base.Engine (2341,)
2019-07-23 11:40:52,065 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,065 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:40:52,067 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,070 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,071 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,071 INFO sqlalchemy.engine.base.Engine (2342,)
2019-07-23 11:40:52,074 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,075 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:40:52,077 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,080 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,080 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,081 INFO sqlalchemy.engine.base.Engine (2343,)
2019-07-23 11:40:52,084 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,084 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:40:52,086 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,089 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,090 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,091 INFO sqlalchemy.engine.base.Engine (2344,)
2019-07-23 11:40:52,093 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,094 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:40:52,096 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,098 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,099 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,100 INFO sqlalchemy.engine.base.Engine (2345,)
2019-07-23 11:40:52,103 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,104 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:40:52,106 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,108 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,109 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,110 INFO sqlalchemy.engine.base.Engine (2346,)
2019-07-23 11:40:52,112 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,112 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:40:52,114 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,117 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,118 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,118 INFO sqlalchemy.engine.base.Engine (2347,)
2019-07-23 11:40:52,121 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,122 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:40:52,124 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,127 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,128 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,128 INFO sqlalchemy.engine.base.Engine (2348,)
2019-07-23 11:40:52,131 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,132 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:40:52,133 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,137 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:40:52,138 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,138 INFO sqlalchemy.engine.base.Engine (2349,)
2019-07-23 11:40:52,142 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,142 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:40:52,144 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,147 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,149 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,150 INFO sqlalchemy.engine.base.Engine (2350,)
2019-07-23 11:40:52,152 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,153 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:40:52,154 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,156 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,158 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,158 INFO sqlalchemy.engine.base.Engine (2351,)
2019-07-23 11:40:52,160 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,161 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:40:52,162 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,165 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,166 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,167 INFO sqlalchemy.engine.base.Engine (2352,)
2019-07-23 11:40:52,169 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,170 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:40:52,172 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,175 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,176 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,176 INFO sqlalchemy.engine.base.Engine (2353,)
2019-07-23 11:40:52,179 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,179 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:40:52,181 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,184 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,185 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,186 INFO sqlalchemy.engine.base.Engine (2354,)
2019-07-23 11:40:52,188 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,189 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:40:52,190 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,194 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,195 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,196 INFO sqlalchemy.engine.base.Engine (2355,)
2019-07-23 11:40:52,198 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,199 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:40:52,201 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,204 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,205 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,205 INFO sqlalchemy.engine.base.Engine (2356,)
2019-07-23 11:40:52,208 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,208 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:40:52,209 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,212 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,213 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,213 INFO sqlalchemy.engine.base.Engine (2357,)
2019-07-23 11:40:52,217 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,218 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:40:52,221 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,223 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,224 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,225 INFO sqlalchemy.engine.base.Engine (2358,)
2019-07-23 11:40:52,227 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,228 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:40:52,229 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,232 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,233 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,234 INFO sqlalchemy.engine.base.Engine (2359,)
2019-07-23 11:40:52,237 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,238 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:40:52,240 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,243 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,244 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:52,245 INFO sqlalchemy.engine.base.Engine (2360,)
2019-07-23 11:40:52,247 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,248 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:40:52,248 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,251 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,252 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,252 INFO sqlalchemy.engine.base.Engine (2361,)
2019-07-23 11:40:52,255 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,255 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:40:52,257 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,261 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,262 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,263 INFO sqlalchemy.engine.base.Engine (2362,)
2019-07-23 11:40:52,265 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,266 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:40:52,267 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,270 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,271 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,271 INFO sqlalchemy.engine.base.Engine (2363,)
2019-07-23 11:40:52,274 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,274 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:40:52,275 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,278 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,279 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,280 INFO sqlalchemy.engine.base.Engine (2364,)
2019-07-23 11:40:52,282 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,283 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:40:52,285 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,288 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,289 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,289 INFO sqlalchemy.engine.base.Engine (2365,)
2019-07-23 11:40:52,291 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,291 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:40:52,292 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,295 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,295 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,296 INFO sqlalchemy.engine.base.Engine (2366,)
2019-07-23 11:40:52,298 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,299 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:52,300 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,303 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,304 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,305 INFO sqlalchemy.engine.base.Engine (2367,)
2019-07-23 11:40:52,307 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,308 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:40:52,309 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,313 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,313 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,314 INFO sqlalchemy.engine.base.Engine (2368,)
2019-07-23 11:40:52,316 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,317 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:40:52,318 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,322 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,323 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,323 INFO sqlalchemy.engine.base.Engine (2369,)
2019-07-23 11:40:52,326 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,326 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:52,328 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,330 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,331 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,332 INFO sqlalchemy.engine.base.Engine (2370,)
2019-07-23 11:40:52,334 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,335 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:40:52,336 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,340 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,340 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,341 INFO sqlalchemy.engine.base.Engine (2371,)
2019-07-23 11:40:52,344 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:52,344 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:40:52,346 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,349 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,350 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,351 INFO sqlalchemy.engine.base.Engine (2372,)
2019-07-23 11:40:52,353 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,354 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:40:52,355 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,358 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,359 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,359 INFO sqlalchemy.engine.base.Engine (2373,)
2019-07-23 11:40:52,361 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,362 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:40:52,364 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,368 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,368 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,369 INFO sqlalchemy.engine.base.Engine (2374,)
2019-07-23 11:40:52,371 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,372 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:40:52,373 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,375 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,376 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,376 INFO sqlalchemy.engine.base.Engine (2375,)
2019-07-23 11:40:52,378 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,379 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:40:52,380 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,383 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,384 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,385 INFO sqlalchemy.engine.base.Engine (2376,)
2019-07-23 11:40:52,387 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,388 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:52,390 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,393 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,394 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,394 INFO sqlalchemy.engine.base.Engine (2377,)
2019-07-23 11:40:52,396 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,397 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:52,399 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,402 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,403 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,404 INFO sqlalchemy.engine.base.Engine (2378,)
2019-07-23 11:40:52,406 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,407 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:40:52,408 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,411 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,412 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,412 INFO sqlalchemy.engine.base.Engine (2379,)
2019-07-23 11:40:52,415 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,416 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:40:52,417 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,421 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,421 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,422 INFO sqlalchemy.engine.base.Engine (2380,)
2019-07-23 11:40:52,424 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,425 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:40:52,426 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,429 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,430 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,430 INFO sqlalchemy.engine.base.Engine (2381,)
2019-07-23 11:40:52,433 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,434 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:40:52,436 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,439 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,440 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,440 INFO sqlalchemy.engine.base.Engine (2382,)
2019-07-23 11:40:52,442 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,443 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:40:52,444 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,447 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:40:52,448 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,449 INFO sqlalchemy.engine.base.Engine (2383,)
2019-07-23 11:40:52,451 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,452 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:40:52,454 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,457 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,458 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,458 INFO sqlalchemy.engine.base.Engine (2384,)
2019-07-23 11:40:52,460 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,461 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:40:52,462 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,465 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,465 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,466 INFO sqlalchemy.engine.base.Engine (2385,)
2019-07-23 11:40:52,469 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,469 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:52,472 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,475 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,476 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,477 INFO sqlalchemy.engine.base.Engine (2386,)
2019-07-23 11:40:52,479 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,480 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:52,481 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,484 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,484 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,485 INFO sqlalchemy.engine.base.Engine (2387,)
2019-07-23 11:40:52,487 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,488 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:40:52,490 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,493 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,494 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,494 INFO sqlalchemy.engine.base.Engine (2388,)
2019-07-23 11:40:52,497 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,498 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:40:52,500 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,503 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,503 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,504 INFO sqlalchemy.engine.base.Engine (2389,)
2019-07-23 11:40:52,506 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,507 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:40:52,508 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,511 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,512 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,513 INFO sqlalchemy.engine.base.Engine (2390,)
2019-07-23 11:40:52,515 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,516 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:40:52,517 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,520 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,521 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,521 INFO sqlalchemy.engine.base.Engine (2391,)
2019-07-23 11:40:52,523 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,524 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:40:52,525 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,529 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,530 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,530 INFO sqlalchemy.engine.base.Engine (2392,)
2019-07-23 11:40:52,532 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,533 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:40:52,534 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,537 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,538 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,538 INFO sqlalchemy.engine.base.Engine (2393,)
2019-07-23 11:40:52,541 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,542 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:40:52,543 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,547 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,547 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,548 INFO sqlalchemy.engine.base.Engine (2394,)
2019-07-23 11:40:52,551 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:52,551 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:40:52,553 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,555 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,556 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,557 INFO sqlalchemy.engine.base.Engine (2395,)
2019-07-23 11:40:52,559 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,559 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:40:52,561 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,563 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,564 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,565 INFO sqlalchemy.engine.base.Engine (2396,)
2019-07-23 11:40:52,568 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,568 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:40:52,569 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,572 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,572 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,573 INFO sqlalchemy.engine.base.Engine (2397,)
2019-07-23 11:40:52,575 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,575 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:40:52,577 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,580 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,580 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,581 INFO sqlalchemy.engine.base.Engine (2398,)
2019-07-23 11:40:52,584 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,585 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:40:52,586 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,590 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,591 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,591 INFO sqlalchemy.engine.base.Engine (2399,)
2019-07-23 11:40:52,593 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,593 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:40:52,594 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,597 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,598 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,598 INFO sqlalchemy.engine.base.Engine (2400,)
2019-07-23 11:40:52,601 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,601 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:40:52,603 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,606 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,607 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,607 INFO sqlalchemy.engine.base.Engine (2401,)
2019-07-23 11:40:52,610 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,611 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:40:52,613 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,616 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,617 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,617 INFO sqlalchemy.engine.base.Engine (2402,)
2019-07-23 11:40:52,620 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,621 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:52,623 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,626 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,627 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,628 INFO sqlalchemy.engine.base.Engine (2403,)
2019-07-23 11:40:52,630 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,630 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:52,631 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,634 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,635 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,635 INFO sqlalchemy.engine.base.Engine (2404,)
2019-07-23 11:40:52,638 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,639 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:40:52,640 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,643 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,645 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,645 INFO sqlalchemy.engine.base.Engine (2405,)
2019-07-23 11:40:52,648 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,649 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:40:52,650 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,653 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,654 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:52,655 INFO sqlalchemy.engine.base.Engine (2406,)
2019-07-23 11:40:52,656 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,658 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:40:52,660 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,663 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,664 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,664 INFO sqlalchemy.engine.base.Engine (2407,)
2019-07-23 11:40:52,667 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,667 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:40:52,669 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,673 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,674 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,674 INFO sqlalchemy.engine.base.Engine (2408,)
2019-07-23 11:40:52,677 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,678 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:40:52,679 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,683 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,685 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,685 INFO sqlalchemy.engine.base.Engine (2409,)
2019-07-23 11:40:52,687 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,688 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:40:52,689 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,692 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,693 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,694 INFO sqlalchemy.engine.base.Engine (2410,)
2019-07-23 11:40:52,696 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,697 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:40:52,699 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,703 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,704 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,705 INFO sqlalchemy.engine.base.Engine (2411,)
2019-07-23 11:40:52,708 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,708 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:40:52,710 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,713 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,714 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,715 INFO sqlalchemy.engine.base.Engine (2412,)
2019-07-23 11:40:52,717 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,718 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:40:52,719 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,722 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,723 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,724 INFO sqlalchemy.engine.base.Engine (2413,)
2019-07-23 11:40:52,726 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,727 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:40:52,728 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,731 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,732 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,732 INFO sqlalchemy.engine.base.Engine (2414,)
2019-07-23 11:40:52,735 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,736 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:40:52,738 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,741 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,742 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,742 INFO sqlalchemy.engine.base.Engine (2415,)
2019-07-23 11:40:52,746 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,747 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:52,748 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,752 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,753 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,753 INFO sqlalchemy.engine.base.Engine (2416,)
2019-07-23 11:40:52,756 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,757 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:40:52,759 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,761 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,762 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,763 INFO sqlalchemy.engine.base.Engine (2417,)
2019-07-23 11:40:52,765 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,765 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')

2019-07-23 11:40:52,766 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,769 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,770 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,771 INFO sqlalchemy.engine.base.Engine (2418,)
2019-07-23 11:40:52,773 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,774 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:40:52,775 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,778 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,779 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,779 INFO sqlalchemy.engine.base.Engine (2419,)
2019-07-23 11:40:52,782 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,783 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:40:52,784 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,787 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,788 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,788 INFO sqlalchemy.engine.base.Engine (2420,)
2019-07-23 11:40:52,790 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,791 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:40:52,792 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,795 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,797 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,797 INFO sqlalchemy.engine.base.Engine (2421,)
2019-07-23 11:40:52,800 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,801 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:40:52,802 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,805 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,806 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,806 INFO sqlalchemy.engine.base.Engine (2422,)
2019-07-23 11:40:52,809 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,810 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:52,811 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,813 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,814 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,815 INFO sqlalchemy.engine.base.Engine (2423,)
2019-07-23 11:40:52,817 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,818 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:40:52,819 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,823 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,824 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,824 INFO sqlalchemy.engine.base.Engine (2424,)
2019-07-23 11:40:52,827 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,828 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:40:52,829 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,832 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,832 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,833 INFO sqlalchemy.engine.base.Engine (2425,)
2019-07-23 11:40:52,836 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,836 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:40:52,838 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,841 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,842 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,842 INFO sqlalchemy.engine.base.Engine (2426,)
2019-07-23 11:40:52,844 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,845 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:40:52,847 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,849 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,850 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,851 INFO sqlalchemy.engine.base.Engine (2427,)
2019-07-23 11:40:52,855 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,857 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:40:52,858 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,862 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,863 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,863 INFO sqlalchemy.engine.base.Engine (2428,)
2019-07-23 11:40:52,866 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,866 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:40:52,867 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,870 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,871 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:52,872 INFO sqlalchemy.engine.base.Engine (2429,)
2019-07-23 11:40:52,874 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,875 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:40:52,877 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,880 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,881 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,882 INFO sqlalchemy.engine.base.Engine (2430,)
2019-07-23 11:40:52,884 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,885 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:40:52,886 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,889 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,891 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,891 INFO sqlalchemy.engine.base.Engine (2431,)
2019-07-23 11:40:52,893 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,894 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:40:52,895 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,898 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,899 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,899 INFO sqlalchemy.engine.base.Engine (2432,)
2019-07-23 11:40:52,902 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,903 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:40:52,904 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,909 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,910 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,911 INFO sqlalchemy.engine.base.Engine (2433,)
2019-07-23 11:40:52,913 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,914 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:40:52,915 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,918 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,918 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,919 INFO sqlalchemy.engine.base.Engine (2434,)
2019-07-23 11:40:52,922 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,922 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:40:52,923 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,927 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,928 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,929 INFO sqlalchemy.engine.base.Engine (2435,)
2019-07-23 11:40:52,931 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,932 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:40:52,935 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,938 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,939 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,940 INFO sqlalchemy.engine.base.Engine (2436,)
2019-07-23 11:40:52,942 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,943 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:40:52,944 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,947 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,948 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,949 INFO sqlalchemy.engine.base.Engine (2437,)
2019-07-23 11:40:52,952 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,953 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:40:52,956 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,959 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,960 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,961 INFO sqlalchemy.engine.base.Engine (2438,)
2019-07-23 11:40:52,963 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,964 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:40:52,965 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,968 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,970 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,970 INFO sqlalchemy.engine.base.Engine (2439,)
2019-07-23 11:40:52,973 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,974 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:40:52,975 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,979 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,981 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,982 INFO sqlalchemy.engine.base.Engine (2440,)
2019-07-23 11:40:52,984 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,985 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')

2019-07-23 11:40:52,986 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,990 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:52,991 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:52,991 INFO sqlalchemy.engine.base.Engine (2441,)
2019-07-23 11:40:52,994 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:52,995 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:40:52,996 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:52,999 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,000 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,001 INFO sqlalchemy.engine.base.Engine (2442,)
2019-07-23 11:40:53,003 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,004 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:40:53,005 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,009 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,010 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,011 INFO sqlalchemy.engine.base.Engine (2443,)
2019-07-23 11:40:53,014 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,015 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:40:53,016 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,019 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,020 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,021 INFO sqlalchemy.engine.base.Engine (2444,)
2019-07-23 11:40:53,024 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,024 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:40:53,026 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,029 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,030 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,030 INFO sqlalchemy.engine.base.Engine (2445,)
2019-07-23 11:40:53,032 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,033 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:40:53,035 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,038 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,039 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,039 INFO sqlalchemy.engine.base.Engine (2446,)
2019-07-23 11:40:53,042 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,042 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:40:53,044 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,048 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,049 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,050 INFO sqlalchemy.engine.base.Engine (2447,)
2019-07-23 11:40:53,052 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,053 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:40:53,055 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,057 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,058 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,059 INFO sqlalchemy.engine.base.Engine (2448,)
2019-07-23 11:40:53,061 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,061 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:40:53,062 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,065 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,066 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,067 INFO sqlalchemy.engine.base.Engine (2449,)
2019-07-23 11:40:53,069 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,070 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:40:53,071 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,075 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,076 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,077 INFO sqlalchemy.engine.base.Engine (2450,)
2019-07-23 11:40:53,079 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,080 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:40:53,082 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,085 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,086 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,086 INFO sqlalchemy.engine.base.Engine (2451,)
2019-07-23 11:40:53,089 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,090 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:40:53,091 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,094 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,095 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:53,096 INFO sqlalchemy.engine.base.Engine (2452,)
2019-07-23 11:40:53,099 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,099 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:40:53,101 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,104 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,105 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,105 INFO sqlalchemy.engine.base.Engine (2453,)
2019-07-23 11:40:53,107 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,108 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:40:53,109 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,111 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,112 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,113 INFO sqlalchemy.engine.base.Engine (2454,)
2019-07-23 11:40:53,115 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,115 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:40:53,117 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,119 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,120 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,120 INFO sqlalchemy.engine.base.Engine (2455,)
2019-07-23 11:40:53,123 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,124 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:40:53,126 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,129 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,130 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,130 INFO sqlalchemy.engine.base.Engine (2456,)
2019-07-23 11:40:53,132 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,133 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:40:53,134 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,137 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,138 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,138 INFO sqlalchemy.engine.base.Engine (2457,)
2019-07-23 11:40:53,140 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,141 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:40:53,142 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,145 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,146 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,146 INFO sqlalchemy.engine.base.Engine (2458,)
2019-07-23 11:40:53,149 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,149 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:40:53,151 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,154 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,155 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,156 INFO sqlalchemy.engine.base.Engine (2459,)
2019-07-23 11:40:53,159 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:53,159 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:40:53,161 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:53,164 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:53,165 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:53,165 INFO sqlalchemy.engine.base.Engine (2460,)
http://sz.ganji.com/zufang/pn4 status: 200
2019-07-23 11:40:54,280 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,281 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:40:54,283 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,286 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,287 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,288 INFO sqlalchemy.engine.base.Engine (2461,)
2019-07-23 11:40:54,290 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,291 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:40:54,292 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,295 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,296 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,297 INFO sqlalchemy.engine.base.Engine (2462,)
2019-07-23 11:40:54,299 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,299 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:40:54,301 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,304 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,305 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,306 INFO sqlalchemy.engine.base.Engine (2463,)
2019-07-23 11:40:54,308 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:54,309 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:40:54,310 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,312 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,313 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,314 INFO sqlalchemy.engine.base.Engine (2464,)
2019-07-23 11:40:54,316 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,316 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:40:54,318 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,322 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,323 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,323 INFO sqlalchemy.engine.base.Engine (2465,)
2019-07-23 11:40:54,326 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,326 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:40:54,328 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,330 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,331 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,332 INFO sqlalchemy.engine.base.Engine (2466,)
2019-07-23 11:40:54,334 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,335 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:40:54,336 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,339 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,340 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,341 INFO sqlalchemy.engine.base.Engine (2467,)
2019-07-23 11:40:54,344 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,345 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:54,347 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,350 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,351 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,351 INFO sqlalchemy.engine.base.Engine (2468,)
2019-07-23 11:40:54,354 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,354 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:40:54,356 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,358 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,359 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,360 INFO sqlalchemy.engine.base.Engine (2469,)
2019-07-23 11:40:54,362 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,362 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:54,364 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,366 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,367 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,368 INFO sqlalchemy.engine.base.Engine (2470,)
2019-07-23 11:40:54,369 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,370 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:40:54,371 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,373 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,374 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,375 INFO sqlalchemy.engine.base.Engine (2471,)
2019-07-23 11:40:54,377 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,378 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:40:54,379 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,382 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,383 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,383 INFO sqlalchemy.engine.base.Engine (2472,)
2019-07-23 11:40:54,386 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,387 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:40:54,388 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,391 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,392 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,393 INFO sqlalchemy.engine.base.Engine (2473,)
2019-07-23 11:40:54,395 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,396 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:40:54,397 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,400 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,401 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,401 INFO sqlalchemy.engine.base.Engine (2474,)
2019-07-23 11:40:54,404 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,405 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:40:54,407 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:40:54,410 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,411 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,412 INFO sqlalchemy.engine.base.Engine (2475,)
2019-07-23 11:40:54,414 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,415 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:40:54,416 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,418 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,419 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,420 INFO sqlalchemy.engine.base.Engine (2476,)
2019-07-23 11:40:54,423 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,423 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:40:54,425 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,427 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,428 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,429 INFO sqlalchemy.engine.base.Engine (2477,)
2019-07-23 11:40:54,431 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,432 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:40:54,433 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,437 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,438 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,438 INFO sqlalchemy.engine.base.Engine (2478,)
2019-07-23 11:40:54,441 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,442 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:40:54,443 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,446 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,447 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,447 INFO sqlalchemy.engine.base.Engine (2479,)
2019-07-23 11:40:54,450 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,450 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:40:54,451 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,454 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,455 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,457 INFO sqlalchemy.engine.base.Engine (2480,)
2019-07-23 11:40:54,459 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,459 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:40:54,461 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,464 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,465 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,465 INFO sqlalchemy.engine.base.Engine (2481,)
2019-07-23 11:40:54,468 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,469 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:40:54,471 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,473 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,474 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,474 INFO sqlalchemy.engine.base.Engine (2482,)
2019-07-23 11:40:54,477 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,478 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:40:54,480 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,483 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,484 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,485 INFO sqlalchemy.engine.base.Engine (2483,)
2019-07-23 11:40:54,488 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,488 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:40:54,490 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,492 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,493 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,493 INFO sqlalchemy.engine.base.Engine (2484,)
2019-07-23 11:40:54,495 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,496 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:40:54,497 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,500 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,501 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,502 INFO sqlalchemy.engine.base.Engine (2485,)
2019-07-23 11:40:54,505 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,506 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:40:54,508 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,510 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,511 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:54,511 INFO sqlalchemy.engine.base.Engine (2486,)
2019-07-23 11:40:54,513 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,514 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:40:54,515 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,518 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,520 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,521 INFO sqlalchemy.engine.base.Engine (2487,)
2019-07-23 11:40:54,524 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,525 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:40:54,527 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,529 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,530 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,531 INFO sqlalchemy.engine.base.Engine (2488,)
2019-07-23 11:40:54,533 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,534 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:40:54,535 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,538 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,539 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,539 INFO sqlalchemy.engine.base.Engine (2489,)
2019-07-23 11:40:54,541 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,542 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:40:54,544 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,548 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,549 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,550 INFO sqlalchemy.engine.base.Engine (2490,)
2019-07-23 11:40:54,553 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,553 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:40:54,555 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,558 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,558 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,559 INFO sqlalchemy.engine.base.Engine (2491,)
2019-07-23 11:40:54,561 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,561 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:40:54,563 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,566 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,567 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,568 INFO sqlalchemy.engine.base.Engine (2492,)
2019-07-23 11:40:54,570 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,571 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:40:54,573 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,576 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,577 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,578 INFO sqlalchemy.engine.base.Engine (2493,)
2019-07-23 11:40:54,580 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,580 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:40:54,582 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,586 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,587 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,588 INFO sqlalchemy.engine.base.Engine (2494,)
2019-07-23 11:40:54,591 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,592 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:40:54,593 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,596 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,597 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,597 INFO sqlalchemy.engine.base.Engine (2495,)
2019-07-23 11:40:54,599 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,600 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:40:54,601 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,605 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,606 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,606 INFO sqlalchemy.engine.base.Engine (2496,)
2019-07-23 11:40:54,609 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,609 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:40:54,611 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,613 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,614 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,614 INFO sqlalchemy.engine.base.Engine (2497,)
2019-07-23 11:40:54,617 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,617 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')

2019-07-23 11:40:54,619 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,622 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,623 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,623 INFO sqlalchemy.engine.base.Engine (2498,)
2019-07-23 11:40:54,626 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,626 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:40:54,627 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,631 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,632 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,632 INFO sqlalchemy.engine.base.Engine (2499,)
2019-07-23 11:40:54,635 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,636 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:40:54,637 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,641 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,642 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,642 INFO sqlalchemy.engine.base.Engine (2500,)
2019-07-23 11:40:54,646 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,646 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:40:54,648 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,650 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,651 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,652 INFO sqlalchemy.engine.base.Engine (2501,)
2019-07-23 11:40:54,655 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,656 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:40:54,657 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,659 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,660 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,660 INFO sqlalchemy.engine.base.Engine (2502,)
2019-07-23 11:40:54,663 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,663 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:40:54,665 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,668 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,669 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,670 INFO sqlalchemy.engine.base.Engine (2503,)
2019-07-23 11:40:54,673 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,673 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:40:54,675 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,678 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,678 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,679 INFO sqlalchemy.engine.base.Engine (2504,)
2019-07-23 11:40:54,682 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,683 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:40:54,685 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,689 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,690 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,691 INFO sqlalchemy.engine.base.Engine (2505,)
2019-07-23 11:40:54,694 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,694 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:54,697 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,700 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,701 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,701 INFO sqlalchemy.engine.base.Engine (2506,)
2019-07-23 11:40:54,704 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,705 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:40:54,706 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,709 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,710 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,711 INFO sqlalchemy.engine.base.Engine (2507,)
2019-07-23 11:40:54,714 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,714 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:40:54,716 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,719 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,720 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,721 INFO sqlalchemy.engine.base.Engine (2508,)
2019-07-23 11:40:54,723 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,724 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:54,726 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,729 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,730 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:54,730 INFO sqlalchemy.engine.base.Engine (2509,)
2019-07-23 11:40:54,733 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,733 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:40:54,736 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,739 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,740 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,741 INFO sqlalchemy.engine.base.Engine (2510,)
2019-07-23 11:40:54,744 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,745 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:40:54,747 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,750 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,751 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,752 INFO sqlalchemy.engine.base.Engine (2511,)
2019-07-23 11:40:54,755 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,755 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:40:54,757 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,760 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,761 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,761 INFO sqlalchemy.engine.base.Engine (2512,)
2019-07-23 11:40:54,764 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,765 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:40:54,766 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,769 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,770 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,771 INFO sqlalchemy.engine.base.Engine (2513,)
2019-07-23 11:40:54,774 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,775 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:40:54,777 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,781 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,782 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,783 INFO sqlalchemy.engine.base.Engine (2514,)
2019-07-23 11:40:54,785 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,786 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:40:54,787 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,791 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,792 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,793 INFO sqlalchemy.engine.base.Engine (2515,)
2019-07-23 11:40:54,795 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,796 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:54,797 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,800 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,801 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,802 INFO sqlalchemy.engine.base.Engine (2516,)
2019-07-23 11:40:54,805 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,806 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:54,807 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,811 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,811 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,812 INFO sqlalchemy.engine.base.Engine (2517,)
2019-07-23 11:40:54,815 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,816 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:40:54,817 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,821 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,822 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,823 INFO sqlalchemy.engine.base.Engine (2518,)
2019-07-23 11:40:54,826 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,826 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:40:54,828 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,831 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,833 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,833 INFO sqlalchemy.engine.base.Engine (2519,)
2019-07-23 11:40:54,836 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,837 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:40:54,839 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,842 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,843 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,844 INFO sqlalchemy.engine.base.Engine (2520,)
2019-07-23 11:40:54,847 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,848 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')

2019-07-23 11:40:54,850 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,853 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,854 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,855 INFO sqlalchemy.engine.base.Engine (2521,)
2019-07-23 11:40:54,857 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,858 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:40:54,860 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,863 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,865 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,866 INFO sqlalchemy.engine.base.Engine (2522,)
2019-07-23 11:40:54,869 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,870 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:40:54,871 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,875 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,876 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,877 INFO sqlalchemy.engine.base.Engine (2523,)
2019-07-23 11:40:54,880 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,881 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:40:54,882 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,886 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,887 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,887 INFO sqlalchemy.engine.base.Engine (2524,)
2019-07-23 11:40:54,890 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,891 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:54,893 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,898 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,899 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,900 INFO sqlalchemy.engine.base.Engine (2525,)
2019-07-23 11:40:54,903 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,904 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:54,906 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,908 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,909 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,910 INFO sqlalchemy.engine.base.Engine (2526,)
2019-07-23 11:40:54,912 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,913 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:40:54,915 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,918 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,918 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,919 INFO sqlalchemy.engine.base.Engine (2527,)
2019-07-23 11:40:54,922 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,923 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:40:54,924 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,928 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,929 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,929 INFO sqlalchemy.engine.base.Engine (2528,)
2019-07-23 11:40:54,933 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,934 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:40:54,935 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,939 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,940 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,940 INFO sqlalchemy.engine.base.Engine (2529,)
2019-07-23 11:40:54,943 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,944 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:40:54,946 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,951 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,952 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,954 INFO sqlalchemy.engine.base.Engine (2530,)
2019-07-23 11:40:54,956 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,957 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:40:54,959 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,963 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,964 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,965 INFO sqlalchemy.engine.base.Engine (2531,)
2019-07-23 11:40:54,967 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,968 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:40:54,970 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,973 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,974 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:54,975 INFO sqlalchemy.engine.base.Engine (2532,)
2019-07-23 11:40:54,978 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,979 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:40:54,980 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,984 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,985 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,985 INFO sqlalchemy.engine.base.Engine (2533,)
2019-07-23 11:40:54,988 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:54,989 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:40:54,990 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:54,993 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:54,994 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:54,995 INFO sqlalchemy.engine.base.Engine (2534,)
2019-07-23 11:40:54,999 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,000 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:40:55,001 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,005 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,006 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,007 INFO sqlalchemy.engine.base.Engine (2535,)
2019-07-23 11:40:55,009 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,009 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:40:55,011 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,014 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,015 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,016 INFO sqlalchemy.engine.base.Engine (2536,)
2019-07-23 11:40:55,019 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,019 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:40:55,021 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,024 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,025 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,026 INFO sqlalchemy.engine.base.Engine (2537,)
2019-07-23 11:40:55,029 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,030 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:40:55,031 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,035 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,037 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,038 INFO sqlalchemy.engine.base.Engine (2538,)
2019-07-23 11:40:55,041 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,041 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:40:55,043 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,047 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,048 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,049 INFO sqlalchemy.engine.base.Engine (2539,)
2019-07-23 11:40:55,051 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,052 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:40:55,055 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,058 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,059 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,059 INFO sqlalchemy.engine.base.Engine (2540,)
2019-07-23 11:40:55,062 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,062 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:40:55,063 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,067 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,068 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,068 INFO sqlalchemy.engine.base.Engine (2541,)
2019-07-23 11:40:55,071 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,072 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:55,074 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,077 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,078 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,079 INFO sqlalchemy.engine.base.Engine (2542,)
2019-07-23 11:40:55,080 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,081 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:55,083 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,087 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,088 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,088 INFO sqlalchemy.engine.base.Engine (2543,)
2019-07-23 11:40:55,091 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,092 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')

2019-07-23 11:40:55,093 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,096 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,097 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,097 INFO sqlalchemy.engine.base.Engine (2544,)
2019-07-23 11:40:55,099 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,100 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:40:55,101 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,104 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,105 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,106 INFO sqlalchemy.engine.base.Engine (2545,)
2019-07-23 11:40:55,109 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,109 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:40:55,111 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,114 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,114 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,115 INFO sqlalchemy.engine.base.Engine (2546,)
2019-07-23 11:40:55,117 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,117 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:40:55,119 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,123 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,124 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,125 INFO sqlalchemy.engine.base.Engine (2547,)
2019-07-23 11:40:55,128 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,128 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:40:55,131 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,134 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,135 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,136 INFO sqlalchemy.engine.base.Engine (2548,)
2019-07-23 11:40:55,138 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,139 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:40:55,140 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,143 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,144 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,145 INFO sqlalchemy.engine.base.Engine (2549,)
2019-07-23 11:40:55,148 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,148 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:40:55,150 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,153 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,155 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,155 INFO sqlalchemy.engine.base.Engine (2550,)
2019-07-23 11:40:55,158 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,158 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:40:55,160 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,164 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,165 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,166 INFO sqlalchemy.engine.base.Engine (2551,)
2019-07-23 11:40:55,168 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,169 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:40:55,171 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,175 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,176 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,177 INFO sqlalchemy.engine.base.Engine (2552,)
2019-07-23 11:40:55,180 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,181 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:40:55,183 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,187 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,188 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,189 INFO sqlalchemy.engine.base.Engine (2553,)
2019-07-23 11:40:55,193 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,194 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:40:55,196 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,199 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,201 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,202 INFO sqlalchemy.engine.base.Engine (2554,)
2019-07-23 11:40:55,204 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,205 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:55,208 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,211 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,213 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:55,214 INFO sqlalchemy.engine.base.Engine (2555,)
2019-07-23 11:40:55,217 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,218 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:40:55,220 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,223 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,224 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,225 INFO sqlalchemy.engine.base.Engine (2556,)
2019-07-23 11:40:55,229 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,229 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:40:55,231 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,235 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,236 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,237 INFO sqlalchemy.engine.base.Engine (2557,)
2019-07-23 11:40:55,240 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,241 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:40:55,244 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,248 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,249 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,250 INFO sqlalchemy.engine.base.Engine (2558,)
2019-07-23 11:40:55,253 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,255 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:40:55,257 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,261 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,262 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,262 INFO sqlalchemy.engine.base.Engine (2559,)
2019-07-23 11:40:55,266 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,267 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:40:55,269 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,273 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,274 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,275 INFO sqlalchemy.engine.base.Engine (2560,)
2019-07-23 11:40:55,279 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,281 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:40:55,283 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,287 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,288 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,289 INFO sqlalchemy.engine.base.Engine (2561,)
2019-07-23 11:40:55,292 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,293 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:55,295 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,299 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,301 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,302 INFO sqlalchemy.engine.base.Engine (2562,)
2019-07-23 11:40:55,305 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,306 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:40:55,308 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,312 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,314 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,315 INFO sqlalchemy.engine.base.Engine (2563,)
2019-07-23 11:40:55,318 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,319 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:40:55,320 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,324 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,326 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,326 INFO sqlalchemy.engine.base.Engine (2564,)
2019-07-23 11:40:55,329 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,330 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:40:55,332 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,336 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,337 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,338 INFO sqlalchemy.engine.base.Engine (2565,)
2019-07-23 11:40:55,342 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,342 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:40:55,344 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,348 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,350 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,351 INFO sqlalchemy.engine.base.Engine (2566,)
2019-07-23 11:40:55,353 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,354 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')

2019-07-23 11:40:55,357 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,360 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,361 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,361 INFO sqlalchemy.engine.base.Engine (2567,)
2019-07-23 11:40:55,364 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,365 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:40:55,367 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,371 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,372 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,373 INFO sqlalchemy.engine.base.Engine (2568,)
2019-07-23 11:40:55,376 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,377 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:40:55,379 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,382 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,384 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,385 INFO sqlalchemy.engine.base.Engine (2569,)
2019-07-23 11:40:55,388 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,389 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:40:55,391 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,395 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,396 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,396 INFO sqlalchemy.engine.base.Engine (2570,)
2019-07-23 11:40:55,400 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,401 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:40:55,403 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,407 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,408 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,408 INFO sqlalchemy.engine.base.Engine (2571,)
2019-07-23 11:40:55,411 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,412 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:40:55,414 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,418 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,419 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,420 INFO sqlalchemy.engine.base.Engine (2572,)
2019-07-23 11:40:55,424 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,425 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:40:55,426 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,430 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,431 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,432 INFO sqlalchemy.engine.base.Engine (2573,)
2019-07-23 11:40:55,435 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,436 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:40:55,439 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,443 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,444 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,445 INFO sqlalchemy.engine.base.Engine (2574,)
2019-07-23 11:40:55,449 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,450 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:40:55,453 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,457 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,458 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,459 INFO sqlalchemy.engine.base.Engine (2575,)
2019-07-23 11:40:55,463 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,464 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:40:55,466 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,470 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,471 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,472 INFO sqlalchemy.engine.base.Engine (2576,)
2019-07-23 11:40:55,475 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,475 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:40:55,477 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,481 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,483 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,484 INFO sqlalchemy.engine.base.Engine (2577,)
2019-07-23 11:40:55,487 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,488 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:40:55,490 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,494 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,496 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental

WHERE rental.id = ?
2019-07-23 11:40:55,497 INFO sqlalchemy.engine.base.Engine (2578,)
2019-07-23 11:40:55,501 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,502 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:40:55,504 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,507 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,509 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,510 INFO sqlalchemy.engine.base.Engine (2579,)
2019-07-23 11:40:55,513 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,514 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:40:55,516 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,521 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,522 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,523 INFO sqlalchemy.engine.base.Engine (2580,)
2019-07-23 11:40:55,526 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,527 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:40:55,529 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,534 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,535 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,536 INFO sqlalchemy.engine.base.Engine (2581,)
2019-07-23 11:40:55,539 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,540 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:40:55,542 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,547 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,549 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,549 INFO sqlalchemy.engine.base.Engine (2582,)
2019-07-23 11:40:55,553 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,554 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:40:55,556 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,560 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,562 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,562 INFO sqlalchemy.engine.base.Engine (2583,)
2019-07-23 11:40:55,566 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,568 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:40:55,570 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,574 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,575 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,576 INFO sqlalchemy.engine.base.Engine (2584,)
2019-07-23 11:40:55,581 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,583 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:40:55,585 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,589 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,590 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,591 INFO sqlalchemy.engine.base.Engine (2585,)
2019-07-23 11:40:55,594 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,595 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:40:55,597 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,601 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,602 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,603 INFO sqlalchemy.engine.base.Engine (2586,)
2019-07-23 11:40:55,607 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,608 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:40:55,611 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,615 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,616 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,617 INFO sqlalchemy.engine.base.Engine (2587,)
2019-07-23 11:40:55,621 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,622 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:40:55,625 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,629 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,630 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,631 INFO sqlalchemy.engine.base.Engine (2588,)
2019-07-23 11:40:55,635 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,636 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:40:55,639 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,643 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,645 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,647 INFO sqlalchemy.engine.base.Engine (2589,)
2019-07-23 11:40:55,650 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,651 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')

2019-07-23 11:40:55,654 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,658 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,659 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,660 INFO sqlalchemy.engine.base.Engine (2590,)
2019-07-23 11:40:55,663 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,664 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:40:55,666 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,671 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,672 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,673 INFO sqlalchemy.engine.base.Engine (2591,)
2019-07-23 11:40:55,676 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,677 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:40:55,679 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,683 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,684 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,685 INFO sqlalchemy.engine.base.Engine (2592,)
2019-07-23 11:40:55,689 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,690 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:40:55,692 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,697 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,698 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,699 INFO sqlalchemy.engine.base.Engine (2593,)
2019-07-23 11:40:55,702 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,703 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:40:55,706 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,709 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,710 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,711 INFO sqlalchemy.engine.base.Engine (2594,)
2019-07-23 11:40:55,714 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,715 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:40:55,717 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,722 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,724 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,725 INFO sqlalchemy.engine.base.Engine (2595,)
2019-07-23 11:40:55,729 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,730 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:40:55,732 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,737 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,738 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,739 INFO sqlalchemy.engine.base.Engine (2596,)
2019-07-23 11:40:55,741 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,743 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:40:55,746 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,751 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,752 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,753 INFO sqlalchemy.engine.base.Engine (2597,)
2019-07-23 11:40:55,757 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,758 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:40:55,760 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,765 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,766 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,767 INFO sqlalchemy.engine.base.Engine (2598,)
2019-07-23 11:40:55,770 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:55,772 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:40:55,775 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:55,779 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:55,781 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:55,782 INFO sqlalchemy.engine.base.Engine (2599,)
http://sz.ganji.com/zufang/pn5 status: 200
2019-07-23 11:40:56,771 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,772 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:40:56,774 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,777 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,779 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,779 INFO sqlalchemy.engine.base.Engine (2600,)
2019-07-23 11:40:56,782 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,783 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:40:56,786 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,789 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,790 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:56,791 INFO sqlalchemy.engine.base.Engine (2601,)
2019-07-23 11:40:56,794 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,795 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:40:56,798 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,802 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,803 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,804 INFO sqlalchemy.engine.base.Engine (2602,)
2019-07-23 11:40:56,807 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,809 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:40:56,810 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,814 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,815 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,815 INFO sqlalchemy.engine.base.Engine (2603,)
2019-07-23 11:40:56,819 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,820 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:40:56,822 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,826 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,827 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,828 INFO sqlalchemy.engine.base.Engine (2604,)
2019-07-23 11:40:56,832 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,832 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:40:56,834 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,838 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,840 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,840 INFO sqlalchemy.engine.base.Engine (2605,)
2019-07-23 11:40:56,843 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,844 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:40:56,846 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,851 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,852 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,853 INFO sqlalchemy.engine.base.Engine (2606,)
2019-07-23 11:40:56,857 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,858 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:56,860 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,864 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,865 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,866 INFO sqlalchemy.engine.base.Engine (2607,)
2019-07-23 11:40:56,869 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,871 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:40:56,874 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,878 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,879 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,880 INFO sqlalchemy.engine.base.Engine (2608,)
2019-07-23 11:40:56,883 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,884 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:56,886 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,891 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,892 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,893 INFO sqlalchemy.engine.base.Engine (2609,)
2019-07-23 11:40:56,897 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,898 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:40:56,900 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,904 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,905 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,906 INFO sqlalchemy.engine.base.Engine (2610,)
2019-07-23 11:40:56,909 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,909 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:40:56,911 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,915 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,916 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,917 INFO sqlalchemy.engine.base.Engine (2611,)
2019-07-23 11:40:56,921 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,922 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:40:56,924 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,927 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,929 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,930 INFO sqlalchemy.engine.base.Engine (2612,)
2019-07-23 11:40:56,934 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:56,935 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:40:56,937 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,941 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,942 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,943 INFO sqlalchemy.engine.base.Engine (2613,)
2019-07-23 11:40:56,947 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,948 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:40:56,950 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,954 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,955 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,956 INFO sqlalchemy.engine.base.Engine (2614,)
2019-07-23 11:40:56,959 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,960 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:40:56,962 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,967 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,969 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,969 INFO sqlalchemy.engine.base.Engine (2615,)
2019-07-23 11:40:56,973 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,974 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:40:56,976 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,981 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,982 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,983 INFO sqlalchemy.engine.base.Engine (2616,)
2019-07-23 11:40:56,986 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:56,987 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:40:56,991 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:56,995 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:56,997 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:56,998 INFO sqlalchemy.engine.base.Engine (2617,)
2019-07-23 11:40:57,001 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,002 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:40:57,004 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,009 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,010 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,010 INFO sqlalchemy.engine.base.Engine (2618,)
2019-07-23 11:40:57,013 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,014 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:40:57,017 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,021 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,023 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,023 INFO sqlalchemy.engine.base.Engine (2619,)
2019-07-23 11:40:57,027 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,028 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:40:57,029 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,033 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,034 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,035 INFO sqlalchemy.engine.base.Engine (2620,)
2019-07-23 11:40:57,038 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,039 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:40:57,041 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,046 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,048 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,048 INFO sqlalchemy.engine.base.Engine (2621,)
2019-07-23 11:40:57,051 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,052 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:40:57,055 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,058 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,059 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,060 INFO sqlalchemy.engine.base.Engine (2622,)
2019-07-23 11:40:57,064 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,065 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:40:57,067 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,071 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,072 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,073 INFO sqlalchemy.engine.base.Engine (2623,)
2019-07-23 11:40:57,076 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,076 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')

2019-07-23 11:40:57,078 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,082 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,083 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,084 INFO sqlalchemy.engine.base.Engine (2624,)
2019-07-23 11:40:57,087 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,088 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:40:57,090 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,095 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,096 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,097 INFO sqlalchemy.engine.base.Engine (2625,)
2019-07-23 11:40:57,100 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,101 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:40:57,102 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,106 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,108 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,108 INFO sqlalchemy.engine.base.Engine (2626,)
2019-07-23 11:40:57,111 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,112 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:40:57,114 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,118 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,119 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,120 INFO sqlalchemy.engine.base.Engine (2627,)
2019-07-23 11:40:57,123 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,124 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:40:57,126 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,130 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,131 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,132 INFO sqlalchemy.engine.base.Engine (2628,)
2019-07-23 11:40:57,135 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,136 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:40:57,138 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,142 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,144 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,145 INFO sqlalchemy.engine.base.Engine (2629,)
2019-07-23 11:40:57,148 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,149 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:40:57,151 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,155 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,156 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,157 INFO sqlalchemy.engine.base.Engine (2630,)
2019-07-23 11:40:57,161 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,162 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:40:57,164 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,168 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,169 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,170 INFO sqlalchemy.engine.base.Engine (2631,)
2019-07-23 11:40:57,173 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,174 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:40:57,175 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,180 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,181 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,182 INFO sqlalchemy.engine.base.Engine (2632,)
2019-07-23 11:40:57,185 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,186 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:40:57,189 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,193 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,195 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,195 INFO sqlalchemy.engine.base.Engine (2633,)
2019-07-23 11:40:57,199 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,199 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:40:57,202 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,206 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,208 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,208 INFO sqlalchemy.engine.base.Engine (2634,)
2019-07-23 11:40:57,212 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,212 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:40:57,215 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,218 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,219 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:57,220 INFO sqlalchemy.engine.base.Engine (2635,)
2019-07-23 11:40:57,223 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,224 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:40:57,226 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,231 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,232 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,233 INFO sqlalchemy.engine.base.Engine (2636,)
2019-07-23 11:40:57,237 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,238 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:40:57,240 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,245 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,246 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,247 INFO sqlalchemy.engine.base.Engine (2637,)
2019-07-23 11:40:57,250 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,251 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:40:57,252 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,256 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,257 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,258 INFO sqlalchemy.engine.base.Engine (2638,)
2019-07-23 11:40:57,262 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,264 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:40:57,266 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,269 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,270 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,271 INFO sqlalchemy.engine.base.Engine (2639,)
2019-07-23 11:40:57,275 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,276 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:40:57,279 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,282 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,284 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,285 INFO sqlalchemy.engine.base.Engine (2640,)
2019-07-23 11:40:57,288 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,289 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:40:57,291 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,296 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,297 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,298 INFO sqlalchemy.engine.base.Engine (2641,)
2019-07-23 11:40:57,302 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,303 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:40:57,305 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,309 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,310 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,311 INFO sqlalchemy.engine.base.Engine (2642,)
2019-07-23 11:40:57,314 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,315 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:40:57,317 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,321 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,323 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,323 INFO sqlalchemy.engine.base.Engine (2643,)
2019-07-23 11:40:57,326 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,326 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:40:57,327 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,332 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,333 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,334 INFO sqlalchemy.engine.base.Engine (2644,)
2019-07-23 11:40:57,338 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,338 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:57,341 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,346 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,347 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,348 INFO sqlalchemy.engine.base.Engine (2645,)
2019-07-23 11:40:57,350 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,351 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:40:57,354 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,357 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,359 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,359 INFO sqlalchemy.engine.base.Engine (2646,)
2019-07-23 11:40:57,363 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:57,364 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:40:57,367 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,371 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,372 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,372 INFO sqlalchemy.engine.base.Engine (2647,)
2019-07-23 11:40:57,375 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,376 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:40:57,378 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,382 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,383 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,384 INFO sqlalchemy.engine.base.Engine (2648,)
2019-07-23 11:40:57,388 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,389 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:40:57,392 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,396 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,397 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,398 INFO sqlalchemy.engine.base.Engine (2649,)
2019-07-23 11:40:57,401 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,402 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:40:57,404 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,407 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,408 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,409 INFO sqlalchemy.engine.base.Engine (2650,)
2019-07-23 11:40:57,412 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,414 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:40:57,416 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,420 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,421 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,422 INFO sqlalchemy.engine.base.Engine (2651,)
2019-07-23 11:40:57,425 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,426 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:40:57,429 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,433 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,434 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,435 INFO sqlalchemy.engine.base.Engine (2652,)
2019-07-23 11:40:57,438 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,439 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:40:57,441 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,445 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,446 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,447 INFO sqlalchemy.engine.base.Engine (2653,)
2019-07-23 11:40:57,450 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,451 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:40:57,454 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,457 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,459 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,459 INFO sqlalchemy.engine.base.Engine (2654,)
2019-07-23 11:40:57,463 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,464 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:57,467 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,471 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,472 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,473 INFO sqlalchemy.engine.base.Engine (2655,)
2019-07-23 11:40:57,476 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,477 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:40:57,479 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,485 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,487 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,488 INFO sqlalchemy.engine.base.Engine (2656,)
2019-07-23 11:40:57,491 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,493 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:40:57,496 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,500 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,501 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,502 INFO sqlalchemy.engine.base.Engine (2657,)
2019-07-23 11:40:57,505 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,506 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:40:57,509 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,513 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:40:57,514 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,515 INFO sqlalchemy.engine.base.Engine (2658,)
2019-07-23 11:40:57,518 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,519 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:40:57,522 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,525 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,526 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,527 INFO sqlalchemy.engine.base.Engine (2659,)
2019-07-23 11:40:57,531 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,532 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:40:57,534 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,539 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,540 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,541 INFO sqlalchemy.engine.base.Engine (2660,)
2019-07-23 11:40:57,544 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,545 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:40:57,547 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,552 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,553 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,554 INFO sqlalchemy.engine.base.Engine (2661,)
2019-07-23 11:40:57,558 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,559 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:40:57,561 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,565 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,566 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,566 INFO sqlalchemy.engine.base.Engine (2662,)
2019-07-23 11:40:57,570 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,571 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:40:57,573 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,577 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,578 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,579 INFO sqlalchemy.engine.base.Engine (2663,)
2019-07-23 11:40:57,583 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,584 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:57,587 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,591 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,592 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,593 INFO sqlalchemy.engine.base.Engine (2664,)
2019-07-23 11:40:57,595 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,596 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:40:57,598 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,603 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,604 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,606 INFO sqlalchemy.engine.base.Engine (2665,)
2019-07-23 11:40:57,610 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,611 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:40:57,613 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,616 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,617 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,618 INFO sqlalchemy.engine.base.Engine (2666,)
2019-07-23 11:40:57,623 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,624 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:40:57,626 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,630 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,632 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,632 INFO sqlalchemy.engine.base.Engine (2667,)
2019-07-23 11:40:57,636 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,637 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:40:57,639 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,642 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,643 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,644 INFO sqlalchemy.engine.base.Engine (2668,)
2019-07-23 11:40:57,648 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,648 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:40:57,651 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,655 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,656 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,657 INFO sqlalchemy.engine.base.Engine (2669,)

2019-07-23 11:40:57,662 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,662 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:40:57,664 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,668 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,669 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,669 INFO sqlalchemy.engine.base.Engine (2670,)
2019-07-23 11:40:57,673 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,674 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:40:57,676 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,680 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,682 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,682 INFO sqlalchemy.engine.base.Engine (2671,)
2019-07-23 11:40:57,687 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,688 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:40:57,689 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,693 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,694 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,695 INFO sqlalchemy.engine.base.Engine (2672,)
2019-07-23 11:40:57,698 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,699 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:40:57,702 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,706 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,707 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,708 INFO sqlalchemy.engine.base.Engine (2673,)
2019-07-23 11:40:57,711 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,712 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:40:57,714 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,717 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,719 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,720 INFO sqlalchemy.engine.base.Engine (2674,)
2019-07-23 11:40:57,724 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,725 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:40:57,727 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,730 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,732 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,732 INFO sqlalchemy.engine.base.Engine (2675,)
2019-07-23 11:40:57,736 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,738 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:40:57,741 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,746 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,747 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,748 INFO sqlalchemy.engine.base.Engine (2676,)
2019-07-23 11:40:57,751 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,752 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:40:57,754 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,759 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,760 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,762 INFO sqlalchemy.engine.base.Engine (2677,)
2019-07-23 11:40:57,766 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,767 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:40:57,769 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,774 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,775 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,776 INFO sqlalchemy.engine.base.Engine (2678,)
2019-07-23 11:40:57,780 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,781 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:40:57,784 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,788 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,789 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,790 INFO sqlalchemy.engine.base.Engine (2679,)
2019-07-23 11:40:57,794 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,795 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:40:57,797 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,800 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,801 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,802 INFO sqlalchemy.engine.base.Engine (2680,)
2019-07-23 11:40:57,806 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,808 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:57,810 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,814 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:40:57,815 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,817 INFO sqlalchemy.engine.base.Engine (2681,)
2019-07-23 11:40:57,820 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,822 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:40:57,824 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,828 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,830 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,832 INFO sqlalchemy.engine.base.Engine (2682,)
2019-07-23 11:40:57,835 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,836 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:40:57,838 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,842 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,843 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,845 INFO sqlalchemy.engine.base.Engine (2683,)
2019-07-23 11:40:57,849 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,850 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:40:57,852 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,856 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,857 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,858 INFO sqlalchemy.engine.base.Engine (2684,)
2019-07-23 11:40:57,863 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,864 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:40:57,866 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,870 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,871 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,872 INFO sqlalchemy.engine.base.Engine (2685,)
2019-07-23 11:40:57,877 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,877 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:40:57,880 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,884 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,885 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,886 INFO sqlalchemy.engine.base.Engine (2686,)
2019-07-23 11:40:57,890 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,891 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:40:57,894 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,899 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,900 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,901 INFO sqlalchemy.engine.base.Engine (2687,)
2019-07-23 11:40:57,905 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,906 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:40:57,908 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,912 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,913 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,914 INFO sqlalchemy.engine.base.Engine (2688,)
2019-07-23 11:40:57,918 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,919 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:40:57,922 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,926 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,927 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,928 INFO sqlalchemy.engine.base.Engine (2689,)
2019-07-23 11:40:57,932 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,933 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:40:57,935 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,940 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,942 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,943 INFO sqlalchemy.engine.base.Engine (2690,)
2019-07-23 11:40:57,947 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,948 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:40:57,950 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,955 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,956 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,957 INFO sqlalchemy.engine.base.Engine (2691,)
2019-07-23 11:40:57,961 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,962 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:40:57,965 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,969 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,970 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,971 INFO sqlalchemy.engine.base.Engine (2692,)

2019-07-23 11:40:57,975 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,976 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:40:57,978 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,982 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,984 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:57,985 INFO sqlalchemy.engine.base.Engine (2693,)
2019-07-23 11:40:57,989 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:57,989 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:57,992 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:57,997 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:57,998 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,000 INFO sqlalchemy.engine.base.Engine (2694,)
2019-07-23 11:40:58,004 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,005 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:40:58,006 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,011 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,013 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,014 INFO sqlalchemy.engine.base.Engine (2695,)
2019-07-23 11:40:58,018 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,019 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:40:58,021 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,026 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,028 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,028 INFO sqlalchemy.engine.base.Engine (2696,)
2019-07-23 11:40:58,033 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,034 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:40:58,036 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,041 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,043 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,043 INFO sqlalchemy.engine.base.Engine (2697,)
2019-07-23 11:40:58,048 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,049 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:40:58,051 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,055 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,057 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,057 INFO sqlalchemy.engine.base.Engine (2698,)
2019-07-23 11:40:58,061 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,062 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:40:58,065 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,069 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,070 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,071 INFO sqlalchemy.engine.base.Engine (2699,)
2019-07-23 11:40:58,074 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,075 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:40:58,077 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,082 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,084 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,084 INFO sqlalchemy.engine.base.Engine (2700,)
2019-07-23 11:40:58,088 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,089 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:40:58,091 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,095 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,097 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,097 INFO sqlalchemy.engine.base.Engine (2701,)
2019-07-23 11:40:58,101 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,101 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:40:58,104 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,109 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,111 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,111 INFO sqlalchemy.engine.base.Engine (2702,)
2019-07-23 11:40:58,115 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,116 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:40:58,119 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,123 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,124 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,125 INFO sqlalchemy.engine.base.Engine (2703,)
2019-07-23 11:40:58,128 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,129 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:40:58,133 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:40:58,136 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,138 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,139 INFO sqlalchemy.engine.base.Engine (2704,)
2019-07-23 11:40:58,142 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,143 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:40:58,145 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,150 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,152 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,153 INFO sqlalchemy.engine.base.Engine (2705,)
2019-07-23 11:40:58,157 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,158 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:40:58,160 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,165 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,166 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,167 INFO sqlalchemy.engine.base.Engine (2706,)
2019-07-23 11:40:58,170 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,171 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:40:58,174 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,178 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,179 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,180 INFO sqlalchemy.engine.base.Engine (2707,)
2019-07-23 11:40:58,184 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,185 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:40:58,188 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,192 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,194 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,194 INFO sqlalchemy.engine.base.Engine (2708,)
2019-07-23 11:40:58,197 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,198 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:40:58,200 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,205 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,206 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,207 INFO sqlalchemy.engine.base.Engine (2709,)
2019-07-23 11:40:58,211 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,212 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:40:58,214 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,218 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,220 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,221 INFO sqlalchemy.engine.base.Engine (2710,)
2019-07-23 11:40:58,224 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,225 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:40:58,227 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,255 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,257 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,259 INFO sqlalchemy.engine.base.Engine (2711,)
2019-07-23 11:40:58,263 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,264 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:40:58,266 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,270 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,272 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,273 INFO sqlalchemy.engine.base.Engine (2712,)
2019-07-23 11:40:58,278 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,279 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:40:58,281 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,285 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,287 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,287 INFO sqlalchemy.engine.base.Engine (2713,)
2019-07-23 11:40:58,292 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,293 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:40:58,295 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,301 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,302 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,303 INFO sqlalchemy.engine.base.Engine (2714,)
2019-07-23 11:40:58,307 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,307 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:40:58,309 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,314 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,316 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:58,317 INFO sqlalchemy.engine.base.Engine (2715,)
2019-07-23 11:40:58,321 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,321 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:40:58,323 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,330 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,331 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,332 INFO sqlalchemy.engine.base.Engine (2716,)
2019-07-23 11:40:58,336 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,337 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:40:58,340 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,346 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,347 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,348 INFO sqlalchemy.engine.base.Engine (2717,)
2019-07-23 11:40:58,352 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,353 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:40:58,355 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,359 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,360 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,361 INFO sqlalchemy.engine.base.Engine (2718,)
2019-07-23 11:40:58,367 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,369 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:40:58,372 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,377 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,379 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,380 INFO sqlalchemy.engine.base.Engine (2719,)
2019-07-23 11:40:58,384 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,385 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:40:58,389 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,393 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,394 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,395 INFO sqlalchemy.engine.base.Engine (2720,)
2019-07-23 11:40:58,398 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,399 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:40:58,401 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,406 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,407 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,408 INFO sqlalchemy.engine.base.Engine (2721,)
2019-07-23 11:40:58,413 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,414 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:40:58,416 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,420 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,421 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,423 INFO sqlalchemy.engine.base.Engine (2722,)
2019-07-23 11:40:58,426 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,427 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:40:58,430 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,434 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,436 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,436 INFO sqlalchemy.engine.base.Engine (2723,)
2019-07-23 11:40:58,440 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,442 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:40:58,444 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,448 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,449 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,450 INFO sqlalchemy.engine.base.Engine (2724,)
2019-07-23 11:40:58,454 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,455 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:40:58,458 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,462 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,463 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,464 INFO sqlalchemy.engine.base.Engine (2725,)
2019-07-23 11:40:58,467 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,469 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:40:58,471 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,475 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,477 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,477 INFO sqlalchemy.engine.base.Engine (2726,)
2019-07-23 11:40:58,481 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,482 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')

2019-07-23 11:40:58,484 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,489 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,490 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,491 INFO sqlalchemy.engine.base.Engine (2727,)
2019-07-23 11:40:58,495 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,496 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:40:58,499 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,503 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,505 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,505 INFO sqlalchemy.engine.base.Engine (2728,)
2019-07-23 11:40:58,510 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,511 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:40:58,513 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,517 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,518 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,519 INFO sqlalchemy.engine.base.Engine (2729,)
2019-07-23 11:40:58,524 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,525 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:40:58,527 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,532 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,534 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,535 INFO sqlalchemy.engine.base.Engine (2730,)
2019-07-23 11:40:58,539 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,540 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:40:58,542 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,546 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,548 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,549 INFO sqlalchemy.engine.base.Engine (2731,)
2019-07-23 11:40:58,552 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,553 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:40:58,556 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,560 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,561 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,562 INFO sqlalchemy.engine.base.Engine (2732,)
2019-07-23 11:40:58,566 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,567 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:40:58,569 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,574 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,575 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,576 INFO sqlalchemy.engine.base.Engine (2733,)
2019-07-23 11:40:58,579 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,580 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:40:58,582 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,587 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,588 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,590 INFO sqlalchemy.engine.base.Engine (2734,)
2019-07-23 11:40:58,594 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,595 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:40:58,598 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,603 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,604 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,605 INFO sqlalchemy.engine.base.Engine (2735,)
2019-07-23 11:40:58,608 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,609 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:40:58,611 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,615 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,617 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,618 INFO sqlalchemy.engine.base.Engine (2736,)
2019-07-23 11:40:58,621 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,622 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:40:58,624 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,630 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,631 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:58,632 INFO sqlalchemy.engine.base.Engine (2737,)
2019-07-23 11:40:58,636 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:58,637 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:40:58,641 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:58,651 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:58,654 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:40:58,656 INFO sqlalchemy.engine.base.Engine (2738,)
http://sz.ganji.com/zufang/pn6 status: 200
2019-07-23 11:40:59,614 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,616 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:40:59,618 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,624 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,625 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,626 INFO sqlalchemy.engine.base.Engine (2739,)
2019-07-23 11:40:59,630 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,632 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:40:59,634 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,639 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,640 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,641 INFO sqlalchemy.engine.base.Engine (2740,)
2019-07-23 11:40:59,646 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,647 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:40:59,649 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,653 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,654 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,655 INFO sqlalchemy.engine.base.Engine (2741,)
2019-07-23 11:40:59,660 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,661 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:40:59,664 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,669 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,671 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,672 INFO sqlalchemy.engine.base.Engine (2742,)
2019-07-23 11:40:59,675 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,676 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:40:59,681 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,685 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,687 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,687 INFO sqlalchemy.engine.base.Engine (2743,)
2019-07-23 11:40:59,691 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,692 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:40:59,695 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,700 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,702 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,703 INFO sqlalchemy.engine.base.Engine (2744,)
2019-07-23 11:40:59,707 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,708 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:40:59,711 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,716 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,717 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,718 INFO sqlalchemy.engine.base.Engine (2745,)
2019-07-23 11:40:59,723 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,724 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:59,726 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,732 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,734 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,735 INFO sqlalchemy.engine.base.Engine (2746,)
2019-07-23 11:40:59,739 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,740 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:40:59,741 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,746 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,748 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,749 INFO sqlalchemy.engine.base.Engine (2747,)
2019-07-23 11:40:59,752 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,753 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:40:59,756 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,760 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,761 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,763 INFO sqlalchemy.engine.base.Engine (2748,)
2019-07-23 11:40:59,767 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,768 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:40:59,771 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,776 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,777 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,778 INFO sqlalchemy.engine.base.Engine (2749,)
2019-07-23 11:40:59,783 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:40:59,784 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:40:59,786 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,791 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,793 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,794 INFO sqlalchemy.engine.base.Engine (2750,)
2019-07-23 11:40:59,798 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,799 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:40:59,801 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,806 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,807 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,808 INFO sqlalchemy.engine.base.Engine (2751,)
2019-07-23 11:40:59,812 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,813 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:40:59,816 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,821 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,822 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,823 INFO sqlalchemy.engine.base.Engine (2752,)
2019-07-23 11:40:59,827 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,828 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:40:59,831 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,836 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,838 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,839 INFO sqlalchemy.engine.base.Engine (2753,)
2019-07-23 11:40:59,843 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,844 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:40:59,846 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,850 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,852 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,852 INFO sqlalchemy.engine.base.Engine (2754,)
2019-07-23 11:40:59,857 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,858 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:40:59,860 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,864 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,866 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,867 INFO sqlalchemy.engine.base.Engine (2755,)
2019-07-23 11:40:59,870 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,872 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:40:59,874 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,878 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,880 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,881 INFO sqlalchemy.engine.base.Engine (2756,)
2019-07-23 11:40:59,884 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,885 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:40:59,887 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,892 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,893 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,894 INFO sqlalchemy.engine.base.Engine (2757,)
2019-07-23 11:40:59,898 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,899 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:40:59,903 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,907 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,908 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,909 INFO sqlalchemy.engine.base.Engine (2758,)
2019-07-23 11:40:59,913 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,915 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:40:59,917 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,921 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,922 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,923 INFO sqlalchemy.engine.base.Engine (2759,)
2019-07-23 11:40:59,927 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,928 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:40:59,930 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,934 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,936 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,937 INFO sqlalchemy.engine.base.Engine (2760,)
2019-07-23 11:40:59,941 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,942 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:40:59,945 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:40:59,950 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,951 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,952 INFO sqlalchemy.engine.base.Engine (2761,)
2019-07-23 11:40:59,955 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,956 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:40:59,958 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,962 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,964 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,965 INFO sqlalchemy.engine.base.Engine (2762,)
2019-07-23 11:40:59,968 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,970 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:40:59,972 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,976 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,978 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,979 INFO sqlalchemy.engine.base.Engine (2763,)
2019-07-23 11:40:59,983 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,984 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:40:59,986 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:40:59,991 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:40:59,992 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:40:59,993 INFO sqlalchemy.engine.base.Engine (2764,)
2019-07-23 11:40:59,997 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:40:59,998 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:00,000 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,006 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,007 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,008 INFO sqlalchemy.engine.base.Engine (2765,)
2019-07-23 11:41:00,012 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,013 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:41:00,015 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,019 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,020 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,021 INFO sqlalchemy.engine.base.Engine (2766,)
2019-07-23 11:41:00,025 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,026 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:00,028 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,034 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,035 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,036 INFO sqlalchemy.engine.base.Engine (2767,)
2019-07-23 11:41:00,039 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,040 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:00,042 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,047 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,048 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,050 INFO sqlalchemy.engine.base.Engine (2768,)
2019-07-23 11:41:00,054 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,055 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:00,057 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,061 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,062 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,063 INFO sqlalchemy.engine.base.Engine (2769,)
2019-07-23 11:41:00,067 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,068 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:00,071 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,075 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,077 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,077 INFO sqlalchemy.engine.base.Engine (2770,)
2019-07-23 11:41:00,081 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,083 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:00,086 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,090 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,091 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,092 INFO sqlalchemy.engine.base.Engine (2771,)
2019-07-23 11:41:00,096 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,097 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:00,099 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,103 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,105 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:00,106 INFO sqlalchemy.engine.base.Engine (2772,)
2019-07-23 11:41:00,109 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,110 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:00,112 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,116 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,117 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,119 INFO sqlalchemy.engine.base.Engine (2773,)
2019-07-23 11:41:00,122 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,124 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:00,126 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,130 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,131 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,132 INFO sqlalchemy.engine.base.Engine (2774,)
2019-07-23 11:41:00,136 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,137 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:00,140 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,144 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,145 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,146 INFO sqlalchemy.engine.base.Engine (2775,)
2019-07-23 11:41:00,150 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,151 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:41:00,154 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,158 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,159 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,160 INFO sqlalchemy.engine.base.Engine (2776,)
2019-07-23 11:41:00,163 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,164 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:00,167 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,171 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,173 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,174 INFO sqlalchemy.engine.base.Engine (2777,)
2019-07-23 11:41:00,177 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,179 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:00,182 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,186 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,187 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,188 INFO sqlalchemy.engine.base.Engine (2778,)
2019-07-23 11:41:00,192 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,193 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:41:00,196 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,200 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,201 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,201 INFO sqlalchemy.engine.base.Engine (2779,)
2019-07-23 11:41:00,206 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,207 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:41:00,209 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,213 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,215 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,216 INFO sqlalchemy.engine.base.Engine (2780,)
2019-07-23 11:41:00,219 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,220 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:00,223 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,227 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,228 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,229 INFO sqlalchemy.engine.base.Engine (2781,)
2019-07-23 11:41:00,233 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,234 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:00,237 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,241 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,242 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,243 INFO sqlalchemy.engine.base.Engine (2782,)
2019-07-23 11:41:00,247 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,248 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:00,251 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,255 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,256 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,257 INFO sqlalchemy.engine.base.Engine (2783,)
2019-07-23 11:41:00,261 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:00,262 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:00,264 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,269 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,270 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,271 INFO sqlalchemy.engine.base.Engine (2784,)
2019-07-23 11:41:00,275 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,276 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:00,279 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,282 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,284 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,285 INFO sqlalchemy.engine.base.Engine (2785,)
2019-07-23 11:41:00,289 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,290 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:00,293 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,297 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,298 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,299 INFO sqlalchemy.engine.base.Engine (2786,)
2019-07-23 11:41:00,303 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,304 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:00,306 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,311 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,312 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,313 INFO sqlalchemy.engine.base.Engine (2787,)
2019-07-23 11:41:00,317 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,318 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:00,321 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,324 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,326 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,326 INFO sqlalchemy.engine.base.Engine (2788,)
2019-07-23 11:41:00,330 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,331 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:00,334 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,338 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,339 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,340 INFO sqlalchemy.engine.base.Engine (2789,)
2019-07-23 11:41:00,344 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,345 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:00,348 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,352 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,354 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,355 INFO sqlalchemy.engine.base.Engine (2790,)
2019-07-23 11:41:00,358 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,359 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:00,361 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,365 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,367 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,367 INFO sqlalchemy.engine.base.Engine (2791,)
2019-07-23 11:41:00,371 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,372 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:00,375 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,379 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,381 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,382 INFO sqlalchemy.engine.base.Engine (2792,)
2019-07-23 11:41:00,386 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,387 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:00,389 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,393 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,394 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,395 INFO sqlalchemy.engine.base.Engine (2793,)
2019-07-23 11:41:00,399 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,401 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:00,403 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,407 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,408 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,409 INFO sqlalchemy.engine.base.Engine (2794,)
2019-07-23 11:41:00,413 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,414 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:00,417 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,421 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:00,422 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,423 INFO sqlalchemy.engine.base.Engine (2795,)
2019-07-23 11:41:00,426 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,427 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:00,429 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,434 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,435 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,436 INFO sqlalchemy.engine.base.Engine (2796,)
2019-07-23 11:41:00,440 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,441 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:00,443 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,448 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,449 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,450 INFO sqlalchemy.engine.base.Engine (2797,)
2019-07-23 11:41:00,454 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,455 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:00,458 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,462 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,463 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,464 INFO sqlalchemy.engine.base.Engine (2798,)
2019-07-23 11:41:00,468 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,469 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:41:00,471 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,476 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,477 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,478 INFO sqlalchemy.engine.base.Engine (2799,)
2019-07-23 11:41:00,482 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,483 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:00,486 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,490 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,491 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,492 INFO sqlalchemy.engine.base.Engine (2800,)
2019-07-23 11:41:00,495 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,496 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:00,499 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,503 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,504 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,506 INFO sqlalchemy.engine.base.Engine (2801,)
2019-07-23 11:41:00,510 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,511 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:41:00,513 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,517 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,518 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,519 INFO sqlalchemy.engine.base.Engine (2802,)
2019-07-23 11:41:00,523 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,525 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:00,527 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,531 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,533 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,534 INFO sqlalchemy.engine.base.Engine (2803,)
2019-07-23 11:41:00,537 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,538 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:00,542 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,546 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,548 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,548 INFO sqlalchemy.engine.base.Engine (2804,)
2019-07-23 11:41:00,552 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,553 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:00,556 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,560 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,561 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,562 INFO sqlalchemy.engine.base.Engine (2805,)
2019-07-23 11:41:00,566 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,567 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:00,569 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,573 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,575 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,576 INFO sqlalchemy.engine.base.Engine (2806,)

2019-07-23 11:41:00,580 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,581 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:00,583 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,587 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,588 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,589 INFO sqlalchemy.engine.base.Engine (2807,)
2019-07-23 11:41:00,593 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,594 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:00,596 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,600 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,602 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,603 INFO sqlalchemy.engine.base.Engine (2808,)
2019-07-23 11:41:00,606 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,607 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:00,609 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,614 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,615 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,616 INFO sqlalchemy.engine.base.Engine (2809,)
2019-07-23 11:41:00,619 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,620 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:00,623 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,627 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,628 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,629 INFO sqlalchemy.engine.base.Engine (2810,)
2019-07-23 11:41:00,633 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,634 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:00,636 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,640 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,641 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,642 INFO sqlalchemy.engine.base.Engine (2811,)
2019-07-23 11:41:00,646 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,647 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:00,650 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,654 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,655 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,656 INFO sqlalchemy.engine.base.Engine (2812,)
2019-07-23 11:41:00,659 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,660 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:00,663 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,666 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,668 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,669 INFO sqlalchemy.engine.base.Engine (2813,)
2019-07-23 11:41:00,673 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,674 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:00,676 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,681 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,683 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,683 INFO sqlalchemy.engine.base.Engine (2814,)
2019-07-23 11:41:00,687 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,688 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:00,691 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,695 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,696 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,697 INFO sqlalchemy.engine.base.Engine (2815,)
2019-07-23 11:41:00,701 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,702 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:00,705 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,709 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,711 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,711 INFO sqlalchemy.engine.base.Engine (2816,)
2019-07-23 11:41:00,715 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,717 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:00,719 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,723 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,724 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,725 INFO sqlalchemy.engine.base.Engine (2817,)
2019-07-23 11:41:00,729 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,730 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:00,733 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,739 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:00,740 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,741 INFO sqlalchemy.engine.base.Engine (2818,)
2019-07-23 11:41:00,745 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,746 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:00,749 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,753 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,755 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,756 INFO sqlalchemy.engine.base.Engine (2819,)
2019-07-23 11:41:00,759 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,761 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:00,763 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,767 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,768 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,769 INFO sqlalchemy.engine.base.Engine (2820,)
2019-07-23 11:41:00,773 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,774 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:00,778 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,782 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,784 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,784 INFO sqlalchemy.engine.base.Engine (2821,)
2019-07-23 11:41:00,789 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,791 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:41:00,793 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,798 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,799 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,800 INFO sqlalchemy.engine.base.Engine (2822,)
2019-07-23 11:41:00,804 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,805 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:00,807 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,811 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,813 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,813 INFO sqlalchemy.engine.base.Engine (2823,)
2019-07-23 11:41:00,817 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,818 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:00,820 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,824 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,825 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,826 INFO sqlalchemy.engine.base.Engine (2824,)
2019-07-23 11:41:00,830 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,832 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:00,835 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,840 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,841 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,842 INFO sqlalchemy.engine.base.Engine (2825,)
2019-07-23 11:41:00,846 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,847 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:41:00,849 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,853 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,855 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,855 INFO sqlalchemy.engine.base.Engine (2826,)
2019-07-23 11:41:00,858 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,859 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:00,863 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,867 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,868 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,869 INFO sqlalchemy.engine.base.Engine (2827,)
2019-07-23 11:41:00,873 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,874 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:00,876 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,881 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,882 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,884 INFO sqlalchemy.engine.base.Engine (2828,)
2019-07-23 11:41:00,888 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,889 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:00,892 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,896 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,898 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,899 INFO sqlalchemy.engine.base.Engine (2829,)

2019-07-23 11:41:00,903 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,904 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:00,906 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,911 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,912 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,913 INFO sqlalchemy.engine.base.Engine (2830,)
2019-07-23 11:41:00,917 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,918 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:00,921 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,925 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,926 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,927 INFO sqlalchemy.engine.base.Engine (2831,)
2019-07-23 11:41:00,930 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,932 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:00,934 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,939 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,941 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,942 INFO sqlalchemy.engine.base.Engine (2832,)
2019-07-23 11:41:00,946 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,947 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:00,950 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,954 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,955 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,956 INFO sqlalchemy.engine.base.Engine (2833,)
2019-07-23 11:41:00,960 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,961 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:00,964 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,968 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,969 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,970 INFO sqlalchemy.engine.base.Engine (2834,)
2019-07-23 11:41:00,973 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,974 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:41:00,977 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,981 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,983 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,984 INFO sqlalchemy.engine.base.Engine (2835,)
2019-07-23 11:41:00,988 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:00,989 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:41:00,992 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:00,996 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:00,998 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:00,998 INFO sqlalchemy.engine.base.Engine (2836,)
2019-07-23 11:41:01,003 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,003 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:01,006 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,010 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,011 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,012 INFO sqlalchemy.engine.base.Engine (2837,)
2019-07-23 11:41:01,016 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,017 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:01,020 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,023 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,024 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,025 INFO sqlalchemy.engine.base.Engine (2838,)
2019-07-23 11:41:01,029 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,030 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:41:01,034 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,038 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,039 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,040 INFO sqlalchemy.engine.base.Engine (2839,)
2019-07-23 11:41:01,043 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,044 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:01,047 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,052 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,053 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,054 INFO sqlalchemy.engine.base.Engine (2840,)
2019-07-23 11:41:01,058 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,058 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')

2019-07-23 11:41:01,061 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,065 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,067 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,068 INFO sqlalchemy.engine.base.Engine (2841,)
2019-07-23 11:41:01,072 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,072 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:01,075 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,079 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,080 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,081 INFO sqlalchemy.engine.base.Engine (2842,)
2019-07-23 11:41:01,085 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,086 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:01,088 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,093 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,094 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,095 INFO sqlalchemy.engine.base.Engine (2843,)
2019-07-23 11:41:01,099 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,100 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:01,103 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,107 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,108 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,109 INFO sqlalchemy.engine.base.Engine (2844,)
2019-07-23 11:41:01,113 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,114 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:41:01,117 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,121 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,123 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,124 INFO sqlalchemy.engine.base.Engine (2845,)
2019-07-23 11:41:01,127 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,128 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:01,129 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,134 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,135 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,136 INFO sqlalchemy.engine.base.Engine (2846,)
2019-07-23 11:41:01,139 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,140 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:01,143 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,148 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,149 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,150 INFO sqlalchemy.engine.base.Engine (2847,)
2019-07-23 11:41:01,154 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,154 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:41:01,157 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,162 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,163 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,164 INFO sqlalchemy.engine.base.Engine (2848,)
2019-07-23 11:41:01,167 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,168 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:41:01,172 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,175 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,177 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,177 INFO sqlalchemy.engine.base.Engine (2849,)
2019-07-23 11:41:01,181 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,182 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:01,184 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,189 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,190 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,191 INFO sqlalchemy.engine.base.Engine (2850,)
2019-07-23 11:41:01,195 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,196 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:01,197 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,202 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,203 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,204 INFO sqlalchemy.engine.base.Engine (2851,)
2019-07-23 11:41:01,207 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,208 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:01,210 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,215 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,216 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:01,217 INFO sqlalchemy.engine.base.Engine (2852,)
2019-07-23 11:41:01,221 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,221 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:01,223 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,227 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,229 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,229 INFO sqlalchemy.engine.base.Engine (2853,)
2019-07-23 11:41:01,233 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,234 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:01,236 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,241 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,242 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,243 INFO sqlalchemy.engine.base.Engine (2854,)
2019-07-23 11:41:01,248 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,249 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:01,252 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,256 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,257 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,258 INFO sqlalchemy.engine.base.Engine (2855,)
2019-07-23 11:41:01,263 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,263 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:01,266 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,270 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,271 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,272 INFO sqlalchemy.engine.base.Engine (2856,)
2019-07-23 11:41:01,276 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,276 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:01,278 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,283 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,285 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,285 INFO sqlalchemy.engine.base.Engine (2857,)
2019-07-23 11:41:01,290 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,290 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:41:01,293 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,297 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,298 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,299 INFO sqlalchemy.engine.base.Engine (2858,)
2019-07-23 11:41:01,303 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,304 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:41:01,307 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,311 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,312 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,313 INFO sqlalchemy.engine.base.Engine (2859,)
2019-07-23 11:41:01,317 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,318 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:01,319 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,324 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,325 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,326 INFO sqlalchemy.engine.base.Engine (2860,)
2019-07-23 11:41:01,330 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,331 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:01,333 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,337 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,339 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,339 INFO sqlalchemy.engine.base.Engine (2861,)
2019-07-23 11:41:01,344 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,345 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:41:01,348 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,352 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,353 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,354 INFO sqlalchemy.engine.base.Engine (2862,)
2019-07-23 11:41:01,357 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,358 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:01,362 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,366 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,367 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,368 INFO sqlalchemy.engine.base.Engine (2863,)
2019-07-23 11:41:01,372 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,373 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')

2019-07-23 11:41:01,375 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,379 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,381 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,382 INFO sqlalchemy.engine.base.Engine (2864,)
2019-07-23 11:41:01,384 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,386 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:01,390 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,393 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,395 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,396 INFO sqlalchemy.engine.base.Engine (2865,)
2019-07-23 11:41:01,400 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,401 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:41:01,403 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,407 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,408 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,409 INFO sqlalchemy.engine.base.Engine (2866,)
2019-07-23 11:41:01,413 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,414 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:01,416 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,421 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,423 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,423 INFO sqlalchemy.engine.base.Engine (2867,)
2019-07-23 11:41:01,427 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,428 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:01,431 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,435 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,437 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,438 INFO sqlalchemy.engine.base.Engine (2868,)
2019-07-23 11:41:01,441 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,442 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:01,446 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,450 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,451 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,452 INFO sqlalchemy.engine.base.Engine (2869,)
2019-07-23 11:41:01,455 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,456 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:01,458 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,463 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,465 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,466 INFO sqlalchemy.engine.base.Engine (2870,)
2019-07-23 11:41:01,469 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,470 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:41:01,472 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,477 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,478 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,479 INFO sqlalchemy.engine.base.Engine (2871,)
2019-07-23 11:41:01,483 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,484 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:41:01,487 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,491 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,492 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,493 INFO sqlalchemy.engine.base.Engine (2872,)
2019-07-23 11:41:01,497 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,497 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:01,500 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,504 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,505 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,506 INFO sqlalchemy.engine.base.Engine (2873,)
2019-07-23 11:41:01,510 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,511 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:01,514 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,518 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,519 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,520 INFO sqlalchemy.engine.base.Engine (2874,)
2019-07-23 11:41:01,524 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,525 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:01,527 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,531 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,533 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:01,534 INFO sqlalchemy.engine.base.Engine (2875,)
2019-07-23 11:41:01,538 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,539 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:01,542 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,546 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,547 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,548 INFO sqlalchemy.engine.base.Engine (2876,)
2019-07-23 11:41:01,552 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:01,553 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:01,555 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:01,560 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:01,561 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:01,562 INFO sqlalchemy.engine.base.Engine (2877,)
http://sz.ganji.com/zufang/pn7 status: 200
2019-07-23 11:41:02,763 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,764 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:41:02,766 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,770 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,772 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,772 INFO sqlalchemy.engine.base.Engine (2878,)
2019-07-23 11:41:02,775 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,776 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:41:02,779 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,783 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,784 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,785 INFO sqlalchemy.engine.base.Engine (2879,)
2019-07-23 11:41:02,788 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,789 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:41:02,791 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,795 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,796 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,797 INFO sqlalchemy.engine.base.Engine (2880,)
2019-07-23 11:41:02,800 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,801 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:41:02,804 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,807 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,808 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,809 INFO sqlalchemy.engine.base.Engine (2881,)
2019-07-23 11:41:02,812 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,813 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:41:02,816 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,819 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,820 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,821 INFO sqlalchemy.engine.base.Engine (2882,)
2019-07-23 11:41:02,825 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,826 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:41:02,828 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,831 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,832 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,833 INFO sqlalchemy.engine.base.Engine (2883,)
2019-07-23 11:41:02,836 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,837 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:41:02,839 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,843 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,844 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,845 INFO sqlalchemy.engine.base.Engine (2884,)
2019-07-23 11:41:02,849 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,850 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:02,852 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,856 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,857 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,857 INFO sqlalchemy.engine.base.Engine (2885,)
2019-07-23 11:41:02,861 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,862 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:41:02,864 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,868 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,869 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,870 INFO sqlalchemy.engine.base.Engine (2886,)
2019-07-23 11:41:02,873 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:02,874 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:02,876 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,880 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,881 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,882 INFO sqlalchemy.engine.base.Engine (2887,)
2019-07-23 11:41:02,885 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,886 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:41:02,888 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,893 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,895 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,896 INFO sqlalchemy.engine.base.Engine (2888,)
2019-07-23 11:41:02,899 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,900 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:41:02,902 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,905 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,906 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,907 INFO sqlalchemy.engine.base.Engine (2889,)
2019-07-23 11:41:02,911 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,912 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:41:02,913 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,917 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,918 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,919 INFO sqlalchemy.engine.base.Engine (2890,)
2019-07-23 11:41:02,922 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,923 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:41:02,925 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,929 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,930 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,930 INFO sqlalchemy.engine.base.Engine (2891,)
2019-07-23 11:41:02,934 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,935 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:41:02,937 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,940 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,941 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,942 INFO sqlalchemy.engine.base.Engine (2892,)
2019-07-23 11:41:02,945 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,946 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:41:02,949 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,952 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,953 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,954 INFO sqlalchemy.engine.base.Engine (2893,)
2019-07-23 11:41:02,957 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,958 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:41:02,960 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,963 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,964 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,965 INFO sqlalchemy.engine.base.Engine (2894,)
2019-07-23 11:41:02,968 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,969 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:41:02,971 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,974 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,975 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,976 INFO sqlalchemy.engine.base.Engine (2895,)
2019-07-23 11:41:02,979 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,980 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:41:02,982 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,986 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,988 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:02,988 INFO sqlalchemy.engine.base.Engine (2896,)
2019-07-23 11:41:02,992 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:02,993 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:41:02,994 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:02,998 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:02,999 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,000 INFO sqlalchemy.engine.base.Engine (2897,)
2019-07-23 11:41:03,004 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,005 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:41:03,007 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:03,010 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,011 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,012 INFO sqlalchemy.engine.base.Engine (2898,)
2019-07-23 11:41:03,015 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,016 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:41:03,019 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,022 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,023 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,024 INFO sqlalchemy.engine.base.Engine (2899,)
2019-07-23 11:41:03,027 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,027 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:41:03,030 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,034 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,035 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,036 INFO sqlalchemy.engine.base.Engine (2900,)
2019-07-23 11:41:03,039 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,040 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:41:03,042 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,046 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,047 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,048 INFO sqlalchemy.engine.base.Engine (2901,)
2019-07-23 11:41:03,051 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,052 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:41:03,053 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,057 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,059 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,059 INFO sqlalchemy.engine.base.Engine (2902,)
2019-07-23 11:41:03,062 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,063 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:41:03,065 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,069 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,070 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,071 INFO sqlalchemy.engine.base.Engine (2903,)
2019-07-23 11:41:03,074 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,075 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:03,077 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,081 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,082 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,082 INFO sqlalchemy.engine.base.Engine (2904,)
2019-07-23 11:41:03,086 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,087 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:41:03,089 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,092 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,094 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,094 INFO sqlalchemy.engine.base.Engine (2905,)
2019-07-23 11:41:03,098 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,098 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:03,100 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,104 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,105 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,106 INFO sqlalchemy.engine.base.Engine (2906,)
2019-07-23 11:41:03,110 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,110 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:03,112 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,116 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,117 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,118 INFO sqlalchemy.engine.base.Engine (2907,)
2019-07-23 11:41:03,121 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,122 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:03,124 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,127 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,128 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,129 INFO sqlalchemy.engine.base.Engine (2908,)
2019-07-23 11:41:03,132 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,133 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:03,135 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,139 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,140 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:03,141 INFO sqlalchemy.engine.base.Engine (2909,)
2019-07-23 11:41:03,143 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,144 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:03,148 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,151 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,153 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,153 INFO sqlalchemy.engine.base.Engine (2910,)
2019-07-23 11:41:03,157 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,158 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:03,160 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,163 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,165 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,165 INFO sqlalchemy.engine.base.Engine (2911,)
2019-07-23 11:41:03,168 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,169 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:03,171 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,174 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,176 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,176 INFO sqlalchemy.engine.base.Engine (2912,)
2019-07-23 11:41:03,180 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,181 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:03,183 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,186 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,187 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,188 INFO sqlalchemy.engine.base.Engine (2913,)
2019-07-23 11:41:03,192 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,192 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:03,194 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,198 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,199 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,200 INFO sqlalchemy.engine.base.Engine (2914,)
2019-07-23 11:41:03,204 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,205 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:41:03,207 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,211 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,212 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,213 INFO sqlalchemy.engine.base.Engine (2915,)
2019-07-23 11:41:03,216 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,217 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:03,219 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,222 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,224 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,225 INFO sqlalchemy.engine.base.Engine (2916,)
2019-07-23 11:41:03,228 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,229 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:03,230 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,234 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,236 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,237 INFO sqlalchemy.engine.base.Engine (2917,)
2019-07-23 11:41:03,239 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,240 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:41:03,242 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,247 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,248 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,248 INFO sqlalchemy.engine.base.Engine (2918,)
2019-07-23 11:41:03,252 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,253 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:41:03,255 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,259 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,260 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,260 INFO sqlalchemy.engine.base.Engine (2919,)
2019-07-23 11:41:03,264 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,265 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:03,267 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,271 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,272 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,273 INFO sqlalchemy.engine.base.Engine (2920,)
2019-07-23 11:41:03,275 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:03,276 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:03,278 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,281 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,283 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,283 INFO sqlalchemy.engine.base.Engine (2921,)
2019-07-23 11:41:03,286 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,287 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:03,290 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,293 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,295 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,295 INFO sqlalchemy.engine.base.Engine (2922,)
2019-07-23 11:41:03,299 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,300 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:03,302 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,306 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,307 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,308 INFO sqlalchemy.engine.base.Engine (2923,)
2019-07-23 11:41:03,311 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,312 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:03,314 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,317 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,319 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,319 INFO sqlalchemy.engine.base.Engine (2924,)
2019-07-23 11:41:03,323 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,324 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:03,325 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,329 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,330 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,331 INFO sqlalchemy.engine.base.Engine (2925,)
2019-07-23 11:41:03,333 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,334 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:03,336 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,341 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,342 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,343 INFO sqlalchemy.engine.base.Engine (2926,)
2019-07-23 11:41:03,346 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,347 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:03,350 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,353 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,354 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,355 INFO sqlalchemy.engine.base.Engine (2927,)
2019-07-23 11:41:03,358 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,359 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:03,362 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,365 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,367 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,367 INFO sqlalchemy.engine.base.Engine (2928,)
2019-07-23 11:41:03,371 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,371 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:03,373 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,377 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,378 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,379 INFO sqlalchemy.engine.base.Engine (2929,)
2019-07-23 11:41:03,382 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,382 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:03,385 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,389 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,390 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,391 INFO sqlalchemy.engine.base.Engine (2930,)
2019-07-23 11:41:03,394 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,395 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:03,397 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,401 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,402 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,403 INFO sqlalchemy.engine.base.Engine (2931,)
2019-07-23 11:41:03,407 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,407 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:03,410 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,413 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:03,414 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,416 INFO sqlalchemy.engine.base.Engine (2932,)
2019-07-23 11:41:03,419 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,420 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:03,422 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,425 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,427 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,427 INFO sqlalchemy.engine.base.Engine (2933,)
2019-07-23 11:41:03,431 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,432 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:03,434 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,438 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,439 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,440 INFO sqlalchemy.engine.base.Engine (2934,)
2019-07-23 11:41:03,443 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,444 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:03,447 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,450 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,452 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,452 INFO sqlalchemy.engine.base.Engine (2935,)
2019-07-23 11:41:03,456 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,457 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:03,460 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,463 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,464 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,464 INFO sqlalchemy.engine.base.Engine (2936,)
2019-07-23 11:41:03,467 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,469 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:03,472 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,475 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,476 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,477 INFO sqlalchemy.engine.base.Engine (2937,)
2019-07-23 11:41:03,481 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,482 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:41:03,484 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,487 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,489 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,489 INFO sqlalchemy.engine.base.Engine (2938,)
2019-07-23 11:41:03,492 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,493 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:03,495 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,499 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,501 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,502 INFO sqlalchemy.engine.base.Engine (2939,)
2019-07-23 11:41:03,505 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,507 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:03,508 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,512 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,513 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,514 INFO sqlalchemy.engine.base.Engine (2940,)
2019-07-23 11:41:03,517 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,518 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:41:03,521 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,524 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,526 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,526 INFO sqlalchemy.engine.base.Engine (2941,)
2019-07-23 11:41:03,530 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,531 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:03,533 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,537 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,538 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,539 INFO sqlalchemy.engine.base.Engine (2942,)
2019-07-23 11:41:03,542 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,543 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:03,546 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,549 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,550 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,551 INFO sqlalchemy.engine.base.Engine (2943,)

2019-07-23 11:41:03,555 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,556 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:03,558 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,561 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,563 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,563 INFO sqlalchemy.engine.base.Engine (2944,)
2019-07-23 11:41:03,566 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,566 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:03,568 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,572 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,574 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,574 INFO sqlalchemy.engine.base.Engine (2945,)
2019-07-23 11:41:03,577 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,578 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:03,581 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,584 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,585 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,586 INFO sqlalchemy.engine.base.Engine (2946,)
2019-07-23 11:41:03,590 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,591 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:03,593 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,596 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,597 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,599 INFO sqlalchemy.engine.base.Engine (2947,)
2019-07-23 11:41:03,602 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,602 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:03,604 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,608 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,609 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,610 INFO sqlalchemy.engine.base.Engine (2948,)
2019-07-23 11:41:03,613 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,614 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:03,616 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,620 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,621 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,622 INFO sqlalchemy.engine.base.Engine (2949,)
2019-07-23 11:41:03,625 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,625 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:03,628 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,632 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,633 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,634 INFO sqlalchemy.engine.base.Engine (2950,)
2019-07-23 11:41:03,636 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,637 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:03,639 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,643 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,644 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,645 INFO sqlalchemy.engine.base.Engine (2951,)
2019-07-23 11:41:03,648 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,649 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:03,651 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,654 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,655 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,656 INFO sqlalchemy.engine.base.Engine (2952,)
2019-07-23 11:41:03,659 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,660 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:03,662 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,666 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,667 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,668 INFO sqlalchemy.engine.base.Engine (2953,)
2019-07-23 11:41:03,671 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,672 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:03,674 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,677 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,679 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,679 INFO sqlalchemy.engine.base.Engine (2954,)
2019-07-23 11:41:03,682 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,683 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:03,685 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,689 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:03,690 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,691 INFO sqlalchemy.engine.base.Engine (2955,)
2019-07-23 11:41:03,693 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,694 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:03,695 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,699 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,700 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,701 INFO sqlalchemy.engine.base.Engine (2956,)
2019-07-23 11:41:03,704 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,705 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:03,707 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,711 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,712 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,713 INFO sqlalchemy.engine.base.Engine (2957,)
2019-07-23 11:41:03,717 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,717 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:03,719 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,723 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,724 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,725 INFO sqlalchemy.engine.base.Engine (2958,)
2019-07-23 11:41:03,728 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,728 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:03,730 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,734 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,735 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,737 INFO sqlalchemy.engine.base.Engine (2959,)
2019-07-23 11:41:03,739 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,740 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:03,743 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,746 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,748 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,749 INFO sqlalchemy.engine.base.Engine (2960,)
2019-07-23 11:41:03,752 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,753 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:41:03,755 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,758 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,759 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,760 INFO sqlalchemy.engine.base.Engine (2961,)
2019-07-23 11:41:03,764 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,764 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:03,766 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,769 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,771 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,771 INFO sqlalchemy.engine.base.Engine (2962,)
2019-07-23 11:41:03,775 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,776 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:03,778 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,781 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,783 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,783 INFO sqlalchemy.engine.base.Engine (2963,)
2019-07-23 11:41:03,787 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,788 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:03,789 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,793 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,794 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,795 INFO sqlalchemy.engine.base.Engine (2964,)
2019-07-23 11:41:03,798 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,799 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:41:03,801 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,805 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,806 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,807 INFO sqlalchemy.engine.base.Engine (2965,)
2019-07-23 11:41:03,810 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,811 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:03,813 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,817 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,818 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,819 INFO sqlalchemy.engine.base.Engine (2966,)

2019-07-23 11:41:03,822 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,823 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:03,825 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,829 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,830 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,830 INFO sqlalchemy.engine.base.Engine (2967,)
2019-07-23 11:41:03,834 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,835 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:03,837 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,840 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,841 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,842 INFO sqlalchemy.engine.base.Engine (2968,)
2019-07-23 11:41:03,846 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,847 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:03,849 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,853 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,854 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,855 INFO sqlalchemy.engine.base.Engine (2969,)
2019-07-23 11:41:03,858 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,859 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:03,861 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,865 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,866 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,867 INFO sqlalchemy.engine.base.Engine (2970,)
2019-07-23 11:41:03,870 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,871 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:03,873 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,876 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,878 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,878 INFO sqlalchemy.engine.base.Engine (2971,)
2019-07-23 11:41:03,881 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,882 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:03,883 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,887 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,889 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,889 INFO sqlalchemy.engine.base.Engine (2972,)
2019-07-23 11:41:03,893 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,893 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:03,895 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,899 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,900 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,901 INFO sqlalchemy.engine.base.Engine (2973,)
2019-07-23 11:41:03,904 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,905 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:41:03,908 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,911 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,913 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,914 INFO sqlalchemy.engine.base.Engine (2974,)
2019-07-23 11:41:03,917 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,917 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:41:03,920 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,923 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,925 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,926 INFO sqlalchemy.engine.base.Engine (2975,)
2019-07-23 11:41:03,929 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,930 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:03,933 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,937 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,938 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,938 INFO sqlalchemy.engine.base.Engine (2976,)
2019-07-23 11:41:03,942 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,943 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:03,946 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,949 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,950 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,951 INFO sqlalchemy.engine.base.Engine (2977,)
2019-07-23 11:41:03,955 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,956 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')

2019-07-23 11:41:03,958 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,961 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,962 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,963 INFO sqlalchemy.engine.base.Engine (2978,)
2019-07-23 11:41:03,966 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,967 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:03,968 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,973 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,974 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,975 INFO sqlalchemy.engine.base.Engine (2979,)
2019-07-23 11:41:03,979 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,980 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:41:03,982 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,986 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,987 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,987 INFO sqlalchemy.engine.base.Engine (2980,)
2019-07-23 11:41:03,991 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:03,992 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:03,994 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:03,997 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:03,998 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:03,999 INFO sqlalchemy.engine.base.Engine (2981,)
2019-07-23 11:41:04,002 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,003 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:04,006 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,009 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,010 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,011 INFO sqlalchemy.engine.base.Engine (2982,)
2019-07-23 11:41:04,014 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,015 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:04,016 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,020 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,021 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,022 INFO sqlalchemy.engine.base.Engine (2983,)
2019-07-23 11:41:04,026 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,026 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:41:04,028 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,032 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,033 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,034 INFO sqlalchemy.engine.base.Engine (2984,)
2019-07-23 11:41:04,037 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,038 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:04,040 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,044 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,045 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,046 INFO sqlalchemy.engine.base.Engine (2985,)
2019-07-23 11:41:04,048 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,049 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:04,051 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,055 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,056 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,056 INFO sqlalchemy.engine.base.Engine (2986,)
2019-07-23 11:41:04,060 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,061 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:41:04,063 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,066 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,068 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,069 INFO sqlalchemy.engine.base.Engine (2987,)
2019-07-23 11:41:04,072 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,073 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:41:04,075 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,078 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,080 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,081 INFO sqlalchemy.engine.base.Engine (2988,)
2019-07-23 11:41:04,084 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,085 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:04,086 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,090 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,091 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:04,092 INFO sqlalchemy.engine.base.Engine (2989,)
2019-07-23 11:41:04,096 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,097 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:04,099 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,102 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,103 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,104 INFO sqlalchemy.engine.base.Engine (2990,)
2019-07-23 11:41:04,107 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,108 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:04,110 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,114 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,115 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,116 INFO sqlalchemy.engine.base.Engine (2991,)
2019-07-23 11:41:04,119 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,120 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:04,122 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,125 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,127 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,128 INFO sqlalchemy.engine.base.Engine (2992,)
2019-07-23 11:41:04,131 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,132 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:04,134 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,138 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,139 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,140 INFO sqlalchemy.engine.base.Engine (2993,)
2019-07-23 11:41:04,142 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,143 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:04,145 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,149 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,151 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,151 INFO sqlalchemy.engine.base.Engine (2994,)
2019-07-23 11:41:04,154 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,155 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:04,158 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,161 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,163 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,163 INFO sqlalchemy.engine.base.Engine (2995,)
2019-07-23 11:41:04,167 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,168 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:04,170 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,174 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,175 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,176 INFO sqlalchemy.engine.base.Engine (2996,)
2019-07-23 11:41:04,179 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,180 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:41:04,182 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,187 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,188 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,189 INFO sqlalchemy.engine.base.Engine (2997,)
2019-07-23 11:41:04,192 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,193 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:41:04,196 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,199 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,200 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,201 INFO sqlalchemy.engine.base.Engine (2998,)
2019-07-23 11:41:04,203 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,204 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:04,206 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,211 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,213 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,214 INFO sqlalchemy.engine.base.Engine (2999,)
2019-07-23 11:41:04,216 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,217 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:04,219 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,223 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,224 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,225 INFO sqlalchemy.engine.base.Engine (3000,)
2019-07-23 11:41:04,228 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,229 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')

2019-07-23 11:41:04,231 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,236 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,238 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,239 INFO sqlalchemy.engine.base.Engine (3001,)
2019-07-23 11:41:04,243 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,244 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:04,247 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,251 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,252 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,253 INFO sqlalchemy.engine.base.Engine (3002,)
2019-07-23 11:41:04,256 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,257 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:41:04,260 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,264 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,266 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,267 INFO sqlalchemy.engine.base.Engine (3003,)
2019-07-23 11:41:04,271 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,272 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:04,275 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,279 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,281 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,281 INFO sqlalchemy.engine.base.Engine (3004,)
2019-07-23 11:41:04,286 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,286 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:41:04,288 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,292 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,293 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,294 INFO sqlalchemy.engine.base.Engine (3005,)
2019-07-23 11:41:04,298 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,298 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:04,300 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,304 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,305 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,307 INFO sqlalchemy.engine.base.Engine (3006,)
2019-07-23 11:41:04,309 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,310 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:04,313 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,316 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,317 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,318 INFO sqlalchemy.engine.base.Engine (3007,)
2019-07-23 11:41:04,321 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,322 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:04,324 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,328 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,329 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,330 INFO sqlalchemy.engine.base.Engine (3008,)
2019-07-23 11:41:04,333 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,333 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:04,336 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,340 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,341 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,342 INFO sqlalchemy.engine.base.Engine (3009,)
2019-07-23 11:41:04,345 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,346 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:41:04,349 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,352 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,353 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,354 INFO sqlalchemy.engine.base.Engine (3010,)
2019-07-23 11:41:04,357 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,358 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:41:04,361 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,365 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,366 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,366 INFO sqlalchemy.engine.base.Engine (3011,)
2019-07-23 11:41:04,370 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,371 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:04,372 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,376 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,377 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:04,377 INFO sqlalchemy.engine.base.Engine (3012,)
2019-07-23 11:41:04,381 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,382 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:04,385 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,388 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,390 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,390 INFO sqlalchemy.engine.base.Engine (3013,)
2019-07-23 11:41:04,393 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,394 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:04,396 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,399 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,401 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,402 INFO sqlalchemy.engine.base.Engine (3014,)
2019-07-23 11:41:04,405 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,406 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:04,407 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,411 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,412 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,413 INFO sqlalchemy.engine.base.Engine (3015,)
2019-07-23 11:41:04,417 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:04,418 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:04,420 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:04,424 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:04,425 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:04,426 INFO sqlalchemy.engine.base.Engine (3016,)
http://sz.ganji.com/zufang/pn8 status: 200
2019-07-23 11:41:05,374 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,374 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:41:05,377 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,381 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,382 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,382 INFO sqlalchemy.engine.base.Engine (3017,)
2019-07-23 11:41:05,385 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,386 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:41:05,388 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,392 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,393 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,394 INFO sqlalchemy.engine.base.Engine (3018,)
2019-07-23 11:41:05,397 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,397 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:41:05,400 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,403 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,404 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,405 INFO sqlalchemy.engine.base.Engine (3019,)
2019-07-23 11:41:05,408 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,409 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:41:05,411 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,414 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,415 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,416 INFO sqlalchemy.engine.base.Engine (3020,)
2019-07-23 11:41:05,419 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,420 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:41:05,423 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,426 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,427 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,428 INFO sqlalchemy.engine.base.Engine (3021,)
2019-07-23 11:41:05,431 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,432 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:41:05,434 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,438 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,439 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,440 INFO sqlalchemy.engine.base.Engine (3022,)
2019-07-23 11:41:05,442 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,443 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:41:05,445 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,449 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,450 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,451 INFO sqlalchemy.engine.base.Engine (3023,)
2019-07-23 11:41:05,455 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:05,456 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:05,458 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,462 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,463 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,463 INFO sqlalchemy.engine.base.Engine (3024,)
2019-07-23 11:41:05,467 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,468 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:41:05,469 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,473 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,474 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,474 INFO sqlalchemy.engine.base.Engine (3025,)
2019-07-23 11:41:05,478 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,478 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:05,481 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,484 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,485 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,486 INFO sqlalchemy.engine.base.Engine (3026,)
2019-07-23 11:41:05,489 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,490 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:41:05,492 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,496 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,497 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,498 INFO sqlalchemy.engine.base.Engine (3027,)
2019-07-23 11:41:05,501 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,502 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:41:05,504 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,507 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,509 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,510 INFO sqlalchemy.engine.base.Engine (3028,)
2019-07-23 11:41:05,512 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,513 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:41:05,515 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,519 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,520 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,521 INFO sqlalchemy.engine.base.Engine (3029,)
2019-07-23 11:41:05,523 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,524 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:41:05,525 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,529 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,531 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,531 INFO sqlalchemy.engine.base.Engine (3030,)
2019-07-23 11:41:05,534 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,535 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:41:05,537 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,541 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,542 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,542 INFO sqlalchemy.engine.base.Engine (3031,)
2019-07-23 11:41:05,546 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,547 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:41:05,549 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,553 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,554 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,555 INFO sqlalchemy.engine.base.Engine (3032,)
2019-07-23 11:41:05,558 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,559 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:41:05,562 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,565 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,566 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,567 INFO sqlalchemy.engine.base.Engine (3033,)
2019-07-23 11:41:05,570 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,571 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:41:05,573 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,577 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,578 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,578 INFO sqlalchemy.engine.base.Engine (3034,)
2019-07-23 11:41:05,582 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,582 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:41:05,584 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:05,588 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,589 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,590 INFO sqlalchemy.engine.base.Engine (3035,)
2019-07-23 11:41:05,593 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,593 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:41:05,595 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,599 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,600 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,601 INFO sqlalchemy.engine.base.Engine (3036,)
2019-07-23 11:41:05,604 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,605 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:41:05,607 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,611 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,612 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,613 INFO sqlalchemy.engine.base.Engine (3037,)
2019-07-23 11:41:05,616 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,617 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:41:05,619 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,623 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,624 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,626 INFO sqlalchemy.engine.base.Engine (3038,)
2019-07-23 11:41:05,628 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,629 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:41:05,631 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,634 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,636 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,636 INFO sqlalchemy.engine.base.Engine (3039,)
2019-07-23 11:41:05,640 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,641 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:41:05,643 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,646 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,648 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,648 INFO sqlalchemy.engine.base.Engine (3040,)
2019-07-23 11:41:05,652 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,653 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:41:05,655 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,658 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,659 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,660 INFO sqlalchemy.engine.base.Engine (3041,)
2019-07-23 11:41:05,663 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,664 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:41:05,666 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,669 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,671 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,672 INFO sqlalchemy.engine.base.Engine (3042,)
2019-07-23 11:41:05,674 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,675 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:05,677 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,681 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,682 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,682 INFO sqlalchemy.engine.base.Engine (3043,)
2019-07-23 11:41:05,686 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,686 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:41:05,689 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,692 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,693 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,694 INFO sqlalchemy.engine.base.Engine (3044,)
2019-07-23 11:41:05,697 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,698 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:05,700 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,704 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,705 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,706 INFO sqlalchemy.engine.base.Engine (3045,)
2019-07-23 11:41:05,709 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,710 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:05,712 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,715 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,716 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:05,717 INFO sqlalchemy.engine.base.Engine (3046,)
2019-07-23 11:41:05,720 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,721 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:05,723 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,727 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,728 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,728 INFO sqlalchemy.engine.base.Engine (3047,)
2019-07-23 11:41:05,732 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,733 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:05,735 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,738 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,739 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,740 INFO sqlalchemy.engine.base.Engine (3048,)
2019-07-23 11:41:05,744 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,745 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:05,747 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,751 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,752 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,753 INFO sqlalchemy.engine.base.Engine (3049,)
2019-07-23 11:41:05,756 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,757 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:05,759 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,762 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,763 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,764 INFO sqlalchemy.engine.base.Engine (3050,)
2019-07-23 11:41:05,767 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,767 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:05,769 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,773 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,774 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,775 INFO sqlalchemy.engine.base.Engine (3051,)
2019-07-23 11:41:05,778 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,779 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:05,782 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,785 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,786 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,787 INFO sqlalchemy.engine.base.Engine (3052,)
2019-07-23 11:41:05,790 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,791 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:05,792 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,796 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,797 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,798 INFO sqlalchemy.engine.base.Engine (3053,)
2019-07-23 11:41:05,801 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,802 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:41:05,804 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,808 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,809 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,810 INFO sqlalchemy.engine.base.Engine (3054,)
2019-07-23 11:41:05,813 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,814 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:05,816 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,820 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,821 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,822 INFO sqlalchemy.engine.base.Engine (3055,)
2019-07-23 11:41:05,824 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,825 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:05,828 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,831 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,832 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,833 INFO sqlalchemy.engine.base.Engine (3056,)
2019-07-23 11:41:05,836 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,837 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:41:05,839 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,842 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,844 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,844 INFO sqlalchemy.engine.base.Engine (3057,)
2019-07-23 11:41:05,847 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,848 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')

2019-07-23 11:41:05,849 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,853 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,854 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,855 INFO sqlalchemy.engine.base.Engine (3058,)
2019-07-23 11:41:05,858 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,859 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:05,861 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,864 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,865 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,866 INFO sqlalchemy.engine.base.Engine (3059,)
2019-07-23 11:41:05,870 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,870 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:05,872 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,876 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,877 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,878 INFO sqlalchemy.engine.base.Engine (3060,)
2019-07-23 11:41:05,881 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,882 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:05,884 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,887 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,889 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,890 INFO sqlalchemy.engine.base.Engine (3061,)
2019-07-23 11:41:05,893 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,894 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:05,895 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,899 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,900 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,901 INFO sqlalchemy.engine.base.Engine (3062,)
2019-07-23 11:41:05,903 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,904 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:05,907 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,910 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,912 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,912 INFO sqlalchemy.engine.base.Engine (3063,)
2019-07-23 11:41:05,916 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,916 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:05,919 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,922 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,923 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,924 INFO sqlalchemy.engine.base.Engine (3064,)
2019-07-23 11:41:05,927 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,928 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:05,931 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,935 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,936 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,937 INFO sqlalchemy.engine.base.Engine (3065,)
2019-07-23 11:41:05,940 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,941 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:05,942 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,946 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,947 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,948 INFO sqlalchemy.engine.base.Engine (3066,)
2019-07-23 11:41:05,951 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,952 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:05,954 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,958 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,959 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,960 INFO sqlalchemy.engine.base.Engine (3067,)
2019-07-23 11:41:05,963 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,964 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:05,966 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,970 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,971 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,971 INFO sqlalchemy.engine.base.Engine (3068,)
2019-07-23 11:41:05,975 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,975 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:05,977 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,981 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,982 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:05,983 INFO sqlalchemy.engine.base.Engine (3069,)
2019-07-23 11:41:05,986 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,987 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:05,990 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:05,993 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:05,994 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:05,995 INFO sqlalchemy.engine.base.Engine (3070,)
2019-07-23 11:41:05,998 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:05,999 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:06,001 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,004 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,005 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,006 INFO sqlalchemy.engine.base.Engine (3071,)
2019-07-23 11:41:06,009 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,010 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:06,012 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,015 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,017 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,017 INFO sqlalchemy.engine.base.Engine (3072,)
2019-07-23 11:41:06,020 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,021 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:06,023 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,027 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,028 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,029 INFO sqlalchemy.engine.base.Engine (3073,)
2019-07-23 11:41:06,032 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,033 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:06,035 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,038 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,039 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,040 INFO sqlalchemy.engine.base.Engine (3074,)
2019-07-23 11:41:06,043 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,043 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:06,046 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,049 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,051 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,051 INFO sqlalchemy.engine.base.Engine (3075,)
2019-07-23 11:41:06,055 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,056 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:06,058 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,062 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,063 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,064 INFO sqlalchemy.engine.base.Engine (3076,)
2019-07-23 11:41:06,067 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,068 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:41:06,070 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,074 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,075 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,076 INFO sqlalchemy.engine.base.Engine (3077,)
2019-07-23 11:41:06,079 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,080 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:06,082 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,085 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,086 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,087 INFO sqlalchemy.engine.base.Engine (3078,)
2019-07-23 11:41:06,090 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,091 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:06,092 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,096 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,097 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,098 INFO sqlalchemy.engine.base.Engine (3079,)
2019-07-23 11:41:06,101 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,102 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:41:06,104 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,108 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,109 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,109 INFO sqlalchemy.engine.base.Engine (3080,)
2019-07-23 11:41:06,113 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,114 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')

2019-07-23 11:41:06,116 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,119 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,120 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,121 INFO sqlalchemy.engine.base.Engine (3081,)
2019-07-23 11:41:06,124 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,125 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:06,127 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,131 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,132 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,133 INFO sqlalchemy.engine.base.Engine (3082,)
2019-07-23 11:41:06,136 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,136 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:06,139 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,142 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,143 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,144 INFO sqlalchemy.engine.base.Engine (3083,)
2019-07-23 11:41:06,148 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,148 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:06,151 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,154 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,155 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,156 INFO sqlalchemy.engine.base.Engine (3084,)
2019-07-23 11:41:06,159 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,160 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:06,162 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,165 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,166 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,167 INFO sqlalchemy.engine.base.Engine (3085,)
2019-07-23 11:41:06,170 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,171 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:06,173 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,177 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,178 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,179 INFO sqlalchemy.engine.base.Engine (3086,)
2019-07-23 11:41:06,182 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,183 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:06,185 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,188 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,189 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,190 INFO sqlalchemy.engine.base.Engine (3087,)
2019-07-23 11:41:06,194 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,195 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:06,196 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,199 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,201 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,201 INFO sqlalchemy.engine.base.Engine (3088,)
2019-07-23 11:41:06,205 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,206 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:06,207 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,211 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,212 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,213 INFO sqlalchemy.engine.base.Engine (3089,)
2019-07-23 11:41:06,216 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,216 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:06,219 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,223 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,224 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,224 INFO sqlalchemy.engine.base.Engine (3090,)
2019-07-23 11:41:06,228 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,229 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:06,231 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,234 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,236 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,236 INFO sqlalchemy.engine.base.Engine (3091,)
2019-07-23 11:41:06,240 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,241 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:06,243 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,247 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,248 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:06,248 INFO sqlalchemy.engine.base.Engine (3092,)
2019-07-23 11:41:06,252 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,253 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:06,255 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,258 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,259 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,260 INFO sqlalchemy.engine.base.Engine (3093,)
2019-07-23 11:41:06,263 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,264 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:06,266 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,269 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,270 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,271 INFO sqlalchemy.engine.base.Engine (3094,)
2019-07-23 11:41:06,274 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,275 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:06,278 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,281 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,282 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,283 INFO sqlalchemy.engine.base.Engine (3095,)
2019-07-23 11:41:06,285 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,287 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:06,290 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,294 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,295 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,296 INFO sqlalchemy.engine.base.Engine (3096,)
2019-07-23 11:41:06,299 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,300 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:06,302 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,305 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,307 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,307 INFO sqlalchemy.engine.base.Engine (3097,)
2019-07-23 11:41:06,311 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,312 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:06,314 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,317 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,318 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,319 INFO sqlalchemy.engine.base.Engine (3098,)
2019-07-23 11:41:06,322 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,323 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:06,325 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,329 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,330 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,331 INFO sqlalchemy.engine.base.Engine (3099,)
2019-07-23 11:41:06,334 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,335 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:41:06,337 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,341 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,342 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,342 INFO sqlalchemy.engine.base.Engine (3100,)
2019-07-23 11:41:06,346 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,347 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:06,349 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,352 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,354 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,355 INFO sqlalchemy.engine.base.Engine (3101,)
2019-07-23 11:41:06,358 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,358 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:06,360 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,364 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,365 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,366 INFO sqlalchemy.engine.base.Engine (3102,)
2019-07-23 11:41:06,369 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,370 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:06,372 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,376 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,377 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,378 INFO sqlalchemy.engine.base.Engine (3103,)
2019-07-23 11:41:06,381 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,382 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')

2019-07-23 11:41:06,384 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,387 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,389 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,389 INFO sqlalchemy.engine.base.Engine (3104,)
2019-07-23 11:41:06,392 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,393 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:06,395 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,399 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,400 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,400 INFO sqlalchemy.engine.base.Engine (3105,)
2019-07-23 11:41:06,404 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,405 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:06,407 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,410 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,411 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,412 INFO sqlalchemy.engine.base.Engine (3106,)
2019-07-23 11:41:06,415 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,416 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:06,417 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,421 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,422 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,423 INFO sqlalchemy.engine.base.Engine (3107,)
2019-07-23 11:41:06,426 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,427 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:06,428 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,432 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,433 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,434 INFO sqlalchemy.engine.base.Engine (3108,)
2019-07-23 11:41:06,437 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,437 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:06,439 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,443 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,445 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,445 INFO sqlalchemy.engine.base.Engine (3109,)
2019-07-23 11:41:06,449 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,449 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:06,451 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,454 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,455 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,456 INFO sqlalchemy.engine.base.Engine (3110,)
2019-07-23 11:41:06,459 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,460 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:06,463 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,466 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,467 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,468 INFO sqlalchemy.engine.base.Engine (3111,)
2019-07-23 11:41:06,471 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,472 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:06,474 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,477 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,478 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,479 INFO sqlalchemy.engine.base.Engine (3112,)
2019-07-23 11:41:06,481 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,482 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:41:06,485 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,488 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,489 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,490 INFO sqlalchemy.engine.base.Engine (3113,)
2019-07-23 11:41:06,493 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,494 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:41:06,496 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,500 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,501 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,501 INFO sqlalchemy.engine.base.Engine (3114,)
2019-07-23 11:41:06,505 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,506 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:06,508 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,511 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,513 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:06,513 INFO sqlalchemy.engine.base.Engine (3115,)
2019-07-23 11:41:06,517 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,517 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:06,519 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,523 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,524 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,525 INFO sqlalchemy.engine.base.Engine (3116,)
2019-07-23 11:41:06,527 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,528 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:41:06,530 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,534 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,535 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,536 INFO sqlalchemy.engine.base.Engine (3117,)
2019-07-23 11:41:06,539 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,539 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:06,542 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,546 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,547 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,548 INFO sqlalchemy.engine.base.Engine (3118,)
2019-07-23 11:41:06,551 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,552 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:41:06,554 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,557 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,558 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,559 INFO sqlalchemy.engine.base.Engine (3119,)
2019-07-23 11:41:06,563 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,564 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:06,566 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,570 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,571 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,572 INFO sqlalchemy.engine.base.Engine (3120,)
2019-07-23 11:41:06,575 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,575 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:06,577 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,581 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,582 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,583 INFO sqlalchemy.engine.base.Engine (3121,)
2019-07-23 11:41:06,586 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,587 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:06,590 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,593 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,595 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,595 INFO sqlalchemy.engine.base.Engine (3122,)
2019-07-23 11:41:06,599 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,600 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:41:06,602 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,605 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,606 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,607 INFO sqlalchemy.engine.base.Engine (3123,)
2019-07-23 11:41:06,609 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,610 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:06,613 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,616 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,617 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,618 INFO sqlalchemy.engine.base.Engine (3124,)
2019-07-23 11:41:06,622 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,623 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:06,625 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,628 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,629 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,630 INFO sqlalchemy.engine.base.Engine (3125,)
2019-07-23 11:41:06,633 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,634 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:41:06,637 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,641 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,642 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,643 INFO sqlalchemy.engine.base.Engine (3126,)
2019-07-23 11:41:06,646 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,647 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')

2019-07-23 11:41:06,650 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,653 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,654 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,655 INFO sqlalchemy.engine.base.Engine (3127,)
2019-07-23 11:41:06,658 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,659 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:06,661 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,664 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,665 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,666 INFO sqlalchemy.engine.base.Engine (3128,)
2019-07-23 11:41:06,669 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,670 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:06,672 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,675 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,676 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,677 INFO sqlalchemy.engine.base.Engine (3129,)
2019-07-23 11:41:06,681 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,682 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:06,684 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,688 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,689 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,689 INFO sqlalchemy.engine.base.Engine (3130,)
2019-07-23 11:41:06,692 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,692 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:06,695 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,698 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,699 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,700 INFO sqlalchemy.engine.base.Engine (3131,)
2019-07-23 11:41:06,703 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,704 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:06,705 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,709 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,710 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,710 INFO sqlalchemy.engine.base.Engine (3132,)
2019-07-23 11:41:06,713 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,713 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:06,715 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,718 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,720 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,720 INFO sqlalchemy.engine.base.Engine (3133,)
2019-07-23 11:41:06,723 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,724 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:06,726 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,730 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,731 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,732 INFO sqlalchemy.engine.base.Engine (3134,)
2019-07-23 11:41:06,735 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,736 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:06,738 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,741 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,743 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,743 INFO sqlalchemy.engine.base.Engine (3135,)
2019-07-23 11:41:06,747 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,748 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:41:06,751 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,754 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,755 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,756 INFO sqlalchemy.engine.base.Engine (3136,)
2019-07-23 11:41:06,759 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,760 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:41:06,762 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,766 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,767 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,767 INFO sqlalchemy.engine.base.Engine (3137,)
2019-07-23 11:41:06,771 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,771 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:06,774 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,777 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,778 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:06,779 INFO sqlalchemy.engine.base.Engine (3138,)
2019-07-23 11:41:06,781 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,782 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:06,784 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,788 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,789 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,790 INFO sqlalchemy.engine.base.Engine (3139,)
2019-07-23 11:41:06,793 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,794 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:41:06,796 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,800 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,801 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,802 INFO sqlalchemy.engine.base.Engine (3140,)
2019-07-23 11:41:06,805 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,806 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:06,808 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,811 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,813 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,813 INFO sqlalchemy.engine.base.Engine (3141,)
2019-07-23 11:41:06,816 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,817 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:41:06,819 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,823 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,824 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,825 INFO sqlalchemy.engine.base.Engine (3142,)
2019-07-23 11:41:06,828 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,829 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:06,831 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,835 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,836 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,837 INFO sqlalchemy.engine.base.Engine (3143,)
2019-07-23 11:41:06,841 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,842 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:41:06,843 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,847 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,849 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,849 INFO sqlalchemy.engine.base.Engine (3144,)
2019-07-23 11:41:06,853 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,854 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:06,856 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,859 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,861 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,861 INFO sqlalchemy.engine.base.Engine (3145,)
2019-07-23 11:41:06,865 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,865 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:06,867 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,871 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,873 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,873 INFO sqlalchemy.engine.base.Engine (3146,)
2019-07-23 11:41:06,876 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,876 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:06,878 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,882 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,884 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,884 INFO sqlalchemy.engine.base.Engine (3147,)
2019-07-23 11:41:06,888 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,889 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:06,891 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,895 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,896 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,897 INFO sqlalchemy.engine.base.Engine (3148,)
2019-07-23 11:41:06,901 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,901 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:41:06,903 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,907 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,908 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,909 INFO sqlalchemy.engine.base.Engine (3149,)
2019-07-23 11:41:06,912 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,913 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')

2019-07-23 11:41:06,915 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,919 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,920 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,921 INFO sqlalchemy.engine.base.Engine (3150,)
2019-07-23 11:41:06,924 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,925 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:06,927 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,931 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,932 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,933 INFO sqlalchemy.engine.base.Engine (3151,)
2019-07-23 11:41:06,937 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,938 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:06,940 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,945 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,946 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,947 INFO sqlalchemy.engine.base.Engine (3152,)
2019-07-23 11:41:06,950 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,951 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:06,954 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,957 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,958 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,959 INFO sqlalchemy.engine.base.Engine (3153,)
2019-07-23 11:41:06,962 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,964 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:06,966 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,970 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,972 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,973 INFO sqlalchemy.engine.base.Engine (3154,)
2019-07-23 11:41:06,977 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:06,979 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:06,982 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:06,986 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:06,988 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:06,989 INFO sqlalchemy.engine.base.Engine (3155,)
http://sz.ganji.com/zufang/pn9 status: 200
2019-07-23 11:41:07,933 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:07,934 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:41:07,936 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:07,940 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:07,941 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:07,942 INFO sqlalchemy.engine.base.Engine (3156,)
2019-07-23 11:41:07,946 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:07,946 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:41:07,949 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:07,952 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:07,953 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:07,954 INFO sqlalchemy.engine.base.Engine (3157,)
2019-07-23 11:41:07,957 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:07,957 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:41:07,959 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:07,963 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:07,964 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:07,965 INFO sqlalchemy.engine.base.Engine (3158,)
2019-07-23 11:41:07,968 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:07,968 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:41:07,970 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:07,974 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:07,975 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:07,975 INFO sqlalchemy.engine.base.Engine (3159,)
2019-07-23 11:41:07,979 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:07,980 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:41:07,981 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:07,985 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:07,987 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:07,988 INFO sqlalchemy.engine.base.Engine (3160,)
2019-07-23 11:41:07,990 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:07,991 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:41:07,993 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:07,996 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:07,997 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:07,998 INFO sqlalchemy.engine.base.Engine (3161,)
2019-07-23 11:41:08,001 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,001 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:41:08,004 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,008 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,009 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,010 INFO sqlalchemy.engine.base.Engine (3162,)
2019-07-23 11:41:08,013 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,014 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:08,017 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,020 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,021 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,021 INFO sqlalchemy.engine.base.Engine (3163,)
2019-07-23 11:41:08,024 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,024 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:41:08,026 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,030 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,031 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,032 INFO sqlalchemy.engine.base.Engine (3164,)
2019-07-23 11:41:08,035 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,035 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:08,038 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,041 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,042 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,043 INFO sqlalchemy.engine.base.Engine (3165,)
2019-07-23 11:41:08,046 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,047 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:41:08,049 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,053 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,054 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,054 INFO sqlalchemy.engine.base.Engine (3166,)
2019-07-23 11:41:08,057 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,058 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:41:08,060 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,064 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,065 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,065 INFO sqlalchemy.engine.base.Engine (3167,)
2019-07-23 11:41:08,069 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,069 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:41:08,071 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,075 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,076 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,077 INFO sqlalchemy.engine.base.Engine (3168,)
2019-07-23 11:41:08,080 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,081 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:41:08,083 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,086 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,087 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,088 INFO sqlalchemy.engine.base.Engine (3169,)
2019-07-23 11:41:08,091 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,092 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:41:08,094 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,097 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,098 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,099 INFO sqlalchemy.engine.base.Engine (3170,)
2019-07-23 11:41:08,101 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,102 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:41:08,104 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,108 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,109 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,110 INFO sqlalchemy.engine.base.Engine (3171,)
2019-07-23 11:41:08,113 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,114 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:41:08,115 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,119 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,120 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,121 INFO sqlalchemy.engine.base.Engine (3172,)
2019-07-23 11:41:08,124 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,125 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')

2019-07-23 11:41:08,127 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,130 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,131 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,132 INFO sqlalchemy.engine.base.Engine (3173,)
2019-07-23 11:41:08,136 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,137 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:41:08,139 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,142 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,143 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,144 INFO sqlalchemy.engine.base.Engine (3174,)
2019-07-23 11:41:08,147 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,148 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:41:08,150 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,153 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,154 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,155 INFO sqlalchemy.engine.base.Engine (3175,)
2019-07-23 11:41:08,158 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,159 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:41:08,161 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,165 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,166 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,166 INFO sqlalchemy.engine.base.Engine (3176,)
2019-07-23 11:41:08,169 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,170 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:41:08,172 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,176 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,177 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,178 INFO sqlalchemy.engine.base.Engine (3177,)
2019-07-23 11:41:08,181 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,182 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:41:08,184 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,187 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,189 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,189 INFO sqlalchemy.engine.base.Engine (3178,)
2019-07-23 11:41:08,192 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,192 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:41:08,195 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,198 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,199 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,200 INFO sqlalchemy.engine.base.Engine (3179,)
2019-07-23 11:41:08,203 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,204 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:41:08,206 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,209 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,210 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,211 INFO sqlalchemy.engine.base.Engine (3180,)
2019-07-23 11:41:08,213 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,214 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:41:08,215 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,219 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,220 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,221 INFO sqlalchemy.engine.base.Engine (3181,)
2019-07-23 11:41:08,224 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,224 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:08,227 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,230 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,231 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,232 INFO sqlalchemy.engine.base.Engine (3182,)
2019-07-23 11:41:08,235 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,236 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:41:08,239 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,242 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,243 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,244 INFO sqlalchemy.engine.base.Engine (3183,)
2019-07-23 11:41:08,247 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,248 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:08,251 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,254 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,255 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:08,256 INFO sqlalchemy.engine.base.Engine (3184,)
2019-07-23 11:41:08,259 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,260 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:08,262 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,265 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,266 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,266 INFO sqlalchemy.engine.base.Engine (3185,)
2019-07-23 11:41:08,269 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,269 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:08,271 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,275 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,276 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,276 INFO sqlalchemy.engine.base.Engine (3186,)
2019-07-23 11:41:08,279 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,280 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:08,282 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,285 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,287 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,287 INFO sqlalchemy.engine.base.Engine (3187,)
2019-07-23 11:41:08,290 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,291 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:08,293 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,296 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,298 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,298 INFO sqlalchemy.engine.base.Engine (3188,)
2019-07-23 11:41:08,302 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,302 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:08,304 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,308 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,309 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,309 INFO sqlalchemy.engine.base.Engine (3189,)
2019-07-23 11:41:08,313 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,313 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:08,315 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,318 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,319 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,320 INFO sqlalchemy.engine.base.Engine (3190,)
2019-07-23 11:41:08,323 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,324 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:08,327 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,330 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,331 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,332 INFO sqlalchemy.engine.base.Engine (3191,)
2019-07-23 11:41:08,335 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,336 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:08,338 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,342 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,343 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,344 INFO sqlalchemy.engine.base.Engine (3192,)
2019-07-23 11:41:08,348 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,348 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:41:08,350 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,354 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,355 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,356 INFO sqlalchemy.engine.base.Engine (3193,)
2019-07-23 11:41:08,359 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,360 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:08,362 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,365 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,366 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,367 INFO sqlalchemy.engine.base.Engine (3194,)
2019-07-23 11:41:08,370 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,371 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:08,372 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,376 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,377 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,378 INFO sqlalchemy.engine.base.Engine (3195,)
2019-07-23 11:41:08,380 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,381 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')

2019-07-23 11:41:08,384 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,387 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,388 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,389 INFO sqlalchemy.engine.base.Engine (3196,)
2019-07-23 11:41:08,392 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,393 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:41:08,395 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,398 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,400 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,400 INFO sqlalchemy.engine.base.Engine (3197,)
2019-07-23 11:41:08,403 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,404 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:08,406 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,409 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,410 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,411 INFO sqlalchemy.engine.base.Engine (3198,)
2019-07-23 11:41:08,413 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,414 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:08,415 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,420 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,421 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,422 INFO sqlalchemy.engine.base.Engine (3199,)
2019-07-23 11:41:08,425 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,427 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:08,429 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,432 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,434 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,434 INFO sqlalchemy.engine.base.Engine (3200,)
2019-07-23 11:41:08,438 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,440 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:08,441 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,444 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,446 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,446 INFO sqlalchemy.engine.base.Engine (3201,)
2019-07-23 11:41:08,449 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,449 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:08,451 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,458 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,461 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,462 INFO sqlalchemy.engine.base.Engine (3202,)
2019-07-23 11:41:08,466 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,466 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:08,469 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,472 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,473 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,473 INFO sqlalchemy.engine.base.Engine (3203,)
2019-07-23 11:41:08,477 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,477 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:08,479 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,482 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,484 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,484 INFO sqlalchemy.engine.base.Engine (3204,)
2019-07-23 11:41:08,487 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,488 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:08,490 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,493 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,494 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,495 INFO sqlalchemy.engine.base.Engine (3205,)
2019-07-23 11:41:08,498 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,499 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:08,500 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,504 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,506 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,506 INFO sqlalchemy.engine.base.Engine (3206,)
2019-07-23 11:41:08,509 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,510 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:08,512 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,515 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,516 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:08,517 INFO sqlalchemy.engine.base.Engine (3207,)
2019-07-23 11:41:08,520 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,521 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:08,523 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,526 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,527 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,528 INFO sqlalchemy.engine.base.Engine (3208,)
2019-07-23 11:41:08,531 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,531 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:08,533 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,536 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,537 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,538 INFO sqlalchemy.engine.base.Engine (3209,)
2019-07-23 11:41:08,541 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,542 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:08,544 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,548 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,549 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,550 INFO sqlalchemy.engine.base.Engine (3210,)
2019-07-23 11:41:08,552 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,553 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:08,555 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,559 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,559 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,560 INFO sqlalchemy.engine.base.Engine (3211,)
2019-07-23 11:41:08,563 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,564 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:08,566 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,569 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,570 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,571 INFO sqlalchemy.engine.base.Engine (3212,)
2019-07-23 11:41:08,574 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,575 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:08,577 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,580 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,581 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,582 INFO sqlalchemy.engine.base.Engine (3213,)
2019-07-23 11:41:08,586 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,587 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:08,589 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,592 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,593 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,594 INFO sqlalchemy.engine.base.Engine (3214,)
2019-07-23 11:41:08,597 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,598 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:08,600 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,603 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,605 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,605 INFO sqlalchemy.engine.base.Engine (3215,)
2019-07-23 11:41:08,608 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,609 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:41:08,611 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,614 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,615 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,616 INFO sqlalchemy.engine.base.Engine (3216,)
2019-07-23 11:41:08,619 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,620 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:08,622 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,626 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,627 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,627 INFO sqlalchemy.engine.base.Engine (3217,)
2019-07-23 11:41:08,631 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,631 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:08,634 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,638 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,639 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,640 INFO sqlalchemy.engine.base.Engine (3218,)
2019-07-23 11:41:08,643 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,644 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')

2019-07-23 11:41:08,647 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,650 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,651 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,652 INFO sqlalchemy.engine.base.Engine (3219,)
2019-07-23 11:41:08,655 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,656 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:08,658 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,661 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,663 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,664 INFO sqlalchemy.engine.base.Engine (3220,)
2019-07-23 11:41:08,667 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,667 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:08,669 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,673 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,674 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,675 INFO sqlalchemy.engine.base.Engine (3221,)
2019-07-23 11:41:08,678 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,679 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:08,681 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,685 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,686 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,687 INFO sqlalchemy.engine.base.Engine (3222,)
2019-07-23 11:41:08,690 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,691 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:08,692 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,696 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,697 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,698 INFO sqlalchemy.engine.base.Engine (3223,)
2019-07-23 11:41:08,701 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,702 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:08,704 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,708 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,709 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,710 INFO sqlalchemy.engine.base.Engine (3224,)
2019-07-23 11:41:08,713 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,713 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:08,715 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,718 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,719 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,720 INFO sqlalchemy.engine.base.Engine (3225,)
2019-07-23 11:41:08,723 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,724 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:08,726 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,729 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,731 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,731 INFO sqlalchemy.engine.base.Engine (3226,)
2019-07-23 11:41:08,734 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,735 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:08,737 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,741 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,742 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,743 INFO sqlalchemy.engine.base.Engine (3227,)
2019-07-23 11:41:08,746 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,747 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:08,750 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,753 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,754 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,755 INFO sqlalchemy.engine.base.Engine (3228,)
2019-07-23 11:41:08,757 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,758 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:08,760 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,764 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,765 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,766 INFO sqlalchemy.engine.base.Engine (3229,)
2019-07-23 11:41:08,769 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,770 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:08,771 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,775 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,777 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,778 INFO sqlalchemy.engine.base.Engine (3230,)

2019-07-23 11:41:08,781 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,782 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:08,784 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,788 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,789 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,789 INFO sqlalchemy.engine.base.Engine (3231,)
2019-07-23 11:41:08,793 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,793 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:08,796 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,799 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,800 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,800 INFO sqlalchemy.engine.base.Engine (3232,)
2019-07-23 11:41:08,803 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,804 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:08,806 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,809 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,811 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,812 INFO sqlalchemy.engine.base.Engine (3233,)
2019-07-23 11:41:08,814 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,815 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:08,818 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,821 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,822 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,823 INFO sqlalchemy.engine.base.Engine (3234,)
2019-07-23 11:41:08,826 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,827 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:08,830 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,834 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,835 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,835 INFO sqlalchemy.engine.base.Engine (3235,)
2019-07-23 11:41:08,839 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,840 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:08,842 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,846 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,847 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,848 INFO sqlalchemy.engine.base.Engine (3236,)
2019-07-23 11:41:08,850 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,851 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:08,854 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,858 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,859 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,860 INFO sqlalchemy.engine.base.Engine (3237,)
2019-07-23 11:41:08,863 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,864 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:08,866 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,869 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,870 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,871 INFO sqlalchemy.engine.base.Engine (3238,)
2019-07-23 11:41:08,874 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,874 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:41:08,876 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,880 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,881 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,882 INFO sqlalchemy.engine.base.Engine (3239,)
2019-07-23 11:41:08,885 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,886 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:08,889 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,892 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,894 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,895 INFO sqlalchemy.engine.base.Engine (3240,)
2019-07-23 11:41:08,897 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,898 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:08,900 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,904 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,905 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,905 INFO sqlalchemy.engine.base.Engine (3241,)
2019-07-23 11:41:08,908 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,908 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:08,910 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:08,914 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,915 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,915 INFO sqlalchemy.engine.base.Engine (3242,)
2019-07-23 11:41:08,918 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,919 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:41:08,921 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,926 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,927 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,927 INFO sqlalchemy.engine.base.Engine (3243,)
2019-07-23 11:41:08,930 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,931 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:08,934 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,938 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,939 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,939 INFO sqlalchemy.engine.base.Engine (3244,)
2019-07-23 11:41:08,943 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,944 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:08,946 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,950 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,951 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,952 INFO sqlalchemy.engine.base.Engine (3245,)
2019-07-23 11:41:08,955 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,956 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:08,957 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,961 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,962 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,963 INFO sqlalchemy.engine.base.Engine (3246,)
2019-07-23 11:41:08,966 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,967 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:08,969 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,972 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,973 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,974 INFO sqlalchemy.engine.base.Engine (3247,)
2019-07-23 11:41:08,977 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,978 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:08,980 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,983 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,984 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,985 INFO sqlalchemy.engine.base.Engine (3248,)
2019-07-23 11:41:08,988 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:08,989 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:08,992 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:08,996 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:08,997 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:08,998 INFO sqlalchemy.engine.base.Engine (3249,)
2019-07-23 11:41:09,001 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,002 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:09,004 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,008 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,009 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,010 INFO sqlalchemy.engine.base.Engine (3250,)
2019-07-23 11:41:09,014 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,015 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:09,020 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,024 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,025 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,025 INFO sqlalchemy.engine.base.Engine (3251,)
2019-07-23 11:41:09,029 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,030 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:41:09,033 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,037 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,038 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,038 INFO sqlalchemy.engine.base.Engine (3252,)
2019-07-23 11:41:09,041 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,042 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:41:09,044 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,048 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,049 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:09,050 INFO sqlalchemy.engine.base.Engine (3253,)
2019-07-23 11:41:09,053 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,054 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:09,055 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,060 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,061 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,061 INFO sqlalchemy.engine.base.Engine (3254,)
2019-07-23 11:41:09,064 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,065 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:09,067 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,070 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,071 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,072 INFO sqlalchemy.engine.base.Engine (3255,)
2019-07-23 11:41:09,075 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,076 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:41:09,077 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,081 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,082 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,083 INFO sqlalchemy.engine.base.Engine (3256,)
2019-07-23 11:41:09,085 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,086 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:09,088 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,092 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,093 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,094 INFO sqlalchemy.engine.base.Engine (3257,)
2019-07-23 11:41:09,098 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,100 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:41:09,102 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,105 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,106 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,108 INFO sqlalchemy.engine.base.Engine (3258,)
2019-07-23 11:41:09,110 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,111 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:09,114 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,117 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,118 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,119 INFO sqlalchemy.engine.base.Engine (3259,)
2019-07-23 11:41:09,123 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,124 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:09,125 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,130 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,131 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,132 INFO sqlalchemy.engine.base.Engine (3260,)
2019-07-23 11:41:09,135 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,136 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:09,138 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,142 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,143 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,144 INFO sqlalchemy.engine.base.Engine (3261,)
2019-07-23 11:41:09,148 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,149 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:41:09,150 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,154 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,155 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,156 INFO sqlalchemy.engine.base.Engine (3262,)
2019-07-23 11:41:09,159 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,160 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:09,162 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,165 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,166 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,167 INFO sqlalchemy.engine.base.Engine (3263,)
2019-07-23 11:41:09,171 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,172 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:09,174 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,178 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,179 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,180 INFO sqlalchemy.engine.base.Engine (3264,)
2019-07-23 11:41:09,184 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,185 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')

2019-07-23 11:41:09,186 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,190 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,191 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,192 INFO sqlalchemy.engine.base.Engine (3265,)
2019-07-23 11:41:09,195 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,196 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:41:09,198 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,202 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,203 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,204 INFO sqlalchemy.engine.base.Engine (3266,)
2019-07-23 11:41:09,207 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,207 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:09,209 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,213 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,214 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,215 INFO sqlalchemy.engine.base.Engine (3267,)
2019-07-23 11:41:09,219 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,219 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:09,222 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,226 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,227 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,228 INFO sqlalchemy.engine.base.Engine (3268,)
2019-07-23 11:41:09,232 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,233 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:09,234 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,238 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,239 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,240 INFO sqlalchemy.engine.base.Engine (3269,)
2019-07-23 11:41:09,242 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,243 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:09,245 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,249 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,250 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,252 INFO sqlalchemy.engine.base.Engine (3270,)
2019-07-23 11:41:09,254 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,255 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:09,257 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,261 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,262 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,263 INFO sqlalchemy.engine.base.Engine (3271,)
2019-07-23 11:41:09,266 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,267 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:09,270 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,273 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,274 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,275 INFO sqlalchemy.engine.base.Engine (3272,)
2019-07-23 11:41:09,278 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,279 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:09,281 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,285 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,287 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,288 INFO sqlalchemy.engine.base.Engine (3273,)
2019-07-23 11:41:09,290 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,291 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:09,294 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,298 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,299 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,300 INFO sqlalchemy.engine.base.Engine (3274,)
2019-07-23 11:41:09,303 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,304 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:41:09,306 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,310 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,311 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,312 INFO sqlalchemy.engine.base.Engine (3275,)
2019-07-23 11:41:09,315 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,316 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:41:09,319 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,323 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,324 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:09,324 INFO sqlalchemy.engine.base.Engine (3276,)
2019-07-23 11:41:09,328 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,329 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:09,332 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,336 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,337 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,338 INFO sqlalchemy.engine.base.Engine (3277,)
2019-07-23 11:41:09,341 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,342 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:09,344 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,348 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,349 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,350 INFO sqlalchemy.engine.base.Engine (3278,)
2019-07-23 11:41:09,354 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,355 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:41:09,357 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,361 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,362 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,362 INFO sqlalchemy.engine.base.Engine (3279,)
2019-07-23 11:41:09,366 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,367 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:09,370 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,373 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,375 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,375 INFO sqlalchemy.engine.base.Engine (3280,)
2019-07-23 11:41:09,379 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,380 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:41:09,382 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,386 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,387 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,387 INFO sqlalchemy.engine.base.Engine (3281,)
2019-07-23 11:41:09,390 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,391 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:09,393 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,397 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,398 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,399 INFO sqlalchemy.engine.base.Engine (3282,)
2019-07-23 11:41:09,402 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,402 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:41:09,405 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,409 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,410 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,411 INFO sqlalchemy.engine.base.Engine (3283,)
2019-07-23 11:41:09,413 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,414 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:09,416 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,420 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,421 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,422 INFO sqlalchemy.engine.base.Engine (3284,)
2019-07-23 11:41:09,425 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,425 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:09,427 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,431 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,432 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,433 INFO sqlalchemy.engine.base.Engine (3285,)
2019-07-23 11:41:09,436 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,436 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:09,439 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,443 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,444 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,445 INFO sqlalchemy.engine.base.Engine (3286,)
2019-07-23 11:41:09,448 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,449 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:09,452 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,455 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,457 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,458 INFO sqlalchemy.engine.base.Engine (3287,)
2019-07-23 11:41:09,461 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,462 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')

2019-07-23 11:41:09,463 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,467 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,468 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,469 INFO sqlalchemy.engine.base.Engine (3288,)
2019-07-23 11:41:09,472 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,473 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:41:09,475 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,478 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,480 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,480 INFO sqlalchemy.engine.base.Engine (3289,)
2019-07-23 11:41:09,484 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,485 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:09,487 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,491 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,492 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,493 INFO sqlalchemy.engine.base.Engine (3290,)
2019-07-23 11:41:09,496 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,497 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:09,499 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,503 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,504 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,505 INFO sqlalchemy.engine.base.Engine (3291,)
2019-07-23 11:41:09,508 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,509 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:09,510 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,514 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,515 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,516 INFO sqlalchemy.engine.base.Engine (3292,)
2019-07-23 11:41:09,519 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,520 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:09,522 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,526 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,527 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,527 INFO sqlalchemy.engine.base.Engine (3293,)
2019-07-23 11:41:09,532 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:09,533 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:09,535 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:09,539 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:09,540 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:09,541 INFO sqlalchemy.engine.base.Engine (3294,)
http://sz.ganji.com/zufang/pn10 status: 200
2019-07-23 11:41:10,684 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,685 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:41:10,687 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,691 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,692 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,693 INFO sqlalchemy.engine.base.Engine (3295,)
2019-07-23 11:41:10,696 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,696 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:41:10,698 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,701 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,702 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,703 INFO sqlalchemy.engine.base.Engine (3296,)
2019-07-23 11:41:10,706 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,707 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:41:10,708 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,713 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,714 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,715 INFO sqlalchemy.engine.base.Engine (3297,)
2019-07-23 11:41:10,718 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,718 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:41:10,720 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,724 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,725 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,726 INFO sqlalchemy.engine.base.Engine (3298,)
2019-07-23 11:41:10,729 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,730 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:41:10,732 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,736 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,737 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:10,738 INFO sqlalchemy.engine.base.Engine (3299,)
2019-07-23 11:41:10,741 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,742 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:41:10,744 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,748 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,749 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,750 INFO sqlalchemy.engine.base.Engine (3300,)
2019-07-23 11:41:10,752 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,753 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:41:10,755 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,759 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,760 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,760 INFO sqlalchemy.engine.base.Engine (3301,)
2019-07-23 11:41:10,764 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,764 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:10,766 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,769 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,770 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,771 INFO sqlalchemy.engine.base.Engine (3302,)
2019-07-23 11:41:10,773 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,774 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:41:10,776 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,780 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,781 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,782 INFO sqlalchemy.engine.base.Engine (3303,)
2019-07-23 11:41:10,785 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,786 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:10,788 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,792 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,793 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,793 INFO sqlalchemy.engine.base.Engine (3304,)
2019-07-23 11:41:10,797 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,797 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:41:10,799 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,803 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,804 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,805 INFO sqlalchemy.engine.base.Engine (3305,)
2019-07-23 11:41:10,808 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,808 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:41:10,810 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,814 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,815 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,816 INFO sqlalchemy.engine.base.Engine (3306,)
2019-07-23 11:41:10,819 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,820 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:41:10,822 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,825 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,826 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,827 INFO sqlalchemy.engine.base.Engine (3307,)
2019-07-23 11:41:10,829 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,830 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:41:10,832 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,837 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,838 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,839 INFO sqlalchemy.engine.base.Engine (3308,)
2019-07-23 11:41:10,842 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,843 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:41:10,845 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,849 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,850 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,851 INFO sqlalchemy.engine.base.Engine (3309,)
2019-07-23 11:41:10,854 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,854 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:41:10,857 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,860 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,861 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,862 INFO sqlalchemy.engine.base.Engine (3310,)
2019-07-23 11:41:10,865 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:10,866 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:41:10,868 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,872 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,873 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,874 INFO sqlalchemy.engine.base.Engine (3311,)
2019-07-23 11:41:10,877 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,877 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:41:10,880 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,884 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,885 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,886 INFO sqlalchemy.engine.base.Engine (3312,)
2019-07-23 11:41:10,889 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,890 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:41:10,892 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,896 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,897 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,898 INFO sqlalchemy.engine.base.Engine (3313,)
2019-07-23 11:41:10,901 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,902 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:41:10,903 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,907 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,908 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,909 INFO sqlalchemy.engine.base.Engine (3314,)
2019-07-23 11:41:10,912 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,913 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:41:10,914 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,918 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,919 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,920 INFO sqlalchemy.engine.base.Engine (3315,)
2019-07-23 11:41:10,923 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,923 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:41:10,926 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,929 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,930 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,932 INFO sqlalchemy.engine.base.Engine (3316,)
2019-07-23 11:41:10,935 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,937 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:41:10,939 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,943 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,944 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,945 INFO sqlalchemy.engine.base.Engine (3317,)
2019-07-23 11:41:10,947 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,948 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:41:10,950 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,954 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,955 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,956 INFO sqlalchemy.engine.base.Engine (3318,)
2019-07-23 11:41:10,958 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,959 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:41:10,961 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,964 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,965 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,966 INFO sqlalchemy.engine.base.Engine (3319,)
2019-07-23 11:41:10,969 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,970 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:41:10,972 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,975 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,976 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,977 INFO sqlalchemy.engine.base.Engine (3320,)
2019-07-23 11:41:10,980 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,981 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:10,983 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,987 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:10,988 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,989 INFO sqlalchemy.engine.base.Engine (3321,)
2019-07-23 11:41:10,992 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:10,993 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:41:10,995 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:10,998 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:10,999 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:10,999 INFO sqlalchemy.engine.base.Engine (3322,)
2019-07-23 11:41:11,002 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,003 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:11,006 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,009 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,010 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,011 INFO sqlalchemy.engine.base.Engine (3323,)
2019-07-23 11:41:11,014 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,015 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:11,017 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,020 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,021 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,022 INFO sqlalchemy.engine.base.Engine (3324,)
2019-07-23 11:41:11,025 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,026 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:11,028 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,031 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,032 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,033 INFO sqlalchemy.engine.base.Engine (3325,)
2019-07-23 11:41:11,036 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,037 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:11,038 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,042 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,043 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,043 INFO sqlalchemy.engine.base.Engine (3326,)
2019-07-23 11:41:11,047 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,048 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:11,050 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,053 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,054 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,055 INFO sqlalchemy.engine.base.Engine (3327,)
2019-07-23 11:41:11,057 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,058 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:11,060 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,063 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,065 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,065 INFO sqlalchemy.engine.base.Engine (3328,)
2019-07-23 11:41:11,068 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,069 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:11,072 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,075 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,076 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,077 INFO sqlalchemy.engine.base.Engine (3329,)
2019-07-23 11:41:11,080 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,080 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:11,083 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,086 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,087 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,088 INFO sqlalchemy.engine.base.Engine (3330,)
2019-07-23 11:41:11,091 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,092 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:11,094 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,098 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,099 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,100 INFO sqlalchemy.engine.base.Engine (3331,)
2019-07-23 11:41:11,102 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,103 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:41:11,105 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,108 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,109 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,110 INFO sqlalchemy.engine.base.Engine (3332,)
2019-07-23 11:41:11,113 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,114 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:11,116 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,120 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,121 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:11,122 INFO sqlalchemy.engine.base.Engine (3333,)
2019-07-23 11:41:11,124 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,125 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:11,127 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,132 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,133 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,134 INFO sqlalchemy.engine.base.Engine (3334,)
2019-07-23 11:41:11,136 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,137 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:41:11,140 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,143 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,144 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,145 INFO sqlalchemy.engine.base.Engine (3335,)
2019-07-23 11:41:11,148 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,149 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:41:11,151 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,155 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,156 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,156 INFO sqlalchemy.engine.base.Engine (3336,)
2019-07-23 11:41:11,159 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,160 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:11,162 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,166 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,167 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,168 INFO sqlalchemy.engine.base.Engine (3337,)
2019-07-23 11:41:11,171 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,171 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:11,173 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,176 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,177 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,178 INFO sqlalchemy.engine.base.Engine (3338,)
2019-07-23 11:41:11,182 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,182 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:11,184 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,188 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,189 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,189 INFO sqlalchemy.engine.base.Engine (3339,)
2019-07-23 11:41:11,193 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,194 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:11,195 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,199 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,200 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,201 INFO sqlalchemy.engine.base.Engine (3340,)
2019-07-23 11:41:11,204 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,205 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:11,207 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,210 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,212 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,213 INFO sqlalchemy.engine.base.Engine (3341,)
2019-07-23 11:41:11,216 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,217 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:11,219 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,223 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,224 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,225 INFO sqlalchemy.engine.base.Engine (3342,)
2019-07-23 11:41:11,228 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,229 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:11,232 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,235 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,237 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,237 INFO sqlalchemy.engine.base.Engine (3343,)
2019-07-23 11:41:11,241 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,242 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:11,244 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,248 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,249 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,250 INFO sqlalchemy.engine.base.Engine (3344,)
2019-07-23 11:41:11,252 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:11,253 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:11,256 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,259 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,260 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,261 INFO sqlalchemy.engine.base.Engine (3345,)
2019-07-23 11:41:11,264 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,265 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:11,267 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,270 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,271 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,272 INFO sqlalchemy.engine.base.Engine (3346,)
2019-07-23 11:41:11,275 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,276 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:11,278 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,282 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,283 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,284 INFO sqlalchemy.engine.base.Engine (3347,)
2019-07-23 11:41:11,287 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,288 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:11,290 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,293 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,294 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,295 INFO sqlalchemy.engine.base.Engine (3348,)
2019-07-23 11:41:11,298 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,299 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:11,301 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,305 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,306 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,307 INFO sqlalchemy.engine.base.Engine (3349,)
2019-07-23 11:41:11,310 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,311 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:11,312 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,316 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,317 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,318 INFO sqlalchemy.engine.base.Engine (3350,)
2019-07-23 11:41:11,321 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,322 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:11,324 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,328 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,329 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,330 INFO sqlalchemy.engine.base.Engine (3351,)
2019-07-23 11:41:11,331 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,332 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:11,334 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,338 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,340 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,340 INFO sqlalchemy.engine.base.Engine (3352,)
2019-07-23 11:41:11,343 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,344 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:11,346 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,350 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,351 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,351 INFO sqlalchemy.engine.base.Engine (3353,)
2019-07-23 11:41:11,356 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,356 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:11,359 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,362 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,364 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,364 INFO sqlalchemy.engine.base.Engine (3354,)
2019-07-23 11:41:11,368 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,368 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:41:11,370 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,374 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,375 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,376 INFO sqlalchemy.engine.base.Engine (3355,)
2019-07-23 11:41:11,379 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,380 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:11,382 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,386 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:11,387 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,388 INFO sqlalchemy.engine.base.Engine (3356,)
2019-07-23 11:41:11,392 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,392 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:11,394 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,397 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,399 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,400 INFO sqlalchemy.engine.base.Engine (3357,)
2019-07-23 11:41:11,403 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,403 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:41:11,405 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,409 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,410 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,410 INFO sqlalchemy.engine.base.Engine (3358,)
2019-07-23 11:41:11,413 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,414 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:11,416 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,420 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,421 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,422 INFO sqlalchemy.engine.base.Engine (3359,)
2019-07-23 11:41:11,425 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,425 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:11,428 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,431 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,432 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,433 INFO sqlalchemy.engine.base.Engine (3360,)
2019-07-23 11:41:11,436 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,437 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:11,439 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,443 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,444 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,445 INFO sqlalchemy.engine.base.Engine (3361,)
2019-07-23 11:41:11,448 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,449 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:11,451 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,454 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,455 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,456 INFO sqlalchemy.engine.base.Engine (3362,)
2019-07-23 11:41:11,459 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,460 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:11,461 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,465 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,467 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,467 INFO sqlalchemy.engine.base.Engine (3363,)
2019-07-23 11:41:11,470 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,471 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:11,473 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,477 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,478 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,479 INFO sqlalchemy.engine.base.Engine (3364,)
2019-07-23 11:41:11,483 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,483 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:11,485 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,489 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,490 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,490 INFO sqlalchemy.engine.base.Engine (3365,)
2019-07-23 11:41:11,494 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,495 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:11,497 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,500 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,501 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,502 INFO sqlalchemy.engine.base.Engine (3366,)
2019-07-23 11:41:11,506 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,506 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:11,509 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,512 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,513 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,514 INFO sqlalchemy.engine.base.Engine (3367,)
2019-07-23 11:41:11,517 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:11,518 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:11,519 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,523 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,525 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,525 INFO sqlalchemy.engine.base.Engine (3368,)
2019-07-23 11:41:11,528 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,530 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:11,532 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,536 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,537 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,538 INFO sqlalchemy.engine.base.Engine (3369,)
2019-07-23 11:41:11,541 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,542 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:11,545 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,549 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,550 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,551 INFO sqlalchemy.engine.base.Engine (3370,)
2019-07-23 11:41:11,554 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,554 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:11,556 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,559 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,561 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,561 INFO sqlalchemy.engine.base.Engine (3371,)
2019-07-23 11:41:11,564 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,565 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:11,567 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,571 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,572 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,572 INFO sqlalchemy.engine.base.Engine (3372,)
2019-07-23 11:41:11,575 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,576 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:11,578 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,581 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,583 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,584 INFO sqlalchemy.engine.base.Engine (3373,)
2019-07-23 11:41:11,586 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,587 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:11,589 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,593 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,594 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,594 INFO sqlalchemy.engine.base.Engine (3374,)
2019-07-23 11:41:11,598 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,599 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:11,601 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,604 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,606 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,606 INFO sqlalchemy.engine.base.Engine (3375,)
2019-07-23 11:41:11,609 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,610 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:11,612 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,616 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,617 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,618 INFO sqlalchemy.engine.base.Engine (3376,)
2019-07-23 11:41:11,621 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,622 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:11,624 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,628 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,629 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,629 INFO sqlalchemy.engine.base.Engine (3377,)
2019-07-23 11:41:11,633 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,634 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:41:11,636 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,639 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,641 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,641 INFO sqlalchemy.engine.base.Engine (3378,)
2019-07-23 11:41:11,644 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,645 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:11,647 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,651 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,652 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:11,653 INFO sqlalchemy.engine.base.Engine (3379,)
2019-07-23 11:41:11,656 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,658 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:11,660 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,663 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,664 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,665 INFO sqlalchemy.engine.base.Engine (3380,)
2019-07-23 11:41:11,668 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,669 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:11,671 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,675 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,676 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,676 INFO sqlalchemy.engine.base.Engine (3381,)
2019-07-23 11:41:11,680 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,681 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:41:11,683 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,687 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,688 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,688 INFO sqlalchemy.engine.base.Engine (3382,)
2019-07-23 11:41:11,691 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,692 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:11,694 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,698 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,699 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,700 INFO sqlalchemy.engine.base.Engine (3383,)
2019-07-23 11:41:11,703 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,704 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:11,707 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,710 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,711 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,712 INFO sqlalchemy.engine.base.Engine (3384,)
2019-07-23 11:41:11,715 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,716 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:11,718 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,721 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,722 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,722 INFO sqlalchemy.engine.base.Engine (3385,)
2019-07-23 11:41:11,726 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,727 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:11,729 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,734 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,735 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,735 INFO sqlalchemy.engine.base.Engine (3386,)
2019-07-23 11:41:11,739 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,740 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:11,741 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,745 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,746 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,747 INFO sqlalchemy.engine.base.Engine (3387,)
2019-07-23 11:41:11,750 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,750 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:11,753 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,756 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,758 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,758 INFO sqlalchemy.engine.base.Engine (3388,)
2019-07-23 11:41:11,762 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,762 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:11,764 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,768 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,769 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,770 INFO sqlalchemy.engine.base.Engine (3389,)
2019-07-23 11:41:11,773 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,773 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:11,775 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,779 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,780 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,781 INFO sqlalchemy.engine.base.Engine (3390,)
2019-07-23 11:41:11,784 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,785 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')

2019-07-23 11:41:11,787 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,791 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,792 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,793 INFO sqlalchemy.engine.base.Engine (3391,)
2019-07-23 11:41:11,797 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,798 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:41:11,799 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,803 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,804 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,805 INFO sqlalchemy.engine.base.Engine (3392,)
2019-07-23 11:41:11,809 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,810 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:11,812 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,815 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,817 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,818 INFO sqlalchemy.engine.base.Engine (3393,)
2019-07-23 11:41:11,821 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,822 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:11,824 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,828 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,829 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,830 INFO sqlalchemy.engine.base.Engine (3394,)
2019-07-23 11:41:11,833 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,834 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:41:11,836 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,840 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,841 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,842 INFO sqlalchemy.engine.base.Engine (3395,)
2019-07-23 11:41:11,846 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,847 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:11,849 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,852 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,853 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,854 INFO sqlalchemy.engine.base.Engine (3396,)
2019-07-23 11:41:11,857 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,858 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:41:11,861 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,864 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,866 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,867 INFO sqlalchemy.engine.base.Engine (3397,)
2019-07-23 11:41:11,870 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,871 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:11,873 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,877 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,878 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,879 INFO sqlalchemy.engine.base.Engine (3398,)
2019-07-23 11:41:11,883 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,884 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:11,886 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,890 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,891 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,891 INFO sqlalchemy.engine.base.Engine (3399,)
2019-07-23 11:41:11,894 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,895 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:11,898 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,901 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,902 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,902 INFO sqlalchemy.engine.base.Engine (3400,)
2019-07-23 11:41:11,906 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,907 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:41:11,908 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,912 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,913 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,914 INFO sqlalchemy.engine.base.Engine (3401,)
2019-07-23 11:41:11,916 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,917 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:11,920 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,924 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,925 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:11,925 INFO sqlalchemy.engine.base.Engine (3402,)
2019-07-23 11:41:11,929 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,930 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:11,931 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,936 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,937 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,938 INFO sqlalchemy.engine.base.Engine (3403,)
2019-07-23 11:41:11,942 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,943 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:41:11,945 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,950 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,951 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,952 INFO sqlalchemy.engine.base.Engine (3404,)
2019-07-23 11:41:11,955 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,956 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:41:11,957 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,962 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,963 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,963 INFO sqlalchemy.engine.base.Engine (3405,)
2019-07-23 11:41:11,966 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,967 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:11,969 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,974 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,976 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,977 INFO sqlalchemy.engine.base.Engine (3406,)
2019-07-23 11:41:11,981 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,982 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:11,984 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:11,988 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:11,990 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:11,990 INFO sqlalchemy.engine.base.Engine (3407,)
2019-07-23 11:41:11,994 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:11,995 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:11,997 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,000 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,002 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,002 INFO sqlalchemy.engine.base.Engine (3408,)
2019-07-23 11:41:12,006 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,007 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:12,010 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,014 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,015 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,016 INFO sqlalchemy.engine.base.Engine (3409,)
2019-07-23 11:41:12,019 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,020 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:12,022 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,026 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,027 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,028 INFO sqlalchemy.engine.base.Engine (3410,)
2019-07-23 11:41:12,031 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,032 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:12,034 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,038 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,039 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,040 INFO sqlalchemy.engine.base.Engine (3411,)
2019-07-23 11:41:12,043 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,044 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:12,047 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,051 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,052 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,053 INFO sqlalchemy.engine.base.Engine (3412,)
2019-07-23 11:41:12,056 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,057 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:12,059 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,063 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,064 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,065 INFO sqlalchemy.engine.base.Engine (3413,)
2019-07-23 11:41:12,068 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,069 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')

2019-07-23 11:41:12,073 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,076 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,077 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,078 INFO sqlalchemy.engine.base.Engine (3414,)
2019-07-23 11:41:12,082 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,083 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:41:12,085 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,088 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,089 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,090 INFO sqlalchemy.engine.base.Engine (3415,)
2019-07-23 11:41:12,094 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,095 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:12,096 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,100 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,102 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,103 INFO sqlalchemy.engine.base.Engine (3416,)
2019-07-23 11:41:12,106 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,106 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:12,108 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,112 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,113 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,114 INFO sqlalchemy.engine.base.Engine (3417,)
2019-07-23 11:41:12,117 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,118 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:41:12,120 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,124 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,126 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,126 INFO sqlalchemy.engine.base.Engine (3418,)
2019-07-23 11:41:12,129 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,130 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:12,132 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,136 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,137 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,138 INFO sqlalchemy.engine.base.Engine (3419,)
2019-07-23 11:41:12,141 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,141 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:41:12,143 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,148 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,149 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,149 INFO sqlalchemy.engine.base.Engine (3420,)
2019-07-23 11:41:12,154 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,154 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:12,156 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,160 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,161 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,162 INFO sqlalchemy.engine.base.Engine (3421,)
2019-07-23 11:41:12,165 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,166 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:41:12,168 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,172 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,173 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,173 INFO sqlalchemy.engine.base.Engine (3422,)
2019-07-23 11:41:12,176 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,177 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:12,180 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,183 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,184 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,186 INFO sqlalchemy.engine.base.Engine (3423,)
2019-07-23 11:41:12,188 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,189 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:12,192 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,195 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,197 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,197 INFO sqlalchemy.engine.base.Engine (3424,)
2019-07-23 11:41:12,200 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,201 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:12,203 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,207 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,209 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:12,209 INFO sqlalchemy.engine.base.Engine (3425,)
2019-07-23 11:41:12,212 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,213 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:12,215 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,218 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,219 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,220 INFO sqlalchemy.engine.base.Engine (3426,)
2019-07-23 11:41:12,223 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,224 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:41:12,227 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,230 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,231 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,232 INFO sqlalchemy.engine.base.Engine (3427,)
2019-07-23 11:41:12,235 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,236 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:41:12,238 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,242 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,243 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,244 INFO sqlalchemy.engine.base.Engine (3428,)
2019-07-23 11:41:12,247 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,248 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:12,251 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,254 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,255 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,256 INFO sqlalchemy.engine.base.Engine (3429,)
2019-07-23 11:41:12,259 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,260 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:12,261 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,265 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,267 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,267 INFO sqlalchemy.engine.base.Engine (3430,)
2019-07-23 11:41:12,270 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,271 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:12,273 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,277 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,278 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,279 INFO sqlalchemy.engine.base.Engine (3431,)
2019-07-23 11:41:12,282 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,284 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:12,285 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,289 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,290 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,291 INFO sqlalchemy.engine.base.Engine (3432,)
2019-07-23 11:41:12,294 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:12,295 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:12,296 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:12,300 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:12,301 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:12,302 INFO sqlalchemy.engine.base.Engine (3433,)
http://sz.ganji.com/zufang/pn11 status: 200
2019-07-23 11:41:13,279 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,280 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:41:13,282 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,286 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,287 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,288 INFO sqlalchemy.engine.base.Engine (3434,)
2019-07-23 11:41:13,290 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,291 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:41:13,294 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,297 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,298 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,299 INFO sqlalchemy.engine.base.Engine (3435,)
2019-07-23 11:41:13,302 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,302 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:41:13,305 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,308 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,309 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,310 INFO sqlalchemy.engine.base.Engine (3436,)
2019-07-23 11:41:13,313 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:13,314 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:41:13,316 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,320 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,321 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,321 INFO sqlalchemy.engine.base.Engine (3437,)
2019-07-23 11:41:13,324 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,325 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:41:13,326 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,330 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,331 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,332 INFO sqlalchemy.engine.base.Engine (3438,)
2019-07-23 11:41:13,334 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,335 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:41:13,338 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,341 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,342 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,343 INFO sqlalchemy.engine.base.Engine (3439,)
2019-07-23 11:41:13,347 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,347 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:41:13,350 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,353 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,355 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,355 INFO sqlalchemy.engine.base.Engine (3440,)
2019-07-23 11:41:13,359 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,360 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:13,362 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,366 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,367 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,367 INFO sqlalchemy.engine.base.Engine (3441,)
2019-07-23 11:41:13,371 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,372 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:41:13,373 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,377 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,378 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,379 INFO sqlalchemy.engine.base.Engine (3442,)
2019-07-23 11:41:13,382 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,382 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:13,385 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,389 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,390 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,391 INFO sqlalchemy.engine.base.Engine (3443,)
2019-07-23 11:41:13,394 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,395 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:41:13,397 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,400 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,401 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,402 INFO sqlalchemy.engine.base.Engine (3444,)
2019-07-23 11:41:13,405 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,406 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:41:13,408 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,411 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,412 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,413 INFO sqlalchemy.engine.base.Engine (3445,)
2019-07-23 11:41:13,416 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,417 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:41:13,419 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,422 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,423 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,424 INFO sqlalchemy.engine.base.Engine (3446,)
2019-07-23 11:41:13,427 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,428 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:41:13,430 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,434 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,435 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,436 INFO sqlalchemy.engine.base.Engine (3447,)
2019-07-23 11:41:13,439 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,440 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:41:13,442 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:13,446 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,447 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,448 INFO sqlalchemy.engine.base.Engine (3448,)
2019-07-23 11:41:13,450 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,452 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:41:13,454 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,458 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,459 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,460 INFO sqlalchemy.engine.base.Engine (3449,)
2019-07-23 11:41:13,463 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,464 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:41:13,466 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,469 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,470 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,471 INFO sqlalchemy.engine.base.Engine (3450,)
2019-07-23 11:41:13,474 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,475 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:41:13,477 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,480 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,482 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,482 INFO sqlalchemy.engine.base.Engine (3451,)
2019-07-23 11:41:13,486 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,486 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:41:13,488 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,492 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,493 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,493 INFO sqlalchemy.engine.base.Engine (3452,)
2019-07-23 11:41:13,496 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,497 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:41:13,499 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,503 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,504 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,505 INFO sqlalchemy.engine.base.Engine (3453,)
2019-07-23 11:41:13,508 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,509 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:41:13,510 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,514 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,515 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,516 INFO sqlalchemy.engine.base.Engine (3454,)
2019-07-23 11:41:13,519 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,520 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:41:13,522 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,525 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,526 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,527 INFO sqlalchemy.engine.base.Engine (3455,)
2019-07-23 11:41:13,530 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,532 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:41:13,533 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,537 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,538 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,539 INFO sqlalchemy.engine.base.Engine (3456,)
2019-07-23 11:41:13,542 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,543 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:41:13,546 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,549 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,550 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,551 INFO sqlalchemy.engine.base.Engine (3457,)
2019-07-23 11:41:13,554 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,555 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:41:13,558 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,561 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,562 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,563 INFO sqlalchemy.engine.base.Engine (3458,)
2019-07-23 11:41:13,565 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,566 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:41:13,568 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,572 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,573 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:13,574 INFO sqlalchemy.engine.base.Engine (3459,)
2019-07-23 11:41:13,578 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,579 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:13,580 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,584 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,585 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,586 INFO sqlalchemy.engine.base.Engine (3460,)
2019-07-23 11:41:13,589 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,590 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:41:13,591 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,595 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,597 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,597 INFO sqlalchemy.engine.base.Engine (3461,)
2019-07-23 11:41:13,600 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,601 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:13,602 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,606 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,607 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,608 INFO sqlalchemy.engine.base.Engine (3462,)
2019-07-23 11:41:13,611 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,612 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:13,614 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,618 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,619 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,619 INFO sqlalchemy.engine.base.Engine (3463,)
2019-07-23 11:41:13,622 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,623 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:13,625 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,629 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,630 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,631 INFO sqlalchemy.engine.base.Engine (3464,)
2019-07-23 11:41:13,634 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,635 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:13,637 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,641 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,642 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,642 INFO sqlalchemy.engine.base.Engine (3465,)
2019-07-23 11:41:13,646 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,647 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:13,650 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,653 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,654 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,655 INFO sqlalchemy.engine.base.Engine (3466,)
2019-07-23 11:41:13,658 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,659 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:13,661 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,665 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,666 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,667 INFO sqlalchemy.engine.base.Engine (3467,)
2019-07-23 11:41:13,671 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,671 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:13,674 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,679 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,680 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,680 INFO sqlalchemy.engine.base.Engine (3468,)
2019-07-23 11:41:13,684 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,685 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:13,687 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,690 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,691 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,692 INFO sqlalchemy.engine.base.Engine (3469,)
2019-07-23 11:41:13,695 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,696 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:13,698 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,702 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,703 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,704 INFO sqlalchemy.engine.base.Engine (3470,)
2019-07-23 11:41:13,707 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,708 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')

2019-07-23 11:41:13,711 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,714 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,715 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,716 INFO sqlalchemy.engine.base.Engine (3471,)
2019-07-23 11:41:13,720 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,720 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:13,722 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,726 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,728 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,728 INFO sqlalchemy.engine.base.Engine (3472,)
2019-07-23 11:41:13,732 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,732 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:13,734 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,738 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,739 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,740 INFO sqlalchemy.engine.base.Engine (3473,)
2019-07-23 11:41:13,743 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,744 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:41:13,747 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,750 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,751 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,752 INFO sqlalchemy.engine.base.Engine (3474,)
2019-07-23 11:41:13,756 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,756 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:41:13,758 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,761 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,762 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,763 INFO sqlalchemy.engine.base.Engine (3475,)
2019-07-23 11:41:13,766 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,766 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:13,768 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,772 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,773 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,774 INFO sqlalchemy.engine.base.Engine (3476,)
2019-07-23 11:41:13,777 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,777 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:13,779 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,783 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,784 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,785 INFO sqlalchemy.engine.base.Engine (3477,)
2019-07-23 11:41:13,788 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,789 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:13,791 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,794 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,795 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,796 INFO sqlalchemy.engine.base.Engine (3478,)
2019-07-23 11:41:13,799 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,800 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:13,802 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,805 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,806 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,807 INFO sqlalchemy.engine.base.Engine (3479,)
2019-07-23 11:41:13,811 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,811 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:13,813 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,817 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,818 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,819 INFO sqlalchemy.engine.base.Engine (3480,)
2019-07-23 11:41:13,823 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,823 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:13,826 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,829 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,830 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,832 INFO sqlalchemy.engine.base.Engine (3481,)
2019-07-23 11:41:13,834 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,835 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:13,837 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,841 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,842 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:13,843 INFO sqlalchemy.engine.base.Engine (3482,)
2019-07-23 11:41:13,847 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,848 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:13,850 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,853 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,854 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,854 INFO sqlalchemy.engine.base.Engine (3483,)
2019-07-23 11:41:13,858 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,859 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:13,861 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,865 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,866 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,867 INFO sqlalchemy.engine.base.Engine (3484,)
2019-07-23 11:41:13,870 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,871 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:13,874 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,878 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,879 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,880 INFO sqlalchemy.engine.base.Engine (3485,)
2019-07-23 11:41:13,884 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,885 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:13,888 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,893 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,894 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,895 INFO sqlalchemy.engine.base.Engine (3486,)
2019-07-23 11:41:13,898 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,899 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:13,902 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,906 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,907 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,908 INFO sqlalchemy.engine.base.Engine (3487,)
2019-07-23 11:41:13,912 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,913 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:13,916 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,920 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,922 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,923 INFO sqlalchemy.engine.base.Engine (3488,)
2019-07-23 11:41:13,926 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,927 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:13,929 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,935 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,936 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,938 INFO sqlalchemy.engine.base.Engine (3489,)
2019-07-23 11:41:13,942 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,943 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:13,945 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,950 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,951 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,952 INFO sqlalchemy.engine.base.Engine (3490,)
2019-07-23 11:41:13,956 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,957 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:13,959 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,963 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,964 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,965 INFO sqlalchemy.engine.base.Engine (3491,)
2019-07-23 11:41:13,968 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,969 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:13,972 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,977 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,978 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,979 INFO sqlalchemy.engine.base.Engine (3492,)
2019-07-23 11:41:13,983 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,984 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:13,987 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:13,991 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:13,993 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:13,993 INFO sqlalchemy.engine.base.Engine (3493,)
2019-07-23 11:41:13,997 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:13,998 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')

2019-07-23 11:41:14,001 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,006 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,008 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,009 INFO sqlalchemy.engine.base.Engine (3494,)
2019-07-23 11:41:14,014 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,015 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:14,016 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,021 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,022 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,023 INFO sqlalchemy.engine.base.Engine (3495,)
2019-07-23 11:41:14,025 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,026 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:14,028 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,034 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,035 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,036 INFO sqlalchemy.engine.base.Engine (3496,)
2019-07-23 11:41:14,039 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,040 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:41:14,042 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,047 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,049 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,050 INFO sqlalchemy.engine.base.Engine (3497,)
2019-07-23 11:41:14,053 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,054 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:14,057 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,060 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,061 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,061 INFO sqlalchemy.engine.base.Engine (3498,)
2019-07-23 11:41:14,064 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,065 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:14,067 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,071 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,072 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,073 INFO sqlalchemy.engine.base.Engine (3499,)
2019-07-23 11:41:14,076 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,076 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:14,078 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,083 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,085 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,086 INFO sqlalchemy.engine.base.Engine (3500,)
2019-07-23 11:41:14,089 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,090 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:14,092 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,097 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,098 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,100 INFO sqlalchemy.engine.base.Engine (3501,)
2019-07-23 11:41:14,103 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,104 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:14,105 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,109 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,110 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,111 INFO sqlalchemy.engine.base.Engine (3502,)
2019-07-23 11:41:14,114 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,115 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:14,117 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,121 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,122 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,122 INFO sqlalchemy.engine.base.Engine (3503,)
2019-07-23 11:41:14,126 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,127 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:14,129 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,133 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,134 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,135 INFO sqlalchemy.engine.base.Engine (3504,)
2019-07-23 11:41:14,138 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,139 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:14,142 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,145 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,146 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:14,147 INFO sqlalchemy.engine.base.Engine (3505,)
2019-07-23 11:41:14,151 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,152 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:14,153 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,157 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,158 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,159 INFO sqlalchemy.engine.base.Engine (3506,)
2019-07-23 11:41:14,162 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,163 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:14,165 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,168 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,169 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,170 INFO sqlalchemy.engine.base.Engine (3507,)
2019-07-23 11:41:14,174 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,174 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:14,177 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,180 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,181 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,182 INFO sqlalchemy.engine.base.Engine (3508,)
2019-07-23 11:41:14,186 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,187 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:14,189 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,192 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,193 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,194 INFO sqlalchemy.engine.base.Engine (3509,)
2019-07-23 11:41:14,197 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,198 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:14,200 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,204 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,205 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,206 INFO sqlalchemy.engine.base.Engine (3510,)
2019-07-23 11:41:14,210 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,210 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:14,212 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,216 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,218 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,219 INFO sqlalchemy.engine.base.Engine (3511,)
2019-07-23 11:41:14,222 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,223 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:14,225 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,228 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,229 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,230 INFO sqlalchemy.engine.base.Engine (3512,)
2019-07-23 11:41:14,234 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,234 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:14,237 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,241 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,242 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,243 INFO sqlalchemy.engine.base.Engine (3513,)
2019-07-23 11:41:14,247 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,248 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:14,250 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,254 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,256 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,256 INFO sqlalchemy.engine.base.Engine (3514,)
2019-07-23 11:41:14,261 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,261 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:14,264 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,268 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,269 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,270 INFO sqlalchemy.engine.base.Engine (3515,)
2019-07-23 11:41:14,273 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,275 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:14,277 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,281 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,283 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,283 INFO sqlalchemy.engine.base.Engine (3516,)
2019-07-23 11:41:14,287 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,288 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')

2019-07-23 11:41:14,290 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,293 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,295 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,295 INFO sqlalchemy.engine.base.Engine (3517,)
2019-07-23 11:41:14,299 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,300 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:14,302 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,306 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,307 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,308 INFO sqlalchemy.engine.base.Engine (3518,)
2019-07-23 11:41:14,312 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,313 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:14,315 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,319 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,320 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,321 INFO sqlalchemy.engine.base.Engine (3519,)
2019-07-23 11:41:14,324 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,325 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:14,326 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,330 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,331 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,332 INFO sqlalchemy.engine.base.Engine (3520,)
2019-07-23 11:41:14,336 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,337 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:41:14,339 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,342 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,344 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,345 INFO sqlalchemy.engine.base.Engine (3521,)
2019-07-23 11:41:14,348 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,349 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:14,352 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,355 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,356 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,357 INFO sqlalchemy.engine.base.Engine (3522,)
2019-07-23 11:41:14,360 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,361 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:14,364 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,368 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,369 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,370 INFO sqlalchemy.engine.base.Engine (3523,)
2019-07-23 11:41:14,373 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,374 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:14,376 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,380 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,381 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,382 INFO sqlalchemy.engine.base.Engine (3524,)
2019-07-23 11:41:14,385 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,386 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:14,388 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,391 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,393 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,393 INFO sqlalchemy.engine.base.Engine (3525,)
2019-07-23 11:41:14,396 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,397 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:14,399 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,403 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,405 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,405 INFO sqlalchemy.engine.base.Engine (3526,)
2019-07-23 11:41:14,409 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,410 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:14,412 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,415 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,416 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,417 INFO sqlalchemy.engine.base.Engine (3527,)
2019-07-23 11:41:14,421 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,421 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:14,423 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,427 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,429 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:14,430 INFO sqlalchemy.engine.base.Engine (3528,)
2019-07-23 11:41:14,433 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,434 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:14,436 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,439 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,441 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,442 INFO sqlalchemy.engine.base.Engine (3529,)
2019-07-23 11:41:14,445 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,445 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:41:14,448 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,452 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,453 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,454 INFO sqlalchemy.engine.base.Engine (3530,)
2019-07-23 11:41:14,457 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,458 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:41:14,460 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,463 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,465 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,465 INFO sqlalchemy.engine.base.Engine (3531,)
2019-07-23 11:41:14,468 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,469 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:14,472 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,475 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,477 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,478 INFO sqlalchemy.engine.base.Engine (3532,)
2019-07-23 11:41:14,481 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,482 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:14,484 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,487 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,488 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,489 INFO sqlalchemy.engine.base.Engine (3533,)
2019-07-23 11:41:14,492 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,493 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:41:14,495 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,499 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,501 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,502 INFO sqlalchemy.engine.base.Engine (3534,)
2019-07-23 11:41:14,505 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,505 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:14,507 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,511 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,512 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,513 INFO sqlalchemy.engine.base.Engine (3535,)
2019-07-23 11:41:14,516 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,518 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:41:14,519 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,523 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,524 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,525 INFO sqlalchemy.engine.base.Engine (3536,)
2019-07-23 11:41:14,528 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,529 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:14,531 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,535 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,536 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,537 INFO sqlalchemy.engine.base.Engine (3537,)
2019-07-23 11:41:14,540 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,541 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:14,544 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,548 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,549 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,550 INFO sqlalchemy.engine.base.Engine (3538,)
2019-07-23 11:41:14,552 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,553 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:14,555 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,559 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,560 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,561 INFO sqlalchemy.engine.base.Engine (3539,)
2019-07-23 11:41:14,564 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,566 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')

2019-07-23 11:41:14,567 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,570 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,572 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,572 INFO sqlalchemy.engine.base.Engine (3540,)
2019-07-23 11:41:14,575 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,576 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:14,579 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,583 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,584 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,585 INFO sqlalchemy.engine.base.Engine (3541,)
2019-07-23 11:41:14,588 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,588 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:14,591 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,594 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,595 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,596 INFO sqlalchemy.engine.base.Engine (3542,)
2019-07-23 11:41:14,600 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,601 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:41:14,603 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,607 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,608 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,609 INFO sqlalchemy.engine.base.Engine (3543,)
2019-07-23 11:41:14,612 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,613 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:41:14,615 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,619 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,620 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,621 INFO sqlalchemy.engine.base.Engine (3544,)
2019-07-23 11:41:14,624 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,625 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:14,627 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,631 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,632 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,633 INFO sqlalchemy.engine.base.Engine (3545,)
2019-07-23 11:41:14,636 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,636 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:14,639 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,643 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,644 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,646 INFO sqlalchemy.engine.base.Engine (3546,)
2019-07-23 11:41:14,650 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,651 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:14,654 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,657 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,659 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,660 INFO sqlalchemy.engine.base.Engine (3547,)
2019-07-23 11:41:14,663 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,664 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:14,667 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,670 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,671 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,672 INFO sqlalchemy.engine.base.Engine (3548,)
2019-07-23 11:41:14,676 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,677 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:14,679 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,683 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,684 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,685 INFO sqlalchemy.engine.base.Engine (3549,)
2019-07-23 11:41:14,689 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,690 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:14,692 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,696 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,697 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,698 INFO sqlalchemy.engine.base.Engine (3550,)
2019-07-23 11:41:14,701 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,702 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:14,705 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,709 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,710 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:14,711 INFO sqlalchemy.engine.base.Engine (3551,)
2019-07-23 11:41:14,714 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,715 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:14,717 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,721 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,722 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,723 INFO sqlalchemy.engine.base.Engine (3552,)
2019-07-23 11:41:14,726 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,728 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:41:14,729 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,733 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,735 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,735 INFO sqlalchemy.engine.base.Engine (3553,)
2019-07-23 11:41:14,739 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,740 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:41:14,743 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,747 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,748 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,748 INFO sqlalchemy.engine.base.Engine (3554,)
2019-07-23 11:41:14,752 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,753 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:14,755 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,759 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,760 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,761 INFO sqlalchemy.engine.base.Engine (3555,)
2019-07-23 11:41:14,765 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,766 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:14,769 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,773 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,774 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,775 INFO sqlalchemy.engine.base.Engine (3556,)
2019-07-23 11:41:14,778 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,779 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:41:14,782 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,785 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,787 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,787 INFO sqlalchemy.engine.base.Engine (3557,)
2019-07-23 11:41:14,790 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,791 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:14,794 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,798 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,799 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,800 INFO sqlalchemy.engine.base.Engine (3558,)
2019-07-23 11:41:14,804 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,805 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:41:14,806 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,811 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,812 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,813 INFO sqlalchemy.engine.base.Engine (3559,)
2019-07-23 11:41:14,816 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,817 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:14,819 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,823 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,824 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,825 INFO sqlalchemy.engine.base.Engine (3560,)
2019-07-23 11:41:14,827 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,829 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:41:14,833 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,836 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,838 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,839 INFO sqlalchemy.engine.base.Engine (3561,)
2019-07-23 11:41:14,842 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,843 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:14,846 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,849 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,850 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,851 INFO sqlalchemy.engine.base.Engine (3562,)
2019-07-23 11:41:14,855 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,856 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:14,858 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:14,862 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,863 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,864 INFO sqlalchemy.engine.base.Engine (3563,)
2019-07-23 11:41:14,868 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,869 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:14,871 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,875 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,876 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,877 INFO sqlalchemy.engine.base.Engine (3564,)
2019-07-23 11:41:14,880 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,881 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:14,884 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,887 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,888 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,889 INFO sqlalchemy.engine.base.Engine (3565,)
2019-07-23 11:41:14,893 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,895 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:41:14,896 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,900 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,901 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,902 INFO sqlalchemy.engine.base.Engine (3566,)
2019-07-23 11:41:14,905 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,906 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:41:14,909 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,912 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,914 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,914 INFO sqlalchemy.engine.base.Engine (3567,)
2019-07-23 11:41:14,917 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,918 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:14,921 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,924 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,926 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,926 INFO sqlalchemy.engine.base.Engine (3568,)
2019-07-23 11:41:14,930 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,931 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:14,933 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,937 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,938 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,939 INFO sqlalchemy.engine.base.Engine (3569,)
2019-07-23 11:41:14,943 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,944 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:14,946 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,950 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,951 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,952 INFO sqlalchemy.engine.base.Engine (3570,)
2019-07-23 11:41:14,955 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,956 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:14,959 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,963 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,964 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,965 INFO sqlalchemy.engine.base.Engine (3571,)
2019-07-23 11:41:14,968 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:14,969 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:14,971 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:14,975 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:14,976 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:14,977 INFO sqlalchemy.engine.base.Engine (3572,)
http://sz.ganji.com/zufang/pn12 status: 200
2019-07-23 11:41:15,951 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:15,952 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:41:15,954 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:15,957 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:15,959 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:15,959 INFO sqlalchemy.engine.base.Engine (3573,)
2019-07-23 11:41:15,962 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:15,963 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:41:15,965 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:15,969 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:15,971 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:15,971 INFO sqlalchemy.engine.base.Engine (3574,)
2019-07-23 11:41:15,974 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:15,975 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:41:15,977 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:15,982 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:15,983 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:15,983 INFO sqlalchemy.engine.base.Engine (3575,)
2019-07-23 11:41:15,987 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:15,988 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:41:15,990 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:15,993 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:15,995 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:15,996 INFO sqlalchemy.engine.base.Engine (3576,)
2019-07-23 11:41:15,998 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:15,999 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:41:16,002 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,005 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,007 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,008 INFO sqlalchemy.engine.base.Engine (3577,)
2019-07-23 11:41:16,012 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,013 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:41:16,016 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,020 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,021 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,022 INFO sqlalchemy.engine.base.Engine (3578,)
2019-07-23 11:41:16,025 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,026 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:41:16,028 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,032 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,034 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,034 INFO sqlalchemy.engine.base.Engine (3579,)
2019-07-23 11:41:16,038 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,039 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:16,040 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,044 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,046 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,047 INFO sqlalchemy.engine.base.Engine (3580,)
2019-07-23 11:41:16,050 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,052 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:41:16,054 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,059 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,060 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,061 INFO sqlalchemy.engine.base.Engine (3581,)
2019-07-23 11:41:16,064 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,065 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:16,067 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,072 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,073 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,074 INFO sqlalchemy.engine.base.Engine (3582,)
2019-07-23 11:41:16,078 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,079 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:41:16,081 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,085 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,086 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,087 INFO sqlalchemy.engine.base.Engine (3583,)
2019-07-23 11:41:16,091 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,091 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:41:16,094 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,098 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,099 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,100 INFO sqlalchemy.engine.base.Engine (3584,)
2019-07-23 11:41:16,103 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,104 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:41:16,106 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,110 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,111 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,112 INFO sqlalchemy.engine.base.Engine (3585,)
2019-07-23 11:41:16,115 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:16,116 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:41:16,118 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,123 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,124 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,124 INFO sqlalchemy.engine.base.Engine (3586,)
2019-07-23 11:41:16,128 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,129 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:41:16,132 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,136 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,137 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,138 INFO sqlalchemy.engine.base.Engine (3587,)
2019-07-23 11:41:16,142 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,142 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:41:16,144 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,148 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,150 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,150 INFO sqlalchemy.engine.base.Engine (3588,)
2019-07-23 11:41:16,154 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,155 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:41:16,157 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,161 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,163 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,163 INFO sqlalchemy.engine.base.Engine (3589,)
2019-07-23 11:41:16,166 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,167 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:41:16,169 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,173 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,174 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,175 INFO sqlalchemy.engine.base.Engine (3590,)
2019-07-23 11:41:16,178 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,179 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:41:16,182 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,185 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,187 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,187 INFO sqlalchemy.engine.base.Engine (3591,)
2019-07-23 11:41:16,191 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,192 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:41:16,194 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,198 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,199 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,200 INFO sqlalchemy.engine.base.Engine (3592,)
2019-07-23 11:41:16,203 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,204 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:41:16,205 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,209 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,210 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,211 INFO sqlalchemy.engine.base.Engine (3593,)
2019-07-23 11:41:16,215 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,215 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:41:16,217 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,221 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,222 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,223 INFO sqlalchemy.engine.base.Engine (3594,)
2019-07-23 11:41:16,226 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,227 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:41:16,229 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,232 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,234 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,234 INFO sqlalchemy.engine.base.Engine (3595,)
2019-07-23 11:41:16,238 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,239 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:41:16,241 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,245 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,246 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,247 INFO sqlalchemy.engine.base.Engine (3596,)
2019-07-23 11:41:16,251 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,251 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:41:16,253 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:16,257 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,258 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,259 INFO sqlalchemy.engine.base.Engine (3597,)
2019-07-23 11:41:16,262 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,263 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:41:16,265 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,269 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,270 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,271 INFO sqlalchemy.engine.base.Engine (3598,)
2019-07-23 11:41:16,274 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,275 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:16,277 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,280 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,282 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,282 INFO sqlalchemy.engine.base.Engine (3599,)
2019-07-23 11:41:16,286 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,287 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:41:16,289 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,292 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,294 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,295 INFO sqlalchemy.engine.base.Engine (3600,)
2019-07-23 11:41:16,298 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,299 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:16,300 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,305 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,306 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,307 INFO sqlalchemy.engine.base.Engine (3601,)
2019-07-23 11:41:16,310 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,311 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:16,313 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,317 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,318 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,318 INFO sqlalchemy.engine.base.Engine (3602,)
2019-07-23 11:41:16,321 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,322 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:16,324 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,327 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,329 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,330 INFO sqlalchemy.engine.base.Engine (3603,)
2019-07-23 11:41:16,333 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,333 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:16,336 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,339 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,340 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,341 INFO sqlalchemy.engine.base.Engine (3604,)
2019-07-23 11:41:16,344 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,345 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:16,348 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,351 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,352 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,353 INFO sqlalchemy.engine.base.Engine (3605,)
2019-07-23 11:41:16,357 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,357 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:16,359 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,363 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,365 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,366 INFO sqlalchemy.engine.base.Engine (3606,)
2019-07-23 11:41:16,369 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,370 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:16,372 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,375 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,376 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,377 INFO sqlalchemy.engine.base.Engine (3607,)
2019-07-23 11:41:16,381 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,382 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:16,383 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,388 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,389 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:16,389 INFO sqlalchemy.engine.base.Engine (3608,)
2019-07-23 11:41:16,393 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,394 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:16,396 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,399 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,400 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,401 INFO sqlalchemy.engine.base.Engine (3609,)
2019-07-23 11:41:16,404 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,405 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:41:16,407 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,411 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,413 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,414 INFO sqlalchemy.engine.base.Engine (3610,)
2019-07-23 11:41:16,417 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,418 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:16,420 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,423 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,425 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,425 INFO sqlalchemy.engine.base.Engine (3611,)
2019-07-23 11:41:16,428 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,429 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:16,431 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,435 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,436 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,437 INFO sqlalchemy.engine.base.Engine (3612,)
2019-07-23 11:41:16,441 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,442 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:41:16,445 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,449 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,450 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,451 INFO sqlalchemy.engine.base.Engine (3613,)
2019-07-23 11:41:16,454 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,455 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:41:16,457 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,460 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,461 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,462 INFO sqlalchemy.engine.base.Engine (3614,)
2019-07-23 11:41:16,465 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,466 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:16,468 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,472 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,473 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,474 INFO sqlalchemy.engine.base.Engine (3615,)
2019-07-23 11:41:16,477 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,478 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:16,481 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,484 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,485 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,486 INFO sqlalchemy.engine.base.Engine (3616,)
2019-07-23 11:41:16,490 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,491 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:16,493 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,496 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,497 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,498 INFO sqlalchemy.engine.base.Engine (3617,)
2019-07-23 11:41:16,501 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,502 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:16,504 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,508 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,509 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,510 INFO sqlalchemy.engine.base.Engine (3618,)
2019-07-23 11:41:16,513 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,514 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:16,516 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,520 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,521 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,521 INFO sqlalchemy.engine.base.Engine (3619,)
2019-07-23 11:41:16,525 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:16,526 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:16,529 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,532 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,533 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,534 INFO sqlalchemy.engine.base.Engine (3620,)
2019-07-23 11:41:16,537 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,538 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:16,540 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,544 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,546 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,547 INFO sqlalchemy.engine.base.Engine (3621,)
2019-07-23 11:41:16,550 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,551 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:16,553 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,557 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,558 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,558 INFO sqlalchemy.engine.base.Engine (3622,)
2019-07-23 11:41:16,562 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,563 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:16,566 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,569 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,570 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,571 INFO sqlalchemy.engine.base.Engine (3623,)
2019-07-23 11:41:16,575 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,575 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:16,578 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,582 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,583 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,583 INFO sqlalchemy.engine.base.Engine (3624,)
2019-07-23 11:41:16,587 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,587 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:16,591 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,594 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,595 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,596 INFO sqlalchemy.engine.base.Engine (3625,)
2019-07-23 11:41:16,599 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,599 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:16,601 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,605 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,606 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,607 INFO sqlalchemy.engine.base.Engine (3626,)
2019-07-23 11:41:16,610 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,611 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:16,613 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,617 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,618 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,619 INFO sqlalchemy.engine.base.Engine (3627,)
2019-07-23 11:41:16,622 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,623 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:16,625 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,629 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,630 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,631 INFO sqlalchemy.engine.base.Engine (3628,)
2019-07-23 11:41:16,634 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,635 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:16,637 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,641 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,642 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,642 INFO sqlalchemy.engine.base.Engine (3629,)
2019-07-23 11:41:16,647 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,648 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:16,650 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,654 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,655 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,656 INFO sqlalchemy.engine.base.Engine (3630,)
2019-07-23 11:41:16,659 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,660 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:16,662 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,665 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:16,667 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,668 INFO sqlalchemy.engine.base.Engine (3631,)
2019-07-23 11:41:16,671 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,672 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:16,674 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,677 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,679 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,679 INFO sqlalchemy.engine.base.Engine (3632,)
2019-07-23 11:41:16,683 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,683 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:41:16,686 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,689 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,690 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,691 INFO sqlalchemy.engine.base.Engine (3633,)
2019-07-23 11:41:16,694 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,695 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:16,697 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,701 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,702 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,703 INFO sqlalchemy.engine.base.Engine (3634,)
2019-07-23 11:41:16,706 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,707 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:16,710 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,713 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,714 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,715 INFO sqlalchemy.engine.base.Engine (3635,)
2019-07-23 11:41:16,719 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,720 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:41:16,722 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,725 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,727 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,727 INFO sqlalchemy.engine.base.Engine (3636,)
2019-07-23 11:41:16,731 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,731 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:16,734 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,737 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,738 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,739 INFO sqlalchemy.engine.base.Engine (3637,)
2019-07-23 11:41:16,742 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,743 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:16,746 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,750 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,751 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,752 INFO sqlalchemy.engine.base.Engine (3638,)
2019-07-23 11:41:16,755 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,756 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:16,758 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,761 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,762 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,763 INFO sqlalchemy.engine.base.Engine (3639,)
2019-07-23 11:41:16,765 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,766 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:16,769 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,772 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,773 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,774 INFO sqlalchemy.engine.base.Engine (3640,)
2019-07-23 11:41:16,777 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,778 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:16,780 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,784 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,786 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,786 INFO sqlalchemy.engine.base.Engine (3641,)
2019-07-23 11:41:16,789 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,790 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:16,793 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,796 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,798 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,798 INFO sqlalchemy.engine.base.Engine (3642,)

2019-07-23 11:41:16,802 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,803 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:16,805 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,809 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,810 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,811 INFO sqlalchemy.engine.base.Engine (3643,)
2019-07-23 11:41:16,815 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,816 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:16,818 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,821 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,823 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,823 INFO sqlalchemy.engine.base.Engine (3644,)
2019-07-23 11:41:16,826 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,827 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:16,830 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,834 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,835 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,836 INFO sqlalchemy.engine.base.Engine (3645,)
2019-07-23 11:41:16,840 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,840 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:16,843 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,847 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,848 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,848 INFO sqlalchemy.engine.base.Engine (3646,)
2019-07-23 11:41:16,852 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,853 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:16,855 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,859 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,860 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,861 INFO sqlalchemy.engine.base.Engine (3647,)
2019-07-23 11:41:16,864 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,865 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:16,867 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,871 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,872 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,872 INFO sqlalchemy.engine.base.Engine (3648,)
2019-07-23 11:41:16,876 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,877 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:16,879 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,883 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,884 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,885 INFO sqlalchemy.engine.base.Engine (3649,)
2019-07-23 11:41:16,889 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,889 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:16,892 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,895 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,896 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,897 INFO sqlalchemy.engine.base.Engine (3650,)
2019-07-23 11:41:16,900 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,901 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:16,903 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,906 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,908 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,908 INFO sqlalchemy.engine.base.Engine (3651,)
2019-07-23 11:41:16,912 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,913 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:16,916 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,919 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,920 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,921 INFO sqlalchemy.engine.base.Engine (3652,)
2019-07-23 11:41:16,925 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,925 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:16,928 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,931 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,932 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,933 INFO sqlalchemy.engine.base.Engine (3653,)
2019-07-23 11:41:16,937 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,938 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:16,940 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,944 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:16,946 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,947 INFO sqlalchemy.engine.base.Engine (3654,)
2019-07-23 11:41:16,951 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,952 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:16,954 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,958 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,959 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,960 INFO sqlalchemy.engine.base.Engine (3655,)
2019-07-23 11:41:16,962 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,963 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:41:16,965 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,969 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,970 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,971 INFO sqlalchemy.engine.base.Engine (3656,)
2019-07-23 11:41:16,974 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,975 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:16,977 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,982 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,983 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,984 INFO sqlalchemy.engine.base.Engine (3657,)
2019-07-23 11:41:16,988 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:16,989 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:16,990 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:16,995 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:16,996 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:16,997 INFO sqlalchemy.engine.base.Engine (3658,)
2019-07-23 11:41:17,000 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,001 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:17,003 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,007 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,008 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,009 INFO sqlalchemy.engine.base.Engine (3659,)
2019-07-23 11:41:17,013 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,015 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:41:17,017 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,021 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,022 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,023 INFO sqlalchemy.engine.base.Engine (3660,)
2019-07-23 11:41:17,026 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,027 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:17,028 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,032 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,034 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,034 INFO sqlalchemy.engine.base.Engine (3661,)
2019-07-23 11:41:17,038 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,039 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:17,041 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,045 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,046 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,047 INFO sqlalchemy.engine.base.Engine (3662,)
2019-07-23 11:41:17,050 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,050 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:17,052 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,056 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,057 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,058 INFO sqlalchemy.engine.base.Engine (3663,)
2019-07-23 11:41:17,061 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,062 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:17,065 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,068 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,069 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,070 INFO sqlalchemy.engine.base.Engine (3664,)
2019-07-23 11:41:17,073 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,074 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:17,077 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,080 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,081 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,082 INFO sqlalchemy.engine.base.Engine (3665,)

2019-07-23 11:41:17,085 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,086 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:17,088 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,092 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,093 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,093 INFO sqlalchemy.engine.base.Engine (3666,)
2019-07-23 11:41:17,097 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,098 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:17,101 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,104 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,106 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,107 INFO sqlalchemy.engine.base.Engine (3667,)
2019-07-23 11:41:17,110 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,110 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:17,113 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,116 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,117 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,118 INFO sqlalchemy.engine.base.Engine (3668,)
2019-07-23 11:41:17,121 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,122 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:41:17,125 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,128 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,130 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,130 INFO sqlalchemy.engine.base.Engine (3669,)
2019-07-23 11:41:17,134 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,135 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:41:17,137 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,141 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,142 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,143 INFO sqlalchemy.engine.base.Engine (3670,)
2019-07-23 11:41:17,147 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,148 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:17,149 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,153 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,154 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,155 INFO sqlalchemy.engine.base.Engine (3671,)
2019-07-23 11:41:17,159 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,160 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:17,162 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,165 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,166 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,167 INFO sqlalchemy.engine.base.Engine (3672,)
2019-07-23 11:41:17,170 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,172 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:41:17,173 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,177 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,178 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,179 INFO sqlalchemy.engine.base.Engine (3673,)
2019-07-23 11:41:17,182 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,183 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:17,186 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,190 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,191 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,192 INFO sqlalchemy.engine.base.Engine (3674,)
2019-07-23 11:41:17,195 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,196 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:41:17,198 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,202 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,203 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,204 INFO sqlalchemy.engine.base.Engine (3675,)
2019-07-23 11:41:17,207 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,207 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:17,210 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,213 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,214 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,216 INFO sqlalchemy.engine.base.Engine (3676,)
2019-07-23 11:41:17,218 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,219 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:17,220 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:17,225 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,226 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,227 INFO sqlalchemy.engine.base.Engine (3677,)
2019-07-23 11:41:17,231 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,232 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:17,234 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,238 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,239 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,239 INFO sqlalchemy.engine.base.Engine (3678,)
2019-07-23 11:41:17,244 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,245 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:41:17,247 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,251 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,252 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,253 INFO sqlalchemy.engine.base.Engine (3679,)
2019-07-23 11:41:17,256 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,257 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:17,260 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,263 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,265 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,265 INFO sqlalchemy.engine.base.Engine (3680,)
2019-07-23 11:41:17,269 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,270 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:17,272 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,276 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,277 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,278 INFO sqlalchemy.engine.base.Engine (3681,)
2019-07-23 11:41:17,282 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,283 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:41:17,286 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,289 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,291 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,291 INFO sqlalchemy.engine.base.Engine (3682,)
2019-07-23 11:41:17,294 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,296 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:41:17,298 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,302 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,303 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,304 INFO sqlalchemy.engine.base.Engine (3683,)
2019-07-23 11:41:17,307 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,308 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:17,310 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,314 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,315 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,316 INFO sqlalchemy.engine.base.Engine (3684,)
2019-07-23 11:41:17,319 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,320 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:17,322 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,326 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,327 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,328 INFO sqlalchemy.engine.base.Engine (3685,)
2019-07-23 11:41:17,332 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,333 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:17,337 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,340 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,342 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,342 INFO sqlalchemy.engine.base.Engine (3686,)
2019-07-23 11:41:17,346 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,347 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:17,348 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,352 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,353 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,354 INFO sqlalchemy.engine.base.Engine (3687,)
2019-07-23 11:41:17,358 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,359 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:17,362 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,366 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,367 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:17,368 INFO sqlalchemy.engine.base.Engine (3688,)
2019-07-23 11:41:17,372 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,372 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:17,375 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,379 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,380 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,381 INFO sqlalchemy.engine.base.Engine (3689,)
2019-07-23 11:41:17,384 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,385 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:17,389 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,393 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,394 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,395 INFO sqlalchemy.engine.base.Engine (3690,)
2019-07-23 11:41:17,398 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,398 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:17,401 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,404 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,405 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,406 INFO sqlalchemy.engine.base.Engine (3691,)
2019-07-23 11:41:17,410 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,411 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:41:17,414 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,418 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,419 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,420 INFO sqlalchemy.engine.base.Engine (3692,)
2019-07-23 11:41:17,424 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,425 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:41:17,427 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,432 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,433 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,434 INFO sqlalchemy.engine.base.Engine (3693,)
2019-07-23 11:41:17,438 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,439 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:17,441 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,445 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,446 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,447 INFO sqlalchemy.engine.base.Engine (3694,)
2019-07-23 11:41:17,450 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,451 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:17,453 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,458 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,459 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,460 INFO sqlalchemy.engine.base.Engine (3695,)
2019-07-23 11:41:17,464 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,464 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:41:17,466 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,470 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,471 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,472 INFO sqlalchemy.engine.base.Engine (3696,)
2019-07-23 11:41:17,475 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,475 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:17,478 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,483 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,485 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,485 INFO sqlalchemy.engine.base.Engine (3697,)
2019-07-23 11:41:17,490 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,491 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:41:17,494 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,498 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,499 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,499 INFO sqlalchemy.engine.base.Engine (3698,)
2019-07-23 11:41:17,503 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,504 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:17,506 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,510 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,511 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,511 INFO sqlalchemy.engine.base.Engine (3699,)
2019-07-23 11:41:17,515 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,516 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')

2019-07-23 11:41:17,518 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,522 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,523 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,524 INFO sqlalchemy.engine.base.Engine (3700,)
2019-07-23 11:41:17,528 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,529 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:17,531 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,535 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,536 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,537 INFO sqlalchemy.engine.base.Engine (3701,)
2019-07-23 11:41:17,541 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,542 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:17,545 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,549 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,550 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,550 INFO sqlalchemy.engine.base.Engine (3702,)
2019-07-23 11:41:17,554 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,555 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:17,557 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,560 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,562 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,562 INFO sqlalchemy.engine.base.Engine (3703,)
2019-07-23 11:41:17,565 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,566 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:17,569 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,573 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,574 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,575 INFO sqlalchemy.engine.base.Engine (3704,)
2019-07-23 11:41:17,578 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,579 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:41:17,583 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,586 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,588 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,588 INFO sqlalchemy.engine.base.Engine (3705,)
2019-07-23 11:41:17,592 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,592 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:41:17,594 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,599 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,601 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,601 INFO sqlalchemy.engine.base.Engine (3706,)
2019-07-23 11:41:17,605 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,607 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:17,609 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,612 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,614 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,614 INFO sqlalchemy.engine.base.Engine (3707,)
2019-07-23 11:41:17,618 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,619 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:17,621 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,625 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,626 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,627 INFO sqlalchemy.engine.base.Engine (3708,)
2019-07-23 11:41:17,630 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,631 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:17,634 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,637 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,638 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,639 INFO sqlalchemy.engine.base.Engine (3709,)
2019-07-23 11:41:17,643 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,644 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:17,646 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,650 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,651 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:17,652 INFO sqlalchemy.engine.base.Engine (3710,)
2019-07-23 11:41:17,655 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:17,656 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:17,659 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:17,663 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:17,665 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:17,665 INFO sqlalchemy.engine.base.Engine (3711,)
http://sz.ganji.com/zufang/pn13 status: 200
2019-07-23 11:41:18,644 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,645 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:41:18,647 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,651 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,652 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,652 INFO sqlalchemy.engine.base.Engine (3712,)
2019-07-23 11:41:18,656 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,657 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:41:18,658 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,662 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,663 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,664 INFO sqlalchemy.engine.base.Engine (3713,)
2019-07-23 11:41:18,667 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,668 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:41:18,671 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,674 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,675 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,676 INFO sqlalchemy.engine.base.Engine (3714,)
2019-07-23 11:41:18,679 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,680 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:41:18,682 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,686 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,687 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,688 INFO sqlalchemy.engine.base.Engine (3715,)
2019-07-23 11:41:18,691 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,692 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:41:18,694 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,698 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,699 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,700 INFO sqlalchemy.engine.base.Engine (3716,)
2019-07-23 11:41:18,703 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,704 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:41:18,706 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,710 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,711 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,712 INFO sqlalchemy.engine.base.Engine (3717,)
2019-07-23 11:41:18,715 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,716 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:41:18,718 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,722 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,724 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,724 INFO sqlalchemy.engine.base.Engine (3718,)
2019-07-23 11:41:18,728 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,728 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:18,730 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,734 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,735 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,735 INFO sqlalchemy.engine.base.Engine (3719,)
2019-07-23 11:41:18,739 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,739 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:41:18,742 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,745 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,747 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,748 INFO sqlalchemy.engine.base.Engine (3720,)
2019-07-23 11:41:18,751 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,752 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:18,753 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,757 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,758 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,759 INFO sqlalchemy.engine.base.Engine (3721,)
2019-07-23 11:41:18,761 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,762 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:41:18,764 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,768 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,769 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,770 INFO sqlalchemy.engine.base.Engine (3722,)
2019-07-23 11:41:18,773 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:18,774 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:41:18,776 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,779 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,781 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,781 INFO sqlalchemy.engine.base.Engine (3723,)
2019-07-23 11:41:18,784 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,785 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:41:18,787 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,791 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,792 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,793 INFO sqlalchemy.engine.base.Engine (3724,)
2019-07-23 11:41:18,796 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,796 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:41:18,798 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,802 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,803 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,804 INFO sqlalchemy.engine.base.Engine (3725,)
2019-07-23 11:41:18,807 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,807 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:41:18,809 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,813 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,814 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,815 INFO sqlalchemy.engine.base.Engine (3726,)
2019-07-23 11:41:18,818 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,819 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:41:18,820 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,824 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,825 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,826 INFO sqlalchemy.engine.base.Engine (3727,)
2019-07-23 11:41:18,828 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,829 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:41:18,832 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,836 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,837 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,838 INFO sqlalchemy.engine.base.Engine (3728,)
2019-07-23 11:41:18,840 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,841 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:41:18,844 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,848 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,849 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,849 INFO sqlalchemy.engine.base.Engine (3729,)
2019-07-23 11:41:18,853 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,854 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:41:18,856 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,859 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,861 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,861 INFO sqlalchemy.engine.base.Engine (3730,)
2019-07-23 11:41:18,865 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,865 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:41:18,867 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,871 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,872 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,873 INFO sqlalchemy.engine.base.Engine (3731,)
2019-07-23 11:41:18,876 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,876 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:41:18,879 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,882 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,884 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,884 INFO sqlalchemy.engine.base.Engine (3732,)
2019-07-23 11:41:18,887 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,888 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:41:18,890 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,894 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,895 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,895 INFO sqlalchemy.engine.base.Engine (3733,)
2019-07-23 11:41:18,899 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,900 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:41:18,902 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:18,906 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,907 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,908 INFO sqlalchemy.engine.base.Engine (3734,)
2019-07-23 11:41:18,911 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,912 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:41:18,913 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,917 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,918 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,919 INFO sqlalchemy.engine.base.Engine (3735,)
2019-07-23 11:41:18,922 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,922 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:41:18,924 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,928 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,929 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,930 INFO sqlalchemy.engine.base.Engine (3736,)
2019-07-23 11:41:18,933 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,934 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:41:18,935 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,939 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,940 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,941 INFO sqlalchemy.engine.base.Engine (3737,)
2019-07-23 11:41:18,944 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,945 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:18,947 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,950 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,951 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,952 INFO sqlalchemy.engine.base.Engine (3738,)
2019-07-23 11:41:18,956 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,957 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:41:18,959 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,962 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,963 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,964 INFO sqlalchemy.engine.base.Engine (3739,)
2019-07-23 11:41:18,968 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,968 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:18,970 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,974 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,975 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,976 INFO sqlalchemy.engine.base.Engine (3740,)
2019-07-23 11:41:18,980 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,980 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:18,983 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,986 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,987 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:18,988 INFO sqlalchemy.engine.base.Engine (3741,)
2019-07-23 11:41:18,991 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:18,993 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:18,995 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:18,998 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:18,999 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,000 INFO sqlalchemy.engine.base.Engine (3742,)
2019-07-23 11:41:19,003 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,004 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:19,005 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,009 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,010 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,011 INFO sqlalchemy.engine.base.Engine (3743,)
2019-07-23 11:41:19,014 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,015 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:19,016 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,020 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,021 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,022 INFO sqlalchemy.engine.base.Engine (3744,)
2019-07-23 11:41:19,025 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,026 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:19,027 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,031 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,032 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:19,033 INFO sqlalchemy.engine.base.Engine (3745,)
2019-07-23 11:41:19,036 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,037 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:19,039 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,042 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,043 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,044 INFO sqlalchemy.engine.base.Engine (3746,)
2019-07-23 11:41:19,047 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,048 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:19,051 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,054 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,055 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,056 INFO sqlalchemy.engine.base.Engine (3747,)
2019-07-23 11:41:19,060 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,060 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:19,063 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,066 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,068 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,068 INFO sqlalchemy.engine.base.Engine (3748,)
2019-07-23 11:41:19,072 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,073 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:41:19,075 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,079 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,080 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,081 INFO sqlalchemy.engine.base.Engine (3749,)
2019-07-23 11:41:19,084 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,085 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:19,087 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,091 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,092 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,093 INFO sqlalchemy.engine.base.Engine (3750,)
2019-07-23 11:41:19,096 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,096 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:19,098 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,102 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,103 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,103 INFO sqlalchemy.engine.base.Engine (3751,)
2019-07-23 11:41:19,106 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,107 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:41:19,108 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,112 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,113 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,114 INFO sqlalchemy.engine.base.Engine (3752,)
2019-07-23 11:41:19,117 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,118 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:41:19,120 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,123 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,124 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,125 INFO sqlalchemy.engine.base.Engine (3753,)
2019-07-23 11:41:19,128 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,129 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:19,131 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,134 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,135 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,136 INFO sqlalchemy.engine.base.Engine (3754,)
2019-07-23 11:41:19,140 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,141 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:19,143 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,147 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,148 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,149 INFO sqlalchemy.engine.base.Engine (3755,)
2019-07-23 11:41:19,152 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,152 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:19,154 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,157 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,158 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,159 INFO sqlalchemy.engine.base.Engine (3756,)
2019-07-23 11:41:19,162 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:19,163 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:19,165 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,168 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,169 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,170 INFO sqlalchemy.engine.base.Engine (3757,)
2019-07-23 11:41:19,173 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,174 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:19,176 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,180 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,181 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,182 INFO sqlalchemy.engine.base.Engine (3758,)
2019-07-23 11:41:19,185 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,186 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:19,188 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,192 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,193 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,194 INFO sqlalchemy.engine.base.Engine (3759,)
2019-07-23 11:41:19,197 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,197 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:19,199 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,203 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,204 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,205 INFO sqlalchemy.engine.base.Engine (3760,)
2019-07-23 11:41:19,207 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,208 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:19,210 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,214 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,216 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,216 INFO sqlalchemy.engine.base.Engine (3761,)
2019-07-23 11:41:19,219 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,220 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:19,222 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,226 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,227 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,228 INFO sqlalchemy.engine.base.Engine (3762,)
2019-07-23 11:41:19,231 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,232 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:19,234 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,237 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,239 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,239 INFO sqlalchemy.engine.base.Engine (3763,)
2019-07-23 11:41:19,242 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,243 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:19,245 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,248 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,250 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,250 INFO sqlalchemy.engine.base.Engine (3764,)
2019-07-23 11:41:19,254 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,255 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:19,257 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,260 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,261 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,262 INFO sqlalchemy.engine.base.Engine (3765,)
2019-07-23 11:41:19,265 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,266 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:19,268 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,272 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,273 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,274 INFO sqlalchemy.engine.base.Engine (3766,)
2019-07-23 11:41:19,277 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,278 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:19,279 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,283 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,284 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,285 INFO sqlalchemy.engine.base.Engine (3767,)
2019-07-23 11:41:19,288 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,289 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:19,291 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,295 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:19,296 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,296 INFO sqlalchemy.engine.base.Engine (3768,)
2019-07-23 11:41:19,300 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,301 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:19,303 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,307 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,308 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,308 INFO sqlalchemy.engine.base.Engine (3769,)
2019-07-23 11:41:19,313 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,313 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:19,315 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,319 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,320 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,320 INFO sqlalchemy.engine.base.Engine (3770,)
2019-07-23 11:41:19,324 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,325 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:19,327 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,330 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,332 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,333 INFO sqlalchemy.engine.base.Engine (3771,)
2019-07-23 11:41:19,336 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,337 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:41:19,339 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,342 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,343 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,344 INFO sqlalchemy.engine.base.Engine (3772,)
2019-07-23 11:41:19,347 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,348 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:19,351 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,354 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,355 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,356 INFO sqlalchemy.engine.base.Engine (3773,)
2019-07-23 11:41:19,359 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,361 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:19,363 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,366 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,368 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,368 INFO sqlalchemy.engine.base.Engine (3774,)
2019-07-23 11:41:19,371 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,372 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:41:19,375 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,378 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,379 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,380 INFO sqlalchemy.engine.base.Engine (3775,)
2019-07-23 11:41:19,383 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,383 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:19,385 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,389 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,390 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,391 INFO sqlalchemy.engine.base.Engine (3776,)
2019-07-23 11:41:19,394 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,396 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:19,397 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,401 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,402 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,402 INFO sqlalchemy.engine.base.Engine (3777,)
2019-07-23 11:41:19,405 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,406 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:19,409 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,412 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,414 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,414 INFO sqlalchemy.engine.base.Engine (3778,)
2019-07-23 11:41:19,418 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,418 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:19,421 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,425 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,426 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,427 INFO sqlalchemy.engine.base.Engine (3779,)

2019-07-23 11:41:19,430 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,431 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:19,433 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,436 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,438 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,439 INFO sqlalchemy.engine.base.Engine (3780,)
2019-07-23 11:41:19,442 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,442 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:19,444 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,449 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,450 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,450 INFO sqlalchemy.engine.base.Engine (3781,)
2019-07-23 11:41:19,453 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,454 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:19,456 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,460 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,461 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,462 INFO sqlalchemy.engine.base.Engine (3782,)
2019-07-23 11:41:19,465 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,466 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:19,468 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,471 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,472 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,473 INFO sqlalchemy.engine.base.Engine (3783,)
2019-07-23 11:41:19,475 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,476 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:19,478 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,482 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,483 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,484 INFO sqlalchemy.engine.base.Engine (3784,)
2019-07-23 11:41:19,488 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,489 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:19,490 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,494 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,495 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,496 INFO sqlalchemy.engine.base.Engine (3785,)
2019-07-23 11:41:19,499 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,500 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:19,502 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,506 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,507 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,508 INFO sqlalchemy.engine.base.Engine (3786,)
2019-07-23 11:41:19,511 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,512 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:19,514 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,517 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,518 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,519 INFO sqlalchemy.engine.base.Engine (3787,)
2019-07-23 11:41:19,522 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,522 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:19,525 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,528 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,530 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,530 INFO sqlalchemy.engine.base.Engine (3788,)
2019-07-23 11:41:19,533 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,534 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:19,536 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,540 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,541 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,541 INFO sqlalchemy.engine.base.Engine (3789,)
2019-07-23 11:41:19,545 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,546 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:19,548 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,552 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,553 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,553 INFO sqlalchemy.engine.base.Engine (3790,)
2019-07-23 11:41:19,557 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,558 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:19,560 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,563 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:19,565 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,565 INFO sqlalchemy.engine.base.Engine (3791,)
2019-07-23 11:41:19,569 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,569 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:19,572 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,576 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,577 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,578 INFO sqlalchemy.engine.base.Engine (3792,)
2019-07-23 11:41:19,582 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,583 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:19,584 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,588 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,589 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,590 INFO sqlalchemy.engine.base.Engine (3793,)
2019-07-23 11:41:19,594 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,594 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:19,596 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,600 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,601 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,602 INFO sqlalchemy.engine.base.Engine (3794,)
2019-07-23 11:41:19,606 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,607 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:41:19,609 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,613 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,614 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,615 INFO sqlalchemy.engine.base.Engine (3795,)
2019-07-23 11:41:19,618 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,619 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:19,620 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,624 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,625 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,626 INFO sqlalchemy.engine.base.Engine (3796,)
2019-07-23 11:41:19,629 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,630 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:19,632 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,635 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,636 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,637 INFO sqlalchemy.engine.base.Engine (3797,)
2019-07-23 11:41:19,641 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,641 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:19,644 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,648 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,649 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,650 INFO sqlalchemy.engine.base.Engine (3798,)
2019-07-23 11:41:19,654 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,654 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:41:19,657 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,660 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,661 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,662 INFO sqlalchemy.engine.base.Engine (3799,)
2019-07-23 11:41:19,665 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,666 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:19,668 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,672 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,673 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,675 INFO sqlalchemy.engine.base.Engine (3800,)
2019-07-23 11:41:19,678 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,679 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:19,681 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,684 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,686 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,686 INFO sqlalchemy.engine.base.Engine (3801,)
2019-07-23 11:41:19,689 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,690 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:19,692 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,696 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,697 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,698 INFO sqlalchemy.engine.base.Engine (3802,)

2019-07-23 11:41:19,701 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,701 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:19,704 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,707 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,708 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,709 INFO sqlalchemy.engine.base.Engine (3803,)
2019-07-23 11:41:19,713 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,713 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:19,716 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,719 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,720 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,721 INFO sqlalchemy.engine.base.Engine (3804,)
2019-07-23 11:41:19,724 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,725 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:19,728 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,731 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,732 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,734 INFO sqlalchemy.engine.base.Engine (3805,)
2019-07-23 11:41:19,737 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,737 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:19,739 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,743 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,745 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,746 INFO sqlalchemy.engine.base.Engine (3806,)
2019-07-23 11:41:19,749 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,750 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:19,752 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,756 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,757 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,757 INFO sqlalchemy.engine.base.Engine (3807,)
2019-07-23 11:41:19,760 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,761 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:41:19,764 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,769 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,770 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,770 INFO sqlalchemy.engine.base.Engine (3808,)
2019-07-23 11:41:19,773 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,774 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:41:19,776 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,781 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,782 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,783 INFO sqlalchemy.engine.base.Engine (3809,)
2019-07-23 11:41:19,786 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,787 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:19,788 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,792 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,793 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,794 INFO sqlalchemy.engine.base.Engine (3810,)
2019-07-23 11:41:19,798 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,798 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:19,801 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,804 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,805 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,806 INFO sqlalchemy.engine.base.Engine (3811,)
2019-07-23 11:41:19,809 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,810 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:41:19,812 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,816 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,817 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,818 INFO sqlalchemy.engine.base.Engine (3812,)
2019-07-23 11:41:19,821 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,823 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:19,824 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,828 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,829 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,830 INFO sqlalchemy.engine.base.Engine (3813,)
2019-07-23 11:41:19,833 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,834 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')

2019-07-23 11:41:19,837 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,840 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,841 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,842 INFO sqlalchemy.engine.base.Engine (3814,)
2019-07-23 11:41:19,846 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,847 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:19,849 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,852 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,853 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,854 INFO sqlalchemy.engine.base.Engine (3815,)
2019-07-23 11:41:19,858 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,859 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:19,861 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,864 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,866 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,866 INFO sqlalchemy.engine.base.Engine (3816,)
2019-07-23 11:41:19,870 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,871 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:19,873 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,877 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,878 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,879 INFO sqlalchemy.engine.base.Engine (3817,)
2019-07-23 11:41:19,882 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,883 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:41:19,884 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,889 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,890 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,890 INFO sqlalchemy.engine.base.Engine (3818,)
2019-07-23 11:41:19,894 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,895 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:19,897 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,900 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,902 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,903 INFO sqlalchemy.engine.base.Engine (3819,)
2019-07-23 11:41:19,906 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,907 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:19,908 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,912 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,913 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,913 INFO sqlalchemy.engine.base.Engine (3820,)
2019-07-23 11:41:19,917 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,918 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:41:19,921 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,924 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,925 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,926 INFO sqlalchemy.engine.base.Engine (3821,)
2019-07-23 11:41:19,929 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,930 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:41:19,933 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,936 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,938 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,938 INFO sqlalchemy.engine.base.Engine (3822,)
2019-07-23 11:41:19,942 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,943 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:19,945 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,949 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,950 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,951 INFO sqlalchemy.engine.base.Engine (3823,)
2019-07-23 11:41:19,954 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,955 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:19,957 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,960 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,962 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,962 INFO sqlalchemy.engine.base.Engine (3824,)
2019-07-23 11:41:19,966 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,967 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:19,969 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,972 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,973 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:19,974 INFO sqlalchemy.engine.base.Engine (3825,)
2019-07-23 11:41:19,978 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,979 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:19,981 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,985 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,986 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,987 INFO sqlalchemy.engine.base.Engine (3826,)
2019-07-23 11:41:19,990 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:19,991 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:19,993 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:19,996 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:19,997 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:19,998 INFO sqlalchemy.engine.base.Engine (3827,)
2019-07-23 11:41:20,002 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,003 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:20,005 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,009 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,010 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,011 INFO sqlalchemy.engine.base.Engine (3828,)
2019-07-23 11:41:20,014 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,015 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:20,017 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,021 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,023 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,024 INFO sqlalchemy.engine.base.Engine (3829,)
2019-07-23 11:41:20,027 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,028 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:20,030 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,033 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,034 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,035 INFO sqlalchemy.engine.base.Engine (3830,)
2019-07-23 11:41:20,038 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,039 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:41:20,041 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,046 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,047 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,048 INFO sqlalchemy.engine.base.Engine (3831,)
2019-07-23 11:41:20,051 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,052 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:41:20,054 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,057 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,059 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,060 INFO sqlalchemy.engine.base.Engine (3832,)
2019-07-23 11:41:20,063 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,063 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:20,066 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,069 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,070 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,071 INFO sqlalchemy.engine.base.Engine (3833,)
2019-07-23 11:41:20,074 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,075 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:20,077 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,082 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,083 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,083 INFO sqlalchemy.engine.base.Engine (3834,)
2019-07-23 11:41:20,087 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,088 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:41:20,090 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,093 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,095 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,095 INFO sqlalchemy.engine.base.Engine (3835,)
2019-07-23 11:41:20,098 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,099 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:20,101 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,106 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,107 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,108 INFO sqlalchemy.engine.base.Engine (3836,)
2019-07-23 11:41:20,110 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,111 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')

2019-07-23 11:41:20,113 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,117 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,118 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,119 INFO sqlalchemy.engine.base.Engine (3837,)
2019-07-23 11:41:20,123 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,124 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:20,127 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,130 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,131 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,132 INFO sqlalchemy.engine.base.Engine (3838,)
2019-07-23 11:41:20,135 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,136 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:41:20,140 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,144 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,145 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,146 INFO sqlalchemy.engine.base.Engine (3839,)
2019-07-23 11:41:20,149 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,150 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:20,152 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,155 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,156 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,157 INFO sqlalchemy.engine.base.Engine (3840,)
2019-07-23 11:41:20,160 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,162 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:20,164 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,167 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,168 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,169 INFO sqlalchemy.engine.base.Engine (3841,)
2019-07-23 11:41:20,172 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,172 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:20,174 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,178 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,179 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,180 INFO sqlalchemy.engine.base.Engine (3842,)
2019-07-23 11:41:20,183 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,184 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:20,186 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,190 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,192 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,193 INFO sqlalchemy.engine.base.Engine (3843,)
2019-07-23 11:41:20,196 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,197 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:41:20,199 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,203 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,204 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,205 INFO sqlalchemy.engine.base.Engine (3844,)
2019-07-23 11:41:20,208 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,209 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:41:20,211 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,215 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,216 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,217 INFO sqlalchemy.engine.base.Engine (3845,)
2019-07-23 11:41:20,220 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,221 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:20,223 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,227 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,228 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,229 INFO sqlalchemy.engine.base.Engine (3846,)
2019-07-23 11:41:20,232 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,233 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:20,235 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,239 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,240 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,240 INFO sqlalchemy.engine.base.Engine (3847,)
2019-07-23 11:41:20,244 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,245 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:20,248 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,251 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,253 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:20,253 INFO sqlalchemy.engine.base.Engine (3848,)
2019-07-23 11:41:20,257 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,257 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:20,260 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,264 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,265 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,266 INFO sqlalchemy.engine.base.Engine (3849,)
2019-07-23 11:41:20,268 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:20,269 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:20,271 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:20,275 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:20,276 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:20,277 INFO sqlalchemy.engine.base.Engine (3850,)
http://sz.ganji.com/zufang/pn14 status: 200
2019-07-23 11:41:21,230 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,231 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:41:21,232 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,236 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,237 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,238 INFO sqlalchemy.engine.base.Engine (3851,)
2019-07-23 11:41:21,241 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,242 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:41:21,244 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,248 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,249 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,250 INFO sqlalchemy.engine.base.Engine (3852,)
2019-07-23 11:41:21,253 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,254 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:41:21,256 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,259 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,260 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,261 INFO sqlalchemy.engine.base.Engine (3853,)
2019-07-23 11:41:21,264 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,265 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:41:21,267 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,270 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,272 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,272 INFO sqlalchemy.engine.base.Engine (3854,)
2019-07-23 11:41:21,275 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,276 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:41:21,277 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,281 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,282 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,283 INFO sqlalchemy.engine.base.Engine (3855,)
2019-07-23 11:41:21,286 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,287 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:41:21,289 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,293 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,294 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,295 INFO sqlalchemy.engine.base.Engine (3856,)
2019-07-23 11:41:21,298 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,299 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:41:21,300 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,304 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,305 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,306 INFO sqlalchemy.engine.base.Engine (3857,)
2019-07-23 11:41:21,310 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,311 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:21,313 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,317 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,318 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,318 INFO sqlalchemy.engine.base.Engine (3858,)
2019-07-23 11:41:21,322 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,323 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:41:21,325 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,329 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,330 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,331 INFO sqlalchemy.engine.base.Engine (3859,)
2019-07-23 11:41:21,334 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:21,335 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:21,336 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,340 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,341 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,342 INFO sqlalchemy.engine.base.Engine (3860,)
2019-07-23 11:41:21,345 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,346 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:41:21,349 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,352 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,353 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,354 INFO sqlalchemy.engine.base.Engine (3861,)
2019-07-23 11:41:21,356 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,357 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:41:21,359 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,362 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,363 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,364 INFO sqlalchemy.engine.base.Engine (3862,)
2019-07-23 11:41:21,367 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,367 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:41:21,369 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,373 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,374 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,375 INFO sqlalchemy.engine.base.Engine (3863,)
2019-07-23 11:41:21,378 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,378 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:41:21,380 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,383 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,385 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,385 INFO sqlalchemy.engine.base.Engine (3864,)
2019-07-23 11:41:21,388 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,390 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:41:21,392 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,395 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,397 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,397 INFO sqlalchemy.engine.base.Engine (3865,)
2019-07-23 11:41:21,400 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,401 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:41:21,403 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,407 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,408 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,409 INFO sqlalchemy.engine.base.Engine (3866,)
2019-07-23 11:41:21,412 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,413 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:41:21,415 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,418 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,419 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,421 INFO sqlalchemy.engine.base.Engine (3867,)
2019-07-23 11:41:21,423 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,424 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:41:21,426 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,429 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,431 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,431 INFO sqlalchemy.engine.base.Engine (3868,)
2019-07-23 11:41:21,434 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,435 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:41:21,437 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,441 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,442 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,443 INFO sqlalchemy.engine.base.Engine (3869,)
2019-07-23 11:41:21,446 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,447 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:41:21,449 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,453 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,454 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,455 INFO sqlalchemy.engine.base.Engine (3870,)
2019-07-23 11:41:21,458 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,458 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:41:21,461 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:21,464 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,466 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,467 INFO sqlalchemy.engine.base.Engine (3871,)
2019-07-23 11:41:21,470 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,470 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:41:21,472 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,476 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,478 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,479 INFO sqlalchemy.engine.base.Engine (3872,)
2019-07-23 11:41:21,481 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,482 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:41:21,483 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,487 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,488 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,489 INFO sqlalchemy.engine.base.Engine (3873,)
2019-07-23 11:41:21,492 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,492 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:41:21,494 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,499 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,500 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,500 INFO sqlalchemy.engine.base.Engine (3874,)
2019-07-23 11:41:21,504 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,504 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:41:21,506 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,509 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,510 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,511 INFO sqlalchemy.engine.base.Engine (3875,)
2019-07-23 11:41:21,514 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,515 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:41:21,517 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,521 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,522 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,523 INFO sqlalchemy.engine.base.Engine (3876,)
2019-07-23 11:41:21,526 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,527 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:21,528 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,532 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,533 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,534 INFO sqlalchemy.engine.base.Engine (3877,)
2019-07-23 11:41:21,537 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,538 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:41:21,540 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,544 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,545 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,545 INFO sqlalchemy.engine.base.Engine (3878,)
2019-07-23 11:41:21,549 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,549 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:21,551 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,555 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,556 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,556 INFO sqlalchemy.engine.base.Engine (3879,)
2019-07-23 11:41:21,559 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,560 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:21,563 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,566 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,567 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,568 INFO sqlalchemy.engine.base.Engine (3880,)
2019-07-23 11:41:21,571 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,572 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:21,574 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,578 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,579 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,580 INFO sqlalchemy.engine.base.Engine (3881,)
2019-07-23 11:41:21,583 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,583 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:21,586 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,589 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,590 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:21,591 INFO sqlalchemy.engine.base.Engine (3882,)
2019-07-23 11:41:21,594 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,595 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:21,597 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,600 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,601 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,602 INFO sqlalchemy.engine.base.Engine (3883,)
2019-07-23 11:41:21,606 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,607 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:21,609 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,613 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,614 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,614 INFO sqlalchemy.engine.base.Engine (3884,)
2019-07-23 11:41:21,618 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,619 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:21,621 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,624 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,626 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,626 INFO sqlalchemy.engine.base.Engine (3885,)
2019-07-23 11:41:21,629 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,630 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:21,632 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,635 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,637 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,637 INFO sqlalchemy.engine.base.Engine (3886,)
2019-07-23 11:41:21,641 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,642 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:21,643 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,648 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,649 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,650 INFO sqlalchemy.engine.base.Engine (3887,)
2019-07-23 11:41:21,653 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,654 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:41:21,656 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,660 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,661 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,661 INFO sqlalchemy.engine.base.Engine (3888,)
2019-07-23 11:41:21,665 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,666 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:21,668 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,671 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,672 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,673 INFO sqlalchemy.engine.base.Engine (3889,)
2019-07-23 11:41:21,676 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,677 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:21,679 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,683 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,684 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,685 INFO sqlalchemy.engine.base.Engine (3890,)
2019-07-23 11:41:21,687 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,688 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:41:21,691 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,694 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,695 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,696 INFO sqlalchemy.engine.base.Engine (3891,)
2019-07-23 11:41:21,699 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,700 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:41:21,702 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,706 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,707 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,707 INFO sqlalchemy.engine.base.Engine (3892,)
2019-07-23 11:41:21,710 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,711 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:21,715 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,718 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,719 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,720 INFO sqlalchemy.engine.base.Engine (3893,)
2019-07-23 11:41:21,723 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:21,724 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:21,726 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,729 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,730 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,731 INFO sqlalchemy.engine.base.Engine (3894,)
2019-07-23 11:41:21,734 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,735 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:21,737 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,741 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,742 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,743 INFO sqlalchemy.engine.base.Engine (3895,)
2019-07-23 11:41:21,747 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,748 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:21,750 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,753 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,755 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,755 INFO sqlalchemy.engine.base.Engine (3896,)
2019-07-23 11:41:21,758 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,759 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:21,761 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,765 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,766 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,766 INFO sqlalchemy.engine.base.Engine (3897,)
2019-07-23 11:41:21,769 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,770 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:21,772 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,776 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,778 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,779 INFO sqlalchemy.engine.base.Engine (3898,)
2019-07-23 11:41:21,781 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,782 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:21,784 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,787 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,788 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,789 INFO sqlalchemy.engine.base.Engine (3899,)
2019-07-23 11:41:21,792 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,793 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:21,795 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,799 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,800 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,801 INFO sqlalchemy.engine.base.Engine (3900,)
2019-07-23 11:41:21,804 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,805 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:21,807 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,811 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,812 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,812 INFO sqlalchemy.engine.base.Engine (3901,)
2019-07-23 11:41:21,815 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,815 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:21,817 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,822 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,823 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,823 INFO sqlalchemy.engine.base.Engine (3902,)
2019-07-23 11:41:21,826 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,827 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:21,830 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,834 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,835 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,836 INFO sqlalchemy.engine.base.Engine (3903,)
2019-07-23 11:41:21,839 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,840 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:21,842 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,846 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,847 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,848 INFO sqlalchemy.engine.base.Engine (3904,)
2019-07-23 11:41:21,851 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,852 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:21,854 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,858 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:21,859 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,860 INFO sqlalchemy.engine.base.Engine (3905,)
2019-07-23 11:41:21,863 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,864 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:21,866 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,869 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,871 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,871 INFO sqlalchemy.engine.base.Engine (3906,)
2019-07-23 11:41:21,875 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,876 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:21,877 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,881 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,882 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,883 INFO sqlalchemy.engine.base.Engine (3907,)
2019-07-23 11:41:21,886 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,887 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:21,889 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,893 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,894 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,895 INFO sqlalchemy.engine.base.Engine (3908,)
2019-07-23 11:41:21,899 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,899 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:21,902 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,905 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,906 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,907 INFO sqlalchemy.engine.base.Engine (3909,)
2019-07-23 11:41:21,909 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,910 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:21,911 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,916 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,917 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,917 INFO sqlalchemy.engine.base.Engine (3910,)
2019-07-23 11:41:21,921 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,922 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:41:21,924 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,928 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,929 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,929 INFO sqlalchemy.engine.base.Engine (3911,)
2019-07-23 11:41:21,933 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,934 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:21,936 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,940 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,941 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,942 INFO sqlalchemy.engine.base.Engine (3912,)
2019-07-23 11:41:21,946 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,947 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:21,949 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,953 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,954 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,954 INFO sqlalchemy.engine.base.Engine (3913,)
2019-07-23 11:41:21,958 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,959 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:41:21,961 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,964 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,965 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,966 INFO sqlalchemy.engine.base.Engine (3914,)
2019-07-23 11:41:21,969 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,970 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:21,973 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,978 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,979 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,979 INFO sqlalchemy.engine.base.Engine (3915,)
2019-07-23 11:41:21,983 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,984 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:21,987 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:21,991 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:21,992 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:21,993 INFO sqlalchemy.engine.base.Engine (3916,)

2019-07-23 11:41:21,996 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:21,997 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:21,999 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,002 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,003 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,004 INFO sqlalchemy.engine.base.Engine (3917,)
2019-07-23 11:41:22,007 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,009 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:22,011 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,014 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,015 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,016 INFO sqlalchemy.engine.base.Engine (3918,)
2019-07-23 11:41:22,019 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,021 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:22,023 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,026 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,027 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,029 INFO sqlalchemy.engine.base.Engine (3919,)
2019-07-23 11:41:22,032 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,032 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:22,035 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,038 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,039 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,040 INFO sqlalchemy.engine.base.Engine (3920,)
2019-07-23 11:41:22,043 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,044 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:22,046 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,050 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,051 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,052 INFO sqlalchemy.engine.base.Engine (3921,)
2019-07-23 11:41:22,055 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,056 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:22,058 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,061 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,062 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,063 INFO sqlalchemy.engine.base.Engine (3922,)
2019-07-23 11:41:22,066 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,067 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:22,069 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,073 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,074 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,074 INFO sqlalchemy.engine.base.Engine (3923,)
2019-07-23 11:41:22,078 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,079 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:22,081 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,084 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,085 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,086 INFO sqlalchemy.engine.base.Engine (3924,)
2019-07-23 11:41:22,090 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,090 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:22,092 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,096 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,097 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,098 INFO sqlalchemy.engine.base.Engine (3925,)
2019-07-23 11:41:22,100 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,101 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:22,102 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,106 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,107 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,108 INFO sqlalchemy.engine.base.Engine (3926,)
2019-07-23 11:41:22,112 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,112 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:22,114 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,117 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,118 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,119 INFO sqlalchemy.engine.base.Engine (3927,)
2019-07-23 11:41:22,122 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,123 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:22,125 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,129 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:22,130 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,131 INFO sqlalchemy.engine.base.Engine (3928,)
2019-07-23 11:41:22,134 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,135 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:22,137 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,140 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,141 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,142 INFO sqlalchemy.engine.base.Engine (3929,)
2019-07-23 11:41:22,146 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,147 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:22,149 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,153 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,154 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,155 INFO sqlalchemy.engine.base.Engine (3930,)
2019-07-23 11:41:22,158 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,159 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:22,161 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,164 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,165 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,166 INFO sqlalchemy.engine.base.Engine (3931,)
2019-07-23 11:41:22,170 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,171 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:22,174 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,178 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,179 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,180 INFO sqlalchemy.engine.base.Engine (3932,)
2019-07-23 11:41:22,184 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,185 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:22,187 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,190 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,191 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,192 INFO sqlalchemy.engine.base.Engine (3933,)
2019-07-23 11:41:22,195 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,196 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:41:22,199 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,203 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,204 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,205 INFO sqlalchemy.engine.base.Engine (3934,)
2019-07-23 11:41:22,208 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,209 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:22,211 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,215 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,216 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,217 INFO sqlalchemy.engine.base.Engine (3935,)
2019-07-23 11:41:22,220 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,221 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:22,223 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,227 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,228 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,229 INFO sqlalchemy.engine.base.Engine (3936,)
2019-07-23 11:41:22,232 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,233 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:22,235 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,239 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,240 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,241 INFO sqlalchemy.engine.base.Engine (3937,)
2019-07-23 11:41:22,245 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,246 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:41:22,248 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,251 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,253 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,253 INFO sqlalchemy.engine.base.Engine (3938,)
2019-07-23 11:41:22,257 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,258 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:22,260 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,263 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,265 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,265 INFO sqlalchemy.engine.base.Engine (3939,)

2019-07-23 11:41:22,268 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,269 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:22,272 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,275 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,276 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,277 INFO sqlalchemy.engine.base.Engine (3940,)
2019-07-23 11:41:22,280 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,281 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:22,283 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,288 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,290 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,291 INFO sqlalchemy.engine.base.Engine (3941,)
2019-07-23 11:41:22,294 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,295 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:22,297 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,302 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,304 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,305 INFO sqlalchemy.engine.base.Engine (3942,)
2019-07-23 11:41:22,308 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,309 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:22,311 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,315 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,317 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,318 INFO sqlalchemy.engine.base.Engine (3943,)
2019-07-23 11:41:22,321 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,322 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:22,324 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,327 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,328 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,329 INFO sqlalchemy.engine.base.Engine (3944,)
2019-07-23 11:41:22,332 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,333 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:22,335 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,339 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,340 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,340 INFO sqlalchemy.engine.base.Engine (3945,)
2019-07-23 11:41:22,344 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,345 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:22,348 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,351 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,352 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,353 INFO sqlalchemy.engine.base.Engine (3946,)
2019-07-23 11:41:22,355 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,356 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:41:22,359 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,363 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,364 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,365 INFO sqlalchemy.engine.base.Engine (3947,)
2019-07-23 11:41:22,368 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,369 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:41:22,371 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,375 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,376 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,376 INFO sqlalchemy.engine.base.Engine (3948,)
2019-07-23 11:41:22,380 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,381 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:22,382 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,386 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,387 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,388 INFO sqlalchemy.engine.base.Engine (3949,)
2019-07-23 11:41:22,392 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,392 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:22,394 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,398 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,399 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,400 INFO sqlalchemy.engine.base.Engine (3950,)
2019-07-23 11:41:22,403 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,404 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')

2019-07-23 11:41:22,406 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,410 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,411 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,412 INFO sqlalchemy.engine.base.Engine (3951,)
2019-07-23 11:41:22,414 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,415 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:22,417 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,421 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,422 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,423 INFO sqlalchemy.engine.base.Engine (3952,)
2019-07-23 11:41:22,425 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,426 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:41:22,428 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,432 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,433 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,434 INFO sqlalchemy.engine.base.Engine (3953,)
2019-07-23 11:41:22,437 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,438 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:22,440 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,445 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,446 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,447 INFO sqlalchemy.engine.base.Engine (3954,)
2019-07-23 11:41:22,450 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,451 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:22,452 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,456 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,458 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,458 INFO sqlalchemy.engine.base.Engine (3955,)
2019-07-23 11:41:22,463 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,463 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:22,465 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,469 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,470 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,471 INFO sqlalchemy.engine.base.Engine (3956,)
2019-07-23 11:41:22,474 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,475 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:41:22,477 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,481 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,482 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,483 INFO sqlalchemy.engine.base.Engine (3957,)
2019-07-23 11:41:22,486 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,487 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:22,489 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,492 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,493 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,494 INFO sqlalchemy.engine.base.Engine (3958,)
2019-07-23 11:41:22,497 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,497 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:22,499 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,503 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,504 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,505 INFO sqlalchemy.engine.base.Engine (3959,)
2019-07-23 11:41:22,508 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,509 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:41:22,511 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,515 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,516 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,517 INFO sqlalchemy.engine.base.Engine (3960,)
2019-07-23 11:41:22,519 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,520 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:41:22,522 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,526 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,527 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,528 INFO sqlalchemy.engine.base.Engine (3961,)
2019-07-23 11:41:22,531 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,532 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:22,535 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,538 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,539 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:22,540 INFO sqlalchemy.engine.base.Engine (3962,)
2019-07-23 11:41:22,544 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,545 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:22,547 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,550 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,551 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,552 INFO sqlalchemy.engine.base.Engine (3963,)
2019-07-23 11:41:22,556 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,557 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:22,559 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,563 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,564 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,565 INFO sqlalchemy.engine.base.Engine (3964,)
2019-07-23 11:41:22,568 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,569 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:22,570 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,574 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,576 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,577 INFO sqlalchemy.engine.base.Engine (3965,)
2019-07-23 11:41:22,579 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,580 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:22,582 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,586 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,587 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,588 INFO sqlalchemy.engine.base.Engine (3966,)
2019-07-23 11:41:22,591 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,592 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:22,594 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,599 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,601 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,602 INFO sqlalchemy.engine.base.Engine (3967,)
2019-07-23 11:41:22,605 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,605 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:22,608 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,611 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,612 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,613 INFO sqlalchemy.engine.base.Engine (3968,)
2019-07-23 11:41:22,616 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,617 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:22,620 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,623 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,624 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,625 INFO sqlalchemy.engine.base.Engine (3969,)
2019-07-23 11:41:22,628 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,629 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:41:22,630 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,634 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,636 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,636 INFO sqlalchemy.engine.base.Engine (3970,)
2019-07-23 11:41:22,640 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,641 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:41:22,644 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,648 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,650 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,650 INFO sqlalchemy.engine.base.Engine (3971,)
2019-07-23 11:41:22,654 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,654 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:22,656 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,661 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,662 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,663 INFO sqlalchemy.engine.base.Engine (3972,)
2019-07-23 11:41:22,667 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,668 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:22,670 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,674 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,675 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,676 INFO sqlalchemy.engine.base.Engine (3973,)
2019-07-23 11:41:22,679 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,680 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')

2019-07-23 11:41:22,682 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,686 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,687 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,688 INFO sqlalchemy.engine.base.Engine (3974,)
2019-07-23 11:41:22,691 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,692 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:22,694 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,699 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,700 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,701 INFO sqlalchemy.engine.base.Engine (3975,)
2019-07-23 11:41:22,705 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,706 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:41:22,709 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,712 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,714 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,714 INFO sqlalchemy.engine.base.Engine (3976,)
2019-07-23 11:41:22,718 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,719 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:22,721 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,725 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,727 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,728 INFO sqlalchemy.engine.base.Engine (3977,)
2019-07-23 11:41:22,732 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,733 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:41:22,735 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,739 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,741 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,742 INFO sqlalchemy.engine.base.Engine (3978,)
2019-07-23 11:41:22,745 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,747 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:22,748 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,753 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,755 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,756 INFO sqlalchemy.engine.base.Engine (3979,)
2019-07-23 11:41:22,759 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,760 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:22,762 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,767 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,768 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,768 INFO sqlalchemy.engine.base.Engine (3980,)
2019-07-23 11:41:22,772 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,773 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:22,775 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,779 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,781 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,782 INFO sqlalchemy.engine.base.Engine (3981,)
2019-07-23 11:41:22,785 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,785 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:22,787 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,792 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,793 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,794 INFO sqlalchemy.engine.base.Engine (3982,)
2019-07-23 11:41:22,798 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,799 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:41:22,802 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,806 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,807 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,809 INFO sqlalchemy.engine.base.Engine (3983,)
2019-07-23 11:41:22,812 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,812 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:41:22,815 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,819 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,820 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,821 INFO sqlalchemy.engine.base.Engine (3984,)
2019-07-23 11:41:22,824 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,825 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:22,828 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,832 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,833 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:22,834 INFO sqlalchemy.engine.base.Engine (3985,)
2019-07-23 11:41:22,836 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,837 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:22,840 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,845 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,846 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,847 INFO sqlalchemy.engine.base.Engine (3986,)
2019-07-23 11:41:22,850 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,852 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:22,853 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,857 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,859 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,859 INFO sqlalchemy.engine.base.Engine (3987,)
2019-07-23 11:41:22,863 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,863 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:22,866 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,869 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,871 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,871 INFO sqlalchemy.engine.base.Engine (3988,)
2019-07-23 11:41:22,875 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:22,876 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:22,878 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:22,882 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:22,883 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:22,884 INFO sqlalchemy.engine.base.Engine (3989,)
http://sz.ganji.com/zufang/pn15 status: 200
2019-07-23 11:41:23,857 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:23,857 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:41:23,860 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,864 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,865 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,865 INFO sqlalchemy.engine.base.Engine (3990,)
2019-07-23 11:41:23,868 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:23,869 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:41:23,871 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,875 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,876 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,877 INFO sqlalchemy.engine.base.Engine (3991,)
2019-07-23 11:41:23,881 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:23,882 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:41:23,884 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,888 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,889 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,890 INFO sqlalchemy.engine.base.Engine (3992,)
2019-07-23 11:41:23,893 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:23,894 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:41:23,897 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,900 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,901 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,902 INFO sqlalchemy.engine.base.Engine (3993,)
2019-07-23 11:41:23,905 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:23,906 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:41:23,908 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,911 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,912 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,913 INFO sqlalchemy.engine.base.Engine (3994,)
2019-07-23 11:41:23,916 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:23,917 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:41:23,919 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,922 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,923 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,924 INFO sqlalchemy.engine.base.Engine (3995,)
2019-07-23 11:41:23,928 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:23,929 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:41:23,931 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,935 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,936 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,937 INFO sqlalchemy.engine.base.Engine (3996,)
2019-07-23 11:41:23,941 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:23,942 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:23,944 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,948 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,949 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,950 INFO sqlalchemy.engine.base.Engine (3997,)
2019-07-23 11:41:23,952 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:23,953 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:41:23,955 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,959 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,960 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,961 INFO sqlalchemy.engine.base.Engine (3998,)
2019-07-23 11:41:23,964 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:23,965 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:23,967 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,970 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,972 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,972 INFO sqlalchemy.engine.base.Engine (3999,)
2019-07-23 11:41:23,975 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:23,975 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:41:23,978 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,982 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,983 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,984 INFO sqlalchemy.engine.base.Engine (4000,)
2019-07-23 11:41:23,987 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:23,988 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:41:23,990 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:23,994 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:23,995 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:23,996 INFO sqlalchemy.engine.base.Engine (4001,)
2019-07-23 11:41:23,999 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,000 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:41:24,001 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,006 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,007 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,008 INFO sqlalchemy.engine.base.Engine (4002,)
2019-07-23 11:41:24,011 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,012 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:41:24,014 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,018 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,019 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,020 INFO sqlalchemy.engine.base.Engine (4003,)
2019-07-23 11:41:24,024 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,025 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:41:24,028 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,032 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,034 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,035 INFO sqlalchemy.engine.base.Engine (4004,)
2019-07-23 11:41:24,038 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,039 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:41:24,041 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,045 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,046 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,047 INFO sqlalchemy.engine.base.Engine (4005,)
2019-07-23 11:41:24,050 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,050 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:41:24,052 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,056 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,058 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,058 INFO sqlalchemy.engine.base.Engine (4006,)
2019-07-23 11:41:24,062 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,063 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:41:24,065 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,068 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,069 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,070 INFO sqlalchemy.engine.base.Engine (4007,)
2019-07-23 11:41:24,074 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,075 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:41:24,077 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:24,080 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,082 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,082 INFO sqlalchemy.engine.base.Engine (4008,)
2019-07-23 11:41:24,086 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,086 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:41:24,089 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,092 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,093 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,094 INFO sqlalchemy.engine.base.Engine (4009,)
2019-07-23 11:41:24,097 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,097 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:41:24,100 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,104 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,105 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,106 INFO sqlalchemy.engine.base.Engine (4010,)
2019-07-23 11:41:24,109 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,110 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:41:24,112 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,115 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,116 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,118 INFO sqlalchemy.engine.base.Engine (4011,)
2019-07-23 11:41:24,120 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,121 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:41:24,123 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,127 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,128 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,128 INFO sqlalchemy.engine.base.Engine (4012,)
2019-07-23 11:41:24,131 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,132 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:41:24,134 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,138 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,139 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,140 INFO sqlalchemy.engine.base.Engine (4013,)
2019-07-23 11:41:24,143 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,144 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:41:24,147 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,150 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,151 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,152 INFO sqlalchemy.engine.base.Engine (4014,)
2019-07-23 11:41:24,155 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,156 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:41:24,158 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,162 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,163 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,163 INFO sqlalchemy.engine.base.Engine (4015,)
2019-07-23 11:41:24,167 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,167 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:24,169 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,173 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,174 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,175 INFO sqlalchemy.engine.base.Engine (4016,)
2019-07-23 11:41:24,177 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,178 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:41:24,181 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,184 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,185 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,186 INFO sqlalchemy.engine.base.Engine (4017,)
2019-07-23 11:41:24,189 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,190 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:24,192 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,196 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,197 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,197 INFO sqlalchemy.engine.base.Engine (4018,)
2019-07-23 11:41:24,201 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,201 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:24,204 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,207 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,208 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:24,209 INFO sqlalchemy.engine.base.Engine (4019,)
2019-07-23 11:41:24,212 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,213 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:24,215 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,219 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,220 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,221 INFO sqlalchemy.engine.base.Engine (4020,)
2019-07-23 11:41:24,223 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,224 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:24,226 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,230 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,231 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,232 INFO sqlalchemy.engine.base.Engine (4021,)
2019-07-23 11:41:24,235 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,236 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:24,237 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,241 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,242 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,243 INFO sqlalchemy.engine.base.Engine (4022,)
2019-07-23 11:41:24,247 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,248 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:24,250 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,253 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,254 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,255 INFO sqlalchemy.engine.base.Engine (4023,)
2019-07-23 11:41:24,258 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,259 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:24,261 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,265 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,266 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,267 INFO sqlalchemy.engine.base.Engine (4024,)
2019-07-23 11:41:24,269 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,270 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:24,272 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,276 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,277 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,278 INFO sqlalchemy.engine.base.Engine (4025,)
2019-07-23 11:41:24,282 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,284 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:24,287 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,291 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,292 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,293 INFO sqlalchemy.engine.base.Engine (4026,)
2019-07-23 11:41:24,297 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,298 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:41:24,301 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,308 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,311 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,312 INFO sqlalchemy.engine.base.Engine (4027,)
2019-07-23 11:41:24,315 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,316 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:24,318 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,322 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,323 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,324 INFO sqlalchemy.engine.base.Engine (4028,)
2019-07-23 11:41:24,326 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,327 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:24,330 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,333 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,334 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,336 INFO sqlalchemy.engine.base.Engine (4029,)
2019-07-23 11:41:24,339 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,340 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:41:24,343 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,347 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,349 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,349 INFO sqlalchemy.engine.base.Engine (4030,)
2019-07-23 11:41:24,352 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,353 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')

2019-07-23 11:41:24,355 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,358 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,360 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,361 INFO sqlalchemy.engine.base.Engine (4031,)
2019-07-23 11:41:24,364 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,365 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:24,366 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,370 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,371 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,372 INFO sqlalchemy.engine.base.Engine (4032,)
2019-07-23 11:41:24,375 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,376 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:24,378 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,382 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,383 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,384 INFO sqlalchemy.engine.base.Engine (4033,)
2019-07-23 11:41:24,388 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,389 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:24,391 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,394 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,395 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,396 INFO sqlalchemy.engine.base.Engine (4034,)
2019-07-23 11:41:24,400 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,400 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:24,402 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,406 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,407 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,408 INFO sqlalchemy.engine.base.Engine (4035,)
2019-07-23 11:41:24,410 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,411 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:24,414 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,417 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,419 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,419 INFO sqlalchemy.engine.base.Engine (4036,)
2019-07-23 11:41:24,422 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,423 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:24,425 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,430 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,431 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,432 INFO sqlalchemy.engine.base.Engine (4037,)
2019-07-23 11:41:24,435 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,436 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:24,438 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,442 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,443 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,444 INFO sqlalchemy.engine.base.Engine (4038,)
2019-07-23 11:41:24,448 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,449 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:24,452 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,457 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,458 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,459 INFO sqlalchemy.engine.base.Engine (4039,)
2019-07-23 11:41:24,463 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,463 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:24,465 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,468 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,469 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,470 INFO sqlalchemy.engine.base.Engine (4040,)
2019-07-23 11:41:24,473 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,474 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:24,476 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,479 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,480 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,481 INFO sqlalchemy.engine.base.Engine (4041,)
2019-07-23 11:41:24,484 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,485 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:24,487 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,491 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,492 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:24,493 INFO sqlalchemy.engine.base.Engine (4042,)
2019-07-23 11:41:24,496 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,497 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:24,499 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,504 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,505 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,505 INFO sqlalchemy.engine.base.Engine (4043,)
2019-07-23 11:41:24,509 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,510 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:24,513 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,517 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,518 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,519 INFO sqlalchemy.engine.base.Engine (4044,)
2019-07-23 11:41:24,522 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,523 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:24,526 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,529 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,530 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,531 INFO sqlalchemy.engine.base.Engine (4045,)
2019-07-23 11:41:24,535 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,536 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:24,538 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,542 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,543 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,544 INFO sqlalchemy.engine.base.Engine (4046,)
2019-07-23 11:41:24,547 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,548 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:24,551 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,555 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,557 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,558 INFO sqlalchemy.engine.base.Engine (4047,)
2019-07-23 11:41:24,562 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,563 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:24,564 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,568 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,569 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,570 INFO sqlalchemy.engine.base.Engine (4048,)
2019-07-23 11:41:24,573 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,574 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:24,577 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,581 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,582 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,583 INFO sqlalchemy.engine.base.Engine (4049,)
2019-07-23 11:41:24,586 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,587 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:41:24,590 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,594 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,595 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,596 INFO sqlalchemy.engine.base.Engine (4050,)
2019-07-23 11:41:24,600 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,601 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:24,604 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,607 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,608 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,609 INFO sqlalchemy.engine.base.Engine (4051,)
2019-07-23 11:41:24,612 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,613 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:24,615 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,618 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,619 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,620 INFO sqlalchemy.engine.base.Engine (4052,)
2019-07-23 11:41:24,623 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,625 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:41:24,628 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,632 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,633 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,634 INFO sqlalchemy.engine.base.Engine (4053,)
2019-07-23 11:41:24,637 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,638 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')

2019-07-23 11:41:24,640 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,643 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,644 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,645 INFO sqlalchemy.engine.base.Engine (4054,)
2019-07-23 11:41:24,648 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,649 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:24,652 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,656 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,657 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,657 INFO sqlalchemy.engine.base.Engine (4055,)
2019-07-23 11:41:24,661 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,662 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:24,664 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,668 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,670 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,671 INFO sqlalchemy.engine.base.Engine (4056,)
2019-07-23 11:41:24,674 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,675 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:24,677 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,681 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,682 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,683 INFO sqlalchemy.engine.base.Engine (4057,)
2019-07-23 11:41:24,686 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,687 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:24,689 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,693 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,694 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,695 INFO sqlalchemy.engine.base.Engine (4058,)
2019-07-23 11:41:24,698 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,699 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:24,702 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,705 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,706 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,707 INFO sqlalchemy.engine.base.Engine (4059,)
2019-07-23 11:41:24,711 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,712 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:24,714 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,719 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,720 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,721 INFO sqlalchemy.engine.base.Engine (4060,)
2019-07-23 11:41:24,725 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,725 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:24,728 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,732 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,733 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,734 INFO sqlalchemy.engine.base.Engine (4061,)
2019-07-23 11:41:24,738 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,739 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:24,741 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,745 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,747 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,747 INFO sqlalchemy.engine.base.Engine (4062,)
2019-07-23 11:41:24,750 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,751 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:24,753 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,757 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,758 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,759 INFO sqlalchemy.engine.base.Engine (4063,)
2019-07-23 11:41:24,763 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,765 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:24,766 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,770 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,771 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,772 INFO sqlalchemy.engine.base.Engine (4064,)
2019-07-23 11:41:24,776 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,776 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:24,779 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,782 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,784 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:24,785 INFO sqlalchemy.engine.base.Engine (4065,)
2019-07-23 11:41:24,789 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,790 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:24,793 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,796 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,797 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,798 INFO sqlalchemy.engine.base.Engine (4066,)
2019-07-23 11:41:24,801 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,801 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:24,804 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,809 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,810 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,811 INFO sqlalchemy.engine.base.Engine (4067,)
2019-07-23 11:41:24,814 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,815 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:24,818 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,822 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,823 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,823 INFO sqlalchemy.engine.base.Engine (4068,)
2019-07-23 11:41:24,828 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,829 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:24,831 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,836 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,837 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,838 INFO sqlalchemy.engine.base.Engine (4069,)
2019-07-23 11:41:24,841 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,842 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:24,844 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,849 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,850 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,851 INFO sqlalchemy.engine.base.Engine (4070,)
2019-07-23 11:41:24,855 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,855 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:24,858 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,862 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,863 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,863 INFO sqlalchemy.engine.base.Engine (4071,)
2019-07-23 11:41:24,868 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,868 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:24,871 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,875 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,876 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,877 INFO sqlalchemy.engine.base.Engine (4072,)
2019-07-23 11:41:24,881 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,882 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:41:24,884 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,889 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,891 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,892 INFO sqlalchemy.engine.base.Engine (4073,)
2019-07-23 11:41:24,895 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,897 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:24,900 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,903 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,905 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,905 INFO sqlalchemy.engine.base.Engine (4074,)
2019-07-23 11:41:24,909 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,909 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:24,913 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,917 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,918 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,919 INFO sqlalchemy.engine.base.Engine (4075,)
2019-07-23 11:41:24,922 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,923 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:24,926 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,929 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,931 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,932 INFO sqlalchemy.engine.base.Engine (4076,)
2019-07-23 11:41:24,935 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,937 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')

2019-07-23 11:41:24,939 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,944 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,946 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,946 INFO sqlalchemy.engine.base.Engine (4077,)
2019-07-23 11:41:24,950 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,951 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:24,953 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,957 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,958 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,959 INFO sqlalchemy.engine.base.Engine (4078,)
2019-07-23 11:41:24,963 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,963 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:24,965 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,969 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,970 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,971 INFO sqlalchemy.engine.base.Engine (4079,)
2019-07-23 11:41:24,975 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,976 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:24,978 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,982 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,983 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,984 INFO sqlalchemy.engine.base.Engine (4080,)
2019-07-23 11:41:24,988 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:24,989 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:24,991 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:24,995 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:24,997 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:24,997 INFO sqlalchemy.engine.base.Engine (4081,)
2019-07-23 11:41:25,001 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,002 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:25,004 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,008 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,009 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,010 INFO sqlalchemy.engine.base.Engine (4082,)
2019-07-23 11:41:25,014 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,015 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:25,017 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,021 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,023 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,024 INFO sqlalchemy.engine.base.Engine (4083,)
2019-07-23 11:41:25,027 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,028 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:25,031 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,034 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,035 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,036 INFO sqlalchemy.engine.base.Engine (4084,)
2019-07-23 11:41:25,040 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,041 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:25,043 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,048 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,049 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,050 INFO sqlalchemy.engine.base.Engine (4085,)
2019-07-23 11:41:25,054 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,055 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:41:25,058 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,061 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,062 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,063 INFO sqlalchemy.engine.base.Engine (4086,)
2019-07-23 11:41:25,066 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,067 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:41:25,069 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,073 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,075 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,076 INFO sqlalchemy.engine.base.Engine (4087,)
2019-07-23 11:41:25,080 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,081 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:25,085 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,088 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,089 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:25,090 INFO sqlalchemy.engine.base.Engine (4088,)
2019-07-23 11:41:25,093 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,094 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:25,097 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,102 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,103 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,104 INFO sqlalchemy.engine.base.Engine (4089,)
2019-07-23 11:41:25,108 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,109 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:41:25,112 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,116 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,117 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,118 INFO sqlalchemy.engine.base.Engine (4090,)
2019-07-23 11:41:25,121 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,122 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:25,124 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,129 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,130 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,131 INFO sqlalchemy.engine.base.Engine (4091,)
2019-07-23 11:41:25,135 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,136 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:41:25,138 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,144 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,146 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,147 INFO sqlalchemy.engine.base.Engine (4092,)
2019-07-23 11:41:25,152 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,153 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:25,155 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,159 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,160 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,161 INFO sqlalchemy.engine.base.Engine (4093,)
2019-07-23 11:41:25,164 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,165 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:25,167 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,171 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,173 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,173 INFO sqlalchemy.engine.base.Engine (4094,)
2019-07-23 11:41:25,177 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,178 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:25,181 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,185 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,186 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,187 INFO sqlalchemy.engine.base.Engine (4095,)
2019-07-23 11:41:25,191 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,192 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:41:25,194 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,199 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,200 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,201 INFO sqlalchemy.engine.base.Engine (4096,)
2019-07-23 11:41:25,204 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,205 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:25,207 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,212 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,213 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,214 INFO sqlalchemy.engine.base.Engine (4097,)
2019-07-23 11:41:25,218 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,219 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:25,221 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,225 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,227 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,227 INFO sqlalchemy.engine.base.Engine (4098,)
2019-07-23 11:41:25,231 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,233 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:41:25,235 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,240 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,241 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,242 INFO sqlalchemy.engine.base.Engine (4099,)
2019-07-23 11:41:25,247 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,248 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')

2019-07-23 11:41:25,250 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,254 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,255 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,256 INFO sqlalchemy.engine.base.Engine (4100,)
2019-07-23 11:41:25,259 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,260 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:25,262 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,266 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,268 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,269 INFO sqlalchemy.engine.base.Engine (4101,)
2019-07-23 11:41:25,273 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,274 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:25,277 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,282 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,283 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,284 INFO sqlalchemy.engine.base.Engine (4102,)
2019-07-23 11:41:25,288 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,289 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:25,291 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,295 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,296 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,297 INFO sqlalchemy.engine.base.Engine (4103,)
2019-07-23 11:41:25,302 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,303 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:25,305 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,309 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,310 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,311 INFO sqlalchemy.engine.base.Engine (4104,)
2019-07-23 11:41:25,315 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,316 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:25,319 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,322 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,324 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,325 INFO sqlalchemy.engine.base.Engine (4105,)
2019-07-23 11:41:25,329 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,330 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:25,332 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,337 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,338 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,339 INFO sqlalchemy.engine.base.Engine (4106,)
2019-07-23 11:41:25,343 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,344 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:25,346 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,351 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,352 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,353 INFO sqlalchemy.engine.base.Engine (4107,)
2019-07-23 11:41:25,356 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,357 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:25,359 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,363 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,365 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,366 INFO sqlalchemy.engine.base.Engine (4108,)
2019-07-23 11:41:25,369 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,371 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:41:25,372 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,377 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,378 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,378 INFO sqlalchemy.engine.base.Engine (4109,)
2019-07-23 11:41:25,383 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,384 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:41:25,386 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,390 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,392 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,393 INFO sqlalchemy.engine.base.Engine (4110,)
2019-07-23 11:41:25,397 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,397 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:25,399 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,403 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,405 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:25,405 INFO sqlalchemy.engine.base.Engine (4111,)
2019-07-23 11:41:25,409 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,410 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:25,413 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,417 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,419 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,420 INFO sqlalchemy.engine.base.Engine (4112,)
2019-07-23 11:41:25,423 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,424 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:41:25,427 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,431 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,432 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,433 INFO sqlalchemy.engine.base.Engine (4113,)
2019-07-23 11:41:25,436 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,438 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:25,439 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,443 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,445 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,445 INFO sqlalchemy.engine.base.Engine (4114,)
2019-07-23 11:41:25,449 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,450 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:41:25,453 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,457 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,458 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,459 INFO sqlalchemy.engine.base.Engine (4115,)
2019-07-23 11:41:25,463 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,464 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:25,467 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,471 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,472 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,473 INFO sqlalchemy.engine.base.Engine (4116,)
2019-07-23 11:41:25,476 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,478 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:41:25,480 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,484 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,486 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,487 INFO sqlalchemy.engine.base.Engine (4117,)
2019-07-23 11:41:25,489 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,490 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:25,493 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,496 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,498 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,499 INFO sqlalchemy.engine.base.Engine (4118,)
2019-07-23 11:41:25,503 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,504 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:25,506 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,510 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,511 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,512 INFO sqlalchemy.engine.base.Engine (4119,)
2019-07-23 11:41:25,516 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,517 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:25,519 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,523 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,524 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,525 INFO sqlalchemy.engine.base.Engine (4120,)
2019-07-23 11:41:25,529 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,530 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:25,532 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,536 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,538 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,538 INFO sqlalchemy.engine.base.Engine (4121,)
2019-07-23 11:41:25,542 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,543 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:41:25,547 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,551 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,552 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,553 INFO sqlalchemy.engine.base.Engine (4122,)
2019-07-23 11:41:25,556 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,558 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')

2019-07-23 11:41:25,560 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,565 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,567 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,567 INFO sqlalchemy.engine.base.Engine (4123,)
2019-07-23 11:41:25,572 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,572 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:25,574 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,578 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,579 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,580 INFO sqlalchemy.engine.base.Engine (4124,)
2019-07-23 11:41:25,585 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,586 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:25,589 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,593 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,594 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,595 INFO sqlalchemy.engine.base.Engine (4125,)
2019-07-23 11:41:25,599 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,600 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:25,602 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,607 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,608 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,609 INFO sqlalchemy.engine.base.Engine (4126,)
2019-07-23 11:41:25,613 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,613 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:25,616 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,621 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,622 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,623 INFO sqlalchemy.engine.base.Engine (4127,)
2019-07-23 11:41:25,626 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:25,627 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:25,631 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:25,635 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:25,637 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:25,638 INFO sqlalchemy.engine.base.Engine (4128,)
http://sz.ganji.com/zufang/pn16 status: 200
2019-07-23 11:41:26,803 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,804 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:41:26,807 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,811 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,812 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,813 INFO sqlalchemy.engine.base.Engine (4129,)
2019-07-23 11:41:26,817 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,818 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:41:26,820 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,826 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,828 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,829 INFO sqlalchemy.engine.base.Engine (4130,)
2019-07-23 11:41:26,835 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,836 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:41:26,839 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,844 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,846 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,847 INFO sqlalchemy.engine.base.Engine (4131,)
2019-07-23 11:41:26,850 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,851 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:41:26,854 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,859 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,860 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,861 INFO sqlalchemy.engine.base.Engine (4132,)
2019-07-23 11:41:26,865 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,866 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')
2019-07-23 11:41:26,869 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,875 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,876 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,877 INFO sqlalchemy.engine.base.Engine (4133,)
2019-07-23 11:41:26,881 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,882 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:41:26,886 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,890 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,892 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:26,893 INFO sqlalchemy.engine.base.Engine (4134,)
2019-07-23 11:41:26,897 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,898 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:41:26,899 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,903 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,904 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,905 INFO sqlalchemy.engine.base.Engine (4135,)
2019-07-23 11:41:26,910 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,911 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:26,913 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,917 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,918 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,919 INFO sqlalchemy.engine.base.Engine (4136,)
2019-07-23 11:41:26,923 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,924 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:41:26,925 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,930 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,932 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,933 INFO sqlalchemy.engine.base.Engine (4137,)
2019-07-23 11:41:26,937 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,938 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:26,941 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,946 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,947 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,948 INFO sqlalchemy.engine.base.Engine (4138,)
2019-07-23 11:41:26,952 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,953 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:41:26,956 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,959 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,961 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,961 INFO sqlalchemy.engine.base.Engine (4139,)
2019-07-23 11:41:26,965 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,966 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:41:26,969 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,972 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,974 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,974 INFO sqlalchemy.engine.base.Engine (4140,)
2019-07-23 11:41:26,979 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,980 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:41:26,982 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:26,987 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:26,988 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:26,989 INFO sqlalchemy.engine.base.Engine (4141,)
2019-07-23 11:41:26,993 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:26,994 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:41:26,998 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,002 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,003 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,004 INFO sqlalchemy.engine.base.Engine (4142,)
2019-07-23 11:41:27,008 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,010 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:41:27,013 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,019 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,021 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,022 INFO sqlalchemy.engine.base.Engine (4143,)
2019-07-23 11:41:27,026 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,027 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:41:27,029 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,035 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,037 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,038 INFO sqlalchemy.engine.base.Engine (4144,)
2019-07-23 11:41:27,042 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,044 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:41:27,047 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,054 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,056 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,058 INFO sqlalchemy.engine.base.Engine (4145,)
2019-07-23 11:41:27,061 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,063 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')

2019-07-23 11:41:27,065 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,072 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,073 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,074 INFO sqlalchemy.engine.base.Engine (4146,)
2019-07-23 11:41:27,080 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,081 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:41:27,085 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,090 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,091 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,093 INFO sqlalchemy.engine.base.Engine (4147,)
2019-07-23 11:41:27,097 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,098 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:41:27,101 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,106 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,108 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,109 INFO sqlalchemy.engine.base.Engine (4148,)
2019-07-23 11:41:27,112 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,113 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:41:27,116 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,120 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,121 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,123 INFO sqlalchemy.engine.base.Engine (4149,)
2019-07-23 11:41:27,126 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,128 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:41:27,130 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,136 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,137 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,139 INFO sqlalchemy.engine.base.Engine (4150,)
2019-07-23 11:41:27,143 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,145 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:41:27,147 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,152 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,153 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,155 INFO sqlalchemy.engine.base.Engine (4151,)
2019-07-23 11:41:27,158 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,159 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:41:27,162 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,166 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,168 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,168 INFO sqlalchemy.engine.base.Engine (4152,)
2019-07-23 11:41:27,173 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,174 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:41:27,176 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,181 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,183 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,184 INFO sqlalchemy.engine.base.Engine (4153,)
2019-07-23 11:41:27,189 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,191 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:41:27,194 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,199 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,200 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,201 INFO sqlalchemy.engine.base.Engine (4154,)
2019-07-23 11:41:27,204 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,205 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:27,207 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,212 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,213 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,214 INFO sqlalchemy.engine.base.Engine (4155,)
2019-07-23 11:41:27,219 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,220 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')
2019-07-23 11:41:27,221 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,226 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,228 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,230 INFO sqlalchemy.engine.base.Engine (4156,)
2019-07-23 11:41:27,234 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,235 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:27,238 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,243 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,244 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental

WHERE rental.id = ?
2019-07-23 11:41:27,246 INFO sqlalchemy.engine.base.Engine (4157,)
2019-07-23 11:41:27,250 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,250 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:27,253 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,258 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,259 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,260 INFO sqlalchemy.engine.base.Engine (4158,)
2019-07-23 11:41:27,264 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,265 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:27,268 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,273 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,275 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,276 INFO sqlalchemy.engine.base.Engine (4159,)
2019-07-23 11:41:27,281 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,282 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:27,285 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,289 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,290 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,291 INFO sqlalchemy.engine.base.Engine (4160,)
2019-07-23 11:41:27,294 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,295 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:27,297 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,303 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,304 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,305 INFO sqlalchemy.engine.base.Engine (4161,)
2019-07-23 11:41:27,310 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,311 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:27,312 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,318 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,319 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,319 INFO sqlalchemy.engine.base.Engine (4162,)
2019-07-23 11:41:27,323 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,324 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:27,328 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,333 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,334 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,335 INFO sqlalchemy.engine.base.Engine (4163,)
2019-07-23 11:41:27,341 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,342 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:27,344 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,350 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,351 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,352 INFO sqlalchemy.engine.base.Engine (4164,)
2019-07-23 11:41:27,356 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,357 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:27,361 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,366 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,367 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,368 INFO sqlalchemy.engine.base.Engine (4165,)
2019-07-23 11:41:27,372 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,373 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:41:27,375 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,380 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,381 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,382 INFO sqlalchemy.engine.base.Engine (4166,)
2019-07-23 11:41:27,386 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,387 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:27,389 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,394 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,395 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,396 INFO sqlalchemy.engine.base.Engine (4167,)
2019-07-23 11:41:27,400 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,401 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:27,404 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,408 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,410 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,411 INFO sqlalchemy.engine.base.Engine (4168,)
2019-07-23 11:41:27,415 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:27,417 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:41:27,419 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,424 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,426 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,426 INFO sqlalchemy.engine.base.Engine (4169,)
2019-07-23 11:41:27,429 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,431 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:41:27,433 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,438 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,440 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,441 INFO sqlalchemy.engine.base.Engine (4170,)
2019-07-23 11:41:27,447 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,449 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:27,452 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,458 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,460 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,461 INFO sqlalchemy.engine.base.Engine (4171,)
2019-07-23 11:41:27,466 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,466 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:27,470 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,474 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,475 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,476 INFO sqlalchemy.engine.base.Engine (4172,)
2019-07-23 11:41:27,480 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,482 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:27,484 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,490 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,492 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,493 INFO sqlalchemy.engine.base.Engine (4173,)
2019-07-23 11:41:27,498 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,499 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:27,502 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,508 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,509 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,510 INFO sqlalchemy.engine.base.Engine (4174,)
2019-07-23 11:41:27,515 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,516 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:27,519 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,524 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,525 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,526 INFO sqlalchemy.engine.base.Engine (4175,)
2019-07-23 11:41:27,531 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,532 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:27,535 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,539 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,540 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,542 INFO sqlalchemy.engine.base.Engine (4176,)
2019-07-23 11:41:27,546 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,547 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:27,550 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,555 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,557 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,558 INFO sqlalchemy.engine.base.Engine (4177,)
2019-07-23 11:41:27,562 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,563 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:27,566 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,572 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,574 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,575 INFO sqlalchemy.engine.base.Engine (4178,)
2019-07-23 11:41:27,580 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,581 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:27,583 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,588 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,590 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,591 INFO sqlalchemy.engine.base.Engine (4179,)
2019-07-23 11:41:27,595 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,596 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:27,600 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:27,605 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,606 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,607 INFO sqlalchemy.engine.base.Engine (4180,)
2019-07-23 11:41:27,611 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,613 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:27,616 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,621 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,623 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,624 INFO sqlalchemy.engine.base.Engine (4181,)
2019-07-23 11:41:27,629 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,630 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:27,633 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,638 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,640 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,641 INFO sqlalchemy.engine.base.Engine (4182,)
2019-07-23 11:41:27,645 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,647 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:27,650 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,655 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,657 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,658 INFO sqlalchemy.engine.base.Engine (4183,)
2019-07-23 11:41:27,662 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,663 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:27,665 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,671 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,673 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,674 INFO sqlalchemy.engine.base.Engine (4184,)
2019-07-23 11:41:27,677 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,679 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:27,681 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,687 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,689 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,690 INFO sqlalchemy.engine.base.Engine (4185,)
2019-07-23 11:41:27,694 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,695 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:27,697 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,702 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,703 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,704 INFO sqlalchemy.engine.base.Engine (4186,)
2019-07-23 11:41:27,707 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,708 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:27,712 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,717 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,718 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,719 INFO sqlalchemy.engine.base.Engine (4187,)
2019-07-23 11:41:27,723 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,724 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:27,726 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,731 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,733 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,734 INFO sqlalchemy.engine.base.Engine (4188,)
2019-07-23 11:41:27,737 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,738 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:41:27,740 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,745 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,747 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,749 INFO sqlalchemy.engine.base.Engine (4189,)
2019-07-23 11:41:27,752 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,753 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:27,756 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,760 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,761 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,762 INFO sqlalchemy.engine.base.Engine (4190,)
2019-07-23 11:41:27,766 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,767 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:27,770 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,775 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,776 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:27,777 INFO sqlalchemy.engine.base.Engine (4191,)
2019-07-23 11:41:27,782 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,783 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:41:27,786 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,791 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,792 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,793 INFO sqlalchemy.engine.base.Engine (4192,)
2019-07-23 11:41:27,797 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,798 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:27,801 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,807 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,809 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,810 INFO sqlalchemy.engine.base.Engine (4193,)
2019-07-23 11:41:27,814 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,816 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:27,819 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,824 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,826 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,827 INFO sqlalchemy.engine.base.Engine (4194,)
2019-07-23 11:41:27,830 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,831 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:27,834 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,839 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,840 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,841 INFO sqlalchemy.engine.base.Engine (4195,)
2019-07-23 11:41:27,846 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,847 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:27,850 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,853 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,855 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,855 INFO sqlalchemy.engine.base.Engine (4196,)
2019-07-23 11:41:27,859 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,860 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:27,862 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,866 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,868 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,869 INFO sqlalchemy.engine.base.Engine (4197,)
2019-07-23 11:41:27,874 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,875 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:27,877 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,882 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,883 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,885 INFO sqlalchemy.engine.base.Engine (4198,)
2019-07-23 11:41:27,889 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,890 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:27,893 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,899 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,900 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,901 INFO sqlalchemy.engine.base.Engine (4199,)
2019-07-23 11:41:27,906 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,907 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:27,910 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,916 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,918 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,920 INFO sqlalchemy.engine.base.Engine (4200,)
2019-07-23 11:41:27,924 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,925 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:27,927 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,933 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,935 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,936 INFO sqlalchemy.engine.base.Engine (4201,)
2019-07-23 11:41:27,941 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,942 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:27,944 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,949 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,951 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,952 INFO sqlalchemy.engine.base.Engine (4202,)
2019-07-23 11:41:27,956 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,957 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:27,959 INFO sqlalchemy.engine.base.Engine COMMIT

2019-07-23 11:41:27,965 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,966 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,968 INFO sqlalchemy.engine.base.Engine (4203,)
2019-07-23 11:41:27,974 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,975 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:27,978 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,983 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:27,985 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:27,986 INFO sqlalchemy.engine.base.Engine (4204,)
2019-07-23 11:41:27,990 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:27,991 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:27,993 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:27,999 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,001 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,002 INFO sqlalchemy.engine.base.Engine (4205,)
2019-07-23 11:41:28,007 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,009 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:28,012 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,018 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,020 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,022 INFO sqlalchemy.engine.base.Engine (4206,)
2019-07-23 11:41:28,027 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,028 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:28,030 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,036 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,037 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,039 INFO sqlalchemy.engine.base.Engine (4207,)
2019-07-23 11:41:28,044 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,045 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:28,048 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,054 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,055 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,056 INFO sqlalchemy.engine.base.Engine (4208,)
2019-07-23 11:41:28,061 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,062 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:28,065 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,071 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,072 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,074 INFO sqlalchemy.engine.base.Engine (4209,)
2019-07-23 11:41:28,078 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,079 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:28,084 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,088 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,089 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,090 INFO sqlalchemy.engine.base.Engine (4210,)
2019-07-23 11:41:28,096 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,097 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:28,099 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,105 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,107 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,109 INFO sqlalchemy.engine.base.Engine (4211,)
2019-07-23 11:41:28,113 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,115 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:41:28,118 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,123 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,125 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,126 INFO sqlalchemy.engine.base.Engine (4212,)
2019-07-23 11:41:28,130 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,130 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:28,133 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,138 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,140 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,141 INFO sqlalchemy.engine.base.Engine (4213,)
2019-07-23 11:41:28,145 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,146 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:28,149 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,155 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,157 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:28,158 INFO sqlalchemy.engine.base.Engine (4214,)
2019-07-23 11:41:28,161 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,162 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:28,165 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,171 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,172 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,173 INFO sqlalchemy.engine.base.Engine (4215,)
2019-07-23 11:41:28,178 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,179 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:41:28,181 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,185 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,186 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,187 INFO sqlalchemy.engine.base.Engine (4216,)
2019-07-23 11:41:28,191 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,192 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:28,196 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,201 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,202 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,203 INFO sqlalchemy.engine.base.Engine (4217,)
2019-07-23 11:41:28,208 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,210 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:28,213 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,218 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,219 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,220 INFO sqlalchemy.engine.base.Engine (4218,)
2019-07-23 11:41:28,226 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,227 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:28,238 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,245 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,247 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,248 INFO sqlalchemy.engine.base.Engine (4219,)
2019-07-23 11:41:28,254 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,256 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:28,258 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,266 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,268 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,269 INFO sqlalchemy.engine.base.Engine (4220,)
2019-07-23 11:41:28,275 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,277 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:28,282 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,288 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,290 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,291 INFO sqlalchemy.engine.base.Engine (4221,)
2019-07-23 11:41:28,296 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,298 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:28,301 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,307 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,309 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,311 INFO sqlalchemy.engine.base.Engine (4222,)
2019-07-23 11:41:28,316 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,317 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:28,319 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,325 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,326 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,328 INFO sqlalchemy.engine.base.Engine (4223,)
2019-07-23 11:41:28,333 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,334 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:28,337 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,343 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,344 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,346 INFO sqlalchemy.engine.base.Engine (4224,)
2019-07-23 11:41:28,350 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,352 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')
2019-07-23 11:41:28,355 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,361 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,363 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,364 INFO sqlalchemy.engine.base.Engine (4225,)
2019-07-23 11:41:28,367 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,369 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')

2019-07-23 11:41:28,373 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,377 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,379 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,380 INFO sqlalchemy.engine.base.Engine (4226,)
2019-07-23 11:41:28,384 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,385 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:28,389 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,394 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,396 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,398 INFO sqlalchemy.engine.base.Engine (4227,)
2019-07-23 11:41:28,402 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,404 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:28,414 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,418 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,420 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,421 INFO sqlalchemy.engine.base.Engine (4228,)
2019-07-23 11:41:28,426 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,427 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:41:28,430 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,435 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,436 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,437 INFO sqlalchemy.engine.base.Engine (4229,)
2019-07-23 11:41:28,441 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,442 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:28,446 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,450 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,452 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,453 INFO sqlalchemy.engine.base.Engine (4230,)
2019-07-23 11:41:28,457 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,458 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:41:28,461 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,465 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,467 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,468 INFO sqlalchemy.engine.base.Engine (4231,)
2019-07-23 11:41:28,473 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,475 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:28,478 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,482 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,484 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,485 INFO sqlalchemy.engine.base.Engine (4232,)
2019-07-23 11:41:28,488 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,489 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:28,492 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,498 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,500 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,501 INFO sqlalchemy.engine.base.Engine (4233,)
2019-07-23 11:41:28,505 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,506 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:28,510 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,514 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,516 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,517 INFO sqlalchemy.engine.base.Engine (4234,)
2019-07-23 11:41:28,522 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,523 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:41:28,526 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,531 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,533 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,534 INFO sqlalchemy.engine.base.Engine (4235,)
2019-07-23 11:41:28,538 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,539 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:28,541 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,547 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,549 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,550 INFO sqlalchemy.engine.base.Engine (4236,)
2019-07-23 11:41:28,556 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,557 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:28,560 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,566 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,568 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:28,569 INFO sqlalchemy.engine.base.Engine (4237,)
2019-07-23 11:41:28,573 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,575 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:41:28,578 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,585 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,587 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,588 INFO sqlalchemy.engine.base.Engine (4238,)
2019-07-23 11:41:28,593 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,595 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:41:28,603 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,611 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,613 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,615 INFO sqlalchemy.engine.base.Engine (4239,)
2019-07-23 11:41:28,618 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,619 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:28,622 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,628 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,629 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,630 INFO sqlalchemy.engine.base.Engine (4240,)
2019-07-23 11:41:28,634 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,636 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:28,638 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,644 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,646 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,647 INFO sqlalchemy.engine.base.Engine (4241,)
2019-07-23 11:41:28,652 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,653 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:28,656 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,662 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,663 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,665 INFO sqlalchemy.engine.base.Engine (4242,)
2019-07-23 11:41:28,670 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,671 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:28,675 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,680 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,682 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,683 INFO sqlalchemy.engine.base.Engine (4243,)
2019-07-23 11:41:28,687 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,689 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:28,692 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,698 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,700 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,701 INFO sqlalchemy.engine.base.Engine (4244,)
2019-07-23 11:41:28,706 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,706 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:28,708 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,715 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,717 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,718 INFO sqlalchemy.engine.base.Engine (4245,)
2019-07-23 11:41:28,722 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,724 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:28,727 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,733 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,735 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,736 INFO sqlalchemy.engine.base.Engine (4246,)
2019-07-23 11:41:28,739 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,741 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:28,744 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,751 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,753 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,754 INFO sqlalchemy.engine.base.Engine (4247,)
2019-07-23 11:41:28,759 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,760 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')
2019-07-23 11:41:28,763 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,769 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,770 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,772 INFO sqlalchemy.engine.base.Engine (4248,)
2019-07-23 11:41:28,777 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,779 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')

2019-07-23 11:41:28,782 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,787 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,789 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,790 INFO sqlalchemy.engine.base.Engine (4249,)
2019-07-23 11:41:28,795 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,796 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:28,800 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,807 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,809 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,810 INFO sqlalchemy.engine.base.Engine (4250,)
2019-07-23 11:41:28,816 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,818 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:28,821 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,827 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,828 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,830 INFO sqlalchemy.engine.base.Engine (4251,)
2019-07-23 11:41:28,834 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,836 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:41:28,839 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,845 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,847 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,848 INFO sqlalchemy.engine.base.Engine (4252,)
2019-07-23 11:41:28,852 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,854 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:28,856 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,863 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,865 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,866 INFO sqlalchemy.engine.base.Engine (4253,)
2019-07-23 11:41:28,871 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,873 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:41:28,876 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,882 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,883 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,885 INFO sqlalchemy.engine.base.Engine (4254,)
2019-07-23 11:41:28,890 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,891 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:28,894 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,900 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,902 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,903 INFO sqlalchemy.engine.base.Engine (4255,)
2019-07-23 11:41:28,907 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,909 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:41:28,914 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,920 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,922 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,923 INFO sqlalchemy.engine.base.Engine (4256,)
2019-07-23 11:41:28,928 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,930 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:28,934 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,943 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,945 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,947 INFO sqlalchemy.engine.base.Engine (4257,)
2019-07-23 11:41:28,954 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,955 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:28,960 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,966 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,968 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,969 INFO sqlalchemy.engine.base.Engine (4258,)
2019-07-23 11:41:28,973 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,974 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:28,978 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:28,985 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:28,987 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:28,988 INFO sqlalchemy.engine.base.Engine (4259,)
2019-07-23 11:41:28,994 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:28,996 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:29,000 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:29,006 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:29,008 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:29,010 INFO sqlalchemy.engine.base.Engine (4260,)
2019-07-23 11:41:29,015 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:29,016 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:41:29,019 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:29,027 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:29,029 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:29,030 INFO sqlalchemy.engine.base.Engine (4261,)
2019-07-23 11:41:29,034 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:29,036 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:41:29,040 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:29,047 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:29,049 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:29,050 INFO sqlalchemy.engine.base.Engine (4262,)
2019-07-23 11:41:29,055 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:29,057 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:29,061 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:29,067 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:29,069 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:29,070 INFO sqlalchemy.engine.base.Engine (4263,)
2019-07-23 11:41:29,075 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:29,076 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:29,079 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:29,088 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:29,090 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:29,092 INFO sqlalchemy.engine.base.Engine (4264,)
2019-07-23 11:41:29,101 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:29,102 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:29,106 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:29,112 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:29,114 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:29,115 INFO sqlalchemy.engine.base.Engine (4265,)
2019-07-23 11:41:29,122 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:29,123 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:29,127 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:29,133 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:29,134 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:29,136 INFO sqlalchemy.engine.base.Engine (4266,)
2019-07-23 11:41:29,141 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:29,143 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:29,147 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:29,155 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:29,157 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:29,158 INFO sqlalchemy.engine.base.Engine (4267,)
http://sz.ganji.com/zufang/pn17 status: 200
2019-07-23 11:41:30,165 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,166 INFO sqlalchemy.engine.base.Engine ('龙华大浪 房东直租  32平单间  豪华装修  全新家私家电', '850 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 文辉物业 - 桂小英')
2019-07-23 11:41:30,169 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,176 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,178 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,179 INFO sqlalchemy.engine.base.Engine (4268,)
2019-07-23 11:41:30,184 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,186 INFO sqlalchemy.engine.base.Engine ('碧桂园品牌公寓 青年白领社区 企业可优惠 家私齐全 停车方便', '850 元/月', '1室1厅1卫 15㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 贾万磊')
2019-07-23 11:41:30,191 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,199 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,201 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,202 INFO sqlalchemy.engine.base.Engine (4269,)
2019-07-23 11:41:30,208 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,209 INFO sqlalchemy.engine.base.Engine ('整租 龙华景乐市场附近 碧桂园碧国际社区 整租拎包入住', '1080 元/月', '1室1厅1卫 26㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 林佳达')
2019-07-23 11:41:30,213 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,218 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,221 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,222 INFO sqlalchemy.engine.base.Engine (4270,)
2019-07-23 11:41:30,228 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,229 INFO sqlalchemy.engine.base.Engine ('11号线马安山地铁，全新家私电器，全新公寓，交通方便', '1280 元/月', '1室0厅1卫 25㎡ 东南向 豪华装修', '来自经纪人： 前海租无忧物业 - 许锹纯')
2019-07-23 11:41:30,233 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,239 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,241 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,243 INFO sqlalchemy.engine.base.Engine (4271,)
2019-07-23 11:41:30,248 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,250 INFO sqlalchemy.engine.base.Engine ('华荣路，公交车站旁，大小单间拎包入住，停车方便，首月免租。', '1180 元/月', '1室0厅1卫 35㎡ 南向 精装修', '来自经纪人： 寓小二公寓 - 寓小二地产(深圳分行) - 杨宗盛')

2019-07-23 11:41:30,253 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,260 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,262 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,263 INFO sqlalchemy.engine.base.Engine (4272,)
2019-07-23 11:41:30,268 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,269 INFO sqlalchemy.engine.base.Engine ('龙华地铁可短租碧桂园直租 有车位家电网络齐全 精装修一房', '1100 元/月', '1室1厅1卫 37㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 蒋娟')
2019-07-23 11:41:30,273 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,280 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,282 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,285 INFO sqlalchemy.engine.base.Engine (4273,)
2019-07-23 11:41:30,289 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,291 INFO sqlalchemy.engine.base.Engine ('房东招租大单间一房一厅带家私家电独立厨卫押一付一拎包入住', '950 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 爱之家物业 - 江姚')
2019-07-23 11:41:30,294 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,302 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,304 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,305 INFO sqlalchemy.engine.base.Engine (4274,)
2019-07-23 11:41:30,312 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,313 INFO sqlalchemy.engine.base.Engine ('龙华大浪商业中心附近豪装公寓全新全配拎包入住（直租）', '1380 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:30,317 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,324 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,326 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,328 INFO sqlalchemy.engine.base.Engine (4275,)
2019-07-23 11:41:30,334 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,335 INFO sqlalchemy.engine.base.Engine ('塘尾品牌公寓[090House]温馨 年轻人的港湾！', '980 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 中际物业 - 汤发洋')
2019-07-23 11:41:30,338 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,346 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,348 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,349 INFO sqlalchemy.engine.base.Engine (4276,)
2019-07-23 11:41:30,354 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,356 INFO sqlalchemy.engine.base.Engine ('希林公寓龙华店公寓直租无中介拎包入住采光好交通便利华荣路', '1380 元/月', '1室0厅1卫 32㎡ 南向 豪华装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪31 - 桂敏翠')
2019-07-23 11:41:30,361 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,369 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,372 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,374 INFO sqlalchemy.engine.base.Engine (4277,)
2019-07-23 11:41:30,380 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,382 INFO sqlalchemy.engine.base.Engine ('4号线龙胜商圈，有一房一厅出租，租房还有惊喜哦', '1250 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 陶寓公寓 - 洪斌')
2019-07-23 11:41:30,386 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,393 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,396 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,397 INFO sqlalchemy.engine.base.Engine (4278,)
2019-07-23 11:41:30,403 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,405 INFO sqlalchemy.engine.base.Engine ('4号线龙华 清湖双地铁 汇海广场旁 南北通透 采光好大单间', '1100 元/月', '1室0厅1卫 20㎡ 东南向 精装修', '来自经纪人： 独立经纪人（龙华） - 廖哲')
2019-07-23 11:41:30,409 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,417 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,420 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,423 INFO sqlalchemy.engine.base.Engine (4279,)
2019-07-23 11:41:30,431 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,433 INFO sqlalchemy.engine.base.Engine ('11号线！看清楚！塘尾地铁口！塘尾地铁口！网红公寓1180元', '1180 元/月', '1室0厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 华越物业 - 杨耀建')
2019-07-23 11:41:30,436 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,442 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,444 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,447 INFO sqlalchemy.engine.base.Engine (4280,)
2019-07-23 11:41:30,452 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,454 INFO sqlalchemy.engine.base.Engine ('龙华地铁 暑假旅游旺季主播房 全新家电 拎包入住 长租有优惠', '1300 元/月', '1室1厅1卫 36㎡ 南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 左建民')
2019-07-23 11:41:30,457 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,463 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,466 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,467 INFO sqlalchemy.engine.base.Engine (4281,)
2019-07-23 11:41:30,472 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,474 INFO sqlalchemy.engine.base.Engine ('观澜章阁富士康北门，精装修公寓，一房一厅，拎包入住', '1280 元/月', '1室1厅1卫 43㎡ 东南向 精装修', '来自经纪人： 荣腾地产 - 荣腾地产章阁分行 - 成海华')
2019-07-23 11:41:30,478 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,485 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,487 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,488 INFO sqlalchemy.engine.base.Engine (4282,)
2019-07-23 11:41:30,494 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,496 INFO sqlalchemy.engine.base.Engine ('1号线单间，一房一厅配套齐全独立厨卫大阳台安全舒适交通便利', '1260 元/月', '1室0厅1卫 27㎡ 南向 精装修', '来自经纪人： 恒康物业 - 何登香')
2019-07-23 11:41:30,499 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,506 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,509 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:30,511 INFO sqlalchemy.engine.base.Engine (4283,)
2019-07-23 11:41:30,517 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,519 INFO sqlalchemy.engine.base.Engine ('房东直租 超值精装修拎包入住交通便利看房方便家私家电齐房东好', '730 元/月', '1室0厅1卫 25㎡ 南北向 精装修', '来自经纪人： 瑞驰物业 - 张迪飞')
2019-07-23 11:41:30,522 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,529 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,531 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,533 INFO sqlalchemy.engine.base.Engine (4284,)
2019-07-23 11:41:30,538 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,540 INFO sqlalchemy.engine.base.Engine ('固戍地铁站400米，精装修品牌公寓全天专人安保家电家私齐全', '1250 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 熊钰莹')
2019-07-23 11:41:30,543 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,551 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,553 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,555 INFO sqlalchemy.engine.base.Engine (4285,)
2019-07-23 11:41:30,561 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,563 INFO sqlalchemy.engine.base.Engine ('西乡固戍地铁口步行3分钟实图实价不喜勿扰', '1300 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： 心愿地产 - 心愿地产(固戍下围园分行) - 谢田')
2019-07-23 11:41:30,567 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,574 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,576 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,577 INFO sqlalchemy.engine.base.Engine (4286,)
2019-07-23 11:41:30,582 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,585 INFO sqlalchemy.engine.base.Engine ('单间，3号线丹竹头地铁站.超大单间，交通便利.房东直租..', '980 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： 御景豪庭公寓 - 姜波')
2019-07-23 11:41:30,589 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,596 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,598 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,599 INFO sqlalchemy.engine.base.Engine (4287,)
2019-07-23 11:41:30,606 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,608 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站 超高性价比单间1100大床家电全齐', '1100 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 亿信达物业管理有限公司 - 黄俊雅')
2019-07-23 11:41:30,611 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,619 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,621 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,623 INFO sqlalchemy.engine.base.Engine (4288,)
2019-07-23 11:41:30,629 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,631 INFO sqlalchemy.engine.base.Engine ('三联尚品公寓，房东直租，交通方便，拎包入住，全新家私家电，', '1300 元/月', '1室0厅1卫 30㎡ 东南向 精装修', '来自经纪人： 优尚公寓 - 余海霞')
2019-07-23 11:41:30,635 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,642 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,645 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,647 INFO sqlalchemy.engine.base.Engine (4289,)
2019-07-23 11:41:30,654 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,656 INFO sqlalchemy.engine.base.Engine ('业主直租！实拍！！！牛栏前大厦附近全新公寓！', '1380 元/月', '1室0厅1卫 25㎡ 东南向 精装修', '来自经纪人： - 王超')
2019-07-23 11:41:30,661 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,668 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,671 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,673 INFO sqlalchemy.engine.base.Engine (4290,)
2019-07-23 11:41:30,679 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,680 INFO sqlalchemy.engine.base.Engine ('微棠社区公寓 24h专属客服安全保卫 精装修拎包住居住省心', '1299 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 美好颂自如寓 - 愿景明创(上梅林分行) - 齐少昆')
2019-07-23 11:41:30,684 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,691 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,694 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,695 INFO sqlalchemy.engine.base.Engine (4291,)
2019-07-23 11:41:30,701 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,703 INFO sqlalchemy.engine.base.Engine ('实图实价 精装修大中小单间 家具家电齐 采光好 沙井核心商圈', '1200 元/月', '1室0厅1卫 22㎡ 南北向 豪华装修', '来自经纪人： 深圳独立经纪人 - 桂行太')
2019-07-23 11:41:30,707 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,714 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,716 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,718 INFO sqlalchemy.engine.base.Engine (4292,)
2019-07-23 11:41:30,725 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,727 INFO sqlalchemy.engine.base.Engine ('三围舒适大单间，欢迎来看房', '980 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 深圳市皇烁物业有限公司 - 黄磊')
2019-07-23 11:41:30,730 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,737 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,739 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,741 INFO sqlalchemy.engine.base.Engine (4293,)
2019-07-23 11:41:30,746 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,748 INFO sqlalchemy.engine.base.Engine ('忍者村 连锁的品牌公寓 押一付一 家电家具全配 高品质', '1500 元/月', '1室1厅1卫 40㎡ 南向 精装修', '来自经纪人： 朗诗寓公寓 - 朱植谊')
2019-07-23 11:41:30,751 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,757 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,759 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,761 INFO sqlalchemy.engine.base.Engine (4294,)
2019-07-23 11:41:30,766 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,768 INFO sqlalchemy.engine.base.Engine ('民治 1970小镇 八号仓旁 碧桂园白领公寓 拎包入住', '1500 元/月', '1室0厅1卫 26㎡ 东南向 豪华装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 肖虎')

2019-07-23 11:41:30,772 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,779 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,781 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,782 INFO sqlalchemy.engine.base.Engine (4295,)
2019-07-23 11:41:30,787 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,788 INFO sqlalchemy.engine.base.Engine ('无中芥 观澜大道 兴万达广场 观澜玫瑰苑 月付优惠租', '1380 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 朗诗寓公寓 - 李佳奇')
2019-07-23 11:41:30,792 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,798 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,800 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,801 INFO sqlalchemy.engine.base.Engine (4296,)
2019-07-23 11:41:30,807 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,809 INFO sqlalchemy.engine.base.Engine ('平湖直租房源!精装大套间出租!配套齐全干净舒适先到先得!', '1200 元/月', '1室0厅1卫 35㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(固戍分行) - 刘迪爱')
2019-07-23 11:41:30,813 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,818 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,820 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,821 INFO sqlalchemy.engine.base.Engine (4297,)
2019-07-23 11:41:30,827 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,828 INFO sqlalchemy.engine.base.Engine ('双龙地铁口 全新精装公寓，单间980元，全齐出租，免介绍费', '980 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 房行天下地产 - 刘利良')
2019-07-23 11:41:30,831 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,837 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,838 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,840 INFO sqlalchemy.engine.base.Engine (4298,)
2019-07-23 11:41:30,846 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,848 INFO sqlalchemy.engine.base.Engine ('龙城广场地铁站 宝龙小区 复式房 精装修 带家电', '1390 元/月', '1室1厅1卫 35㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 曾文华')
2019-07-23 11:41:30,852 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,858 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,860 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,862 INFO sqlalchemy.engine.base.Engine (4299,)
2019-07-23 11:41:30,867 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,868 INFO sqlalchemy.engine.base.Engine ('全新精装公寓招租家私家电齐全可拎包入住电梯房首.次招租', '1200 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 大合物业 - 徐文华')
2019-07-23 11:41:30,871 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,877 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,878 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,879 INFO sqlalchemy.engine.base.Engine (4300,)
2019-07-23 11:41:30,884 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,885 INFO sqlalchemy.engine.base.Engine ('离机场东地铁站较近 拎包入住 直租 采光好  精修公寓', '1100 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 黄晓薇')
2019-07-23 11:41:30,889 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,895 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,897 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,898 INFO sqlalchemy.engine.base.Engine (4301,)
2019-07-23 11:41:30,902 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,903 INFO sqlalchemy.engine.base.Engine ('1580秒杀固戍海滨新村精装公寓单间，直租无中介', '1580 元/月', '1室0厅1卫 28㎡ 南向 豪华装修', '来自经纪人： 招商置业 - 程常群')
2019-07-23 11:41:30,906 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,912 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,914 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,915 INFO sqlalchemy.engine.base.Engine (4302,)
2019-07-23 11:41:30,921 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,922 INFO sqlalchemy.engine.base.Engine ('急租！急租！丹竹头单间出租！配套齐全！拎包入住！非诚勿扰！！', '1380 元/月', '1室0厅1卫 18㎡ 南向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 赵瑞')
2019-07-23 11:41:30,925 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,931 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,933 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,935 INFO sqlalchemy.engine.base.Engine (4303,)
2019-07-23 11:41:30,940 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,942 INFO sqlalchemy.engine.base.Engine ('万科泊寓 交通便利 采光好通风好 带厨房  独立卫浴', '1037 元/月', '1室0厅1卫 25㎡ 南向 精装修', '来自经纪人： 泊寓租赁 - 张雲晏')
2019-07-23 11:41:30,946 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,951 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,953 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,954 INFO sqlalchemy.engine.base.Engine (4304,)
2019-07-23 11:41:30,960 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,962 INFO sqlalchemy.engine.base.Engine ('无中介 7月免租 免管理费 拎包入住南山科技园 5号线民治站', '1580 元/月', '1室1厅1卫 48㎡ 东南向 精装修', '来自经纪人： 深圳房产经纪 - 万振亚')
2019-07-23 11:41:30,966 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,971 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,972 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:30,974 INFO sqlalchemy.engine.base.Engine (4305,)
2019-07-23 11:41:30,978 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,979 INFO sqlalchemy.engine.base.Engine ('佳兆业白领公寓  8折大放送  押一付一  近地铁白石龙站', '1450 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： 佳兆业 - 陈观云')
2019-07-23 11:41:30,982 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:30,989 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:30,991 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:30,992 INFO sqlalchemy.engine.base.Engine (4306,)
2019-07-23 11:41:30,997 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:30,998 INFO sqlalchemy.engine.base.Engine ('一号线固戍地铁站采光一流海景房房间1400装修好格局好', '1400 元/月', '1室0厅1卫 26㎡ 南向 精装修', '来自经纪人： Z+逐梦空间 - Z+逐梦空间(洪浪北分行) - 修学龙')
2019-07-23 11:41:31,003 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,009 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,011 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,012 INFO sqlalchemy.engine.base.Engine (4307,)
2019-07-23 11:41:31,018 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,019 INFO sqlalchemy.engine.base.Engine ('南园枫叶公寓 全新装修 全新家私家电 近地铁口 周边配套齐全', '4800 元/月', '2室2厅1卫 66㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 裕丰地产鸿瑞分行 - 车轩')
2019-07-23 11:41:31,022 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,027 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,029 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,030 INFO sqlalchemy.engine.base.Engine (4308,)
2019-07-23 11:41:31,036 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,038 INFO sqlalchemy.engine.base.Engine ('东门 一品东门雅园 精装二房 看房有钥匙 近地铁站 东方颐园', '5500 元/月', '2室2厅1卫 65㎡ 东南向 精装修', '来自经纪人： 裕丰地产 - 深圳裕丰房地产销售代理有限公司(东门168分行) - 蒙奇')
2019-07-23 11:41:31,042 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,048 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,051 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,052 INFO sqlalchemy.engine.base.Engine (4309,)
2019-07-23 11:41:31,059 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,061 INFO sqlalchemy.engine.base.Engine ('蛇口壹栈公寓壹间 全新精装2房 带电，官网直租 免拥代理', '7288 元/月', '2室2厅1卫 72㎡ 南向 精装修', '来自经纪人： 深圳市华创房地产投资顾问有限公司 - 华创地产海韵嘉园分行 - 戴国龙')
2019-07-23 11:41:31,065 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,070 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,071 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,072 INFO sqlalchemy.engine.base.Engine (4310,)
2019-07-23 11:41:31,078 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,080 INFO sqlalchemy.engine.base.Engine ('南岭锦绣山庄高楼层光线超好价钱实惠', '3500 元/月', '3室2厅2卫 120㎡ 东北向 精装修', '来自经纪人： 家家世纪 - 家家世纪(南岭分行) - 刘波')
2019-07-23 11:41:31,083 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,090 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,092 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,093 INFO sqlalchemy.engine.base.Engine (4311,)
2019-07-23 11:41:31,099 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,100 INFO sqlalchemy.engine.base.Engine ('木棉湾站精装2包  拎包入住。8月1日可以住', '3600 元/月', '2室2厅1卫 75㎡ 东北向 精装修', '来自经纪人： Q房网 - Q房网茂业城分行 - 周春娣')
2019-07-23 11:41:31,103 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,108 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,110 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,111 INFO sqlalchemy.engine.base.Engine (4312,)
2019-07-23 11:41:31,116 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,117 INFO sqlalchemy.engine.base.Engine ('精装一房一厅，适合情侣居住，带家私家电，环境优雅，拎包入住', '1350 元/月', '1室0厅1卫 20㎡ 南北向 豪华装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:31,121 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,126 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,128 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,129 INFO sqlalchemy.engine.base.Engine (4313,)
2019-07-23 11:41:31,135 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,136 INFO sqlalchemy.engine.base.Engine ('深大附近精装两房，业主精装', '5800 元/月', '2室2厅0卫 38.04㎡ 南北向 简单装修', '来自经纪人： 乐有家地产 - 黄景崇')
2019-07-23 11:41:31,141 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,148 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,150 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,151 INFO sqlalchemy.engine.base.Engine (4314,)
2019-07-23 11:41:31,156 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,158 INFO sqlalchemy.engine.base.Engine ('五和地铁站B出口200米 大小单间一房一厅超大阳台 可短租', '1200 元/月', '1室0厅1卫 29㎡ 西北向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪22 - 周秀龙')
2019-07-23 11:41:31,160 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,166 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,168 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,169 INFO sqlalchemy.engine.base.Engine (4315,)
2019-07-23 11:41:31,174 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,176 INFO sqlalchemy.engine.base.Engine ('精装电梯公寓， 光线好， 家私家电齐，  大阳台，采光通风好', '1380 元/月', '1室0厅1卫 20㎡ 南北向 精装修', '来自经纪人： 蚂蚁物业 - 赖珍琼')
2019-07-23 11:41:31,179 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,188 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,190 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,192 INFO sqlalchemy.engine.base.Engine (4316,)
2019-07-23 11:41:31,198 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,200 INFO sqlalchemy.engine.base.Engine ('希尔顿酒店旁酒店式公寓 停车方便装修好 福田岗厦', '9000 元/月', '2室2厅1卫 81㎡ 东向 豪华装修', '来自经纪人： 美联物业 - 美联物业彩田分行 - 杨艳')
2019-07-23 11:41:31,204 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,210 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,211 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,213 INFO sqlalchemy.engine.base.Engine (4317,)
2019-07-23 11:41:31,218 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:31,219 INFO sqlalchemy.engine.base.Engine ('艺术大厦 2室2厅1卫', '3680 元/月', '2室2厅1卫 80㎡ 东南向', '来自个人房源：侯先生')
2019-07-23 11:41:31,223 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,229 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,231 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,233 INFO sqlalchemy.engine.base.Engine (4318,)
2019-07-23 11:41:31,240 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,242 INFO sqlalchemy.engine.base.Engine ('民治地铁站，全新私家，电梯房，随时看房，随时拎包入住免中费', '1280 元/月', '1室0厅1卫 28㎡ 西南向 精装修', '来自经纪人： 深圳房产经纪 - 深圳房产经纪60 - 兰雪雯')
2019-07-23 11:41:31,246 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,252 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,254 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,255 INFO sqlalchemy.engine.base.Engine (4319,)
2019-07-23 11:41:31,262 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,264 INFO sqlalchemy.engine.base.Engine ('龙东社区.单身情侣酒店式电梯公寓诚信招租.环境好带阳台好停车', '600 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 中润家物业 - 张政')
2019-07-23 11:41:31,268 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,273 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,275 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,276 INFO sqlalchemy.engine.base.Engine (4320,)
2019-07-23 11:41:31,282 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,284 INFO sqlalchemy.engine.base.Engine ('地铁11号线塘尾站（直达福永南山）配置齐全拎包入住', '680 元/月', '1室0厅1卫 21㎡ 南北向 精装修', '来自经纪人： - 燕钢')
2019-07-23 11:41:31,287 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,296 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,297 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,298 INFO sqlalchemy.engine.base.Engine (4321,)
2019-07-23 11:41:31,304 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,306 INFO sqlalchemy.engine.base.Engine ('直租 精装公寓 家私家电齐全  阳光大单间 干净卫生专人管理', '800 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： - 肖礼')
2019-07-23 11:41:31,309 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,315 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,317 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,318 INFO sqlalchemy.engine.base.Engine (4322,)
2019-07-23 11:41:31,325 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,328 INFO sqlalchemy.engine.base.Engine ('业主出租！全新精装复式公寓', '2500 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:31,332 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,339 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,341 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,343 INFO sqlalchemy.engine.base.Engine (4323,)
2019-07-23 11:41:31,349 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,351 INFO sqlalchemy.engine.base.Engine ('房东直租 康扬创客谷精装loft公寓，依山伴水，拎包入住', '1980 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 中润永利 - 姜治国')
2019-07-23 11:41:31,355 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,364 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,367 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,368 INFO sqlalchemy.engine.base.Engine (4324,)
2019-07-23 11:41:31,374 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,377 INFO sqlalchemy.engine.base.Engine ('灵芝地铁口 水口花园精装公寓 复式楼一房一厅 两房一厅采光好', '1400 元/月', '1室1厅1卫 45㎡ 南北向 精装修', '来自经纪人： 永利公寓物业管理 - 朱炫')
2019-07-23 11:41:31,381 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,390 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,393 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,394 INFO sqlalchemy.engine.base.Engine (4325,)
2019-07-23 11:41:31,400 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,401 INFO sqlalchemy.engine.base.Engine ('六约 独栋品牌公寓 停车场 综合公区 拎包入住 配备保洁保安', '1200 元/月', '1室0厅1卫 28㎡ 南北向 精装修', '来自经纪人： 恒康物业 - 陆忠炜')
2019-07-23 11:41:31,405 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,412 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,415 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,417 INFO sqlalchemy.engine.base.Engine (4326,)
2019-07-23 11:41:31,424 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,425 INFO sqlalchemy.engine.base.Engine ('整租 4号线白石龙地铁站 精装电梯房 家私齐全 采光好可做法', '950 元/月', '1室0厅1卫 27㎡ 南北向 精装修', '来自经纪人： 俊辉物业 - 代逢平')
2019-07-23 11:41:31,428 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,436 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,438 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,440 INFO sqlalchemy.engine.base.Engine (4327,)
2019-07-23 11:41:31,447 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,448 INFO sqlalchemy.engine.base.Engine ('松岗益安居 1室0厅1卫', '980 元/月', '1室0厅1卫 28㎡ 南北向', '来自个人房源：张先生')
2019-07-23 11:41:31,451 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,458 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,460 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,462 INFO sqlalchemy.engine.base.Engine (4328,)
2019-07-23 11:41:31,469 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,470 INFO sqlalchemy.engine.base.Engine ('新出精装大三房，朝南看花园泳池，景观棒，绿化好，物业负责安心', '5300 元/月', '3室2厅1卫 85㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产尚水天成分行 - 何根权')
2019-07-23 11:41:31,474 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,482 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)

2019-07-23 11:41:31,484 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,486 INFO sqlalchemy.engine.base.Engine (4329,)
2019-07-23 11:41:31,493 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,495 INFO sqlalchemy.engine.base.Engine ('知音文创产业园 章阁科技园 超大公区 押一付一 拎包入住', '700 元/月', '1室1厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 李颖')
2019-07-23 11:41:31,499 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,507 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,509 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,511 INFO sqlalchemy.engine.base.Engine (4330,)
2019-07-23 11:41:31,517 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,518 INFO sqlalchemy.engine.base.Engine ('碧桂园精装一房 近地铁无中介 家私家电网络齐全 厨房健身房', '1500 元/月', '1室1厅1卫 30㎡ 东南向 精装修', '来自经纪人： 碧家国际社区 - 碧家国际社区(深圳店) - 冷怡豪')
2019-07-23 11:41:31,521 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,529 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,531 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,533 INFO sqlalchemy.engine.base.Engine (4331,)
2019-07-23 11:41:31,538 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,540 INFO sqlalchemy.engine.base.Engine ('倍利得电子科技观澜工业园 全新精装家电齐全 拎包入住', '650 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:31,544 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,551 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,554 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,557 INFO sqlalchemy.engine.base.Engine (4332,)
2019-07-23 11:41:31,563 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,565 INFO sqlalchemy.engine.base.Engine ('硅谷动力产业园 毕业生每月200京东卡 精装 押一付一', '650 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 冠寓 - 李颖')
2019-07-23 11:41:31,570 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,579 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,582 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,585 INFO sqlalchemy.engine.base.Engine (4333,)
2019-07-23 11:41:31,591 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,593 INFO sqlalchemy.engine.base.Engine ('实图实价，豪装3房基本未入住，双地铁口，车位宽松，欢迎咨询', '15800 元/月', '3室2厅2卫 110㎡ 南向 豪华装修', '来自经纪人： 美联物业 - 美联物业臻山府分行 - 邵佳明')
2019-07-23 11:41:31,597 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,608 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,611 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,613 INFO sqlalchemy.engine.base.Engine (4334,)
2019-07-23 11:41:31,620 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,622 INFO sqlalchemy.engine.base.Engine ('民乐新村 1室1厅1卫', '1780 元/月', '1室1厅1卫 30㎡ 南向', '来自个人房源：干先生')
2019-07-23 11:41:31,625 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,633 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,636 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,638 INFO sqlalchemy.engine.base.Engine (4335,)
2019-07-23 11:41:31,644 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,646 INFO sqlalchemy.engine.base.Engine ('地铁11号线福永站C出口六百米', '1400 元/月', '1室1厅1卫 40㎡ 东南向 精装修', '来自经纪人： 宜宿 - 龚志华')
2019-07-23 11:41:31,649 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,660 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,664 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,671 INFO sqlalchemy.engine.base.Engine (4336,)
2019-07-23 11:41:31,680 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,685 INFO sqlalchemy.engine.base.Engine ('华南西苑可短租家电齐全 1室0厅1卫', '1400 元/月', '1室0厅1卫 23㎡ 南向', '来自经纪人： - 陈彩云')
2019-07-23 11:41:31,689 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,702 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,706 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,709 INFO sqlalchemy.engine.base.Engine (4337,)
2019-07-23 11:41:31,720 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,721 INFO sqlalchemy.engine.base.Engine ('优优公寓清湖地铁站800米大单间带阳台直租中，价格1299起', '1299 元/月', '1室0厅1卫 26㎡ 南北向 精装修', '来自经纪人： Q房网 - 帅乐乐')
2019-07-23 11:41:31,725 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,736 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,738 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,740 INFO sqlalchemy.engine.base.Engine (4338,)
2019-07-23 11:41:31,748 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,750 INFO sqlalchemy.engine.base.Engine ('山咀头村 1室1厅1卫', '2200 元/月', '1室1厅1卫 30㎡ 东向', '来自个人房源：叶女士')
2019-07-23 11:41:31,754 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,764 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,766 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,768 INFO sqlalchemy.engine.base.Engine (4339,)
2019-07-23 11:41:31,774 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,775 INFO sqlalchemy.engine.base.Engine ('下早村 1室0厅1卫', '980 元/月', '1室0厅1卫 20㎡ 南北向', '来自个人房源：黄先生')
2019-07-23 11:41:31,779 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,787 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,790 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,791 INFO sqlalchemy.engine.base.Engine (4340,)
2019-07-23 11:41:31,799 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)

2019-07-23 11:41:31,801 INFO sqlalchemy.engine.base.Engine ('单间拎包入住 五和地铁站 可以养宠物 1980 随时方便看房', '1980 元/月', '1室1厅1卫 20㎡ 东南向 精装修', '来自经纪人： 星窝公寓 - 潘玲玉')
2019-07-23 11:41:31,805 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,812 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,815 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,821 INFO sqlalchemy.engine.base.Engine (4341,)
2019-07-23 11:41:31,830 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,832 INFO sqlalchemy.engine.base.Engine ('五和南路 1室1厅1卫', '1000 元/月', '1室1厅1卫 32㎡ 南向', '来自个人房源：杜先生')
2019-07-23 11:41:31,839 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,850 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,854 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,856 INFO sqlalchemy.engine.base.Engine (4342,)
2019-07-23 11:41:31,862 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,864 INFO sqlalchemy.engine.base.Engine ('南山站附近 整租公寓 家私电配齐 拎包入住 O中介 随时可看', '2600 元/月', '1室1厅1卫 38㎡ 南向 精装修', '来自经纪人： 深圳万间信息 - 曾炳浩')
2019-07-23 11:41:31,869 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,878 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,881 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,883 INFO sqlalchemy.engine.base.Engine (4343,)
2019-07-23 11:41:31,891 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,893 INFO sqlalchemy.engine.base.Engine ('西乡宝立方流塘新村直租房 无中介 家私家电齐全 拎包入住', '1000 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(洪浪北分行) - 吴勇平')
2019-07-23 11:41:31,897 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,905 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,908 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,910 INFO sqlalchemy.engine.base.Engine (4344,)
2019-07-23 11:41:31,919 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,920 INFO sqlalchemy.engine.base.Engine ('官田村星城广场斜对面 1室0厅1卫', '980 元/月', '1室0厅1卫 25㎡ 南北向', '来自经纪人： - 周小姐女士')
2019-07-23 11:41:31,924 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,934 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,936 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,938 INFO sqlalchemy.engine.base.Engine (4345,)
2019-07-23 11:41:31,945 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,948 INFO sqlalchemy.engine.base.Engine ('富裕居花园 2室2厅1卫', '1800 元/月', '2室2厅1卫 107.86㎡ 南北向', '来自个人房源：黄女士')
2019-07-23 11:41:31,952 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:31,963 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:31,979 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:31,982 INFO sqlalchemy.engine.base.Engine (4346,)
2019-07-23 11:41:31,991 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:31,994 INFO sqlalchemy.engine.base.Engine ('物业直租，免中介费，3栋公寓出租，共13层，3栋290套，', '87000 元/月', '15室15厅15卫 1500㎡ 东向 精装修', '来自经纪人： 晔伦物业 - 张志华')
2019-07-23 11:41:31,998 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,012 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,015 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,017 INFO sqlalchemy.engine.base.Engine (4347,)
2019-07-23 11:41:32,023 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,025 INFO sqlalchemy.engine.base.Engine ('全新公寓单房临近丹竹头地铁站', '1000 元/月', '1室0厅1卫 30㎡ 南向 精装修', '来自经纪人： 家家发公寓 - 林岩松')
2019-07-23 11:41:32,029 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,041 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,045 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,047 INFO sqlalchemy.engine.base.Engine (4348,)
2019-07-23 11:41:32,056 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,060 INFO sqlalchemy.engine.base.Engine ('4号线白石龙地铁！2000元起！近梅林关口民乐深圳北民治', '2680 元/月', '1室1厅1卫 32㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:32,064 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,075 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,078 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,081 INFO sqlalchemy.engine.base.Engine (4349,)
2019-07-23 11:41:32,090 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,093 INFO sqlalchemy.engine.base.Engine ('白石龙地铁300米！花园小区拎包入住！近梅林关口民乐深圳北站', '3500 元/月', '1室1厅1卫 35㎡ 东南向 精装修', '来自经纪人： 秒猪窝巢公寓 - 王彩美')
2019-07-23 11:41:32,097 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,105 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,107 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,108 INFO sqlalchemy.engine.base.Engine (4350,)
2019-07-23 11:41:32,115 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,117 INFO sqlalchemy.engine.base.Engine ('西乡 哇塞!瞧一瞧,看一看 丰雅苑正规 让您尽享经典生活', '1280 元/月', '1室1厅1卫 46㎡ 南向 精装修', '来自经纪人： - 叶广进')
2019-07-23 11:41:32,121 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,130 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,133 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,135 INFO sqlalchemy.engine.base.Engine (4351,)
2019-07-23 11:41:32,143 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,144 INFO sqlalchemy.engine.base.Engine ('五和地铁站 大发埔村 超大一居室 拎包入住', '2000 元/月', '1室0厅1卫 32㎡ 南北向 精装修', '来自经纪人： 壹鼎冠小壹租 - 钟俊华')
2019-07-23 11:41:32,148 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,154 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,157 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:32,159 INFO sqlalchemy.engine.base.Engine (4352,)
2019-07-23 11:41:32,166 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,169 INFO sqlalchemy.engine.base.Engine ('直租地铁口一室空房', '2300 元/月', '1室0厅1卫 35㎡ 东南向 精装修', '来自经纪人： 汉兴物业 - 游军')
2019-07-23 11:41:32,173 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,178 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,179 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,181 INFO sqlalchemy.engine.base.Engine (4353,)
2019-07-23 11:41:32,187 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,189 INFO sqlalchemy.engine.base.Engine ('龙华腾龙工业区个人房源出租', '450 元/月', '1室0厅1卫 20㎡ 南向 简单装修', '来自经纪人： 深圳市杰瑞物业管理有限公司 - 杰瑞物业(皇都广场分行) - 范东梁')
2019-07-23 11:41:32,192 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,199 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,201 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,202 INFO sqlalchemy.engine.base.Engine (4354,)
2019-07-23 11:41:32,208 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,209 INFO sqlalchemy.engine.base.Engine ('科技中二路 1室0厅1卫', '3000 元/月', '1室0厅1卫 20㎡ 北向', '来自个人房源：黄女士')
2019-07-23 11:41:32,213 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,221 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,223 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,224 INFO sqlalchemy.engine.base.Engine (4355,)
2019-07-23 11:41:32,230 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,232 INFO sqlalchemy.engine.base.Engine ('大小单间，岗头发展大厦附近，直租，免中介', '780 元/月', '1室0厅1卫 26㎡ 东南向 精装修', '来自经纪人： 深圳市舜善投资有限公司 - 深圳市舜善投资有限公司(新港鸿分行) - 余水珍')
2019-07-23 11:41:32,237 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,243 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,245 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,247 INFO sqlalchemy.engine.base.Engine (4356,)
2019-07-23 11:41:32,252 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,254 INFO sqlalchemy.engine.base.Engine ('大运软件小镇旁 复式两房一厅 带家电 户型好 有阳台 采光好', '1800 元/月', '2室1厅1卫 60㎡ 南向 豪华装修', '来自经纪人： 恒康物业 - 冯文运')
2019-07-23 11:41:32,258 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,264 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,266 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,267 INFO sqlalchemy.engine.base.Engine (4357,)
2019-07-23 11:41:32,273 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,274 INFO sqlalchemy.engine.base.Engine ('沙井 新桥小学附近 精装公寓', '590 元/月', '1室0厅1卫 15㎡ 东向 精装修', '来自经纪人： 和隅物业 - 赖钦')
2019-07-23 11:41:32,278 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,285 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,288 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,290 INFO sqlalchemy.engine.base.Engine (4358,)
2019-07-23 11:41:32,297 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,299 INFO sqlalchemy.engine.base.Engine ('下沙地铁站附近 六坊全新装修公寓单间 家私家电齐全', '1300 元/月', '1室0厅1卫 20㎡ 南向 精装修', '来自经纪人： Q房网 - 黄雪娇')
2019-07-23 11:41:32,305 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,313 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,317 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,319 INFO sqlalchemy.engine.base.Engine (4359,)
2019-07-23 11:41:32,326 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,327 INFO sqlalchemy.engine.base.Engine ('华南城精装公寓850领包入住房东直租', '850 元/月', '1室0厅0卫 20㎡ 南向 精装修', '来自经纪人： 深圳市新平盛投资发展有限公司 - 深圳市新平盛投资发展有限公司(平湖店) - 黄建发')
2019-07-23 11:41:32,331 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,338 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,340 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,342 INFO sqlalchemy.engine.base.Engine (4360,)
2019-07-23 11:41:32,347 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,350 INFO sqlalchemy.engine.base.Engine ('民治地铁口 精装修 拎包入住 全智能家居 图片实拍', '2180 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 爱美家物业 - 陈晓镇')
2019-07-23 11:41:32,354 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,361 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,365 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,367 INFO sqlalchemy.engine.base.Engine (4361,)
2019-07-23 11:41:32,373 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,375 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 硅谷动力产业园 观澜上班必选', '1532 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:32,379 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,387 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,390 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,392 INFO sqlalchemy.engine.base.Engine (4362,)
2019-07-23 11:41:32,403 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,405 INFO sqlalchemy.engine.base.Engine ('龙华区龙观大道近壹方天地百佳华，万科泊寓，交通便利品牌保障', '1298 元/月', '1室0厅1卫 19㎡ 东南向 精装修', '来自经纪人： - 张炽洪')
2019-07-23 11:41:32,413 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,421 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,423 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,426 INFO sqlalchemy.engine.base.Engine (4363,)
2019-07-23 11:41:32,433 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,434 INFO sqlalchemy.engine.base.Engine ('丹竹头地铁口附近，周边生活配套设施齐全！', '4000 元/月', '4室2厅2卫 120㎡ 南向 豪华装修', '来自经纪人： 广坤地产 - 广坤地产(下水径分行) - 张金才')

2019-07-23 11:41:32,440 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,446 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,449 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,451 INFO sqlalchemy.engine.base.Engine (4364,)
2019-07-23 11:41:32,457 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,459 INFO sqlalchemy.engine.base.Engine ('!鸿达兴花园好房出租,居住舒适,干净整洁', '880 元/月', '1室1厅1卫 36㎡ 东南向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(桥头分行) - 万磊')
2019-07-23 11:41:32,463 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,469 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,471 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,472 INFO sqlalchemy.engine.base.Engine (4365,)
2019-07-23 11:41:32,477 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,478 INFO sqlalchemy.engine.base.Engine ('大单间,就是要住得舒心些', '1300 元/月', '1室0厅1卫 40㎡ 南北向 简单装修', '来自经纪人： - 詹前场')
2019-07-23 11:41:32,482 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,489 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,491 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,493 INFO sqlalchemy.engine.base.Engine (4366,)
2019-07-23 11:41:32,498 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,501 INFO sqlalchemy.engine.base.Engine ('西丽，留仙洞双地铁 时尚品牌公寓 单间低至1584 拎包入住', '1880 元/月', '1室1厅1卫 30㎡ 南向 精装修', '来自经纪人： - 陈建洪')
2019-07-23 11:41:32,506 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,512 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,515 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,517 INFO sqlalchemy.engine.base.Engine (4367,)
2019-07-23 11:41:32,523 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,525 INFO sqlalchemy.engine.base.Engine ('富佳源公寓 精装一房一厅 家私家电齐全 拧包入住 随时看房', '2650 元/月', '1室1厅1卫 35㎡ 南向 精装修', '来自经纪人： 独立经纪人（龙华） - 独立经纪人（龙华） - 李敏锋')
2019-07-23 11:41:32,528 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,536 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,538 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,540 INFO sqlalchemy.engine.base.Engine (4368,)
2019-07-23 11:41:32,546 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,547 INFO sqlalchemy.engine.base.Engine ('毕业生立返2400 志扬科技园 拎包入住 电梯房', '1532 元/月', '2室1厅1卫 58㎡ 南向 精装修', '来自经纪人： 冠寓 - 冠寓(新安分行) - 黎苗')
2019-07-23 11:41:32,551 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,560 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,562 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,564 INFO sqlalchemy.engine.base.Engine (4369,)
2019-07-23 11:41:32,569 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,571 INFO sqlalchemy.engine.base.Engine ('业主公寓直租 家私家电齐全 地铁口 交通便利', '1800 元/月', '1室0厅1卫 30㎡ 南北向 精装修', '来自经纪人： 独立经纪人 - 邹建')
2019-07-23 11:41:32,575 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,583 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,586 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,588 INFO sqlalchemy.engine.base.Engine (4370,)
2019-07-23 11:41:32,593 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,595 INFO sqlalchemy.engine.base.Engine ('马安山花园 1室1厅1卫', '700 元/月', '1室1厅1卫 40㎡ 东向', '来自个人房源：周小姐女士')
2019-07-23 11:41:32,598 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,607 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,611 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,613 INFO sqlalchemy.engine.base.Engine (4371,)
2019-07-23 11:41:32,621 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,623 INFO sqlalchemy.engine.base.Engine ('如意大厦 1室0厅1卫', '1280 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：王萍女士')
2019-07-23 11:41:32,628 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,636 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,639 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,640 INFO sqlalchemy.engine.base.Engine (4372,)
2019-07-23 11:41:32,647 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,649 INFO sqlalchemy.engine.base.Engine ('四号线龙胜地铁站 港铁天颂豪华精装品牌连锁公寓 押一付一', '1300 元/月', '1室1厅1卫 46㎡ 南北向 精装修', '来自经纪人： 搜鱼租房 - 搜鱼租房(上塘) - 曹理想')
2019-07-23 11:41:32,654 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,660 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,663 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,666 INFO sqlalchemy.engine.base.Engine (4373,)
2019-07-23 11:41:32,673 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,675 INFO sqlalchemy.engine.base.Engine ('你的酒馆为我打了样。宁水居家双学位罗湖前十，在我胸口上上膛。', '4500 元/月', '2室2厅1卫 81.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产幸福城分行 - 陈振宇')
2019-07-23 11:41:32,679 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,687 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,690 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,691 INFO sqlalchemy.engine.base.Engine (4374,)
2019-07-23 11:41:32,699 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,701 INFO sqlalchemy.engine.base.Engine ('华南城旁边熙璟城对面同创新作精装两房两厅家电家私全齐看房方便', '2600 元/月', '2室2厅2卫 78㎡ 东南向 精装修', '来自经纪人： 丽湖地产 - 丽湖地产同创新作分行 - 边厚金')
2019-07-23 11:41:32,705 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,712 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,715 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:32,717 INFO sqlalchemy.engine.base.Engine (4375,)
2019-07-23 11:41:32,723 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,725 INFO sqlalchemy.engine.base.Engine ('旺塘八巷3号小区 1室0厅1卫', '1700 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：郑艳萍女士')
2019-07-23 11:41:32,730 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,737 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,739 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,742 INFO sqlalchemy.engine.base.Engine (4376,)
2019-07-23 11:41:32,748 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,750 INFO sqlalchemy.engine.base.Engine ('五和地铁站 单间一室一厅 临近华为 购物方便  家私齐全', '1500 元/月', '1室1厅1卫 45.00㎡ 南向 精装修', '来自经纪人： - 方官义')
2019-07-23 11:41:32,754 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,762 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,764 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,765 INFO sqlalchemy.engine.base.Engine (4377,)
2019-07-23 11:41:32,771 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,772 INFO sqlalchemy.engine.base.Engine ('荣德国际沃尔玛 横岗地铁站 直达福田 通勤方便 个人直租', '1750 元/月', '2室1厅1卫 45.0㎡ 南向 简单装修', '来自经纪人： 深圳万间信息 - 深圳万间信息(科技园分行) - 谭思玲')
2019-07-23 11:41:32,776 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,784 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,786 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,787 INFO sqlalchemy.engine.base.Engine (4378,)
2019-07-23 11:41:32,794 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,795 INFO sqlalchemy.engine.base.Engine ('地铁口500米 精装公寓招租 单间 一房一厅 两房 直租', '1330 元/月', '1室0厅1卫 23㎡ 南向 精装修', '来自经纪人： - 陈文')
2019-07-23 11:41:32,799 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,806 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,809 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,811 INFO sqlalchemy.engine.base.Engine (4379,)
2019-07-23 11:41:32,818 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,820 INFO sqlalchemy.engine.base.Engine ('布吉一村 1室0厅1卫', '1750 元/月', '1室0厅1卫 36㎡ 南北向', '来自个人房源：小万先生')
2019-07-23 11:41:32,824 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,835 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,838 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,840 INFO sqlalchemy.engine.base.Engine (4380,)
2019-07-23 11:41:32,847 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,849 INFO sqlalchemy.engine.base.Engine ('房东直租 丹竹头地铁站花园小区一房一厅双阳台 家具家电齐全', '2580 元/月', '1室1厅1卫 62㎡ 南向 精装修', '来自经纪人： 同城快租 - 林佳泉')
2019-07-23 11:41:32,853 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,861 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,864 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,865 INFO sqlalchemy.engine.base.Engine (4381,)
2019-07-23 11:41:32,872 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,873 INFO sqlalchemy.engine.base.Engine ('急租，户型方正，使用率高，位置好环境安静，靠近地铁', '9800 元/月', '4室2厅2卫 138.79㎡ 南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产阳光海湾三分行 - 刘炳荣')
2019-07-23 11:41:32,877 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,886 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,888 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,891 INFO sqlalchemy.engine.base.Engine (4382,)
2019-07-23 11:41:32,898 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,899 INFO sqlalchemy.engine.base.Engine ('荔香苑 1室1厅1卫', '2000 元/月', '1室1厅1卫 38㎡ 东南向', '来自个人房源：黄先生')
2019-07-23 11:41:32,904 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,919 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,922 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,924 INFO sqlalchemy.engine.base.Engine (4383,)
2019-07-23 11:41:32,934 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,937 INFO sqlalchemy.engine.base.Engine ('口沃尔玛旁 万科物业 精装三房 家电齐全拎包入住', '4300 元/月', '3室2厅2卫 89.00㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 梁菲霞')
2019-07-23 11:41:32,947 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,954 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,957 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,959 INFO sqlalchemy.engine.base.Engine (4384,)
2019-07-23 11:41:32,965 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:32,967 INFO sqlalchemy.engine.base.Engine ('上塘地铁口500米豪华装修 家私电齐全  看房有钥匙', '5500 元/月', '3室2厅2卫 89㎡ 东南向 豪华装修', '来自经纪人： 乐有家地产 - 乐有家地产世纪春城五分行 - 刘东')
2019-07-23 11:41:32,972 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:32,981 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:32,984 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:32,989 INFO sqlalchemy.engine.base.Engine (4385,)
2019-07-23 11:41:32,998 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,000 INFO sqlalchemy.engine.base.Engine ('传麒尚林豪华装大两房 成熟社区 家私电齐全 拎包入住', '2950 元/月', '2室2厅1卫 69㎡ 南向 豪华装修', '来自经纪人： 人人居地产 - 刘锦祥')
2019-07-23 11:41:33,003 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,010 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,013 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,015 INFO sqlalchemy.engine.base.Engine (4386,)
2019-07-23 11:41:33,022 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,024 INFO sqlalchemy.engine.base.Engine ('平吉上苑 精装大三房 有钥匙随时看房', '4000 元/月', '3室2厅2卫 102㎡ 东南向 精装修', '来自经纪人： 中房宜居 - 中房宜居(格林联盟分行) - 黄永原')

2019-07-23 11:41:33,028 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,036 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,038 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,039 INFO sqlalchemy.engine.base.Engine (4387,)
2019-07-23 11:41:33,045 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,047 INFO sqlalchemy.engine.base.Engine ('登良地铁口旁的两房出租', '6500 元/月', '2室1厅0卫 57.0㎡ 北向 简单装修', '来自经纪人： Q房网 - Q房网天骄华庭分行 - 聂云祥')
2019-07-23 11:41:33,049 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,059 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,061 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,064 INFO sqlalchemy.engine.base.Engine (4388,)
2019-07-23 11:41:33,070 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,071 INFO sqlalchemy.engine.base.Engine ('海语西湾 3室2厅1卫', '7000 元/月', '3室2厅1卫 88㎡ 南北向', '来自个人房源：高先生')
2019-07-23 11:41:33,075 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,085 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,087 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,089 INFO sqlalchemy.engine.base.Engine (4389,)
2019-07-23 11:41:33,095 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,097 INFO sqlalchemy.engine.base.Engine ('3,5号线交汇，地铁口物业，百合星城', '4300 元/月', '2室2厅1卫 62㎡ 南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产百合分行 - 朱家正')
2019-07-23 11:41:33,101 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,109 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,112 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,115 INFO sqlalchemy.engine.base.Engine (4390,)
2019-07-23 11:41:33,122 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,124 INFO sqlalchemy.engine.base.Engine ('1号线西乡坪洲地铁站，精装修一房一厅采光好，单身公寓不再单身', '1680 元/月', '1室1厅1卫 45㎡ 南向 精装修', '来自经纪人： 寓联公寓 - 寓联公寓(西乡分行) - 肖芬连')
2019-07-23 11:41:33,129 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,138 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,141 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,142 INFO sqlalchemy.engine.base.Engine (4391,)
2019-07-23 11:41:33,148 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,150 INFO sqlalchemy.engine.base.Engine ('麒麟名都大型花园小区 精装两房全齐出租 可随时看房', '3300 元/月', '2室1厅1卫 84㎡ 南北向 豪华装修', '来自经纪人： - 张蓉')
2019-07-23 11:41:33,154 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,162 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,164 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,166 INFO sqlalchemy.engine.base.Engine (4392,)
2019-07-23 11:41:33,174 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,176 INFO sqlalchemy.engine.base.Engine ('平山村 1室0厅1卫', '1750 元/月', '1室0厅1卫 25㎡ 南向', '来自个人房源：罗先生')
2019-07-23 11:41:33,180 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,188 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,191 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,194 INFO sqlalchemy.engine.base.Engine (4393,)
2019-07-23 11:41:33,201 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,203 INFO sqlalchemy.engine.base.Engine ('科苑西住宅小区 2室2厅1卫', '6600 元/月', '2室2厅1卫 75㎡ 南向', '来自个人房源：余先生')
2019-07-23 11:41:33,210 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,219 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,223 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,226 INFO sqlalchemy.engine.base.Engine (4394,)
2019-07-23 11:41:33,235 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,237 INFO sqlalchemy.engine.base.Engine ('水口花园 1室0厅1卫', '1500 元/月', '1室0厅1卫 30㎡ 南向', '来自个人房源：张志豪先生')
2019-07-23 11:41:33,242 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,253 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,257 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,258 INFO sqlalchemy.engine.base.Engine (4395,)
2019-07-23 11:41:33,265 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,269 INFO sqlalchemy.engine.base.Engine ('金源工业区 1室1厅1卫', '1300 元/月', '1室1厅1卫 40㎡ 南北向', '来自个人房源：王先生')
2019-07-23 11:41:33,274 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,287 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,290 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,292 INFO sqlalchemy.engine.base.Engine (4396,)
2019-07-23 11:41:33,300 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,303 INFO sqlalchemy.engine.base.Engine ('租房立省4000元前海花园精装好房 先到先得  月付', '2830 元/月', '1室0厅1卫 14㎡ 北向 精装修', '来自经纪人： 云家商务 - 云家商务(深圳分行) - 林洋')
2019-07-23 11:41:33,307 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,315 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,318 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,320 INFO sqlalchemy.engine.base.Engine (4397,)
2019-07-23 11:41:33,330 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,332 INFO sqlalchemy.engine.base.Engine ('双地铁带飘窗厅卧一体 品牌公寓直租 配套齐全 1个月起租', '2500 元/月', '1室0厅1卫 28.00㎡ 东南向 精装修', '来自经纪人： 乐有家地产 - 乐有家地产棕榈堡二分行 - 钟怡云')
2019-07-23 11:41:33,336 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,345 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,349 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?

2019-07-23 11:41:33,351 INFO sqlalchemy.engine.base.Engine (4398,)
2019-07-23 11:41:33,356 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,358 INFO sqlalchemy.engine.base.Engine ('西丽珠光站口 安静小区 龙辉花园 精装三房 采光好 随时入住', '5800 元/月', '3室2厅1卫 87.00㎡ 南向 精装修', '来自经纪人： 好房网地产 - 好房网地产(南国丽城分行) - 尹华强')
2019-07-23 11:41:33,362 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,380 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,384 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,387 INFO sqlalchemy.engine.base.Engine (4399,)
2019-07-23 11:41:33,395 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,399 INFO sqlalchemy.engine.base.Engine ('固戍精装大两房一厅75平超大空间 直租无中介可居家和宿舍', '2800 元/月', '2室1厅1卫 85㎡ 东南向 精装修', '来自经纪人： 租云物业 - 彭德胜')
2019-07-23 11:41:33,402 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,410 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,414 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,417 INFO sqlalchemy.engine.base.Engine (4400,)
2019-07-23 11:41:33,427 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,429 INFO sqlalchemy.engine.base.Engine ('西乡 鸿隆广场(港隆城） 2室1厅', '4000 元/月', '2室1厅1卫 48㎡ 西南向 精装修', '来自经纪人： 独立经纪人（龙华） - 傅俊镇')
2019-07-23 11:41:33,435 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,444 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,447 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,450 INFO sqlalchemy.engine.base.Engine (4401,)
2019-07-23 11:41:33,455 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,458 INFO sqlalchemy.engine.base.Engine ('熙璟城精装三房，业主自住房，配套成熟商业，', '5000 元/月', '3室2厅1卫 85㎡ 东南向 精装修', '来自经纪人： 中原地产 - 林志安')
2019-07-23 11:41:33,463 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,476 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,483 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,486 INFO sqlalchemy.engine.base.Engine (4402,)
2019-07-23 11:41:33,494 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,496 INFO sqlalchemy.engine.base.Engine ('布吉丹竹头 豪华情侣大单间 独立厨卫 拎包入住 可停车', '1000 元/月', '1室0厅1卫 28㎡ 南北向 豪华装修', '来自经纪人： - 陈明祥')
2019-07-23 11:41:33,502 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,510 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,512 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,514 INFO sqlalchemy.engine.base.Engine (4403,)
2019-07-23 11:41:33,523 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,527 INFO sqlalchemy.engine.base.Engine ('村前路 1室0厅1卫', '550 元/月', '1室0厅1卫 28㎡ 南向', '来自个人房源：方先生')
2019-07-23 11:41:33,532 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,542 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,546 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,551 INFO sqlalchemy.engine.base.Engine (4404,)
2019-07-23 11:41:33,561 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,563 INFO sqlalchemy.engine.base.Engine ('整租  四号线龙胜地铁站  三号线丹竹头  房源采光好通风好', '970 元/月', '1室0厅1卫 22㎡ 南北向 精装修', '来自经纪人： 众合物业 - 熊贤徽')
2019-07-23 11:41:33,569 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,584 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,591 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,594 INFO sqlalchemy.engine.base.Engine (4405,)
2019-07-23 11:41:33,602 INFO sqlalchemy.engine.base.Engine INSERT INTO rental (title, price, info, agent) VALUES (?, ?, ?, ?)
2019-07-23 11:41:33,607 INFO sqlalchemy.engine.base.Engine ('桃源居11区，双龙抱珠户型，采光好南北通，位置安静，拎包入住', '7500 元/月', '4室2厅2卫 138㎡ 南向 精装修', '来自经纪人： Q房网 - Q房网桃源盛景分行 - 房浩')
2019-07-23 11:41:33,616 INFO sqlalchemy.engine.base.Engine COMMIT
2019-07-23 11:41:33,625 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-07-23 11:41:33,628 INFO sqlalchemy.engine.base.Engine SELECT rental.id AS rental_id, rental.title AS rental_title, rental.price AS rental_price, rental.info AS rental_info, rental.agent AS rental_agent
FROM rental
WHERE rental.id = ?
2019-07-23 11:41:33,632 INFO sqlalchemy.engine.base.Engine (4406,)
http://sz.ganji.com/zufang/pn18 status: 200

KeyboardInterrupt: